-- W3 approved Pricing aggregate. Immutable after first successful Flyway application.
-- PostgreSQL only. No foreign keys; parent row locks protect price periods.

CREATE TABLE customer_agreement_price (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    unit_price NUMERIC(18,4) NOT NULL,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64), updated_by VARCHAR(64),
    CONSTRAINT ck_customer_agreement_price_amount CHECK (unit_price >= 0),
    CONSTRAINT ck_customer_agreement_price_period CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT ck_customer_agreement_price_version CHECK (version >= 0)
);
CREATE INDEX idx_customer_agreement_price_lookup ON customer_agreement_price (customer_id,sku_id,effective_from,effective_to) WHERE deleted=FALSE;
CREATE INDEX idx_customer_agreement_price_effective ON customer_agreement_price (effective_from DESC,id DESC) WHERE deleted=FALSE;
CREATE INDEX idx_customer_agreement_price_sku_id ON customer_agreement_price (sku_id) WHERE deleted=FALSE;

CREATE TABLE customer_type_price (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_type_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    unit_price NUMERIC(18,4) NOT NULL,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64), updated_by VARCHAR(64),
    CONSTRAINT ck_customer_type_price_amount CHECK (unit_price >= 0),
    CONSTRAINT ck_customer_type_price_period CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT ck_customer_type_price_version CHECK (version >= 0)
);
CREATE INDEX idx_customer_type_price_lookup ON customer_type_price (customer_type_id,sku_id,effective_from,effective_to) WHERE deleted=FALSE;
CREATE INDEX idx_customer_type_price_effective ON customer_type_price (effective_from DESC,id DESC) WHERE deleted=FALSE;
CREATE INDEX idx_customer_type_price_sku_id ON customer_type_price (sku_id) WHERE deleted=FALSE;

CREATE TABLE customer_agreement_price_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agreement_price_id BIGINT NOT NULL,
    operation_type VARCHAR(20) NOT NULL,
    operator VARCHAR(64) NOT NULL,
    before_data JSONB, after_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    CONSTRAINT ck_agreement_price_log_operation CHECK (operation_type IN ('CREATE','UPDATE','DELETE')),
    CONSTRAINT ck_agreement_price_log_before_data CHECK (before_data IS NULL OR jsonb_typeof(before_data)='object'),
    CONSTRAINT ck_agreement_price_log_after_data CHECK (after_data IS NULL OR jsonb_typeof(after_data)='object')
);
CREATE INDEX idx_agreement_price_log_price_created ON customer_agreement_price_operation_log (agreement_price_id,created_at DESC);
CREATE INDEX idx_agreement_price_log_created ON customer_agreement_price_operation_log (created_at DESC);

CREATE TABLE customer_type_price_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_type_price_id BIGINT NOT NULL,
    operation_type VARCHAR(20) NOT NULL,
    operator VARCHAR(64) NOT NULL,
    before_data JSONB, after_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    CONSTRAINT ck_customer_type_price_log_operation CHECK (operation_type IN ('CREATE','UPDATE','DELETE')),
    CONSTRAINT ck_customer_type_price_log_before_data CHECK (before_data IS NULL OR jsonb_typeof(before_data)='object'),
    CONSTRAINT ck_customer_type_price_log_after_data CHECK (after_data IS NULL OR jsonb_typeof(after_data)='object')
);
CREATE INDEX idx_customer_type_price_log_price_created ON customer_type_price_operation_log (customer_type_price_id,created_at DESC);
CREATE INDEX idx_customer_type_price_log_created ON customer_type_price_operation_log (created_at DESC);

CREATE TABLE customer_price_batch_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_key VARCHAR(100) NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    result VARCHAR(16) NOT NULL,
    row_count INTEGER NOT NULL,
    error_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    CONSTRAINT ck_customer_price_batch_result CHECK (result IN ('SUCCESS','FAILED'))
);
CREATE INDEX idx_customer_price_batch_audit_key ON customer_price_batch_audit (batch_key,created_at DESC);
CREATE UNIQUE INDEX uk_customer_price_batch_audit_success ON customer_price_batch_audit (batch_key) WHERE result='SUCCESS';

CREATE TABLE customer_sku_visibility (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL, sku_id BIGINT NOT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64), updated_by VARCHAR(64),
    CONSTRAINT ck_customer_sku_visibility_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_customer_sku_visibility_active ON customer_sku_visibility (customer_id,sku_id) WHERE deleted=FALSE;
CREATE INDEX idx_customer_sku_visibility_sku_id ON customer_sku_visibility (sku_id);
ALTER TABLE customer ADD COLUMN visibility_policy VARCHAR(20) NOT NULL DEFAULT 'ALL_ENABLED';
ALTER TABLE customer ADD CONSTRAINT ck_customer_visibility_policy CHECK (visibility_policy IN ('ALL_ENABLED','ALLOWLIST'));
