-- =====================================================================
-- V2 系统表基线 · 登录 / RBAC 关联最小集
--
-- 说明：V1 只覆盖 PoC 三表（t_employee / t_menu / t_dict）。
-- 「登录关联」验证需要员工 → 角色 → 菜单（权限点）这条链路可查通，
-- 因此本文件转换该链路所需的最小表集。
-- 其余系统表（约 30 张）在 PoC 验收通过后按同样规则转换。
-- 转换规则见 V1 文件头。
-- =====================================================================

-- ---------------------------------------------------------------------
-- t_department 部门
-- ---------------------------------------------------------------------
CREATE TABLE t_department (
    department_id   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(50)  NOT NULL,
    manager_id      BIGINT,
    parent_id       BIGINT       NOT NULL DEFAULT 0,
    sort            INTEGER      NOT NULL DEFAULT 0,
    update_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_t_department_parent_id ON t_department (parent_id);

COMMENT ON TABLE t_department IS '部门';
COMMENT ON COLUMN t_department.manager_id IS '部门负责人id';
COMMENT ON COLUMN t_department.parent_id IS '部门的父级id';

-- ---------------------------------------------------------------------
-- t_position 职务表
-- ---------------------------------------------------------------------
CREATE TABLE t_position (
    position_id    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_name  VARCHAR(200) NOT NULL,
    position_level VARCHAR(200),
    sort           INTEGER      DEFAULT 0,
    remark         VARCHAR(200),
    deleted_flag   BOOLEAN      DEFAULT FALSE,
    create_time    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE t_position IS '职务表';

-- ---------------------------------------------------------------------
-- t_role 角色表
-- ---------------------------------------------------------------------
CREATE TABLE t_role (
    role_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR(20)  NOT NULL,
    role_code   VARCHAR(500),
    remark      VARCHAR(255),
    update_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_role_role_code UNIQUE (role_code)
);

COMMENT ON TABLE t_role IS '角色表';

-- ---------------------------------------------------------------------
-- t_role_employee 角色-员工
-- ---------------------------------------------------------------------
CREATE TABLE t_role_employee (
    id          BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id     BIGINT    NOT NULL,
    employee_id BIGINT    NOT NULL,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_role_employee UNIQUE (role_id, employee_id)
);

COMMENT ON TABLE t_role_employee IS '角色员工功能表';

-- ---------------------------------------------------------------------
-- t_role_menu 角色-菜单（菜单含功能点，即权限授予载体）
-- ---------------------------------------------------------------------
CREATE TABLE t_role_menu (
    role_menu_id BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id      BIGINT    NOT NULL,
    menu_id      BIGINT    NOT NULL,
    update_time  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_t_role_menu_role_id ON t_role_menu (role_id);
CREATE INDEX idx_t_role_menu_menu_id ON t_role_menu (menu_id);

COMMENT ON TABLE t_role_menu IS '角色-菜单';

-- ---------------------------------------------------------------------
-- t_role_data_scope 角色的数据范围
-- ---------------------------------------------------------------------
CREATE TABLE t_role_data_scope (
    id              BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_scope_type INTEGER   NOT NULL,
    view_type       INTEGER   NOT NULL,
    role_id         BIGINT    NOT NULL,
    update_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_t_role_data_scope_role_id ON t_role_data_scope (role_id);

COMMENT ON TABLE t_role_data_scope IS '角色的数据范围';
