-- ==========================================================================
-- XSY-SCM  PostgreSQL 建表脚本 —— 系统基础表（SmartAdmin 框架：权限 / 组织 / 字典 / 公告 / 帮助文档 / 任务 / OA）
-- 由 MySQL 结构自动转换生成，表数量：44
-- 目标数据库：PostgreSQL 12+
-- ==========================================================================

-- ------------------------------------------------------------------
-- ON UPDATE CURRENT_TIMESTAMP 在 PostgreSQL 中没有等价列属性，
-- 统一用下面这个触发器函数替代（每张有 update_time 的表挂一个 BEFORE UPDATE 触发器）。
-- 如果业务代码里已经显式维护 update_time，可以整段删除。
-- ------------------------------------------------------------------
CREATE OR REPLACE FUNCTION xsy_set_update_time() RETURNS trigger AS $$
BEGIN
  NEW.update_time := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------
-- t_category  分类表，主要用于商品分类
-- ----------------------------
DROP TABLE IF EXISTS "t_category";
CREATE TABLE "t_category" (
  "category_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "category_name" varchar(100) NOT NULL,
  "category_type" smallint NOT NULL,
  "parent_id" integer NOT NULL,
  "sort" integer NOT NULL DEFAULT 0,
  "disabled_flag" smallint NOT NULL DEFAULT 0,
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  "remark" varchar(255),
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("category_id")
);
COMMENT ON TABLE "t_category" IS '分类表，主要用于商品分类';
COMMENT ON COLUMN "t_category"."category_id" IS '分类id';
COMMENT ON COLUMN "t_category"."category_name" IS '分类名称';
COMMENT ON COLUMN "t_category"."category_type" IS '分类类型';
COMMENT ON COLUMN "t_category"."parent_id" IS '父级id';
COMMENT ON COLUMN "t_category"."sort" IS '排序';
COMMENT ON COLUMN "t_category"."disabled_flag" IS '是否禁用';
COMMENT ON COLUMN "t_category"."deleted_flag" IS '是否删除';
CREATE INDEX "idx_parent_id" ON "t_category" ("parent_id");
CREATE TRIGGER "trg_t_category_update_time" BEFORE UPDATE ON "t_category"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_change_log  系统更新日志
-- ----------------------------
DROP TABLE IF EXISTS "t_change_log";
CREATE TABLE "t_change_log" (
  "change_log_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "update_version" varchar(255) NOT NULL,
  "type" integer NOT NULL,
  "publish_author" varchar(255) NOT NULL,
  "public_date" date NOT NULL,
  "content" text NOT NULL,
  "link" text,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("change_log_id"),
  CONSTRAINT "version_unique" UNIQUE ("update_version")
);
COMMENT ON TABLE "t_change_log" IS '系统更新日志';
COMMENT ON COLUMN "t_change_log"."change_log_id" IS '更新日志id';
COMMENT ON COLUMN "t_change_log"."update_version" IS '版本';
COMMENT ON COLUMN "t_change_log"."type" IS '更新类型:[1:特大版本功能更新;2:功能更新;3:bug修复]';
COMMENT ON COLUMN "t_change_log"."publish_author" IS '发布人';
COMMENT ON COLUMN "t_change_log"."public_date" IS '发布日期';
COMMENT ON COLUMN "t_change_log"."content" IS '更新内容';
COMMENT ON COLUMN "t_change_log"."link" IS '跳转链接';
COMMENT ON COLUMN "t_change_log"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_change_log"."update_time" IS '更新时间';
CREATE TRIGGER "trg_t_change_log_update_time" BEFORE UPDATE ON "t_change_log"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_code_generator_config  代码生成器的每个表的配置
-- ----------------------------
DROP TABLE IF EXISTS "t_code_generator_config";
CREATE TABLE "t_code_generator_config" (
  "table_name" varchar(255) NOT NULL,
  "basic" text,
  "fields" text,
  "insert_and_update" text,
  "delete_info" text,
  "query_fields" text,
  "table_fields" text,
  "detail" text,
  "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("table_name")
);
COMMENT ON TABLE "t_code_generator_config" IS '代码生成器的每个表的配置';
COMMENT ON COLUMN "t_code_generator_config"."table_name" IS '表名';
COMMENT ON COLUMN "t_code_generator_config"."basic" IS '基础命名信息';
COMMENT ON COLUMN "t_code_generator_config"."fields" IS '字段列表';
COMMENT ON COLUMN "t_code_generator_config"."insert_and_update" IS '新建、修改';
COMMENT ON COLUMN "t_code_generator_config"."delete_info" IS '删除';
COMMENT ON COLUMN "t_code_generator_config"."query_fields" IS '查询';
COMMENT ON COLUMN "t_code_generator_config"."table_fields" IS '列表';
COMMENT ON COLUMN "t_code_generator_config"."detail" IS '详情';
COMMENT ON COLUMN "t_code_generator_config"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_code_generator_config"."update_time" IS '更新时间';
CREATE TRIGGER "trg_t_code_generator_config_update_time" BEFORE UPDATE ON "t_code_generator_config"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_config  系统配置
-- ----------------------------
DROP TABLE IF EXISTS "t_config";
CREATE TABLE "t_config" (
  "config_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "config_name" varchar(255) NOT NULL,
  "config_key" varchar(255) NOT NULL,
  "config_value" text NOT NULL,
  "remark" varchar(255),
  "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("config_id")
);
COMMENT ON TABLE "t_config" IS '系统配置';
COMMENT ON COLUMN "t_config"."config_id" IS '主键';
COMMENT ON COLUMN "t_config"."config_name" IS '参数名字';
COMMENT ON COLUMN "t_config"."config_key" IS '参数key';
COMMENT ON COLUMN "t_config"."update_time" IS '上次修改时间';
COMMENT ON COLUMN "t_config"."create_time" IS '创建时间';
CREATE TRIGGER "trg_t_config_update_time" BEFORE UPDATE ON "t_config"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_data_tracer  各种单据操作记录
-- ----------------------------
DROP TABLE IF EXISTS "t_data_tracer";
CREATE TABLE "t_data_tracer" (
  "data_tracer_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "data_id" bigint NOT NULL,
  "type" integer NOT NULL,
  "content" text,
  "diff_old" text,
  "diff_new" text,
  "extra_data" text,
  "user_id" bigint NOT NULL,
  "user_type" integer NOT NULL,
  "user_name" varchar(50) NOT NULL,
  "ip" varchar(50),
  "ip_region" varchar(1000),
  "user_agent" varchar(2000),
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("data_tracer_id")
);
COMMENT ON TABLE "t_data_tracer" IS '各种单据操作记录';
COMMENT ON COLUMN "t_data_tracer"."data_id" IS '各种单据的id';
COMMENT ON COLUMN "t_data_tracer"."type" IS '单据类型';
COMMENT ON COLUMN "t_data_tracer"."content" IS '操作内容';
COMMENT ON COLUMN "t_data_tracer"."diff_old" IS '差异：旧的数据';
COMMENT ON COLUMN "t_data_tracer"."diff_new" IS '差异：新的数据';
COMMENT ON COLUMN "t_data_tracer"."extra_data" IS '额外信息';
COMMENT ON COLUMN "t_data_tracer"."user_id" IS '用户id';
COMMENT ON COLUMN "t_data_tracer"."user_type" IS '用户类型：1 后管用户 ';
COMMENT ON COLUMN "t_data_tracer"."user_name" IS '用户名称';
COMMENT ON COLUMN "t_data_tracer"."ip" IS 'ip';
COMMENT ON COLUMN "t_data_tracer"."ip_region" IS 'ip地区';
COMMENT ON COLUMN "t_data_tracer"."user_agent" IS '用户ua';
COMMENT ON COLUMN "t_data_tracer"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_data_tracer"."create_time" IS '创建时间';
CREATE INDEX "order_id_order_type" ON "t_data_tracer" ("data_id", "type");
CREATE TRIGGER "trg_t_data_tracer_update_time" BEFORE UPDATE ON "t_data_tracer"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_department  部门
-- ----------------------------
DROP TABLE IF EXISTS "t_department";
CREATE TABLE "t_department" (
  "department_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "department_name" varchar(50) NOT NULL,
  "manager_id" bigint,
  "parent_id" bigint NOT NULL DEFAULT 0,
  "sort" integer NOT NULL,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("department_id")
);
COMMENT ON TABLE "t_department" IS '部门';
COMMENT ON COLUMN "t_department"."department_id" IS '部门主键id';
COMMENT ON COLUMN "t_department"."department_name" IS '部门名称';
COMMENT ON COLUMN "t_department"."manager_id" IS '部门负责人id';
COMMENT ON COLUMN "t_department"."parent_id" IS '部门的父级id';
COMMENT ON COLUMN "t_department"."sort" IS '部门排序';
COMMENT ON COLUMN "t_department"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_department"."create_time" IS '创建时间';
CREATE INDEX "parent_id" ON "t_department" ("parent_id");

-- ----------------------------
-- t_dict  字典表
-- ----------------------------
DROP TABLE IF EXISTS "t_dict";
CREATE TABLE "t_dict" (
  "dict_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "dict_name" varchar(500) NOT NULL,
  "dict_code" varchar(500) NOT NULL,
  "remark" varchar(1000),
  "disabled_flag" smallint NOT NULL DEFAULT 0,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("dict_id"),
  CONSTRAINT "unique_code" UNIQUE ("dict_code")
);
COMMENT ON TABLE "t_dict" IS '字典表';
COMMENT ON COLUMN "t_dict"."dict_id" IS '字典id';
COMMENT ON COLUMN "t_dict"."dict_name" IS '字典名字';
COMMENT ON COLUMN "t_dict"."dict_code" IS '字典编码';
COMMENT ON COLUMN "t_dict"."remark" IS '字典备注';
COMMENT ON COLUMN "t_dict"."disabled_flag" IS '禁用状态';
COMMENT ON COLUMN "t_dict"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_dict"."update_time" IS '更新时间';
CREATE TRIGGER "trg_t_dict_update_time" BEFORE UPDATE ON "t_dict"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_dict_data  字典数据表
-- ----------------------------
DROP TABLE IF EXISTS "t_dict_data";
CREATE TABLE "t_dict_data" (
  "dict_data_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "dict_id" bigint NOT NULL,
  "data_value" varchar(500) NOT NULL,
  "data_label" varchar(500) NOT NULL,
  "data_style" varchar(500),
  "remark" varchar(1000),
  "sort_order" integer NOT NULL,
  "disabled_flag" smallint NOT NULL DEFAULT 0,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("dict_data_id")
);
COMMENT ON TABLE "t_dict_data" IS '字典数据表';
COMMENT ON COLUMN "t_dict_data"."dict_data_id" IS '字典数据id';
COMMENT ON COLUMN "t_dict_data"."dict_id" IS '字典id';
COMMENT ON COLUMN "t_dict_data"."data_value" IS '字典项值';
COMMENT ON COLUMN "t_dict_data"."data_label" IS '字典项显示名称';
COMMENT ON COLUMN "t_dict_data"."data_style" IS '字典项样式';
COMMENT ON COLUMN "t_dict_data"."remark" IS '备注';
COMMENT ON COLUMN "t_dict_data"."sort_order" IS '排序（越大越靠前）';
COMMENT ON COLUMN "t_dict_data"."disabled_flag" IS '禁用状态';
COMMENT ON COLUMN "t_dict_data"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_dict_data"."update_time" IS '更新时间';
CREATE TRIGGER "trg_t_dict_data_update_time" BEFORE UPDATE ON "t_dict_data"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_employee  员工表
-- ----------------------------
DROP TABLE IF EXISTS "t_employee";
CREATE TABLE "t_employee" (
  "employee_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_uid" varchar(100),
  "login_name" varchar(30) NOT NULL,
  "login_pwd" varchar(255) NOT NULL,
  "actual_name" varchar(30) NOT NULL,
  "avatar" varchar(200),
  "gender" smallint NOT NULL DEFAULT 0,
  "phone" varchar(15),
  "department_id" bigint NOT NULL,
  "position_id" bigint,
  "email" varchar(100),
  "disabled_flag" smallint NOT NULL,
  "deleted_flag" smallint NOT NULL,
  "administrator_flag" smallint NOT NULL DEFAULT 0,
  "remark" varchar(200),
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("employee_id"),
  CONSTRAINT "employee_uid_index" UNIQUE ("employee_uid")
);
COMMENT ON TABLE "t_employee" IS '员工表';
COMMENT ON COLUMN "t_employee"."employee_id" IS '主键';
COMMENT ON COLUMN "t_employee"."employee_uid" IS '员工uuid';
COMMENT ON COLUMN "t_employee"."login_name" IS '登录帐号';
COMMENT ON COLUMN "t_employee"."login_pwd" IS '登录密码(argon2)';
COMMENT ON COLUMN "t_employee"."actual_name" IS '员工名称';
COMMENT ON COLUMN "t_employee"."gender" IS '性别';
COMMENT ON COLUMN "t_employee"."phone" IS '手机号码';
COMMENT ON COLUMN "t_employee"."department_id" IS '部门id';
COMMENT ON COLUMN "t_employee"."position_id" IS '职务ID';
COMMENT ON COLUMN "t_employee"."email" IS '邮箱';
COMMENT ON COLUMN "t_employee"."disabled_flag" IS '是否被禁用 0否1是';
COMMENT ON COLUMN "t_employee"."deleted_flag" IS '是否删除0否 1是';
COMMENT ON COLUMN "t_employee"."administrator_flag" IS '是否为超级管理员: 0 不是，1是';
COMMENT ON COLUMN "t_employee"."remark" IS '备注';
COMMENT ON COLUMN "t_employee"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_employee"."create_time" IS '创建时间';
CREATE TRIGGER "trg_t_employee_update_time" BEFORE UPDATE ON "t_employee"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_feedback  意见反馈
-- ----------------------------
DROP TABLE IF EXISTS "t_feedback";
CREATE TABLE "t_feedback" (
  "feedback_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "feedback_content" text,
  "feedback_attachment" varchar(500),
  "user_id" bigint NOT NULL,
  "user_type" integer NOT NULL,
  "user_name" varchar(50) NOT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("feedback_id")
);
COMMENT ON TABLE "t_feedback" IS '意见反馈';
COMMENT ON COLUMN "t_feedback"."feedback_id" IS '主键';
COMMENT ON COLUMN "t_feedback"."feedback_content" IS '反馈内容';
COMMENT ON COLUMN "t_feedback"."feedback_attachment" IS '反馈图片';
COMMENT ON COLUMN "t_feedback"."user_id" IS '创建人id';
COMMENT ON COLUMN "t_feedback"."user_type" IS '创建人用户类型';
COMMENT ON COLUMN "t_feedback"."user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_feedback"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_feedback"."update_time" IS '更新时间';
CREATE TRIGGER "trg_t_feedback_update_time" BEFORE UPDATE ON "t_feedback"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_file  文件
-- ----------------------------
DROP TABLE IF EXISTS "t_file";
CREATE TABLE "t_file" (
  "file_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "folder_type" smallint NOT NULL,
  "file_name" varchar(100),
  "file_size" integer,
  "file_key" varchar(200) NOT NULL,
  "file_type" varchar(50) NOT NULL,
  "creator_id" bigint,
  "creator_user_type" integer,
  "creator_name" varchar(100),
  "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("file_id"),
  CONSTRAINT "uk_file_key" UNIQUE ("file_key")
);
COMMENT ON TABLE "t_file" IS '文件';
COMMENT ON COLUMN "t_file"."file_id" IS '主键ID';
COMMENT ON COLUMN "t_file"."folder_type" IS '文件夹类型';
COMMENT ON COLUMN "t_file"."file_name" IS '文件名称';
COMMENT ON COLUMN "t_file"."file_size" IS '文件大小';
COMMENT ON COLUMN "t_file"."file_key" IS '文件key，用于文件下载';
COMMENT ON COLUMN "t_file"."file_type" IS '文件类型';
COMMENT ON COLUMN "t_file"."creator_id" IS '创建人，即上传人';
COMMENT ON COLUMN "t_file"."creator_user_type" IS '创建人用户类型';
COMMENT ON COLUMN "t_file"."creator_name" IS '创建人姓名';
COMMENT ON COLUMN "t_file"."update_time" IS '上次更新时间';
COMMENT ON COLUMN "t_file"."create_time" IS '创建时间';
CREATE INDEX "module_id_module_type" ON "t_file" ("folder_type");

-- ----------------------------
-- t_goods  商品
-- ----------------------------
DROP TABLE IF EXISTS "t_goods";
CREATE TABLE "t_goods" (
  "goods_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "goods_status" integer,
  "category_id" integer NOT NULL,
  "goods_name" varchar(50) NOT NULL,
  "place" varchar(255),
  "price" numeric(10,2) NOT NULL,
  "shelves_flag" smallint NOT NULL,
  "deleted_flag" smallint NOT NULL,
  "remark" varchar(255),
  "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("goods_id")
);
COMMENT ON TABLE "t_goods" IS '商品';
COMMENT ON COLUMN "t_goods"."goods_status" IS '商品状态:[1:预约中,2:售卖中,3:售罄]';
COMMENT ON COLUMN "t_goods"."category_id" IS '商品类目';
COMMENT ON COLUMN "t_goods"."goods_name" IS '商品名称';
COMMENT ON COLUMN "t_goods"."place" IS '产地';
COMMENT ON COLUMN "t_goods"."price" IS '价格';
COMMENT ON COLUMN "t_goods"."shelves_flag" IS '上架状态';
COMMENT ON COLUMN "t_goods"."deleted_flag" IS '删除状态';
COMMENT ON COLUMN "t_goods"."remark" IS '备注';
CREATE TRIGGER "trg_t_goods_update_time" BEFORE UPDATE ON "t_goods"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_heart_beat_record  公用服务 - 服务心跳
-- ----------------------------
DROP TABLE IF EXISTS "t_heart_beat_record";
CREATE TABLE "t_heart_beat_record" (
  "heart_beat_record_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_path" varchar(100) NOT NULL,
  "server_ip" varchar(200) NOT NULL,
  "process_no" integer NOT NULL,
  "process_start_time" timestamp NOT NULL,
  "heart_beat_time" timestamp NOT NULL,
  PRIMARY KEY ("heart_beat_record_id")
);
COMMENT ON TABLE "t_heart_beat_record" IS '公用服务 - 服务心跳';
COMMENT ON COLUMN "t_heart_beat_record"."heart_beat_record_id" IS '自增id';
COMMENT ON COLUMN "t_heart_beat_record"."project_path" IS '项目名称';
COMMENT ON COLUMN "t_heart_beat_record"."server_ip" IS '服务器ip';
COMMENT ON COLUMN "t_heart_beat_record"."process_no" IS '进程号';
COMMENT ON COLUMN "t_heart_beat_record"."process_start_time" IS '进程开启时间';
COMMENT ON COLUMN "t_heart_beat_record"."heart_beat_time" IS '心跳时间';

-- ----------------------------
-- t_help_doc  帮助文档
-- ----------------------------
DROP TABLE IF EXISTS "t_help_doc";
CREATE TABLE "t_help_doc" (
  "help_doc_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "help_doc_catalog_id" bigint NOT NULL,
  "title" varchar(200) NOT NULL,
  "content_text" text NOT NULL,
  "content_html" text NOT NULL,
  "attachment" varchar(1000),
  "sort" integer NOT NULL DEFAULT 0,
  "page_view_count" integer NOT NULL DEFAULT 0,
  "user_view_count" integer NOT NULL DEFAULT 0,
  "author" varchar(1000),
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("help_doc_id")
);
COMMENT ON TABLE "t_help_doc" IS '帮助文档';
COMMENT ON COLUMN "t_help_doc"."help_doc_catalog_id" IS '类型1公告 2动态';
COMMENT ON COLUMN "t_help_doc"."title" IS '标题';
COMMENT ON COLUMN "t_help_doc"."content_text" IS '文本内容';
COMMENT ON COLUMN "t_help_doc"."content_html" IS 'html内容';
COMMENT ON COLUMN "t_help_doc"."attachment" IS '附件';
COMMENT ON COLUMN "t_help_doc"."sort" IS '排序';
COMMENT ON COLUMN "t_help_doc"."page_view_count" IS '页面浏览量，传说中的pv';
COMMENT ON COLUMN "t_help_doc"."user_view_count" IS '用户浏览量，传说中的uv';
COMMENT ON COLUMN "t_help_doc"."author" IS '作者';
CREATE TRIGGER "trg_t_help_doc_update_time" BEFORE UPDATE ON "t_help_doc"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_help_doc_catalog  帮助文档-目录
-- ----------------------------
DROP TABLE IF EXISTS "t_help_doc_catalog";
CREATE TABLE "t_help_doc_catalog" (
  "help_doc_catalog_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(1000) NOT NULL,
  "sort" integer NOT NULL DEFAULT 0,
  "parent_id" bigint NOT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("help_doc_catalog_id")
);
COMMENT ON TABLE "t_help_doc_catalog" IS '帮助文档-目录';
COMMENT ON COLUMN "t_help_doc_catalog"."help_doc_catalog_id" IS '帮助文档目录';
COMMENT ON COLUMN "t_help_doc_catalog"."name" IS '名称';
COMMENT ON COLUMN "t_help_doc_catalog"."sort" IS '排序字段';
COMMENT ON COLUMN "t_help_doc_catalog"."parent_id" IS '父级id';
CREATE TRIGGER "trg_t_help_doc_catalog_update_time" BEFORE UPDATE ON "t_help_doc_catalog"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_help_doc_relation  帮助文档-关联表
-- ----------------------------
DROP TABLE IF EXISTS "t_help_doc_relation";
CREATE TABLE "t_help_doc_relation" (
  "relation_id" bigint NOT NULL,
  "relation_name" varchar(255),
  "help_doc_id" bigint NOT NULL,
  "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("relation_id", "help_doc_id")
);
COMMENT ON TABLE "t_help_doc_relation" IS '帮助文档-关联表';
COMMENT ON COLUMN "t_help_doc_relation"."relation_id" IS '关联id';
COMMENT ON COLUMN "t_help_doc_relation"."relation_name" IS '关联名称';
COMMENT ON COLUMN "t_help_doc_relation"."help_doc_id" IS '文档id';
CREATE TRIGGER "trg_t_help_doc_relation_update_time" BEFORE UPDATE ON "t_help_doc_relation"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_help_doc_view_record  帮助文档-查看记录
-- ----------------------------
DROP TABLE IF EXISTS "t_help_doc_view_record";
CREATE TABLE "t_help_doc_view_record" (
  "help_doc_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "user_name" varchar(255),
  "page_view_count" integer DEFAULT 0,
  "first_ip" varchar(255),
  "first_user_agent" varchar(1000),
  "last_ip" varchar(255),
  "last_user_agent" varchar(1000),
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("help_doc_id", "user_id")
);
COMMENT ON TABLE "t_help_doc_view_record" IS '帮助文档-查看记录';
COMMENT ON COLUMN "t_help_doc_view_record"."help_doc_id" IS '通知公告id';
COMMENT ON COLUMN "t_help_doc_view_record"."user_id" IS '用户id';
COMMENT ON COLUMN "t_help_doc_view_record"."user_name" IS '用户名称';
COMMENT ON COLUMN "t_help_doc_view_record"."page_view_count" IS '查看次数';
COMMENT ON COLUMN "t_help_doc_view_record"."first_ip" IS '首次ip';
COMMENT ON COLUMN "t_help_doc_view_record"."first_user_agent" IS '首次用户设备等标识';
COMMENT ON COLUMN "t_help_doc_view_record"."last_ip" IS '最后一次ip';
COMMENT ON COLUMN "t_help_doc_view_record"."last_user_agent" IS '最后一次用户设备等标识';
CREATE TRIGGER "trg_t_help_doc_view_record_update_time" BEFORE UPDATE ON "t_help_doc_view_record"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_login_fail  登录失败次数记录表
-- ----------------------------
DROP TABLE IF EXISTS "t_login_fail";
CREATE TABLE "t_login_fail" (
  "login_fail_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" bigint NOT NULL,
  "user_type" integer NOT NULL,
  "login_name" varchar(1000),
  "login_fail_count" integer,
  "lock_flag" smallint DEFAULT 0,
  "login_lock_begin_time" timestamp,
  "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("login_fail_id"),
  CONSTRAINT "uid_and_utype" UNIQUE ("user_id", "user_type")
);
COMMENT ON TABLE "t_login_fail" IS '登录失败次数记录表';
COMMENT ON COLUMN "t_login_fail"."login_fail_id" IS '自增id';
COMMENT ON COLUMN "t_login_fail"."user_id" IS '用户id';
COMMENT ON COLUMN "t_login_fail"."user_type" IS '用户类型';
COMMENT ON COLUMN "t_login_fail"."login_name" IS '登录名';
COMMENT ON COLUMN "t_login_fail"."login_fail_count" IS '连续登录失败次数';
COMMENT ON COLUMN "t_login_fail"."lock_flag" IS '锁定状态:1锁定，0未锁定';
COMMENT ON COLUMN "t_login_fail"."login_lock_begin_time" IS '连续登录失败锁定开始时间';
COMMENT ON COLUMN "t_login_fail"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_login_fail"."update_time" IS '更新时间';
CREATE TRIGGER "trg_t_login_fail_update_time" BEFORE UPDATE ON "t_login_fail"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_login_log  用户登录日志
-- ----------------------------
DROP TABLE IF EXISTS "t_login_log";
CREATE TABLE "t_login_log" (
  "login_log_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer NOT NULL,
  "user_type" integer NOT NULL,
  "user_name" varchar(1000) NOT NULL,
  "login_ip" varchar(1000),
  "login_ip_region" varchar(1000),
  "user_agent" text,
  "login_device" varchar(1000),
  "login_result" integer NOT NULL,
  "remark" varchar(2000),
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("login_log_id")
);
COMMENT ON TABLE "t_login_log" IS '用户登录日志';
COMMENT ON COLUMN "t_login_log"."login_log_id" IS '主键';
COMMENT ON COLUMN "t_login_log"."user_id" IS '用户id';
COMMENT ON COLUMN "t_login_log"."user_type" IS '用户类型';
COMMENT ON COLUMN "t_login_log"."user_name" IS '用户名';
COMMENT ON COLUMN "t_login_log"."login_ip" IS '用户ip';
COMMENT ON COLUMN "t_login_log"."login_ip_region" IS '用户ip地区';
COMMENT ON COLUMN "t_login_log"."user_agent" IS 'user-agent信息';
COMMENT ON COLUMN "t_login_log"."login_device" IS '登录设备';
COMMENT ON COLUMN "t_login_log"."login_result" IS '登录结果：0成功 1失败 2 退出';
COMMENT ON COLUMN "t_login_log"."remark" IS '备注';
COMMENT ON COLUMN "t_login_log"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_login_log"."create_time" IS '创建时间';
CREATE INDEX "customer_id" ON "t_login_log" ("user_id");
CREATE TRIGGER "trg_t_login_log_update_time" BEFORE UPDATE ON "t_login_log"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_mail_template
-- ----------------------------
DROP TABLE IF EXISTS "t_mail_template";
CREATE TABLE "t_mail_template" (
  "template_code" varchar(200) NOT NULL,
  "template_subject" varchar(100) NOT NULL,
  "template_content" text NOT NULL,
  "template_type" varchar(50) NOT NULL,
  "disable_flag" smallint NOT NULL DEFAULT 0,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("template_code")
);
COMMENT ON COLUMN "t_mail_template"."template_subject" IS '模板名称';
COMMENT ON COLUMN "t_mail_template"."template_content" IS '模板内容';
COMMENT ON COLUMN "t_mail_template"."template_type" IS '解析类型 string，freemarker';
COMMENT ON COLUMN "t_mail_template"."disable_flag" IS '是否禁用';
COMMENT ON COLUMN "t_mail_template"."update_time" IS '创建时间';
COMMENT ON COLUMN "t_mail_template"."create_time" IS '创建时间';
CREATE TRIGGER "trg_t_mail_template_update_time" BEFORE UPDATE ON "t_mail_template"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_menu  菜单表
-- ----------------------------
DROP TABLE IF EXISTS "t_menu";
CREATE TABLE "t_menu" (
  "menu_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "menu_name" varchar(200) NOT NULL,
  "menu_type" integer NOT NULL,
  "parent_id" bigint NOT NULL,
  "sort" integer,
  "path" varchar(255),
  "component" varchar(255),
  "perms_type" integer,
  "api_perms" varchar(5000),
  "web_perms" varchar(5000),
  "icon" varchar(100),
  "context_menu_id" bigint,
  "frame_flag" smallint NOT NULL DEFAULT 0,
  "frame_url" text,
  "cache_flag" smallint NOT NULL DEFAULT 0,
  "visible_flag" smallint NOT NULL DEFAULT 1,
  "disabled_flag" smallint NOT NULL DEFAULT 0,
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  "create_user_id" bigint NOT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_user_id" bigint,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("menu_id")
);
COMMENT ON TABLE "t_menu" IS '菜单表';
COMMENT ON COLUMN "t_menu"."menu_id" IS '菜单ID';
COMMENT ON COLUMN "t_menu"."menu_name" IS '菜单名称';
COMMENT ON COLUMN "t_menu"."menu_type" IS '类型';
COMMENT ON COLUMN "t_menu"."parent_id" IS '父菜单ID';
COMMENT ON COLUMN "t_menu"."sort" IS '显示顺序';
COMMENT ON COLUMN "t_menu"."path" IS '路由地址';
COMMENT ON COLUMN "t_menu"."component" IS '组件路径';
COMMENT ON COLUMN "t_menu"."perms_type" IS '权限类型';
COMMENT ON COLUMN "t_menu"."api_perms" IS '后端权限字符串';
COMMENT ON COLUMN "t_menu"."web_perms" IS '前端权限字符串';
COMMENT ON COLUMN "t_menu"."icon" IS '菜单图标';
COMMENT ON COLUMN "t_menu"."context_menu_id" IS '功能点关联菜单ID';
COMMENT ON COLUMN "t_menu"."frame_flag" IS '是否为外链';
COMMENT ON COLUMN "t_menu"."frame_url" IS '外链地址';
COMMENT ON COLUMN "t_menu"."cache_flag" IS '是否缓存';
COMMENT ON COLUMN "t_menu"."visible_flag" IS '显示状态';
COMMENT ON COLUMN "t_menu"."disabled_flag" IS '禁用状态';
COMMENT ON COLUMN "t_menu"."deleted_flag" IS '删除状态';
COMMENT ON COLUMN "t_menu"."create_user_id" IS '创建人';
COMMENT ON COLUMN "t_menu"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_menu"."update_user_id" IS '更新人';
COMMENT ON COLUMN "t_menu"."update_time" IS '更新时间';
CREATE TRIGGER "trg_t_menu_update_time" BEFORE UPDATE ON "t_menu"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_message  通知消息
-- ----------------------------
DROP TABLE IF EXISTS "t_message";
CREATE TABLE "t_message" (
  "message_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "message_type" smallint NOT NULL,
  "receiver_user_type" integer NOT NULL,
  "receiver_user_id" bigint NOT NULL,
  "data_id" varchar(500) DEFAULT '',
  "title" varchar(1000) NOT NULL,
  "content" text NOT NULL,
  "read_flag" smallint NOT NULL DEFAULT 0,
  "read_time" timestamp,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("message_id")
);
COMMENT ON TABLE "t_message" IS '通知消息';
COMMENT ON COLUMN "t_message"."message_id" IS '消息id';
COMMENT ON COLUMN "t_message"."message_type" IS '消息类型';
COMMENT ON COLUMN "t_message"."receiver_user_type" IS '接收者用户类型';
COMMENT ON COLUMN "t_message"."receiver_user_id" IS '接收者用户id';
COMMENT ON COLUMN "t_message"."data_id" IS '相关数据id';
COMMENT ON COLUMN "t_message"."title" IS '标题';
COMMENT ON COLUMN "t_message"."content" IS '内容';
COMMENT ON COLUMN "t_message"."read_flag" IS '是否已读';
COMMENT ON COLUMN "t_message"."read_time" IS '已读时间';
COMMENT ON COLUMN "t_message"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_message"."update_time" IS '更新时间';
CREATE INDEX "idx_msg" ON "t_message" ("message_type", "receiver_user_type", "receiver_user_id");
CREATE TRIGGER "trg_t_message_update_time" BEFORE UPDATE ON "t_message"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_notice  通知
-- ----------------------------
DROP TABLE IF EXISTS "t_notice";
CREATE TABLE "t_notice" (
  "notice_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "notice_type_id" bigint NOT NULL,
  "title" varchar(200) NOT NULL,
  "all_visible_flag" smallint NOT NULL,
  "scheduled_publish_flag" smallint NOT NULL,
  "publish_time" timestamp NOT NULL,
  "content_text" text NOT NULL,
  "content_html" text NOT NULL,
  "attachment" varchar(1000),
  "page_view_count" integer NOT NULL DEFAULT 0,
  "user_view_count" integer NOT NULL DEFAULT 0,
  "source" varchar(1000),
  "author" varchar(1000),
  "document_number" varchar(1000),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  "create_user_id" bigint,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("notice_id")
);
COMMENT ON TABLE "t_notice" IS '通知';
COMMENT ON COLUMN "t_notice"."notice_type_id" IS '类型1公告 2动态';
COMMENT ON COLUMN "t_notice"."title" IS '标题';
COMMENT ON COLUMN "t_notice"."all_visible_flag" IS '是否全部可见';
COMMENT ON COLUMN "t_notice"."scheduled_publish_flag" IS '是否定时发布';
COMMENT ON COLUMN "t_notice"."publish_time" IS '发布时间';
COMMENT ON COLUMN "t_notice"."content_text" IS '文本内容';
COMMENT ON COLUMN "t_notice"."content_html" IS 'html内容';
COMMENT ON COLUMN "t_notice"."attachment" IS '附件';
COMMENT ON COLUMN "t_notice"."page_view_count" IS '页面浏览量，传说中的pv';
COMMENT ON COLUMN "t_notice"."user_view_count" IS '用户浏览量，传说中的uv';
COMMENT ON COLUMN "t_notice"."source" IS '来源';
COMMENT ON COLUMN "t_notice"."author" IS '作者';
COMMENT ON COLUMN "t_notice"."document_number" IS '文号，如：1024创新实验室发〔2022〕字第36号';
COMMENT ON COLUMN "t_notice"."create_user_id" IS '创建人';
CREATE TRIGGER "trg_t_notice_update_time" BEFORE UPDATE ON "t_notice"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_notice_type  通知类型
-- ----------------------------
DROP TABLE IF EXISTS "t_notice_type";
CREATE TABLE "t_notice_type" (
  "notice_type_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "notice_type_name" varchar(1000) NOT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("notice_type_id")
);
COMMENT ON TABLE "t_notice_type" IS '通知类型';
COMMENT ON COLUMN "t_notice_type"."notice_type_id" IS '通知类型';
COMMENT ON COLUMN "t_notice_type"."notice_type_name" IS '类型名称';
CREATE TRIGGER "trg_t_notice_type_update_time" BEFORE UPDATE ON "t_notice_type"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_notice_view_record  通知查看记录
-- ----------------------------
DROP TABLE IF EXISTS "t_notice_view_record";
CREATE TABLE "t_notice_view_record" (
  "notice_id" bigint NOT NULL,
  "employee_id" bigint NOT NULL,
  "page_view_count" integer DEFAULT 0,
  "first_ip" varchar(255),
  "first_user_agent" varchar(1000),
  "last_ip" varchar(255),
  "last_user_agent" varchar(1000),
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("notice_id", "employee_id")
);
COMMENT ON TABLE "t_notice_view_record" IS '通知查看记录';
COMMENT ON COLUMN "t_notice_view_record"."notice_id" IS '通知公告id';
COMMENT ON COLUMN "t_notice_view_record"."employee_id" IS '员工id';
COMMENT ON COLUMN "t_notice_view_record"."page_view_count" IS '查看次数';
COMMENT ON COLUMN "t_notice_view_record"."first_ip" IS '首次ip';
COMMENT ON COLUMN "t_notice_view_record"."first_user_agent" IS '首次用户设备等标识';
COMMENT ON COLUMN "t_notice_view_record"."last_ip" IS '最后一次ip';
COMMENT ON COLUMN "t_notice_view_record"."last_user_agent" IS '最后一次用户设备等标识';
CREATE TRIGGER "trg_t_notice_view_record_update_time" BEFORE UPDATE ON "t_notice_view_record"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_notice_visible_range  通知可见范围
-- ----------------------------
DROP TABLE IF EXISTS "t_notice_visible_range";
CREATE TABLE "t_notice_visible_range" (
  "notice_id" bigint NOT NULL,
  "data_type" smallint NOT NULL,
  "data_id" bigint NOT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "uk_notice_data" UNIQUE ("notice_id", "data_type", "data_id")
);
COMMENT ON TABLE "t_notice_visible_range" IS '通知可见范围';
COMMENT ON COLUMN "t_notice_visible_range"."notice_id" IS '资讯id';
COMMENT ON COLUMN "t_notice_visible_range"."data_type" IS '数据类型1员工 2部门';
COMMENT ON COLUMN "t_notice_visible_range"."data_id" IS '员工or部门id';

-- ----------------------------
-- t_oa_bank  OA银行信息\n
-- ----------------------------
DROP TABLE IF EXISTS "t_oa_bank";
CREATE TABLE "t_oa_bank" (
  "bank_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "bank_name" varchar(255) NOT NULL,
  "account_name" varchar(255) NOT NULL,
  "account_number" varchar(255) NOT NULL,
  "remark" varchar(255),
  "business_flag" smallint NOT NULL,
  "enterprise_id" bigint NOT NULL,
  "disabled_flag" smallint NOT NULL DEFAULT 0,
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  "create_user_id" bigint NOT NULL,
  "create_user_name" varchar(50) NOT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("bank_id")
);
COMMENT ON TABLE "t_oa_bank" IS 'OA银行信息\n';
COMMENT ON COLUMN "t_oa_bank"."bank_id" IS '银行信息ID';
COMMENT ON COLUMN "t_oa_bank"."bank_name" IS '开户银行';
COMMENT ON COLUMN "t_oa_bank"."account_name" IS '账户名称';
COMMENT ON COLUMN "t_oa_bank"."account_number" IS '账号';
COMMENT ON COLUMN "t_oa_bank"."remark" IS '备注';
COMMENT ON COLUMN "t_oa_bank"."business_flag" IS '是否对公';
COMMENT ON COLUMN "t_oa_bank"."enterprise_id" IS '企业ID';
COMMENT ON COLUMN "t_oa_bank"."disabled_flag" IS '禁用状态';
COMMENT ON COLUMN "t_oa_bank"."deleted_flag" IS '删除状态';
COMMENT ON COLUMN "t_oa_bank"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_oa_bank"."create_user_name" IS '创建人';
COMMENT ON COLUMN "t_oa_bank"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_oa_bank"."update_time" IS '更新时间';
CREATE INDEX "idx_enterprise_id" ON "t_oa_bank" ("enterprise_id");
CREATE TRIGGER "trg_t_oa_bank_update_time" BEFORE UPDATE ON "t_oa_bank"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_oa_enterprise  OA企业模块\r\n
-- ----------------------------
DROP TABLE IF EXISTS "t_oa_enterprise";
CREATE TABLE "t_oa_enterprise" (
  "enterprise_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "enterprise_name" varchar(255) NOT NULL,
  "enterprise_logo" varchar(255),
  "type" integer NOT NULL DEFAULT 1,
  "unified_social_credit_code" varchar(255) NOT NULL,
  "contact" varchar(100) NOT NULL,
  "contact_phone" varchar(100) NOT NULL,
  "email" varchar(100),
  "province" varchar(100),
  "province_name" varchar(100),
  "city" varchar(100),
  "city_name" varchar(100),
  "district" varchar(100),
  "district_name" varchar(100),
  "address" varchar(255),
  "business_license" varchar(255),
  "disabled_flag" smallint NOT NULL DEFAULT 0,
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  "create_user_id" bigint NOT NULL,
  "create_user_name" varchar(50) NOT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("enterprise_id")
);
COMMENT ON TABLE "t_oa_enterprise" IS 'OA企业模块\r\n';
COMMENT ON COLUMN "t_oa_enterprise"."enterprise_id" IS '企业ID';
COMMENT ON COLUMN "t_oa_enterprise"."enterprise_name" IS '企业名称';
COMMENT ON COLUMN "t_oa_enterprise"."enterprise_logo" IS '企业logo';
COMMENT ON COLUMN "t_oa_enterprise"."type" IS '类型（1:有限公司;2:合伙公司）';
COMMENT ON COLUMN "t_oa_enterprise"."unified_social_credit_code" IS '统一社会信用代码';
COMMENT ON COLUMN "t_oa_enterprise"."contact" IS '联系人';
COMMENT ON COLUMN "t_oa_enterprise"."contact_phone" IS '联系人电话';
COMMENT ON COLUMN "t_oa_enterprise"."email" IS '邮箱';
COMMENT ON COLUMN "t_oa_enterprise"."province" IS '省份';
COMMENT ON COLUMN "t_oa_enterprise"."province_name" IS '省份名称';
COMMENT ON COLUMN "t_oa_enterprise"."city" IS '市';
COMMENT ON COLUMN "t_oa_enterprise"."city_name" IS '城市名称';
COMMENT ON COLUMN "t_oa_enterprise"."district" IS '区县';
COMMENT ON COLUMN "t_oa_enterprise"."district_name" IS '区县名称';
COMMENT ON COLUMN "t_oa_enterprise"."address" IS '详细地址';
COMMENT ON COLUMN "t_oa_enterprise"."business_license" IS '营业执照';
COMMENT ON COLUMN "t_oa_enterprise"."disabled_flag" IS '禁用状态';
COMMENT ON COLUMN "t_oa_enterprise"."deleted_flag" IS '删除状态';
COMMENT ON COLUMN "t_oa_enterprise"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_oa_enterprise"."create_user_name" IS '创建人';
COMMENT ON COLUMN "t_oa_enterprise"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_oa_enterprise"."update_time" IS '更新时间';
CREATE TRIGGER "trg_t_oa_enterprise_update_time" BEFORE UPDATE ON "t_oa_enterprise"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_oa_enterprise_employee  企业关联的员工
-- ----------------------------
DROP TABLE IF EXISTS "t_oa_enterprise_employee";
CREATE TABLE "t_oa_enterprise_employee" (
  "enterprise_employee_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "enterprise_id" varchar(100) NOT NULL,
  "employee_id" varchar(100) NOT NULL,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("enterprise_employee_id"),
  CONSTRAINT "uk_enterprise_employee" UNIQUE ("enterprise_id", "employee_id")
);
COMMENT ON TABLE "t_oa_enterprise_employee" IS '企业关联的员工';
COMMENT ON COLUMN "t_oa_enterprise_employee"."enterprise_employee_id" IS '主键ID';
COMMENT ON COLUMN "t_oa_enterprise_employee"."enterprise_id" IS '订单ID';
COMMENT ON COLUMN "t_oa_enterprise_employee"."employee_id" IS '货物名称';
COMMENT ON COLUMN "t_oa_enterprise_employee"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_oa_enterprise_employee"."create_time" IS '创建时间';
CREATE INDEX "idx_employee_id" ON "t_oa_enterprise_employee" ("employee_id");
CREATE INDEX "t_oa_enterprise_employee_idx_enterprise_id" ON "t_oa_enterprise_employee" ("enterprise_id");
CREATE TRIGGER "trg_t_oa_enterprise_employee_update_time" BEFORE UPDATE ON "t_oa_enterprise_employee"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_oa_invoice  OA发票信息\n
-- ----------------------------
DROP TABLE IF EXISTS "t_oa_invoice";
CREATE TABLE "t_oa_invoice" (
  "invoice_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "invoice_heads" varchar(255) NOT NULL,
  "taxpayer_identification_number" varchar(255) NOT NULL,
  "account_number" varchar(255) NOT NULL,
  "bank_name" varchar(255) NOT NULL,
  "remark" varchar(255),
  "enterprise_id" bigint NOT NULL,
  "disabled_flag" smallint NOT NULL DEFAULT 0,
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  "create_user_id" bigint NOT NULL,
  "create_user_name" varchar(50) NOT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("invoice_id")
);
COMMENT ON TABLE "t_oa_invoice" IS 'OA发票信息\n';
COMMENT ON COLUMN "t_oa_invoice"."invoice_id" IS '发票信息ID';
COMMENT ON COLUMN "t_oa_invoice"."invoice_heads" IS '开票抬头';
COMMENT ON COLUMN "t_oa_invoice"."taxpayer_identification_number" IS '纳税人识别号';
COMMENT ON COLUMN "t_oa_invoice"."account_number" IS '银行账户';
COMMENT ON COLUMN "t_oa_invoice"."bank_name" IS '开户行';
COMMENT ON COLUMN "t_oa_invoice"."remark" IS '备注';
COMMENT ON COLUMN "t_oa_invoice"."enterprise_id" IS '企业ID';
COMMENT ON COLUMN "t_oa_invoice"."disabled_flag" IS '禁用状态';
COMMENT ON COLUMN "t_oa_invoice"."deleted_flag" IS '删除状态';
COMMENT ON COLUMN "t_oa_invoice"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_oa_invoice"."create_user_name" IS '创建人';
COMMENT ON COLUMN "t_oa_invoice"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_oa_invoice"."update_time" IS '更新时间';
CREATE INDEX "t_oa_invoice_idx_enterprise_id" ON "t_oa_invoice" ("enterprise_id");
CREATE TRIGGER "trg_t_oa_invoice_update_time" BEFORE UPDATE ON "t_oa_invoice"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_operate_log  操作记录
-- ----------------------------
DROP TABLE IF EXISTS "t_operate_log";
CREATE TABLE "t_operate_log" (
  "operate_log_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "operate_user_id" bigint NOT NULL,
  "operate_user_type" integer NOT NULL,
  "operate_user_name" varchar(500) NOT NULL,
  "module" varchar(500),
  "content" text,
  "url" text,
  "method" text,
  "param" text,
  "response" text,
  "ip" varchar(1000),
  "ip_region" varchar(1000),
  "user_agent" text,
  "success_flag" smallint,
  "fail_reason" text,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("operate_log_id")
);
COMMENT ON TABLE "t_operate_log" IS '操作记录';
COMMENT ON COLUMN "t_operate_log"."operate_log_id" IS '主键';
COMMENT ON COLUMN "t_operate_log"."operate_user_id" IS '用户id';
COMMENT ON COLUMN "t_operate_log"."operate_user_type" IS '用户类型';
COMMENT ON COLUMN "t_operate_log"."operate_user_name" IS '用户名称';
COMMENT ON COLUMN "t_operate_log"."module" IS '操作模块';
COMMENT ON COLUMN "t_operate_log"."content" IS '操作内容';
COMMENT ON COLUMN "t_operate_log"."url" IS '请求路径';
COMMENT ON COLUMN "t_operate_log"."method" IS '请求方法';
COMMENT ON COLUMN "t_operate_log"."param" IS '请求参数';
COMMENT ON COLUMN "t_operate_log"."response" IS '返回值';
COMMENT ON COLUMN "t_operate_log"."ip" IS '请求ip';
COMMENT ON COLUMN "t_operate_log"."ip_region" IS '请求ip地区';
COMMENT ON COLUMN "t_operate_log"."user_agent" IS '请求user-agent';
COMMENT ON COLUMN "t_operate_log"."success_flag" IS '请求结果 0失败 1成功';
COMMENT ON COLUMN "t_operate_log"."fail_reason" IS '失败原因';
COMMENT ON COLUMN "t_operate_log"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_operate_log"."create_time" IS '创建时间';
CREATE TRIGGER "trg_t_operate_log_update_time" BEFORE UPDATE ON "t_operate_log"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_password_log  密码修改记录
-- ----------------------------
DROP TABLE IF EXISTS "t_password_log";
CREATE TABLE "t_password_log" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" bigint NOT NULL,
  "user_type" smallint NOT NULL,
  "old_password" varchar(255) NOT NULL,
  "new_password" varchar(255),
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "t_password_log" IS '密码修改记录';
COMMENT ON COLUMN "t_password_log"."id" IS '主键';
COMMENT ON COLUMN "t_password_log"."user_id" IS '用户id';
COMMENT ON COLUMN "t_password_log"."user_type" IS '用户类型';
COMMENT ON COLUMN "t_password_log"."old_password" IS '旧密码';
COMMENT ON COLUMN "t_password_log"."new_password" IS '新密码';
COMMENT ON COLUMN "t_password_log"."update_time" IS '创建时间';
COMMENT ON COLUMN "t_password_log"."create_time" IS '创建时间';
CREATE INDEX "user_and_type_index" ON "t_password_log" ("user_id", "user_type");
CREATE TRIGGER "trg_t_password_log_update_time" BEFORE UPDATE ON "t_password_log"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_position  职务表
-- ----------------------------
DROP TABLE IF EXISTS "t_position";
CREATE TABLE "t_position" (
  "position_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "position_name" varchar(200) NOT NULL,
  "position_level" varchar(200),
  "sort" integer DEFAULT 0,
  "remark" varchar(200),
  "deleted_flag" smallint DEFAULT 0,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("position_id")
);
COMMENT ON TABLE "t_position" IS '职务表';
COMMENT ON COLUMN "t_position"."position_id" IS '职务ID';
COMMENT ON COLUMN "t_position"."position_name" IS '职务名称';
COMMENT ON COLUMN "t_position"."position_level" IS '职级';
COMMENT ON COLUMN "t_position"."sort" IS '排序';
COMMENT ON COLUMN "t_position"."remark" IS '备注';
CREATE TRIGGER "trg_t_position_update_time" BEFORE UPDATE ON "t_position"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_reload_item  reload项目
-- ----------------------------
DROP TABLE IF EXISTS "t_reload_item";
CREATE TABLE "t_reload_item" (
  "tag" varchar(255) NOT NULL,
  "args" varchar(255),
  "identification" varchar(255) NOT NULL,
  "update_time" timestamp,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("tag")
);
COMMENT ON TABLE "t_reload_item" IS 'reload项目';
COMMENT ON COLUMN "t_reload_item"."tag" IS '项名称';
COMMENT ON COLUMN "t_reload_item"."args" IS '参数 可选';
COMMENT ON COLUMN "t_reload_item"."identification" IS '运行标识';
CREATE TRIGGER "trg_t_reload_item_update_time" BEFORE UPDATE ON "t_reload_item"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_reload_result  reload结果
-- ----------------------------
DROP TABLE IF EXISTS "t_reload_result";
CREATE TABLE "t_reload_result" (
  "tag" varchar(255) NOT NULL,
  "identification" varchar(255) NOT NULL,
  "args" varchar(255),
  "result" smallint NOT NULL,
  "exception" text,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE "t_reload_result" IS 'reload结果';
COMMENT ON COLUMN "t_reload_result"."identification" IS '运行标识';
COMMENT ON COLUMN "t_reload_result"."result" IS '是否成功 ';

-- ----------------------------
-- t_role  角色表
-- ----------------------------
DROP TABLE IF EXISTS "t_role";
CREATE TABLE "t_role" (
  "role_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "role_name" varchar(20) NOT NULL,
  "role_code" varchar(500),
  "remark" varchar(255),
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("role_id"),
  CONSTRAINT "role_code_uni" UNIQUE ("role_code")
);
COMMENT ON TABLE "t_role" IS '角色表';
COMMENT ON COLUMN "t_role"."role_id" IS '主键';
COMMENT ON COLUMN "t_role"."role_name" IS '角色名称';
COMMENT ON COLUMN "t_role"."role_code" IS '角色编码';
COMMENT ON COLUMN "t_role"."remark" IS '角色描述';
COMMENT ON COLUMN "t_role"."update_time" IS '创建时间';
COMMENT ON COLUMN "t_role"."create_time" IS '创建时间';
CREATE TRIGGER "trg_t_role_update_time" BEFORE UPDATE ON "t_role"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_role_data_scope  角色的数据范围
-- ----------------------------
DROP TABLE IF EXISTS "t_role_data_scope";
CREATE TABLE "t_role_data_scope" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "data_scope_type" integer NOT NULL,
  "view_type" integer NOT NULL,
  "role_id" bigint NOT NULL,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "t_role_data_scope" IS '角色的数据范围';
COMMENT ON COLUMN "t_role_data_scope"."data_scope_type" IS '数据范围类型';
COMMENT ON COLUMN "t_role_data_scope"."view_type" IS '数据可见范围类型';
COMMENT ON COLUMN "t_role_data_scope"."role_id" IS '角色id';
COMMENT ON COLUMN "t_role_data_scope"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_role_data_scope"."create_time" IS '创建时间';
CREATE TRIGGER "trg_t_role_data_scope_update_time" BEFORE UPDATE ON "t_role_data_scope"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_role_employee  角色员工功能表
-- ----------------------------
DROP TABLE IF EXISTS "t_role_employee";
CREATE TABLE "t_role_employee" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "role_id" bigint NOT NULL,
  "employee_id" bigint NOT NULL,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_role_employee" UNIQUE ("role_id", "employee_id")
);
COMMENT ON TABLE "t_role_employee" IS '角色员工功能表';
COMMENT ON COLUMN "t_role_employee"."role_id" IS '角色id';
COMMENT ON COLUMN "t_role_employee"."employee_id" IS '员工id';
COMMENT ON COLUMN "t_role_employee"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_role_employee"."create_time" IS '创建时间';
CREATE TRIGGER "trg_t_role_employee_update_time" BEFORE UPDATE ON "t_role_employee"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_role_menu  角色-菜单\n
-- ----------------------------
DROP TABLE IF EXISTS "t_role_menu";
CREATE TABLE "t_role_menu" (
  "role_menu_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "role_id" bigint NOT NULL,
  "menu_id" bigint NOT NULL,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("role_menu_id")
);
COMMENT ON TABLE "t_role_menu" IS '角色-菜单\n';
COMMENT ON COLUMN "t_role_menu"."role_menu_id" IS '主键id';
COMMENT ON COLUMN "t_role_menu"."role_id" IS '角色id';
COMMENT ON COLUMN "t_role_menu"."menu_id" IS '菜单id';
COMMENT ON COLUMN "t_role_menu"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_role_menu"."create_time" IS '创建时间';
CREATE INDEX "idx_role_id" ON "t_role_menu" ("role_id");
CREATE INDEX "idx_menu_id" ON "t_role_menu" ("menu_id");
CREATE TRIGGER "trg_t_role_menu_update_time" BEFORE UPDATE ON "t_role_menu"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_serial_number  单号生成器定义表
-- ----------------------------
DROP TABLE IF EXISTS "t_serial_number";
CREATE TABLE "t_serial_number" (
  "serial_number_id" integer NOT NULL,
  "business_name" varchar(50) NOT NULL,
  "format" varchar(50),
  "rule_type" varchar(20) NOT NULL,
  "init_number" integer NOT NULL,
  "step_random_range" integer NOT NULL,
  "remark" varchar(255),
  "last_number" bigint,
  "last_time" timestamp,
  "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("serial_number_id"),
  CONSTRAINT "key_name" UNIQUE ("business_name")
);
COMMENT ON TABLE "t_serial_number" IS '单号生成器定义表';
COMMENT ON COLUMN "t_serial_number"."business_name" IS '业务名称';
COMMENT ON COLUMN "t_serial_number"."format" IS '格式[yyyy]表示年,[mm]标识月,[dd]表示日,[nnn]表示三位数字';
COMMENT ON COLUMN "t_serial_number"."rule_type" IS '规则格式。none没有周期, year 年周期, month月周期, day日周期';
COMMENT ON COLUMN "t_serial_number"."init_number" IS '初始值';
COMMENT ON COLUMN "t_serial_number"."step_random_range" IS '步长随机数';
COMMENT ON COLUMN "t_serial_number"."remark" IS '备注';
COMMENT ON COLUMN "t_serial_number"."last_number" IS '上次产生的单号, 默认为空';
COMMENT ON COLUMN "t_serial_number"."last_time" IS '上次产生的单号时间';
CREATE TRIGGER "trg_t_serial_number_update_time" BEFORE UPDATE ON "t_serial_number"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_serial_number_record  serial_number记录表
-- ----------------------------
DROP TABLE IF EXISTS "t_serial_number_record";
CREATE TABLE "t_serial_number_record" (
  "serial_number_id" integer NOT NULL,
  "record_date" date NOT NULL,
  "last_number" bigint NOT NULL DEFAULT 0,
  "last_time" timestamp NOT NULL,
  "count" bigint NOT NULL DEFAULT 0,
  "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE "t_serial_number_record" IS 'serial_number记录表';
COMMENT ON COLUMN "t_serial_number_record"."record_date" IS '记录日期';
COMMENT ON COLUMN "t_serial_number_record"."last_number" IS '最后更新值';
COMMENT ON COLUMN "t_serial_number_record"."last_time" IS '最后更新时间';
COMMENT ON COLUMN "t_serial_number_record"."count" IS '更新次数';
CREATE INDEX "uk_generator" ON "t_serial_number_record" ("serial_number_id", "record_date");
CREATE TRIGGER "trg_t_serial_number_record_update_time" BEFORE UPDATE ON "t_serial_number_record"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_smart_job  定时任务配置 @listen
-- ----------------------------
DROP TABLE IF EXISTS "t_smart_job";
CREATE TABLE "t_smart_job" (
  "job_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "job_name" varchar(50) NOT NULL,
  "job_class" varchar(200) NOT NULL,
  "trigger_type" varchar(30) NOT NULL,
  "trigger_value" varchar(200) NOT NULL,
  "enabled_flag" smallint NOT NULL DEFAULT 0,
  "param" varchar(1000),
  "last_execute_time" timestamp,
  "last_execute_log_id" integer,
  "sort" integer NOT NULL DEFAULT 0,
  "remark" varchar(255),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  "update_name" varchar(50) NOT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("job_id")
);
COMMENT ON TABLE "t_smart_job" IS '定时任务配置 @listen';
COMMENT ON COLUMN "t_smart_job"."job_id" IS '任务id';
COMMENT ON COLUMN "t_smart_job"."job_name" IS '任务名称';
COMMENT ON COLUMN "t_smart_job"."job_class" IS '任务执行类';
COMMENT ON COLUMN "t_smart_job"."trigger_type" IS '触发类型';
COMMENT ON COLUMN "t_smart_job"."trigger_value" IS '触发配置';
COMMENT ON COLUMN "t_smart_job"."enabled_flag" IS '是否开启';
COMMENT ON COLUMN "t_smart_job"."param" IS '参数';
COMMENT ON COLUMN "t_smart_job"."last_execute_time" IS '最后一次执行时间';
COMMENT ON COLUMN "t_smart_job"."last_execute_log_id" IS '最后一次执行记录id';
COMMENT ON COLUMN "t_smart_job"."sort" IS '排序';
COMMENT ON COLUMN "t_smart_job"."remark" IS '描述';
COMMENT ON COLUMN "t_smart_job"."deleted_flag" IS '删除状态';
COMMENT ON COLUMN "t_smart_job"."update_name" IS '更新人';
CREATE TRIGGER "trg_t_smart_job_update_time" BEFORE UPDATE ON "t_smart_job"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_smart_job_log  定时任务-执行记录 @listen
-- ----------------------------
DROP TABLE IF EXISTS "t_smart_job_log";
CREATE TABLE "t_smart_job_log" (
  "log_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "job_id" integer NOT NULL,
  "job_name" varchar(100) NOT NULL,
  "param" varchar(2000),
  "success_flag" smallint NOT NULL,
  "execute_start_time" timestamp NOT NULL,
  "execute_time_millis" integer,
  "execute_end_time" timestamp,
  "execute_result" varchar(2000),
  "ip" varchar(50) NOT NULL,
  "process_id" varchar(50) NOT NULL,
  "program_path" varchar(255) NOT NULL,
  "create_name" varchar(100) NOT NULL,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("log_id")
);
COMMENT ON TABLE "t_smart_job_log" IS '定时任务-执行记录 @listen';
COMMENT ON COLUMN "t_smart_job_log"."job_id" IS '任务id';
COMMENT ON COLUMN "t_smart_job_log"."job_name" IS '任务名称';
COMMENT ON COLUMN "t_smart_job_log"."param" IS '执行参数';
COMMENT ON COLUMN "t_smart_job_log"."success_flag" IS '是否成功';
COMMENT ON COLUMN "t_smart_job_log"."execute_start_time" IS '执行开始时间';
COMMENT ON COLUMN "t_smart_job_log"."execute_time_millis" IS '执行时长';
COMMENT ON COLUMN "t_smart_job_log"."execute_end_time" IS '执行结束时间';
COMMENT ON COLUMN "t_smart_job_log"."ip" IS 'ip';
COMMENT ON COLUMN "t_smart_job_log"."process_id" IS '进程id';
COMMENT ON COLUMN "t_smart_job_log"."program_path" IS '程序目录';
COMMENT ON COLUMN "t_smart_job_log"."create_name" IS '创建人';
CREATE INDEX "idx_job_id" ON "t_smart_job_log" ("job_id");

-- ----------------------------
-- t_table_column  表格的自定义列存储
-- ----------------------------
DROP TABLE IF EXISTS "t_table_column";
CREATE TABLE "t_table_column" (
  "table_column_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" bigint NOT NULL,
  "user_type" integer NOT NULL,
  "table_id" integer NOT NULL,
  "columns" text,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("table_column_id"),
  CONSTRAINT "uni_employee_table" UNIQUE ("user_id", "table_id")
);
COMMENT ON TABLE "t_table_column" IS '表格的自定义列存储';
COMMENT ON COLUMN "t_table_column"."user_id" IS '用户id';
COMMENT ON COLUMN "t_table_column"."user_type" IS '用户类型';
COMMENT ON COLUMN "t_table_column"."table_id" IS '表格id';
COMMENT ON COLUMN "t_table_column"."columns" IS '具体的表格列，存入的json';
CREATE TRIGGER "trg_t_table_column_update_time" BEFORE UPDATE ON "t_table_column"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

