-- ==========================================================================
-- XSY-SCM  PostgreSQL 建表脚本 —— 商品与价格（P0）
-- 由 MySQL 结构自动转换生成，表数量：5
-- 目标数据库：PostgreSQL 12+
-- ==========================================================================

-- ------------------------------------------------------------------
-- ON UPDATE CURRENT_TIMESTAMP 在 PostgreSQL 中没有等价列属性，
-- 统一用下面这个触发器函数替代（每张有 update_time 的表挂一个 BEFORE UPDATE 触发器）。
-- 如果业务代码里已经显式维护 update_time，可以整段删除。
-- ------------------------------------------------------------------
CREATE OR REPLACE FUNCTION xsy_set_update_time() RETURNS trigger AS $$
BEGIN
  NEW.update_time := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------
-- t_product  商品 SPU
-- ----------------------------
DROP TABLE IF EXISTS "t_product";
CREATE TABLE "t_product" (
  "product_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_no" varchar(32) NOT NULL,
  "category_id" bigint NOT NULL,
  "product_name" varchar(128) NOT NULL,
  "product_type" smallint NOT NULL DEFAULT 1,
  "measure_type" smallint NOT NULL DEFAULT 1,
  "base_unit" varchar(16) NOT NULL DEFAULT '',
  "spec_flag" smallint NOT NULL DEFAULT 0,
  "purchase_mode" smallint NOT NULL DEFAULT 1,
  "default_supplier_id" bigint,
  "default_buyer_id" bigint,
  "detail" text,
  "main_image" varchar(255) NOT NULL DEFAULT '',
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("product_id"),
  CONSTRAINT "uk_product_no" UNIQUE ("product_no")
);
COMMENT ON TABLE "t_product" IS '商品 SPU';
COMMENT ON COLUMN "t_product"."product_id" IS '主键';
COMMENT ON COLUMN "t_product"."product_no" IS '商品编码，SP + 6 位流水（G-01）';
COMMENT ON COLUMN "t_product"."category_id" IS '三级分类 ID';
COMMENT ON COLUMN "t_product"."product_name" IS '商品名称';
COMMENT ON COLUMN "t_product"."product_type" IS '商品类型：1 标品，2 非标品';
COMMENT ON COLUMN "t_product"."measure_type" IS '计量方式：1 按件，2 按重';
COMMENT ON COLUMN "t_product"."base_unit" IS '基本单位，如 件 / kg';
COMMENT ON COLUMN "t_product"."spec_flag" IS '是否多规格：0 否，1 是';
COMMENT ON COLUMN "t_product"."purchase_mode" IS '采购方式：1 自采，2 供应商送货';
COMMENT ON COLUMN "t_product"."default_supplier_id" IS '默认供应商 ID';
COMMENT ON COLUMN "t_product"."default_buyer_id" IS '默认采购员 ID';
COMMENT ON COLUMN "t_product"."detail" IS '商品详情';
COMMENT ON COLUMN "t_product"."main_image" IS '主图（文件服务地址，不硬编码公网 URL）';
COMMENT ON COLUMN "t_product"."status" IS '状态：1 草稿，2 待上架，3 已上架，4 已下架，5 已作废';
COMMENT ON COLUMN "t_product"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_product"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_product"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_product"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_product"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_category_id" ON "t_product" ("category_id");
CREATE INDEX "idx_status" ON "t_product" ("status");
CREATE INDEX "idx_product_name" ON "t_product" ("product_name");
CREATE TRIGGER "trg_t_product_update_time" BEFORE UPDATE ON "t_product"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_product_category  商品分类
-- ----------------------------
DROP TABLE IF EXISTS "t_product_category";
CREATE TABLE "t_product_category" (
  "category_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "parent_id" bigint NOT NULL DEFAULT 0,
  "category_name" varchar(64) NOT NULL,
  "level" smallint NOT NULL DEFAULT 1,
  "sort" integer NOT NULL DEFAULT 0,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("category_id")
);
COMMENT ON TABLE "t_product_category" IS '商品分类';
COMMENT ON COLUMN "t_product_category"."category_id" IS '主键';
COMMENT ON COLUMN "t_product_category"."parent_id" IS '父级ID，一级为 0';
COMMENT ON COLUMN "t_product_category"."category_name" IS '分类名称';
COMMENT ON COLUMN "t_product_category"."level" IS '层级：1 一级，2 二级，3 三级';
COMMENT ON COLUMN "t_product_category"."sort" IS '排序，升序';
COMMENT ON COLUMN "t_product_category"."status" IS '状态：1 启用，2 停用';
COMMENT ON COLUMN "t_product_category"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_product_category"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_product_category"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_product_category"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_product_category"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_product_category_idx_parent_id" ON "t_product_category" ("parent_id");
CREATE INDEX "t_product_category_idx_status" ON "t_product_category" ("status");
CREATE TRIGGER "trg_t_product_category_update_time" BEFORE UPDATE ON "t_product_category"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_product_price  商品价格
-- ----------------------------
DROP TABLE IF EXISTS "t_product_price";
CREATE TABLE "t_product_price" (
  "price_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" bigint NOT NULL,
  "sku_id" bigint,
  "price_type" smallint NOT NULL,
  "customer_level_id" bigint,
  "customer_id" bigint,
  "price" numeric(18,4) NOT NULL,
  "effective_time" timestamp,
  "expire_time" timestamp,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("price_id")
);
COMMENT ON TABLE "t_product_price" IS '商品价格';
COMMENT ON COLUMN "t_product_price"."price_id" IS '主键';
COMMENT ON COLUMN "t_product_price"."product_id" IS '商品 ID';
COMMENT ON COLUMN "t_product_price"."sku_id" IS '规格 ID，为空表示按商品定价';
COMMENT ON COLUMN "t_product_price"."price_type" IS '价格类型：1 基础价，2 客户分级价，3 时价，4 协议价';
COMMENT ON COLUMN "t_product_price"."customer_level_id" IS '客户分级 ID，分级价使用';
COMMENT ON COLUMN "t_product_price"."customer_id" IS '指定客户 ID，协议价使用';
COMMENT ON COLUMN "t_product_price"."price" IS '单价（不含税）';
COMMENT ON COLUMN "t_product_price"."effective_time" IS '生效时间，时价使用';
COMMENT ON COLUMN "t_product_price"."expire_time" IS '失效时间';
COMMENT ON COLUMN "t_product_price"."status" IS '状态：1 生效，2 失效';
COMMENT ON COLUMN "t_product_price"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_product_price"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_product_price"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_product_price"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_product_price"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_product_sku" ON "t_product_price" ("product_id", "sku_id");
CREATE INDEX "idx_customer_id" ON "t_product_price" ("customer_id");
CREATE INDEX "idx_price_type_status" ON "t_product_price" ("price_type", "status");
CREATE TRIGGER "trg_t_product_price_update_time" BEFORE UPDATE ON "t_product_price"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_product_sku  商品规格 SKU
-- ----------------------------
DROP TABLE IF EXISTS "t_product_sku";
CREATE TABLE "t_product_sku" (
  "sku_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" bigint NOT NULL,
  "sku_no" varchar(32) NOT NULL,
  "spec_name" varchar(128) NOT NULL DEFAULT '',
  "unit" varchar(16) NOT NULL DEFAULT '',
  "unit_weight" numeric(18,3) NOT NULL DEFAULT 0.000,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("sku_id"),
  CONSTRAINT "uk_sku_no" UNIQUE ("sku_no")
);
COMMENT ON TABLE "t_product_sku" IS '商品规格 SKU';
COMMENT ON COLUMN "t_product_sku"."sku_id" IS '主键';
COMMENT ON COLUMN "t_product_sku"."product_id" IS '所属商品 ID';
COMMENT ON COLUMN "t_product_sku"."sku_no" IS '规格编码';
COMMENT ON COLUMN "t_product_sku"."spec_name" IS '规格名称，如 规格/单位 组合';
COMMENT ON COLUMN "t_product_sku"."unit" IS '销售单位';
COMMENT ON COLUMN "t_product_sku"."unit_weight" IS '单件折算重量（kg），非标品换算用';
COMMENT ON COLUMN "t_product_sku"."status" IS '状态：1 启用，2 停用';
COMMENT ON COLUMN "t_product_sku"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_product_sku"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_product_sku"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_product_sku"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_product_sku"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_product_id" ON "t_product_sku" ("product_id");
CREATE TRIGGER "trg_t_product_sku_update_time" BEFORE UPDATE ON "t_product_sku"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_product_supplier  商品-供应商关系
-- ----------------------------
DROP TABLE IF EXISTS "t_product_supplier";
CREATE TABLE "t_product_supplier" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" bigint NOT NULL,
  "supplier_id" bigint NOT NULL,
  "supply_price" numeric(18,4) NOT NULL DEFAULT 0.0000,
  "default_flag" smallint NOT NULL DEFAULT 0,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_product_supplier" UNIQUE ("product_id", "supplier_id")
);
COMMENT ON TABLE "t_product_supplier" IS '商品-供应商关系';
COMMENT ON COLUMN "t_product_supplier"."id" IS '主键';
COMMENT ON COLUMN "t_product_supplier"."product_id" IS '商品 ID';
COMMENT ON COLUMN "t_product_supplier"."supplier_id" IS '供应商 ID';
COMMENT ON COLUMN "t_product_supplier"."supply_price" IS '供应价（不含税）';
COMMENT ON COLUMN "t_product_supplier"."default_flag" IS '是否默认供应商：0 否，1 是';
COMMENT ON COLUMN "t_product_supplier"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_product_supplier"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_product_supplier"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_product_supplier"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_product_supplier"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_supplier_id" ON "t_product_supplier" ("supplier_id");
CREATE TRIGGER "trg_t_product_supplier_update_time" BEFORE UPDATE ON "t_product_supplier"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

