-- ==========================================================================
-- XSY-SCM  PostgreSQL 建表脚本 —— 客户（P0）
-- 由 MySQL 结构自动转换生成，表数量：4
-- 目标数据库：PostgreSQL 12+
-- ==========================================================================

-- ------------------------------------------------------------------
-- ON UPDATE CURRENT_TIMESTAMP 在 PostgreSQL 中没有等价列属性，
-- 统一用下面这个触发器函数替代（每张有 update_time 的表挂一个 BEFORE UPDATE 触发器）。
-- 如果业务代码里已经显式维护 update_time，可以整段删除。
-- ------------------------------------------------------------------
CREATE OR REPLACE FUNCTION xsy_set_update_time() RETURNS trigger AS $$
BEGIN
  NEW.update_time := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------
-- t_customer  客户档案
-- ----------------------------
DROP TABLE IF EXISTS "t_customer";
CREATE TABLE "t_customer" (
  "customer_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "customer_no" varchar(32) NOT NULL,
  "customer_name" varchar(128) NOT NULL,
  "customer_type" smallint NOT NULL DEFAULT 1,
  "customer_level_id" bigint,
  "parent_customer_id" bigint NOT NULL DEFAULT 0,
  "settle_mode" smallint NOT NULL DEFAULT 1,
  "seller_id" bigint,
  "supplier_id" bigint,
  "contact_name" varchar(32) NOT NULL DEFAULT '',
  "contact_phone" varchar(32) NOT NULL DEFAULT '',
  "address" varchar(255) NOT NULL DEFAULT '',
  "longitude" numeric(10,7),
  "latitude" numeric(10,7),
  "balance" numeric(18,2) NOT NULL DEFAULT 0.00,
  "credit_amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("customer_id"),
  CONSTRAINT "uk_customer_no" UNIQUE ("customer_no")
);
COMMENT ON TABLE "t_customer" IS '客户档案';
COMMENT ON COLUMN "t_customer"."customer_id" IS '主键';
COMMENT ON COLUMN "t_customer"."customer_no" IS '客户编码，KH + 6 位流水（G-01）';
COMMENT ON COLUMN "t_customer"."customer_name" IS '客户名称';
COMMENT ON COLUMN "t_customer"."customer_type" IS '客户类型：1 企业，2 个人，3 集团';
COMMENT ON COLUMN "t_customer"."customer_level_id" IS '客户分级 ID，影响取价';
COMMENT ON COLUMN "t_customer"."parent_customer_id" IS '上级集团客户 ID，独立客户为 0';
COMMENT ON COLUMN "t_customer"."settle_mode" IS '结算方式：1 独立结算，2 集团统一结算';
COMMENT ON COLUMN "t_customer"."seller_id" IS '归属业务员 ID';
COMMENT ON COLUMN "t_customer"."supplier_id" IS '绑定供应商 ID';
COMMENT ON COLUMN "t_customer"."contact_name" IS '联系人';
COMMENT ON COLUMN "t_customer"."contact_phone" IS '联系电话';
COMMENT ON COLUMN "t_customer"."address" IS '地址，配送使用';
COMMENT ON COLUMN "t_customer"."longitude" IS '经度，线路规划使用';
COMMENT ON COLUMN "t_customer"."latitude" IS '纬度，线路规划使用';
COMMENT ON COLUMN "t_customer"."balance" IS '余额账户（不含税），余额充值结算使用';
COMMENT ON COLUMN "t_customer"."credit_amount" IS '授信额度（不含税），账期按金额时使用';
COMMENT ON COLUMN "t_customer"."status" IS '状态：1 潜在，2 合作中，3 暂停合作，4 黑名单';
COMMENT ON COLUMN "t_customer"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_customer"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_customer"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_customer"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_customer"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_seller_id" ON "t_customer" ("seller_id");
CREATE INDEX "t_customer_idx_status" ON "t_customer" ("status");
CREATE INDEX "idx_parent_customer_id" ON "t_customer" ("parent_customer_id");
CREATE INDEX "idx_customer_name" ON "t_customer" ("customer_name");
CREATE TRIGGER "trg_t_customer_update_time" BEFORE UPDATE ON "t_customer"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_customer_goods_visible  客户商品可见性
-- ----------------------------
DROP TABLE IF EXISTS "t_customer_goods_visible";
CREATE TABLE "t_customer_goods_visible" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "customer_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "visible_type" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_customer_product" UNIQUE ("customer_id", "product_id")
);
COMMENT ON TABLE "t_customer_goods_visible" IS '客户商品可见性';
COMMENT ON COLUMN "t_customer_goods_visible"."id" IS '主键';
COMMENT ON COLUMN "t_customer_goods_visible"."customer_id" IS '客户 ID';
COMMENT ON COLUMN "t_customer_goods_visible"."product_id" IS '商品 ID';
COMMENT ON COLUMN "t_customer_goods_visible"."visible_type" IS '可见性：1 显示，2 屏蔽';
COMMENT ON COLUMN "t_customer_goods_visible"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_customer_goods_visible"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_customer_goods_visible"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_customer_goods_visible"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_customer_goods_visible"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE TRIGGER "trg_t_customer_goods_visible_update_time" BEFORE UPDATE ON "t_customer_goods_visible"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_customer_period  客户账期
-- ----------------------------
DROP TABLE IF EXISTS "t_customer_period";
CREATE TABLE "t_customer_period" (
  "period_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "customer_id" bigint NOT NULL,
  "period_type" smallint NOT NULL DEFAULT 2,
  "amount_threshold" numeric(18,2),
  "period_value" integer,
  "period_unit" smallint,
  "settle_day" smallint,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("period_id")
);
COMMENT ON TABLE "t_customer_period" IS '客户账期';
COMMENT ON COLUMN "t_customer_period"."period_id" IS '主键';
COMMENT ON COLUMN "t_customer_period"."customer_id" IS '客户 ID';
COMMENT ON COLUMN "t_customer_period"."period_type" IS '账期类型：1 按金额，2 按时间';
COMMENT ON COLUMN "t_customer_period"."amount_threshold" IS '金额阈值（不含税），按金额时使用';
COMMENT ON COLUMN "t_customer_period"."period_value" IS '账期值，按时间时使用';
COMMENT ON COLUMN "t_customer_period"."period_unit" IS '账期单位：1 天，2 月';
COMMENT ON COLUMN "t_customer_period"."settle_day" IS '固定结算日，按月时使用';
COMMENT ON COLUMN "t_customer_period"."status" IS '状态：1 生效，2 暂停';
COMMENT ON COLUMN "t_customer_period"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_customer_period"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_customer_period"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_customer_period"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_customer_period"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_customer_period_idx_customer_id" ON "t_customer_period" ("customer_id");
CREATE INDEX "t_customer_period_idx_status" ON "t_customer_period" ("status");
CREATE TRIGGER "trg_t_customer_period_update_time" BEFORE UPDATE ON "t_customer_period"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_customer_qrcode  业务员推广二维码
-- ----------------------------
DROP TABLE IF EXISTS "t_customer_qrcode";
CREATE TABLE "t_customer_qrcode" (
  "qrcode_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "seller_id" bigint NOT NULL,
  "qrcode_url" varchar(255) NOT NULL DEFAULT '',
  "scan_count" integer NOT NULL DEFAULT 0,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("qrcode_id")
);
COMMENT ON TABLE "t_customer_qrcode" IS '业务员推广二维码';
COMMENT ON COLUMN "t_customer_qrcode"."qrcode_id" IS '主键';
COMMENT ON COLUMN "t_customer_qrcode"."seller_id" IS '业务员 ID';
COMMENT ON COLUMN "t_customer_qrcode"."qrcode_url" IS '二维码地址（文件服务，不硬编码公网 URL）';
COMMENT ON COLUMN "t_customer_qrcode"."scan_count" IS '扫描次数';
COMMENT ON COLUMN "t_customer_qrcode"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_customer_qrcode"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_customer_qrcode"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_customer_qrcode"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_customer_qrcode"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_customer_qrcode_idx_seller_id" ON "t_customer_qrcode" ("seller_id");
CREATE TRIGGER "trg_t_customer_qrcode_update_time" BEFORE UPDATE ON "t_customer_qrcode"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

