-- ==========================================================================
-- XSY-SCM  PostgreSQL 建表脚本 —— 订单（P0）
-- 由 MySQL 结构自动转换生成，表数量：4
-- 目标数据库：PostgreSQL 12+
-- ==========================================================================

-- ------------------------------------------------------------------
-- ON UPDATE CURRENT_TIMESTAMP 在 PostgreSQL 中没有等价列属性，
-- 统一用下面这个触发器函数替代（每张有 update_time 的表挂一个 BEFORE UPDATE 触发器）。
-- 如果业务代码里已经显式维护 update_time，可以整段删除。
-- ------------------------------------------------------------------
CREATE OR REPLACE FUNCTION xsy_set_update_time() RETURNS trigger AS $$
BEGIN
  NEW.update_time := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------
-- t_order  订单主表
-- ----------------------------
DROP TABLE IF EXISTS "t_order";
CREATE TABLE "t_order" (
  "order_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_no" varchar(32) NOT NULL,
  "customer_id" bigint NOT NULL,
  "settle_customer_id" bigint NOT NULL,
  "source" smallint NOT NULL DEFAULT 1,
  "settle_type" smallint NOT NULL DEFAULT 1,
  "total_amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "discount_amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "payable_amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "actual_amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "pay_status" smallint NOT NULL DEFAULT 1,
  "expect_delivery_time" timestamp,
  "seller_id" bigint,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("order_id"),
  CONSTRAINT "uk_order_no" UNIQUE ("order_no")
);
COMMENT ON TABLE "t_order" IS '订单主表';
COMMENT ON COLUMN "t_order"."order_id" IS '主键';
COMMENT ON COLUMN "t_order"."order_no" IS '订单号，XSD + yyyyMMdd + 4 位流水（G-01）';
COMMENT ON COLUMN "t_order"."customer_id" IS '下单客户 ID（下属单位下单时为本单位）';
COMMENT ON COLUMN "t_order"."settle_customer_id" IS '结算客户 ID（集团统一结算时为集团客户）';
COMMENT ON COLUMN "t_order"."source" IS '来源：1 商城下单，2 后台录单，3 补单';
COMMENT ON COLUMN "t_order"."settle_type" IS '结算方式：1 账期支付，2 货到付款，3 在线支付，4 余额充值';
COMMENT ON COLUMN "t_order"."total_amount" IS '下单金额（不含税，快照价计算）';
COMMENT ON COLUMN "t_order"."discount_amount" IS '优惠金额（不含税）';
COMMENT ON COLUMN "t_order"."payable_amount" IS '应付金额（不含税）';
COMMENT ON COLUMN "t_order"."actual_amount" IS '核算金额（不含税，按实重核算后）';
COMMENT ON COLUMN "t_order"."pay_status" IS '支付状态：1 未付，2 部分支付，3 已付';
COMMENT ON COLUMN "t_order"."expect_delivery_time" IS '期望配送时间';
COMMENT ON COLUMN "t_order"."seller_id" IS '归属业务员 ID';
COMMENT ON COLUMN "t_order"."status" IS '状态：1 草稿，2 待确认，3 已确认，4 采购中，5 待分拣，6 分拣中，7 配送中，8 已签收，9 已完成，10 退款中，11 已取消，12 已作废';
COMMENT ON COLUMN "t_order"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_order"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_order"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_order"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_order"."deleted_flag" IS '逻辑删除：0 否，1 是（订单不允许物理删除）';
CREATE INDEX "t_order_idx_customer_id" ON "t_order" ("customer_id");
CREATE INDEX "idx_settle_customer_id" ON "t_order" ("settle_customer_id");
CREATE INDEX "t_order_idx_status" ON "t_order" ("status");
CREATE INDEX "t_order_idx_seller_id" ON "t_order" ("seller_id");
CREATE INDEX "idx_create_time" ON "t_order" ("create_time");
CREATE TRIGGER "trg_t_order_update_time" BEFORE UPDATE ON "t_order"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_order_item  订单明细
-- ----------------------------
DROP TABLE IF EXISTS "t_order_item";
CREATE TABLE "t_order_item" (
  "item_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "sku_id" bigint,
  "quantity" numeric(18,3) NOT NULL DEFAULT 0.000,
  "snapshot_price" numeric(18,4) NOT NULL DEFAULT 0.0000,
  "price_type" smallint,
  "actual_weight" numeric(18,3),
  "actual_quantity" numeric(18,3),
  "item_amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("item_id")
);
COMMENT ON TABLE "t_order_item" IS '订单明细';
COMMENT ON COLUMN "t_order_item"."item_id" IS '主键';
COMMENT ON COLUMN "t_order_item"."order_id" IS '订单 ID';
COMMENT ON COLUMN "t_order_item"."product_id" IS '商品 ID';
COMMENT ON COLUMN "t_order_item"."sku_id" IS '规格 ID';
COMMENT ON COLUMN "t_order_item"."quantity" IS '下单数量';
COMMENT ON COLUMN "t_order_item"."snapshot_price" IS '成交价快照（不含税），下单时锁定，后续改价不影响';
COMMENT ON COLUMN "t_order_item"."price_type" IS '取价类型：1 基础价，2 客户分级价，3 时价，4 协议价';
COMMENT ON COLUMN "t_order_item"."actual_weight" IS '实际重量（kg），分拣/收货后回写';
COMMENT ON COLUMN "t_order_item"."actual_quantity" IS '实际数量';
COMMENT ON COLUMN "t_order_item"."item_amount" IS '明细核算金额（不含税，按实重计算）';
COMMENT ON COLUMN "t_order_item"."status" IS '明细状态：1 正常，2 已退款，3 已退货';
COMMENT ON COLUMN "t_order_item"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_order_item"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_order_item"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_order_item"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_order_item"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_order_id" ON "t_order_item" ("order_id");
CREATE INDEX "t_order_item_idx_product_id" ON "t_order_item" ("product_id");
CREATE TRIGGER "trg_t_order_item_update_time" BEFORE UPDATE ON "t_order_item"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_order_log  订单操作日志
-- ----------------------------
DROP TABLE IF EXISTS "t_order_log";
CREATE TABLE "t_order_log" (
  "log_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" bigint NOT NULL,
  "operate_type" smallint NOT NULL,
  "before_value" text,
  "after_value" text,
  "operate_by" bigint,
  "operate_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("log_id")
);
COMMENT ON TABLE "t_order_log" IS '订单操作日志';
COMMENT ON COLUMN "t_order_log"."log_id" IS '主键';
COMMENT ON COLUMN "t_order_log"."order_id" IS '订单 ID';
COMMENT ON COLUMN "t_order_log"."operate_type" IS '操作类型：1 创建，2 确认，3 改价，4 编辑，5 取消，6 发货，7 签收，8 核算，9 退款，10 作废';
COMMENT ON COLUMN "t_order_log"."before_value" IS '修改前值';
COMMENT ON COLUMN "t_order_log"."after_value" IS '修改后值';
COMMENT ON COLUMN "t_order_log"."operate_by" IS '操作人';
COMMENT ON COLUMN "t_order_log"."operate_time" IS '操作时间';
COMMENT ON COLUMN "t_order_log"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_order_log"."update_time" IS '更新时间';
CREATE INDEX "t_order_log_idx_order_id" ON "t_order_log" ("order_id");
CREATE INDEX "idx_operate_time" ON "t_order_log" ("operate_time");
CREATE TRIGGER "trg_t_order_log_update_time" BEFORE UPDATE ON "t_order_log"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_refund  退款单
-- ----------------------------
DROP TABLE IF EXISTS "t_refund";
CREATE TABLE "t_refund" (
  "refund_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "refund_no" varchar(32) NOT NULL,
  "order_id" bigint NOT NULL,
  "item_id" bigint,
  "refund_type" smallint NOT NULL DEFAULT 1,
  "refund_amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "refund_reason" varchar(255) NOT NULL DEFAULT '',
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("refund_id"),
  CONSTRAINT "uk_refund_no" UNIQUE ("refund_no")
);
COMMENT ON TABLE "t_refund" IS '退款单';
COMMENT ON COLUMN "t_refund"."refund_id" IS '主键';
COMMENT ON COLUMN "t_refund"."refund_no" IS '退款单号，TKD + yyyyMMdd + 4 位流水（G-01）';
COMMENT ON COLUMN "t_refund"."order_id" IS '订单 ID';
COMMENT ON COLUMN "t_refund"."item_id" IS '订单明细 ID，整单退款时为空';
COMMENT ON COLUMN "t_refund"."refund_type" IS '退款类型：1 仅退款，2 退货退款';
COMMENT ON COLUMN "t_refund"."refund_amount" IS '退款金额（不含税）';
COMMENT ON COLUMN "t_refund"."refund_reason" IS '退款原因';
COMMENT ON COLUMN "t_refund"."status" IS '状态：1 待审核，2 已通过，3 已退款，4 已驳回';
COMMENT ON COLUMN "t_refund"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_refund"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_refund"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_refund"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_refund"."deleted_flag" IS '逻辑删除：0 否，1 是（退款记录不允许物理删除）';
CREATE INDEX "t_refund_idx_order_id" ON "t_refund" ("order_id");
CREATE INDEX "t_refund_idx_status" ON "t_refund" ("status");
CREATE TRIGGER "trg_t_refund_update_time" BEFORE UPDATE ON "t_refund"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

