-- ==========================================================================
-- XSY-SCM  PostgreSQL 建表脚本 —— 采购（P0）
-- 由 MySQL 结构自动转换生成，表数量：4
-- 目标数据库：PostgreSQL 12+
-- ==========================================================================

-- ------------------------------------------------------------------
-- ON UPDATE CURRENT_TIMESTAMP 在 PostgreSQL 中没有等价列属性，
-- 统一用下面这个触发器函数替代（每张有 update_time 的表挂一个 BEFORE UPDATE 触发器）。
-- 如果业务代码里已经显式维护 update_time，可以整段删除。
-- ------------------------------------------------------------------
CREATE OR REPLACE FUNCTION xsy_set_update_time() RETURNS trigger AS $$
BEGIN
  NEW.update_time := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------
-- t_purchase_item  采购明细
-- ----------------------------
DROP TABLE IF EXISTS "t_purchase_item";
CREATE TABLE "t_purchase_item" (
  "item_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "purchase_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "sku_id" bigint,
  "require_quantity" numeric(18,3) NOT NULL DEFAULT 0.000,
  "purchase_quantity" numeric(18,3) NOT NULL DEFAULT 0.000,
  "received_quantity" numeric(18,3) NOT NULL DEFAULT 0.000,
  "unit_price" numeric(18,4) NOT NULL DEFAULT 0.0000,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("item_id")
);
COMMENT ON TABLE "t_purchase_item" IS '采购明细';
COMMENT ON COLUMN "t_purchase_item"."item_id" IS '主键';
COMMENT ON COLUMN "t_purchase_item"."purchase_id" IS '采购单 ID';
COMMENT ON COLUMN "t_purchase_item"."product_id" IS '商品 ID';
COMMENT ON COLUMN "t_purchase_item"."sku_id" IS '规格 ID';
COMMENT ON COLUMN "t_purchase_item"."require_quantity" IS '需求量（订单汇总得出）';
COMMENT ON COLUMN "t_purchase_item"."purchase_quantity" IS '计划采购量';
COMMENT ON COLUMN "t_purchase_item"."received_quantity" IS '累计已收数量';
COMMENT ON COLUMN "t_purchase_item"."unit_price" IS '采购单价（不含税），可后续回填';
COMMENT ON COLUMN "t_purchase_item"."status" IS '状态：1 待收，2 部分收，3 已收齐';
COMMENT ON COLUMN "t_purchase_item"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_purchase_item"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_purchase_item"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_purchase_item"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_purchase_item"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_purchase_id" ON "t_purchase_item" ("purchase_id");
CREATE INDEX "t_purchase_item_idx_product_id" ON "t_purchase_item" ("product_id");
CREATE TRIGGER "trg_t_purchase_item_update_time" BEFORE UPDATE ON "t_purchase_item"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_purchase_order  采购单
-- ----------------------------
DROP TABLE IF EXISTS "t_purchase_order";
CREATE TABLE "t_purchase_order" (
  "purchase_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "purchase_no" varchar(32) NOT NULL,
  "supplier_id" bigint NOT NULL,
  "buyer_id" bigint,
  "category_id" bigint,
  "total_amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "actual_amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "expect_arrive_time" timestamp,
  "qrcode_url" varchar(255) NOT NULL DEFAULT '',
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("purchase_id"),
  CONSTRAINT "uk_purchase_no" UNIQUE ("purchase_no")
);
COMMENT ON TABLE "t_purchase_order" IS '采购单';
COMMENT ON COLUMN "t_purchase_order"."purchase_id" IS '主键';
COMMENT ON COLUMN "t_purchase_order"."purchase_no" IS '采购单号，CGD + yyyyMMdd + 4 位流水（G-01）';
COMMENT ON COLUMN "t_purchase_order"."supplier_id" IS '供应商 ID';
COMMENT ON COLUMN "t_purchase_order"."buyer_id" IS '采购员 ID';
COMMENT ON COLUMN "t_purchase_order"."category_id" IS '品类 ID，按品类汇总时使用';
COMMENT ON COLUMN "t_purchase_order"."total_amount" IS '采购预估金额（不含税）';
COMMENT ON COLUMN "t_purchase_order"."actual_amount" IS '实际采购金额（不含税，按实重收货后）';
COMMENT ON COLUMN "t_purchase_order"."expect_arrive_time" IS '期望到货时间';
COMMENT ON COLUMN "t_purchase_order"."qrcode_url" IS '采购单二维码（文件服务，不硬编码公网 URL）';
COMMENT ON COLUMN "t_purchase_order"."status" IS '状态：1 待接单，2 采购中，3 部分收货，4 已完成，5 已取消';
COMMENT ON COLUMN "t_purchase_order"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_purchase_order"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_purchase_order"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_purchase_order"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_purchase_order"."deleted_flag" IS '逻辑删除：0 否，1 是（采购单不允许物理删除）';
CREATE INDEX "t_purchase_order_idx_supplier_id" ON "t_purchase_order" ("supplier_id");
CREATE INDEX "idx_buyer_id" ON "t_purchase_order" ("buyer_id");
CREATE INDEX "t_purchase_order_idx_status" ON "t_purchase_order" ("status");
CREATE TRIGGER "trg_t_purchase_order_update_time" BEFORE UPDATE ON "t_purchase_order"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_receive  采购收货单
-- ----------------------------
DROP TABLE IF EXISTS "t_receive";
CREATE TABLE "t_receive" (
  "receive_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "receive_no" varchar(32) NOT NULL,
  "purchase_id" bigint NOT NULL,
  "item_id" bigint NOT NULL,
  "receive_quantity" numeric(18,3) NOT NULL DEFAULT 0.000,
  "receive_weight" numeric(18,3) NOT NULL DEFAULT 0.000,
  "unit_price" numeric(18,4) NOT NULL DEFAULT 0.0000,
  "receive_by" bigint,
  "receive_time" timestamp,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  "receive_flag" smallint NOT NULL DEFAULT 1,
  PRIMARY KEY ("receive_id"),
  CONSTRAINT "uk_receive_no" UNIQUE ("receive_no")
);
COMMENT ON TABLE "t_receive" IS '采购收货单';
COMMENT ON COLUMN "t_receive"."receive_id" IS '主键';
COMMENT ON COLUMN "t_receive"."receive_no" IS '收货单号，SHD + yyyyMMdd + 4 位流水（G-01）';
COMMENT ON COLUMN "t_receive"."purchase_id" IS '采购单 ID';
COMMENT ON COLUMN "t_receive"."item_id" IS '采购明细 ID';
COMMENT ON COLUMN "t_receive"."receive_quantity" IS '本次收货数量';
COMMENT ON COLUMN "t_receive"."receive_weight" IS '本次实收重量（kg），G-05 一期手工录入';
COMMENT ON COLUMN "t_receive"."unit_price" IS '本次单价（不含税），可传输回填';
COMMENT ON COLUMN "t_receive"."receive_by" IS '收货人';
COMMENT ON COLUMN "t_receive"."receive_time" IS '收货时间';
COMMENT ON COLUMN "t_receive"."status" IS '状态：1 已收，2 已入库，3 已作废（入库后生成应付）';
COMMENT ON COLUMN "t_receive"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_receive"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_receive"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_receive"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_receive"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_receive_idx_purchase_id" ON "t_receive" ("purchase_id");
CREATE INDEX "t_receive_idx_status" ON "t_receive" ("status");
CREATE TRIGGER "trg_t_receive_update_time" BEFORE UPDATE ON "t_receive"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_supplier  供应商档案
-- ----------------------------
DROP TABLE IF EXISTS "t_supplier";
CREATE TABLE "t_supplier" (
  "supplier_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "supplier_no" varchar(32) NOT NULL,
  "supplier_name" varchar(128) NOT NULL,
  "contact_name" varchar(32) NOT NULL DEFAULT '',
  "contact_phone" varchar(32) NOT NULL DEFAULT '',
  "address" varchar(255) NOT NULL DEFAULT '',
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("supplier_id"),
  CONSTRAINT "uk_supplier_no" UNIQUE ("supplier_no")
);
COMMENT ON TABLE "t_supplier" IS '供应商档案';
COMMENT ON COLUMN "t_supplier"."supplier_id" IS '主键';
COMMENT ON COLUMN "t_supplier"."supplier_no" IS '供应商编码，GYS + 6 位流水（G-01 补充前缀）';
COMMENT ON COLUMN "t_supplier"."supplier_name" IS '供应商名称';
COMMENT ON COLUMN "t_supplier"."contact_name" IS '联系人';
COMMENT ON COLUMN "t_supplier"."contact_phone" IS '联系电话';
COMMENT ON COLUMN "t_supplier"."address" IS '地址';
COMMENT ON COLUMN "t_supplier"."status" IS '状态：1 启用，2 停用';
COMMENT ON COLUMN "t_supplier"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_supplier"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_supplier"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_supplier"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_supplier"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_supplier_name" ON "t_supplier" ("supplier_name");
CREATE TRIGGER "trg_t_supplier_update_time" BEFORE UPDATE ON "t_supplier"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

