-- ==========================================================================
-- XSY-SCM  PostgreSQL 建表脚本 —— 库存（P0）
-- 由 MySQL 结构自动转换生成，表数量：5
-- 目标数据库：PostgreSQL 12+
-- ==========================================================================

-- ------------------------------------------------------------------
-- ON UPDATE CURRENT_TIMESTAMP 在 PostgreSQL 中没有等价列属性，
-- 统一用下面这个触发器函数替代（每张有 update_time 的表挂一个 BEFORE UPDATE 触发器）。
-- 如果业务代码里已经显式维护 update_time，可以整段删除。
-- ------------------------------------------------------------------
CREATE OR REPLACE FUNCTION xsy_set_update_time() RETURNS trigger AS $$
BEGIN
  NEW.update_time := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------
-- t_stock_adjust  库存调整单（报损/报溢/盘点调整/规格转换）
-- ----------------------------
DROP TABLE IF EXISTS "t_stock_adjust";
CREATE TABLE "t_stock_adjust" (
  "adjust_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "adjust_no" varchar(32) NOT NULL,
  "adjust_type" smallint NOT NULL,
  "product_id" bigint NOT NULL,
  "sku_id" bigint NOT NULL,
  "warehouse_id" bigint NOT NULL DEFAULT 1,
  "quantity" numeric(18,3) NOT NULL DEFAULT 0.000,
  "weight" numeric(18,3) NOT NULL DEFAULT 0.000,
  "reason" varchar(255) NOT NULL DEFAULT '',
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("adjust_id"),
  CONSTRAINT "uk_adjust_no" UNIQUE ("adjust_no")
);
COMMENT ON TABLE "t_stock_adjust" IS '库存调整单（报损/报溢/盘点调整/规格转换）';
COMMENT ON COLUMN "t_stock_adjust"."adjust_id" IS '主键';
COMMENT ON COLUMN "t_stock_adjust"."adjust_no" IS '调整单号，BSD 报损 / BYD 报溢 / ZHD 转换 + yyyyMMdd + 4 位流水（G-01）';
COMMENT ON COLUMN "t_stock_adjust"."adjust_type" IS '调整类型：1 报损，2 报溢，3 盘点调整，4 规格转换';
COMMENT ON COLUMN "t_stock_adjust"."product_id" IS '商品 ID';
COMMENT ON COLUMN "t_stock_adjust"."sku_id" IS '规格 ID';
COMMENT ON COLUMN "t_stock_adjust"."warehouse_id" IS '仓库 ID，G-03 单仓库，字段保留备用';
COMMENT ON COLUMN "t_stock_adjust"."quantity" IS '调整数量（正数）';
COMMENT ON COLUMN "t_stock_adjust"."weight" IS '调整重量（kg，正数）';
COMMENT ON COLUMN "t_stock_adjust"."reason" IS '调整原因';
COMMENT ON COLUMN "t_stock_adjust"."status" IS '状态：1 待审核，2 已完成，3 已驳回';
COMMENT ON COLUMN "t_stock_adjust"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_stock_adjust"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_stock_adjust"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_stock_adjust"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_stock_adjust"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_stock_adjust_idx_status" ON "t_stock_adjust" ("status");
CREATE INDEX "idx_sku_id" ON "t_stock_adjust" ("sku_id");
CREATE TRIGGER "trg_t_stock_adjust_update_time" BEFORE UPDATE ON "t_stock_adjust"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_stock_balance  库存余额
-- ----------------------------
DROP TABLE IF EXISTS "t_stock_balance";
CREATE TABLE "t_stock_balance" (
  "balance_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" bigint NOT NULL,
  "sku_id" bigint NOT NULL,
  "warehouse_id" bigint NOT NULL DEFAULT 1,
  "batch_id" bigint,
  "quantity" numeric(18,3) NOT NULL DEFAULT 0.000,
  "weight" numeric(18,3) NOT NULL DEFAULT 0.000,
  "avg_cost" numeric(18,4) NOT NULL DEFAULT 0.0000,
  "total_cost" numeric(18,2) NOT NULL DEFAULT 0.00,
  "warn_min" numeric(18,3),
  "warn_max" numeric(18,3),
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("balance_id"),
  CONSTRAINT "uk_sku_warehouse" UNIQUE ("sku_id", "warehouse_id")
);
COMMENT ON TABLE "t_stock_balance" IS '库存余额';
COMMENT ON COLUMN "t_stock_balance"."balance_id" IS '主键';
COMMENT ON COLUMN "t_stock_balance"."product_id" IS '商品 ID';
COMMENT ON COLUMN "t_stock_balance"."sku_id" IS '规格 ID';
COMMENT ON COLUMN "t_stock_balance"."warehouse_id" IS '仓库 ID，G-03 单仓库，字段保留备用';
COMMENT ON COLUMN "t_stock_balance"."batch_id" IS '批次 ID，G-03 不启用批次，字段保留备用';
COMMENT ON COLUMN "t_stock_balance"."quantity" IS '当前数量';
COMMENT ON COLUMN "t_stock_balance"."weight" IS '当前重量（kg）';
COMMENT ON COLUMN "t_stock_balance"."avg_cost" IS '加权平均成本单价（不含税），每次入库实时重算';
COMMENT ON COLUMN "t_stock_balance"."total_cost" IS '结存总成本（不含税）';
COMMENT ON COLUMN "t_stock_balance"."warn_min" IS '预警下限';
COMMENT ON COLUMN "t_stock_balance"."warn_max" IS '预警上限';
COMMENT ON COLUMN "t_stock_balance"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_stock_balance"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_stock_balance"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_stock_balance"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_stock_balance"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_stock_balance_idx_product_id" ON "t_stock_balance" ("product_id");
CREATE TRIGGER "trg_t_stock_balance_update_time" BEFORE UPDATE ON "t_stock_balance"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_stock_check  库存盘点单
-- ----------------------------
DROP TABLE IF EXISTS "t_stock_check";
CREATE TABLE "t_stock_check" (
  "check_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "check_no" varchar(32) NOT NULL,
  "warehouse_id" bigint NOT NULL DEFAULT 1,
  "check_type" smallint NOT NULL DEFAULT 1,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("check_id"),
  CONSTRAINT "uk_check_no" UNIQUE ("check_no")
);
COMMENT ON TABLE "t_stock_check" IS '库存盘点单';
COMMENT ON COLUMN "t_stock_check"."check_id" IS '主键';
COMMENT ON COLUMN "t_stock_check"."check_no" IS '盘点单号，PDD + yyyyMMdd + 4 位流水（G-01）';
COMMENT ON COLUMN "t_stock_check"."warehouse_id" IS '仓库 ID，G-03 单仓库，字段保留备用';
COMMENT ON COLUMN "t_stock_check"."check_type" IS '盘点类型：1 全盘，2 抽盘';
COMMENT ON COLUMN "t_stock_check"."status" IS '状态：1 待盘点，2 盘点中，3 已完成，4 已取消';
COMMENT ON COLUMN "t_stock_check"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_stock_check"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_stock_check"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_stock_check"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_stock_check"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_stock_check_idx_status" ON "t_stock_check" ("status");
CREATE TRIGGER "trg_t_stock_check_update_time" BEFORE UPDATE ON "t_stock_check"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_stock_check_item  库存盘点明细
-- ----------------------------
DROP TABLE IF EXISTS "t_stock_check_item";
CREATE TABLE "t_stock_check_item" (
  "item_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "check_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "sku_id" bigint NOT NULL,
  "book_quantity" numeric(18,3) NOT NULL DEFAULT 0.000,
  "book_weight" numeric(18,3) NOT NULL DEFAULT 0.000,
  "actual_quantity" numeric(18,3),
  "actual_weight" numeric(18,3),
  "diff_quantity" numeric(18,3),
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("item_id")
);
COMMENT ON TABLE "t_stock_check_item" IS '库存盘点明细';
COMMENT ON COLUMN "t_stock_check_item"."item_id" IS '主键';
COMMENT ON COLUMN "t_stock_check_item"."check_id" IS '盘点单 ID';
COMMENT ON COLUMN "t_stock_check_item"."product_id" IS '商品 ID';
COMMENT ON COLUMN "t_stock_check_item"."sku_id" IS '规格 ID';
COMMENT ON COLUMN "t_stock_check_item"."book_quantity" IS '账面数量';
COMMENT ON COLUMN "t_stock_check_item"."book_weight" IS '账面重量（kg）';
COMMENT ON COLUMN "t_stock_check_item"."actual_quantity" IS '实盘数量';
COMMENT ON COLUMN "t_stock_check_item"."actual_weight" IS '实盘重量（kg）';
COMMENT ON COLUMN "t_stock_check_item"."diff_quantity" IS '差异数量（实盘 - 账面）';
COMMENT ON COLUMN "t_stock_check_item"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_stock_check_item"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_stock_check_item"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_stock_check_item"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_stock_check_item"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_check_id" ON "t_stock_check_item" ("check_id");
CREATE INDEX "t_stock_check_item_idx_sku_id" ON "t_stock_check_item" ("sku_id");
CREATE TRIGGER "trg_t_stock_check_item_update_time" BEFORE UPDATE ON "t_stock_check_item"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_stock_flow  库存流水
-- ----------------------------
DROP TABLE IF EXISTS "t_stock_flow";
CREATE TABLE "t_stock_flow" (
  "flow_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "flow_no" varchar(64) NOT NULL,
  "product_id" bigint NOT NULL,
  "sku_id" bigint NOT NULL,
  "warehouse_id" bigint NOT NULL DEFAULT 1,
  "batch_id" bigint,
  "flow_type" smallint NOT NULL,
  "biz_type" smallint NOT NULL,
  "biz_id" bigint,
  "direction" smallint NOT NULL,
  "quantity" numeric(18,3) NOT NULL DEFAULT 0.000,
  "weight" numeric(18,3) NOT NULL DEFAULT 0.000,
  "unit_price" numeric(18,4) NOT NULL DEFAULT 0.0000,
  "amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "before_quantity" numeric(18,3) NOT NULL DEFAULT 0.000,
  "after_quantity" numeric(18,3) NOT NULL DEFAULT 0.000,
  "before_avg_cost" numeric(18,4) NOT NULL DEFAULT 0.0000,
  "after_avg_cost" numeric(18,4) NOT NULL DEFAULT 0.0000,
  "operate_by" bigint,
  "operate_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("flow_id")
);
COMMENT ON TABLE "t_stock_flow" IS '库存流水';
COMMENT ON COLUMN "t_stock_flow"."flow_id" IS '主键';
COMMENT ON COLUMN "t_stock_flow"."flow_no" IS '流水号';
COMMENT ON COLUMN "t_stock_flow"."product_id" IS '商品 ID';
COMMENT ON COLUMN "t_stock_flow"."sku_id" IS '规格 ID';
COMMENT ON COLUMN "t_stock_flow"."warehouse_id" IS '仓库 ID，G-03 单仓库，字段保留备用';
COMMENT ON COLUMN "t_stock_flow"."batch_id" IS '批次 ID，G-03 不启用，字段保留备用';
COMMENT ON COLUMN "t_stock_flow"."flow_type" IS '流水类型：1 采购入库，2 销售出库，3 退货入库，4 报损，5 报溢，6 盘点调整，7 规格转换出，8 规格转换入';
COMMENT ON COLUMN "t_stock_flow"."biz_type" IS '关联业务：1 采购，2 订单，3 分拣，4 盘点，5 报损报溢，6 规格转换';
COMMENT ON COLUMN "t_stock_flow"."biz_id" IS '关联业务单 ID';
COMMENT ON COLUMN "t_stock_flow"."direction" IS '方向：1 入，2 出';
COMMENT ON COLUMN "t_stock_flow"."quantity" IS '变动数量（正数）';
COMMENT ON COLUMN "t_stock_flow"."weight" IS '变动重量（kg，正数）';
COMMENT ON COLUMN "t_stock_flow"."unit_price" IS '变动单价（不含税）';
COMMENT ON COLUMN "t_stock_flow"."amount" IS '变动金额（不含税）';
COMMENT ON COLUMN "t_stock_flow"."before_quantity" IS '变动前数量';
COMMENT ON COLUMN "t_stock_flow"."after_quantity" IS '变动后数量';
COMMENT ON COLUMN "t_stock_flow"."before_avg_cost" IS '变动前加权平均成本';
COMMENT ON COLUMN "t_stock_flow"."after_avg_cost" IS '变动后加权平均成本';
COMMENT ON COLUMN "t_stock_flow"."operate_by" IS '操作人';
COMMENT ON COLUMN "t_stock_flow"."operate_time" IS '操作时间';
COMMENT ON COLUMN "t_stock_flow"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_stock_flow"."update_time" IS '更新时间';
CREATE INDEX "t_stock_flow_idx_product_sku" ON "t_stock_flow" ("product_id", "sku_id");
CREATE INDEX "idx_biz" ON "t_stock_flow" ("biz_type", "biz_id");
CREATE INDEX "t_stock_flow_idx_operate_time" ON "t_stock_flow" ("operate_time");
CREATE TRIGGER "trg_t_stock_flow_update_time" BEFORE UPDATE ON "t_stock_flow"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

