-- ==========================================================================
-- XSY-SCM  PostgreSQL 建表脚本 —— 补充模块（P1）
-- 由 MySQL 结构自动转换生成，表数量：23
-- 目标数据库：PostgreSQL 12+
-- ==========================================================================

-- ------------------------------------------------------------------
-- ON UPDATE CURRENT_TIMESTAMP 在 PostgreSQL 中没有等价列属性，
-- 统一用下面这个触发器函数替代（每张有 update_time 的表挂一个 BEFORE UPDATE 触发器）。
-- 如果业务代码里已经显式维护 update_time，可以整段删除。
-- ------------------------------------------------------------------
CREATE OR REPLACE FUNCTION xsy_set_update_time() RETURNS trigger AS $$
BEGIN
  NEW.update_time := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------
-- t_supplier_account  供应商账号
-- ----------------------------
DROP TABLE IF EXISTS "t_supplier_account";
CREATE TABLE "t_supplier_account" (
  "account_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "supplier_id" bigint NOT NULL,
  "account" varchar(64) NOT NULL,
  "mobile" varchar(32) NOT NULL DEFAULT '',
  "password" varchar(128) NOT NULL DEFAULT '',
  "openid" varchar(64) NOT NULL DEFAULT '',
  "login_version" integer NOT NULL DEFAULT 0,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("account_id"),
  CONSTRAINT "uk_account" UNIQUE ("account")
);
COMMENT ON TABLE "t_supplier_account" IS '供应商账号';
COMMENT ON COLUMN "t_supplier_account"."account_id" IS '主键';
COMMENT ON COLUMN "t_supplier_account"."supplier_id" IS '供应商ID';
COMMENT ON COLUMN "t_supplier_account"."account" IS '登录账号';
COMMENT ON COLUMN "t_supplier_account"."mobile" IS '手机号';
COMMENT ON COLUMN "t_supplier_account"."password" IS '密码（加密存储，禁止明文）';
COMMENT ON COLUMN "t_supplier_account"."openid" IS '微信openid（小程序登录用）';
COMMENT ON COLUMN "t_supplier_account"."login_version" IS '登录态版本号，改密/禁用后+1，使历史登录态失效';
COMMENT ON COLUMN "t_supplier_account"."status" IS '状态：1 启用，2 停用';
COMMENT ON COLUMN "t_supplier_account"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_supplier_account"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_supplier_account"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_supplier_account"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_supplier_account"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_supplier_account_idx_supplier_id" ON "t_supplier_account" ("supplier_id");
CREATE INDEX "idx_openid" ON "t_supplier_account" ("openid");
CREATE TRIGGER "trg_t_supplier_account_update_time" BEFORE UPDATE ON "t_supplier_account"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_supplier_product_apply  供应商商品提报
-- ----------------------------
DROP TABLE IF EXISTS "t_supplier_product_apply";
CREATE TABLE "t_supplier_product_apply" (
  "apply_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "apply_no" varchar(32) NOT NULL,
  "supplier_id" bigint NOT NULL,
  "product_name" varchar(128) NOT NULL,
  "alias" varchar(64) NOT NULL DEFAULT '',
  "category_id" bigint,
  "supply_price" numeric(18,4) NOT NULL DEFAULT 0.0000,
  "last_purchase_price" numeric(18,4) NOT NULL DEFAULT 0.0000,
  "image" varchar(255) NOT NULL DEFAULT '',
  "audit_status" smallint NOT NULL DEFAULT 1,
  "reject_reason" varchar(255) NOT NULL DEFAULT '',
  "product_id" bigint,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("apply_id"),
  CONSTRAINT "uk_apply_no" UNIQUE ("apply_no")
);
COMMENT ON TABLE "t_supplier_product_apply" IS '供应商商品提报';
COMMENT ON COLUMN "t_supplier_product_apply"."apply_id" IS '主键';
COMMENT ON COLUMN "t_supplier_product_apply"."apply_no" IS '提报单号，SPB + yyyyMMdd + 4 位流水';
COMMENT ON COLUMN "t_supplier_product_apply"."supplier_id" IS '供应商ID';
COMMENT ON COLUMN "t_supplier_product_apply"."product_name" IS '商品名称';
COMMENT ON COLUMN "t_supplier_product_apply"."alias" IS '商品别名（≤20 字）';
COMMENT ON COLUMN "t_supplier_product_apply"."category_id" IS '拟归类ID';
COMMENT ON COLUMN "t_supplier_product_apply"."supply_price" IS '供货价（不含税）';
COMMENT ON COLUMN "t_supplier_product_apply"."last_purchase_price" IS '最近一次进价（不含税，受权限控制）';
COMMENT ON COLUMN "t_supplier_product_apply"."image" IS '商品图片（文件服务）';
COMMENT ON COLUMN "t_supplier_product_apply"."audit_status" IS '审核状态：1 待审核，2 已通过，3 已驳回';
COMMENT ON COLUMN "t_supplier_product_apply"."reject_reason" IS '驳回原因';
COMMENT ON COLUMN "t_supplier_product_apply"."product_id" IS '审核通过后生成的商品ID';
COMMENT ON COLUMN "t_supplier_product_apply"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_supplier_product_apply"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_supplier_product_apply"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_supplier_product_apply"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_supplier_product_apply"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_supplier_product_apply_idx_supplier_id" ON "t_supplier_product_apply" ("supplier_id");
CREATE INDEX "idx_audit_status" ON "t_supplier_product_apply" ("audit_status");
CREATE TRIGGER "trg_t_supplier_product_apply_update_time" BEFORE UPDATE ON "t_supplier_product_apply"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_supplier_manufacturer  供应商厂商信息
-- ----------------------------
DROP TABLE IF EXISTS "t_supplier_manufacturer";
CREATE TABLE "t_supplier_manufacturer" (
  "manufacturer_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "supplier_id" bigint NOT NULL,
  "manufacturer_name" varchar(128) NOT NULL,
  "qualification_file" varchar(255) NOT NULL DEFAULT '',
  "qualification_expire_date" date,
  "inspect_report_file" varchar(255) NOT NULL DEFAULT '',
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("manufacturer_id")
);
COMMENT ON TABLE "t_supplier_manufacturer" IS '供应商厂商信息';
COMMENT ON COLUMN "t_supplier_manufacturer"."manufacturer_id" IS '主键';
COMMENT ON COLUMN "t_supplier_manufacturer"."supplier_id" IS '供应商ID';
COMMENT ON COLUMN "t_supplier_manufacturer"."manufacturer_name" IS '厂商名称';
COMMENT ON COLUMN "t_supplier_manufacturer"."qualification_file" IS '资质证件（文件服务）';
COMMENT ON COLUMN "t_supplier_manufacturer"."qualification_expire_date" IS '资质到期日期（支持预警）';
COMMENT ON COLUMN "t_supplier_manufacturer"."inspect_report_file" IS '质检报告文件（文件服务）';
COMMENT ON COLUMN "t_supplier_manufacturer"."status" IS '状态：1 启用，2 停用';
COMMENT ON COLUMN "t_supplier_manufacturer"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_supplier_manufacturer"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_supplier_manufacturer"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_supplier_manufacturer"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_supplier_manufacturer"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_supplier_manufacturer_idx_supplier_id" ON "t_supplier_manufacturer" ("supplier_id");
CREATE TRIGGER "trg_t_supplier_manufacturer_update_time" BEFORE UPDATE ON "t_supplier_manufacturer"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_supplier_statement  供应商对账单
-- ----------------------------
DROP TABLE IF EXISTS "t_supplier_statement";
CREATE TABLE "t_supplier_statement" (
  "statement_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "statement_no" varchar(32) NOT NULL,
  "supplier_id" bigint NOT NULL,
  "period_start" date NOT NULL,
  "period_end" date NOT NULL,
  "total_amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "paid_amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("statement_id"),
  CONSTRAINT "uk_statement_no" UNIQUE ("statement_no")
);
COMMENT ON TABLE "t_supplier_statement" IS '供应商对账单';
COMMENT ON COLUMN "t_supplier_statement"."statement_id" IS '主键';
COMMENT ON COLUMN "t_supplier_statement"."statement_no" IS '对账单号，DZD + yyyyMMdd + 4 位流水';
COMMENT ON COLUMN "t_supplier_statement"."supplier_id" IS '供应商ID';
COMMENT ON COLUMN "t_supplier_statement"."period_start" IS '对账周期开始';
COMMENT ON COLUMN "t_supplier_statement"."period_end" IS '对账周期结束';
COMMENT ON COLUMN "t_supplier_statement"."total_amount" IS '对账总金额（不含税）';
COMMENT ON COLUMN "t_supplier_statement"."paid_amount" IS '已结算金额（不含税）';
COMMENT ON COLUMN "t_supplier_statement"."status" IS '状态：1 待供应商确认，2 供应商已确认，3 已结算，4 已驳回';
COMMENT ON COLUMN "t_supplier_statement"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_supplier_statement"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_supplier_statement"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_supplier_statement"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_supplier_statement"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_supplier_statement_idx_supplier_id" ON "t_supplier_statement" ("supplier_id");
CREATE INDEX "t_supplier_statement_idx_status" ON "t_supplier_statement" ("status");
CREATE TRIGGER "trg_t_supplier_statement_update_time" BEFORE UPDATE ON "t_supplier_statement"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_inquiry  询价单
-- ----------------------------
DROP TABLE IF EXISTS "t_inquiry";
CREATE TABLE "t_inquiry" (
  "inquiry_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "inquiry_no" varchar(32) NOT NULL,
  "inquiry_name" varchar(128) NOT NULL DEFAULT '',
  "valid_start" timestamp NOT NULL,
  "valid_end" timestamp NOT NULL,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("inquiry_id"),
  CONSTRAINT "uk_inquiry_no" UNIQUE ("inquiry_no")
);
COMMENT ON TABLE "t_inquiry" IS '询价单';
COMMENT ON COLUMN "t_inquiry"."inquiry_id" IS '主键';
COMMENT ON COLUMN "t_inquiry"."inquiry_no" IS '询价单号，XJD + yyyyMMdd + 4 位流水';
COMMENT ON COLUMN "t_inquiry"."inquiry_name" IS '询价单名称';
COMMENT ON COLUMN "t_inquiry"."valid_start" IS '询价有效开始时间';
COMMENT ON COLUMN "t_inquiry"."valid_end" IS '询价有效结束时间';
COMMENT ON COLUMN "t_inquiry"."status" IS '状态：1 待报价，2 报价中，3 已完成，4 已取消';
COMMENT ON COLUMN "t_inquiry"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_inquiry"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_inquiry"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_inquiry"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_inquiry"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_inquiry_idx_status" ON "t_inquiry" ("status");
CREATE TRIGGER "trg_t_inquiry_update_time" BEFORE UPDATE ON "t_inquiry"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_inquiry_item  询价明细
-- ----------------------------
DROP TABLE IF EXISTS "t_inquiry_item";
CREATE TABLE "t_inquiry_item" (
  "item_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "inquiry_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "sku_id" bigint,
  "require_quantity" numeric(18,3) NOT NULL DEFAULT 0.000,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("item_id")
);
COMMENT ON TABLE "t_inquiry_item" IS '询价明细';
COMMENT ON COLUMN "t_inquiry_item"."item_id" IS '主键';
COMMENT ON COLUMN "t_inquiry_item"."inquiry_id" IS '询价单ID';
COMMENT ON COLUMN "t_inquiry_item"."product_id" IS '商品ID';
COMMENT ON COLUMN "t_inquiry_item"."sku_id" IS '规格ID';
COMMENT ON COLUMN "t_inquiry_item"."require_quantity" IS '询价数量';
COMMENT ON COLUMN "t_inquiry_item"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_inquiry_item"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_inquiry_item"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_inquiry_item"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_inquiry_item"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_inquiry_id" ON "t_inquiry_item" ("inquiry_id");
CREATE INDEX "t_inquiry_item_idx_product_id" ON "t_inquiry_item" ("product_id");
CREATE TRIGGER "trg_t_inquiry_item_update_time" BEFORE UPDATE ON "t_inquiry_item"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_inquiry_quote  供应商报价
-- ----------------------------
DROP TABLE IF EXISTS "t_inquiry_quote";
CREATE TABLE "t_inquiry_quote" (
  "quote_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "inquiry_id" bigint NOT NULL,
  "item_id" bigint NOT NULL,
  "supplier_id" bigint NOT NULL,
  "quote_price" numeric(18,4) NOT NULL DEFAULT 0.0000,
  "quote_time" timestamp,
  "score" numeric(5,2) NOT NULL DEFAULT 0.00,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("quote_id"),
  CONSTRAINT "uk_item_supplier" UNIQUE ("item_id", "supplier_id")
);
COMMENT ON TABLE "t_inquiry_quote" IS '供应商报价';
COMMENT ON COLUMN "t_inquiry_quote"."quote_id" IS '主键';
COMMENT ON COLUMN "t_inquiry_quote"."inquiry_id" IS '询价单ID';
COMMENT ON COLUMN "t_inquiry_quote"."item_id" IS '询价明细ID';
COMMENT ON COLUMN "t_inquiry_quote"."supplier_id" IS '供应商ID';
COMMENT ON COLUMN "t_inquiry_quote"."quote_price" IS '报价（不含税）';
COMMENT ON COLUMN "t_inquiry_quote"."quote_time" IS '报价时间';
COMMENT ON COLUMN "t_inquiry_quote"."score" IS '供应商综合评分（0~100）';
COMMENT ON COLUMN "t_inquiry_quote"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_inquiry_quote"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_inquiry_quote"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_inquiry_quote"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_inquiry_quote"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_inquiry_quote_idx_inquiry_id" ON "t_inquiry_quote" ("inquiry_id");
CREATE INDEX "t_inquiry_quote_idx_supplier_id" ON "t_inquiry_quote" ("supplier_id");
CREATE TRIGGER "trg_t_inquiry_quote_update_time" BEFORE UPDATE ON "t_inquiry_quote"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_product_convert  商品转换单
-- ----------------------------
DROP TABLE IF EXISTS "t_product_convert";
CREATE TABLE "t_product_convert" (
  "convert_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "convert_no" varchar(32) NOT NULL,
  "convert_type" smallint NOT NULL DEFAULT 1,
  "warehouse_id" bigint NOT NULL DEFAULT 1,
  "source_type" smallint NOT NULL DEFAULT 1,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("convert_id"),
  CONSTRAINT "uk_convert_no" UNIQUE ("convert_no")
);
COMMENT ON TABLE "t_product_convert" IS '商品转换单';
COMMENT ON COLUMN "t_product_convert"."convert_id" IS '主键';
COMMENT ON COLUMN "t_product_convert"."convert_no" IS '转换单号，ZHD + yyyyMMdd + 4 位流水';
COMMENT ON COLUMN "t_product_convert"."convert_type" IS '转换类型：1 整件拆零，2 组合拆分';
COMMENT ON COLUMN "t_product_convert"."warehouse_id" IS '仓库ID（单仓库，字段保留）';
COMMENT ON COLUMN "t_product_convert"."source_type" IS '来源：1 手工创建，2 发货差异表批量转换';
COMMENT ON COLUMN "t_product_convert"."status" IS '状态：1 待审核，2 已完成，3 已驳回';
COMMENT ON COLUMN "t_product_convert"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_product_convert"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_product_convert"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_product_convert"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_product_convert"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_product_convert_idx_status" ON "t_product_convert" ("status");
CREATE TRIGGER "trg_t_product_convert_update_time" BEFORE UPDATE ON "t_product_convert"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_product_convert_item  商品转换明细
-- ----------------------------
DROP TABLE IF EXISTS "t_product_convert_item";
CREATE TABLE "t_product_convert_item" (
  "item_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "convert_id" bigint NOT NULL,
  "source_product_id" bigint NOT NULL,
  "source_sku_id" bigint,
  "source_quantity" numeric(18,3) NOT NULL DEFAULT 0.000,
  "source_weight" numeric(18,3) NOT NULL DEFAULT 0.000,
  "target_product_id" bigint NOT NULL,
  "target_sku_id" bigint,
  "target_quantity" numeric(18,3) NOT NULL DEFAULT 0.000,
  "target_weight" numeric(18,3) NOT NULL DEFAULT 0.000,
  "target_unit_price" numeric(18,4) NOT NULL DEFAULT 0.0000,
  "target_amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("item_id")
);
COMMENT ON TABLE "t_product_convert_item" IS '商品转换明细';
COMMENT ON COLUMN "t_product_convert_item"."item_id" IS '主键';
COMMENT ON COLUMN "t_product_convert_item"."convert_id" IS '转换单ID';
COMMENT ON COLUMN "t_product_convert_item"."source_product_id" IS '原商品ID';
COMMENT ON COLUMN "t_product_convert_item"."source_sku_id" IS '原规格ID';
COMMENT ON COLUMN "t_product_convert_item"."source_quantity" IS '出库数量（扣减原商品）';
COMMENT ON COLUMN "t_product_convert_item"."source_weight" IS '出库重量（kg）';
COMMENT ON COLUMN "t_product_convert_item"."target_product_id" IS '目标商品ID';
COMMENT ON COLUMN "t_product_convert_item"."target_sku_id" IS '目标规格ID';
COMMENT ON COLUMN "t_product_convert_item"."target_quantity" IS '入库数量';
COMMENT ON COLUMN "t_product_convert_item"."target_weight" IS '入库重量（kg）';
COMMENT ON COLUMN "t_product_convert_item"."target_unit_price" IS '入库单价（不含税），生成新商品成本';
COMMENT ON COLUMN "t_product_convert_item"."target_amount" IS '入库金额（不含税）';
COMMENT ON COLUMN "t_product_convert_item"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_product_convert_item"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_product_convert_item"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_product_convert_item"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_product_convert_item"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_convert_id" ON "t_product_convert_item" ("convert_id");
CREATE INDEX "idx_source_product_id" ON "t_product_convert_item" ("source_product_id");
CREATE INDEX "idx_target_product_id" ON "t_product_convert_item" ("target_product_id");
CREATE TRIGGER "trg_t_product_convert_item_update_time" BEFORE UPDATE ON "t_product_convert_item"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_customer_discount  客户折扣率（计算折前价）
-- ----------------------------
DROP TABLE IF EXISTS "t_customer_discount";
CREATE TABLE "t_customer_discount" (
  "discount_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "customer_id" bigint NOT NULL,
  "scope_type" smallint NOT NULL DEFAULT 1,
  "product_id" bigint,
  "category_id" bigint,
  "discount_rate" numeric(18,4) NOT NULL DEFAULT 1.0000,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("discount_id")
);
COMMENT ON TABLE "t_customer_discount" IS '客户折扣率（计算折前价）';
COMMENT ON COLUMN "t_customer_discount"."discount_id" IS '主键';
COMMENT ON COLUMN "t_customer_discount"."customer_id" IS '客户ID';
COMMENT ON COLUMN "t_customer_discount"."scope_type" IS '折扣范围：1 统一折扣，2 按商品，3 按分类';
COMMENT ON COLUMN "t_customer_discount"."product_id" IS '商品ID（scope_type=2 时使用）';
COMMENT ON COLUMN "t_customer_discount"."category_id" IS '分类ID（scope_type=3 时使用）';
COMMENT ON COLUMN "t_customer_discount"."discount_rate" IS '折扣率（0~1，1 表示不打折）';
COMMENT ON COLUMN "t_customer_discount"."status" IS '状态：1 生效，2 停用';
COMMENT ON COLUMN "t_customer_discount"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_customer_discount"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_customer_discount"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_customer_discount"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_customer_discount"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_customer_discount_idx_customer_id" ON "t_customer_discount" ("customer_id");
CREATE INDEX "t_customer_discount_idx_product_id" ON "t_customer_discount" ("product_id");
CREATE INDEX "t_customer_discount_idx_category_id" ON "t_customer_discount" ("category_id");
CREATE TRIGGER "trg_t_customer_discount_update_time" BEFORE UPDATE ON "t_customer_discount"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_customer_product_alias  客户商品别名
-- ----------------------------
DROP TABLE IF EXISTS "t_customer_product_alias";
CREATE TABLE "t_customer_product_alias" (
  "alias_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "customer_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "sku_id" bigint,
  "alias_name" varchar(64) NOT NULL DEFAULT '',
  "alias_desc" varchar(50) NOT NULL DEFAULT '',
  "sub_alias_name" varchar(64) NOT NULL DEFAULT '',
  "sub_alias_desc" varchar(50) NOT NULL DEFAULT '',
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("alias_id"),
  CONSTRAINT "uk_customer_product_sku" UNIQUE ("customer_id", "product_id", "sku_id")
);
COMMENT ON TABLE "t_customer_product_alias" IS '客户商品别名';
COMMENT ON COLUMN "t_customer_product_alias"."alias_id" IS '主键';
COMMENT ON COLUMN "t_customer_product_alias"."customer_id" IS '客户ID';
COMMENT ON COLUMN "t_customer_product_alias"."product_id" IS '商品ID';
COMMENT ON COLUMN "t_customer_product_alias"."sku_id" IS '规格ID';
COMMENT ON COLUMN "t_customer_product_alias"."alias_name" IS '别名';
COMMENT ON COLUMN "t_customer_product_alias"."alias_desc" IS '别名描述（≤50 字）';
COMMENT ON COLUMN "t_customer_product_alias"."sub_alias_name" IS '副别名';
COMMENT ON COLUMN "t_customer_product_alias"."sub_alias_desc" IS '副别名描述（≤50 字）';
COMMENT ON COLUMN "t_customer_product_alias"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_customer_product_alias"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_customer_product_alias"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_customer_product_alias"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_customer_product_alias"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_customer_product_alias_idx_product_id" ON "t_customer_product_alias" ("product_id");
CREATE TRIGGER "trg_t_customer_product_alias_update_time" BEFORE UPDATE ON "t_customer_product_alias"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_product_barcode  商品条码
-- ----------------------------
DROP TABLE IF EXISTS "t_product_barcode";
CREATE TABLE "t_product_barcode" (
  "barcode_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_id" bigint NOT NULL,
  "sku_id" bigint,
  "barcode" varchar(64) NOT NULL,
  "unit" varchar(32) NOT NULL DEFAULT '',
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("barcode_id"),
  CONSTRAINT "uk_barcode" UNIQUE ("barcode")
);
COMMENT ON TABLE "t_product_barcode" IS '商品条码';
COMMENT ON COLUMN "t_product_barcode"."barcode_id" IS '主键';
COMMENT ON COLUMN "t_product_barcode"."product_id" IS '商品ID';
COMMENT ON COLUMN "t_product_barcode"."sku_id" IS '规格ID';
COMMENT ON COLUMN "t_product_barcode"."barcode" IS '条形码（唯一）';
COMMENT ON COLUMN "t_product_barcode"."unit" IS '对应单位';
COMMENT ON COLUMN "t_product_barcode"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_product_barcode"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_product_barcode"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_product_barcode"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_product_barcode"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_product_barcode_idx_product_id" ON "t_product_barcode" ("product_id");
CREATE TRIGGER "trg_t_product_barcode_update_time" BEFORE UPDATE ON "t_product_barcode"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_print_template  打印模板
-- ----------------------------
DROP TABLE IF EXISTS "t_print_template";
CREATE TABLE "t_print_template" (
  "template_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "template_code" varchar(64) NOT NULL,
  "template_name" varchar(128) NOT NULL,
  "biz_type" smallint NOT NULL,
  "content" text NOT NULL,
  "paper_size" varchar(32) NOT NULL DEFAULT '',
  "default_flag" smallint NOT NULL DEFAULT 0,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("template_id"),
  CONSTRAINT "uk_template_code" UNIQUE ("template_code")
);
COMMENT ON TABLE "t_print_template" IS '打印模板';
COMMENT ON COLUMN "t_print_template"."template_id" IS '主键';
COMMENT ON COLUMN "t_print_template"."template_code" IS '模板编码';
COMMENT ON COLUMN "t_print_template"."template_name" IS '模板名称';
COMMENT ON COLUMN "t_print_template"."biz_type" IS '业务类型：1 采购单，2 发货单，3 分拣小票，4 询价报价单';
COMMENT ON COLUMN "t_print_template"."content" IS '模板内容（HTML，{{key}} 占位）';
COMMENT ON COLUMN "t_print_template"."paper_size" IS '纸张规格（A4 / 58mm / 80mm）';
COMMENT ON COLUMN "t_print_template"."default_flag" IS '是否默认模板：0 否，1 是';
COMMENT ON COLUMN "t_print_template"."status" IS '状态：1 启用，2 停用';
COMMENT ON COLUMN "t_print_template"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_print_template"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_print_template"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_print_template"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_print_template"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_biz_type" ON "t_print_template" ("biz_type");
CREATE TRIGGER "trg_t_print_template_update_time" BEFORE UPDATE ON "t_print_template"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_screen_config  数据大屏配置
-- ----------------------------
DROP TABLE IF EXISTS "t_screen_config";
CREATE TABLE "t_screen_config" (
  "screen_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "screen_code" smallint NOT NULL,
  "screen_name" varchar(64) NOT NULL DEFAULT '',
  "layout_json" text,
  "refresh_interval" integer,
  "sort_field" varchar(32) NOT NULL DEFAULT '',
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("screen_id")
);
COMMENT ON TABLE "t_screen_config" IS '数据大屏配置';
COMMENT ON COLUMN "t_screen_config"."screen_id" IS '主键';
COMMENT ON COLUMN "t_screen_config"."screen_code" IS '大屏编码：1 经营，2 库存，3 采购，4 分拣绩效，5 配送，6 溯源';
COMMENT ON COLUMN "t_screen_config"."screen_name" IS '大屏名称';
COMMENT ON COLUMN "t_screen_config"."layout_json" IS '布局与指标配置（JSON）';
COMMENT ON COLUMN "t_screen_config"."refresh_interval" IS '刷新间隔（秒）';
COMMENT ON COLUMN "t_screen_config"."sort_field" IS '排序维度';
COMMENT ON COLUMN "t_screen_config"."status" IS '状态：1 启用，2 停用';
COMMENT ON COLUMN "t_screen_config"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_screen_config"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_screen_config"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_screen_config"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_screen_config"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_screen_code" ON "t_screen_config" ("screen_code");
CREATE TRIGGER "trg_t_screen_config_update_time" BEFORE UPDATE ON "t_screen_config"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_finance_voucher  会计凭证
-- ----------------------------
DROP TABLE IF EXISTS "t_finance_voucher";
CREATE TABLE "t_finance_voucher" (
  "voucher_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "voucher_no" varchar(32) NOT NULL,
  "voucher_date" date NOT NULL,
  "voucher_type" smallint NOT NULL,
  "biz_type" smallint,
  "biz_id" bigint,
  "total_debit" numeric(18,2) NOT NULL DEFAULT 0.00,
  "total_credit" numeric(18,2) NOT NULL DEFAULT 0.00,
  "sync_status" smallint NOT NULL DEFAULT 1,
  "external_no" varchar(64) NOT NULL DEFAULT '',
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("voucher_id"),
  CONSTRAINT "uk_voucher_no" UNIQUE ("voucher_no")
);
COMMENT ON TABLE "t_finance_voucher" IS '会计凭证';
COMMENT ON COLUMN "t_finance_voucher"."voucher_id" IS '主键';
COMMENT ON COLUMN "t_finance_voucher"."voucher_no" IS '凭证号，PZD + yyyyMMdd + 4 位流水';
COMMENT ON COLUMN "t_finance_voucher"."voucher_date" IS '凭证日期';
COMMENT ON COLUMN "t_finance_voucher"."voucher_type" IS '凭证类型：1 收款，2 付款，3 应收，4 应付，5 费用';
COMMENT ON COLUMN "t_finance_voucher"."biz_type" IS '关联业务类型';
COMMENT ON COLUMN "t_finance_voucher"."biz_id" IS '关联业务单ID';
COMMENT ON COLUMN "t_finance_voucher"."total_debit" IS '借方合计（不含税）';
COMMENT ON COLUMN "t_finance_voucher"."total_credit" IS '贷方合计（不含税）';
COMMENT ON COLUMN "t_finance_voucher"."sync_status" IS '同步状态：1 未同步，2 同步中，3 同步成功，4 同步失败';
COMMENT ON COLUMN "t_finance_voucher"."external_no" IS '外部系统单据号';
COMMENT ON COLUMN "t_finance_voucher"."status" IS '凭证状态：1 已生成，2 已作废';
COMMENT ON COLUMN "t_finance_voucher"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_finance_voucher"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_finance_voucher"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_finance_voucher"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_finance_voucher"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_voucher_type" ON "t_finance_voucher" ("voucher_type");
CREATE INDEX "t_finance_voucher_idx_biz" ON "t_finance_voucher" ("biz_type", "biz_id");
CREATE INDEX "idx_sync_status" ON "t_finance_voucher" ("sync_status");
CREATE TRIGGER "trg_t_finance_voucher_update_time" BEFORE UPDATE ON "t_finance_voucher"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_voucher_entry  凭证分录
-- ----------------------------
DROP TABLE IF EXISTS "t_voucher_entry";
CREATE TABLE "t_voucher_entry" (
  "entry_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "voucher_id" bigint NOT NULL,
  "subject_code" varchar(32) NOT NULL,
  "subject_name" varchar(64) NOT NULL DEFAULT '',
  "direction" smallint NOT NULL,
  "amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("entry_id")
);
COMMENT ON TABLE "t_voucher_entry" IS '凭证分录';
COMMENT ON COLUMN "t_voucher_entry"."entry_id" IS '主键';
COMMENT ON COLUMN "t_voucher_entry"."voucher_id" IS '凭证ID';
COMMENT ON COLUMN "t_voucher_entry"."subject_code" IS '会计科目编码';
COMMENT ON COLUMN "t_voucher_entry"."subject_name" IS '会计科目名称';
COMMENT ON COLUMN "t_voucher_entry"."direction" IS '借贷方向：1 借，2 贷';
COMMENT ON COLUMN "t_voucher_entry"."amount" IS '金额（不含税）';
COMMENT ON COLUMN "t_voucher_entry"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_voucher_entry"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_voucher_entry"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_voucher_entry"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_voucher_entry"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_voucher_id" ON "t_voucher_entry" ("voucher_id");
CREATE TRIGGER "trg_t_voucher_entry_update_time" BEFORE UPDATE ON "t_voucher_entry"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_external_config  外部系统配置
-- ----------------------------
DROP TABLE IF EXISTS "t_external_config";
CREATE TABLE "t_external_config" (
  "config_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "system_type" smallint NOT NULL,
  "api_url" varchar(255) NOT NULL DEFAULT '',
  "app_key" varchar(128) NOT NULL DEFAULT '',
  "app_secret" varchar(255) NOT NULL DEFAULT '',
  "field_mapping_json" text,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("config_id")
);
COMMENT ON TABLE "t_external_config" IS '外部系统配置';
COMMENT ON COLUMN "t_external_config"."config_id" IS '主键';
COMMENT ON COLUMN "t_external_config"."system_type" IS '系统类型：1 金蝶云星空，2 金蝶云星瀚，3 用友T+，4 用友U8，5 溯源平台，6 团餐平台';
COMMENT ON COLUMN "t_external_config"."api_url" IS '接口地址';
COMMENT ON COLUMN "t_external_config"."app_key" IS '应用Key';
COMMENT ON COLUMN "t_external_config"."app_secret" IS '应用密钥（加密存储）';
COMMENT ON COLUMN "t_external_config"."field_mapping_json" IS '字段映射配置（JSON）';
COMMENT ON COLUMN "t_external_config"."status" IS '状态：1 启用，2 停用';
COMMENT ON COLUMN "t_external_config"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_external_config"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_external_config"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_external_config"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_external_config"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_system_type" ON "t_external_config" ("system_type");
CREATE TRIGGER "trg_t_external_config_update_time" BEFORE UPDATE ON "t_external_config"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_invoice  发票
-- ----------------------------
DROP TABLE IF EXISTS "t_invoice";
CREATE TABLE "t_invoice" (
  "invoice_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "invoice_no" varchar(64) NOT NULL,
  "order_id" bigint NOT NULL,
  "relate_invoice_nos" varchar(512) NOT NULL DEFAULT '',
  "amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "tax_rate" numeric(18,4) NOT NULL DEFAULT 0.0000,
  "status" smallint NOT NULL DEFAULT 2,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("invoice_id"),
  CONSTRAINT "uk_invoice_no" UNIQUE ("invoice_no")
);
COMMENT ON TABLE "t_invoice" IS '发票';
COMMENT ON COLUMN "t_invoice"."invoice_id" IS '主键';
COMMENT ON COLUMN "t_invoice"."invoice_no" IS '发票号';
COMMENT ON COLUMN "t_invoice"."order_id" IS '关联订单ID';
COMMENT ON COLUMN "t_invoice"."relate_invoice_nos" IS '关联发票号（多张逗号分隔）';
COMMENT ON COLUMN "t_invoice"."amount" IS '价税合计';
COMMENT ON COLUMN "t_invoice"."tax_rate" IS '税率';
COMMENT ON COLUMN "t_invoice"."status" IS '状态：1 可开票，2 已开票，3 已红冲';
COMMENT ON COLUMN "t_invoice"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_invoice"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_invoice"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_invoice"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_invoice"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_invoice_idx_order_id" ON "t_invoice" ("order_id");
CREATE INDEX "t_invoice_idx_status" ON "t_invoice" ("status");
CREATE TRIGGER "trg_t_invoice_update_time" BEFORE UPDATE ON "t_invoice"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_trace_batch  溯源批次（生产批号）
-- ----------------------------
DROP TABLE IF EXISTS "t_trace_batch";
CREATE TABLE "t_trace_batch" (
  "batch_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "batch_no" varchar(32) NOT NULL,
  "product_id" bigint NOT NULL,
  "sku_id" bigint,
  "supplier_id" bigint,
  "manufacturer_id" bigint,
  "produce_batch_no" varchar(64) NOT NULL,
  "origin_place" varchar(128) NOT NULL DEFAULT '',
  "produce_date" date NOT NULL,
  "shelf_life_unit" smallint,
  "shelf_life_value" integer,
  "expire_date" date,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("batch_id"),
  CONSTRAINT "uk_trace_batch_no" UNIQUE ("batch_no")
);
COMMENT ON TABLE "t_trace_batch" IS '溯源批次（生产批号）';
COMMENT ON COLUMN "t_trace_batch"."batch_id" IS '主键';
COMMENT ON COLUMN "t_trace_batch"."batch_no" IS '批次号，PCB + yyyyMMdd + 4 位流水';
COMMENT ON COLUMN "t_trace_batch"."product_id" IS '商品ID';
COMMENT ON COLUMN "t_trace_batch"."sku_id" IS '规格ID';
COMMENT ON COLUMN "t_trace_batch"."supplier_id" IS '供应商ID';
COMMENT ON COLUMN "t_trace_batch"."manufacturer_id" IS '厂商ID';
COMMENT ON COLUMN "t_trace_batch"."produce_batch_no" IS '生产批号';
COMMENT ON COLUMN "t_trace_batch"."origin_place" IS '产地';
COMMENT ON COLUMN "t_trace_batch"."produce_date" IS '生产/采收日期';
COMMENT ON COLUMN "t_trace_batch"."shelf_life_unit" IS '保质期单位：1 天，2 月';
COMMENT ON COLUMN "t_trace_batch"."shelf_life_value" IS '保质期数值';
COMMENT ON COLUMN "t_trace_batch"."expire_date" IS '到期日期';
COMMENT ON COLUMN "t_trace_batch"."status" IS '状态：1 有效，2 已过期，3 已作废';
COMMENT ON COLUMN "t_trace_batch"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_trace_batch"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_trace_batch"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_trace_batch"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_trace_batch"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_trace_batch_idx_product_id" ON "t_trace_batch" ("product_id");
CREATE INDEX "t_trace_batch_idx_supplier_id" ON "t_trace_batch" ("supplier_id");
CREATE TRIGGER "trg_t_trace_batch_update_time" BEFORE UPDATE ON "t_trace_batch"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_trace_inspect  检测报告
-- ----------------------------
DROP TABLE IF EXISTS "t_trace_inspect";
CREATE TABLE "t_trace_inspect" (
  "inspect_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "batch_id" bigint,
  "product_id" bigint NOT NULL,
  "report_name" varchar(128) NOT NULL,
  "match_mode" smallint NOT NULL DEFAULT 2,
  "report_file" varchar(255) NOT NULL DEFAULT '',
  "pdf_file" varchar(255) NOT NULL DEFAULT '',
  "inspect_date" date,
  "inspect_org" varchar(128) NOT NULL DEFAULT '',
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("inspect_id")
);
COMMENT ON TABLE "t_trace_inspect" IS '检测报告';
COMMENT ON COLUMN "t_trace_inspect"."inspect_id" IS '主键';
COMMENT ON COLUMN "t_trace_inspect"."batch_id" IS '关联溯源批次ID';
COMMENT ON COLUMN "t_trace_inspect"."product_id" IS '商品ID';
COMMENT ON COLUMN "t_trace_inspect"."report_name" IS '报告名称';
COMMENT ON COLUMN "t_trace_inspect"."match_mode" IS '匹配模式：1 绑定采购单，2 绑定生产批号';
COMMENT ON COLUMN "t_trace_inspect"."report_file" IS '报告图片';
COMMENT ON COLUMN "t_trace_inspect"."pdf_file" IS '报告PDF';
COMMENT ON COLUMN "t_trace_inspect"."inspect_date" IS '检测日期';
COMMENT ON COLUMN "t_trace_inspect"."inspect_org" IS '检测机构';
COMMENT ON COLUMN "t_trace_inspect"."status" IS '状态：1 有效，2 已作废';
COMMENT ON COLUMN "t_trace_inspect"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_trace_inspect"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_trace_inspect"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_trace_inspect"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_trace_inspect"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_batch_id" ON "t_trace_inspect" ("batch_id");
CREATE INDEX "t_trace_inspect_idx_product_id" ON "t_trace_inspect" ("product_id");
CREATE TRIGGER "trg_t_trace_inspect_update_time" BEFORE UPDATE ON "t_trace_inspect"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_trace_code  溯源码
-- ----------------------------
DROP TABLE IF EXISTS "t_trace_code";
CREATE TABLE "t_trace_code" (
  "code_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "trace_code" varchar(64) NOT NULL,
  "code_type" smallint NOT NULL DEFAULT 1,
  "product_id" bigint NOT NULL,
  "sku_id" bigint,
  "batch_id" bigint NOT NULL,
  "qrcode_url" varchar(255) NOT NULL DEFAULT '',
  "status" smallint NOT NULL DEFAULT 2,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("code_id"),
  CONSTRAINT "uk_trace_code" UNIQUE ("trace_code")
);
COMMENT ON TABLE "t_trace_code" IS '溯源码';
COMMENT ON COLUMN "t_trace_code"."code_id" IS '主键';
COMMENT ON COLUMN "t_trace_code"."trace_code" IS '唯一溯源码';
COMMENT ON COLUMN "t_trace_code"."code_type" IS '类型：1 批次码';
COMMENT ON COLUMN "t_trace_code"."product_id" IS '商品ID';
COMMENT ON COLUMN "t_trace_code"."sku_id" IS '规格ID';
COMMENT ON COLUMN "t_trace_code"."batch_id" IS '关联溯源批次ID';
COMMENT ON COLUMN "t_trace_code"."qrcode_url" IS '二维码图片';
COMMENT ON COLUMN "t_trace_code"."status" IS '状态：1 未启用，2 已启用，3 已作废';
COMMENT ON COLUMN "t_trace_code"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_trace_code"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_trace_code"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_trace_code"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_trace_code"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_trace_code_idx_batch_id" ON "t_trace_code" ("batch_id");
CREATE INDEX "t_trace_code_idx_product_id" ON "t_trace_code" ("product_id");
CREATE TRIGGER "trg_t_trace_code_update_time" BEFORE UPDATE ON "t_trace_code"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_external_mapping  外部平台映射
-- ----------------------------
DROP TABLE IF EXISTS "t_external_mapping";
CREATE TABLE "t_external_mapping" (
  "mapping_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "system_type" smallint NOT NULL,
  "biz_type" smallint NOT NULL,
  "local_id" bigint NOT NULL,
  "external_id" varchar(64) NOT NULL,
  "convert_ratio" numeric(18,4) NOT NULL DEFAULT 1.0000,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("mapping_id")
);
COMMENT ON TABLE "t_external_mapping" IS '外部平台映射';
COMMENT ON COLUMN "t_external_mapping"."mapping_id" IS '主键';
COMMENT ON COLUMN "t_external_mapping"."system_type" IS '平台类型：1 金蝶云星空，2 金蝶云星瀚，3 用友T+，4 用友U8，5 溯源平台，6 团餐平台';
COMMENT ON COLUMN "t_external_mapping"."biz_type" IS '映射对象：1 商品，2 客户，3 供应商';
COMMENT ON COLUMN "t_external_mapping"."local_id" IS '系统内ID';
COMMENT ON COLUMN "t_external_mapping"."external_id" IS '外部平台ID';
COMMENT ON COLUMN "t_external_mapping"."convert_ratio" IS '单位转换系数（未填默认1）';
COMMENT ON COLUMN "t_external_mapping"."status" IS '状态：1 启用，2 停用';
COMMENT ON COLUMN "t_external_mapping"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_external_mapping"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_external_mapping"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_external_mapping"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_external_mapping"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "idx_system_biz" ON "t_external_mapping" ("system_type", "biz_type");
CREATE INDEX "idx_local_id" ON "t_external_mapping" ("local_id");
CREATE INDEX "idx_external_id" ON "t_external_mapping" ("external_id");
CREATE TRIGGER "trg_t_external_mapping_update_time" BEFORE UPDATE ON "t_external_mapping"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_external_sync_log  外部平台同步日志
-- ----------------------------
DROP TABLE IF EXISTS "t_external_sync_log";
CREATE TABLE "t_external_sync_log" (
  "log_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "system_type" smallint NOT NULL,
  "biz_type" smallint NOT NULL,
  "biz_id" bigint NOT NULL,
  "sync_type" smallint NOT NULL,
  "sync_status" smallint NOT NULL DEFAULT 3,
  "fail_reason" varchar(500) NOT NULL DEFAULT '',
  "retry_count" integer NOT NULL DEFAULT 0,
  "sync_time" timestamp,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("log_id")
);
COMMENT ON TABLE "t_external_sync_log" IS '外部平台同步日志';
COMMENT ON COLUMN "t_external_sync_log"."log_id" IS '主键';
COMMENT ON COLUMN "t_external_sync_log"."system_type" IS '平台类型';
COMMENT ON COLUMN "t_external_sync_log"."biz_type" IS '业务单据类型';
COMMENT ON COLUMN "t_external_sync_log"."biz_id" IS '业务单据ID';
COMMENT ON COLUMN "t_external_sync_log"."sync_type" IS '同步方向：1 上报，2 拉取';
COMMENT ON COLUMN "t_external_sync_log"."sync_status" IS '同步状态：1 成功，2 失败，3 待同步';
COMMENT ON COLUMN "t_external_sync_log"."fail_reason" IS '失败原因';
COMMENT ON COLUMN "t_external_sync_log"."retry_count" IS '重试次数';
COMMENT ON COLUMN "t_external_sync_log"."sync_time" IS '同步时间';
COMMENT ON COLUMN "t_external_sync_log"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_external_sync_log"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_external_sync_log"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_external_sync_log"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_external_sync_log"."deleted_flag" IS '逻辑删除：0 否，1 是';
CREATE INDEX "t_external_sync_log_idx_system_biz" ON "t_external_sync_log" ("system_type", "biz_type", "biz_id");
CREATE INDEX "t_external_sync_log_idx_sync_status" ON "t_external_sync_log" ("sync_status");
CREATE TRIGGER "trg_t_external_sync_log_update_time" BEFORE UPDATE ON "t_external_sync_log"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

