-- ==========================================================================
-- XSY-SCM  PostgreSQL 建表脚本 —— 财务（应收 / 应付 / 收付款）
-- 由 MySQL 结构自动转换生成，表数量：2
-- 目标数据库：PostgreSQL 12+
-- ==========================================================================

-- ------------------------------------------------------------------
-- ON UPDATE CURRENT_TIMESTAMP 在 PostgreSQL 中没有等价列属性，
-- 统一用下面这个触发器函数替代（每张有 update_time 的表挂一个 BEFORE UPDATE 触发器）。
-- 如果业务代码里已经显式维护 update_time，可以整段删除。
-- ------------------------------------------------------------------
CREATE OR REPLACE FUNCTION xsy_set_update_time() RETURNS trigger AS $$
BEGIN
  NEW.update_time := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------
-- t_payment  收款单
-- ----------------------------
DROP TABLE IF EXISTS "t_payment";
CREATE TABLE "t_payment" (
  "payment_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "payment_no" varchar(32) NOT NULL,
  "order_id" bigint,
  "receivable_id" bigint,
  "customer_id" bigint,
  "amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "pay_channel" smallint,
  "pay_time" timestamp,
  "proof_image" varchar(255),
  "status" smallint NOT NULL DEFAULT 1,
  "remark" varchar(255),
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("payment_id"),
  CONSTRAINT "uk_payment_no" UNIQUE ("payment_no")
);
COMMENT ON TABLE "t_payment" IS '收款单';
CREATE INDEX "t_payment_idx_customer_id" ON "t_payment" ("customer_id");
CREATE INDEX "idx_receivable_id" ON "t_payment" ("receivable_id");
CREATE INDEX "t_payment_idx_order_id" ON "t_payment" ("order_id");
CREATE INDEX "t_payment_idx_status" ON "t_payment" ("status");
CREATE TRIGGER "trg_t_payment_update_time" BEFORE UPDATE ON "t_payment"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

-- ----------------------------
-- t_receivable  应收单
-- ----------------------------
DROP TABLE IF EXISTS "t_receivable";
CREATE TABLE "t_receivable" (
  "receivable_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "receivable_no" varchar(32) NOT NULL,
  "order_id" bigint NOT NULL,
  "customer_id" bigint,
  "settle_customer_id" bigint,
  "settle_type" smallint,
  "amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "received_amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "balance_amount" numeric(18,2) NOT NULL DEFAULT 0.00,
  "due_time" timestamp,
  "status" smallint NOT NULL DEFAULT 1,
  "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "create_user_id" bigint,
  "create_user_name" varchar(30),
  "deleted_flag" smallint NOT NULL DEFAULT 0,
  PRIMARY KEY ("receivable_id"),
  CONSTRAINT "uk_receivable_no" UNIQUE ("receivable_no")
);
COMMENT ON TABLE "t_receivable" IS '应收单';
COMMENT ON COLUMN "t_receivable"."receivable_id" IS '主键';
COMMENT ON COLUMN "t_receivable"."receivable_no" IS '应收单号';
COMMENT ON COLUMN "t_receivable"."order_id" IS '订单ID';
COMMENT ON COLUMN "t_receivable"."customer_id" IS '下单客户ID';
COMMENT ON COLUMN "t_receivable"."settle_customer_id" IS '结算客户ID';
COMMENT ON COLUMN "t_receivable"."settle_type" IS '结算方式';
COMMENT ON COLUMN "t_receivable"."amount" IS '应收金额';
COMMENT ON COLUMN "t_receivable"."received_amount" IS '已收金额';
COMMENT ON COLUMN "t_receivable"."balance_amount" IS '待收余额';
COMMENT ON COLUMN "t_receivable"."due_time" IS '到期日';
COMMENT ON COLUMN "t_receivable"."status" IS '状态：1 待收款，2 部分收款，3 已结清，4 已冲销';
COMMENT ON COLUMN "t_receivable"."create_time" IS '创建时间';
COMMENT ON COLUMN "t_receivable"."update_time" IS '更新时间';
COMMENT ON COLUMN "t_receivable"."create_user_id" IS '创建人ID';
COMMENT ON COLUMN "t_receivable"."create_user_name" IS '创建人姓名';
COMMENT ON COLUMN "t_receivable"."deleted_flag" IS '逻辑删除';
CREATE INDEX "t_receivable_idx_order_id" ON "t_receivable" ("order_id");
CREATE INDEX "t_receivable_idx_settle_customer_id" ON "t_receivable" ("settle_customer_id");
CREATE INDEX "t_receivable_idx_status" ON "t_receivable" ("status");
CREATE TRIGGER "trg_t_receivable_update_time" BEFORE UPDATE ON "t_receivable"
  FOR EACH ROW EXECUTE FUNCTION xsy_set_update_time();

