package com.xianshuyuan.scm.order.entity;

import com.baomidou.mybatisplus.annotation.*;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

@TableName("order_return")
public class OrderReturnEntity {
 @TableId(type=IdType.AUTO) private Long id; private String returnNo; private Long orderId; private Long customerId; private OrderReturnStatus status; private String reason; private String decisionReason; private BigDecimal approvedAmount; private OffsetDateTime approvedAt; private OffsetDateTime rejectedAt; private OffsetDateTime cancelledAt; @Version private Integer version; @TableLogic private Boolean deleted; private OffsetDateTime createdAt; private OffsetDateTime updatedAt; private String createdBy; private String updatedBy;
 public Long getId(){return id;} public void setId(Long v){id=v;} public String getReturnNo(){return returnNo;} public void setReturnNo(String v){returnNo=v;} public Long getOrderId(){return orderId;} public void setOrderId(Long v){orderId=v;} public Long getCustomerId(){return customerId;} public void setCustomerId(Long v){customerId=v;} public OrderReturnStatus getStatus(){return status;} public void setStatus(OrderReturnStatus v){status=v;} public String getReason(){return reason;} public void setReason(String v){reason=v;} public String getDecisionReason(){return decisionReason;} public void setDecisionReason(String v){decisionReason=v;} public BigDecimal getApprovedAmount(){return approvedAmount;} public void setApprovedAmount(BigDecimal v){approvedAmount=v;} public OffsetDateTime getApprovedAt(){return approvedAt;} public void setApprovedAt(OffsetDateTime v){approvedAt=v;} public OffsetDateTime getRejectedAt(){return rejectedAt;} public void setRejectedAt(OffsetDateTime v){rejectedAt=v;} public OffsetDateTime getCancelledAt(){return cancelledAt;} public void setCancelledAt(OffsetDateTime v){cancelledAt=v;} public Integer getVersion(){return version;} public void setVersion(Integer v){version=v;} public Boolean getDeleted(){return deleted;} public void setDeleted(Boolean v){deleted=v;} public OffsetDateTime getCreatedAt(){return createdAt;} public void setCreatedAt(OffsetDateTime v){createdAt=v;} public OffsetDateTime getUpdatedAt(){return updatedAt;} public void setUpdatedAt(OffsetDateTime v){updatedAt=v;} public String getCreatedBy(){return createdBy;} public void setCreatedBy(String v){createdBy=v;} public String getUpdatedBy(){return updatedBy;} public void setUpdatedBy(String v){updatedBy=v;}
}
