CREATE SEQUENCE purchase_receipt_confirmation_no_seq START WITH 1 INCREMENT BY 1;

ALTER TABLE purchase_receipt DROP CONSTRAINT ck_purchase_receipt_status;
ALTER TABLE purchase_receipt ADD CONSTRAINT ck_purchase_receipt_status
    CHECK (status IN ('DRAFT', 'PARTIALLY_CONFIRMED', 'CONFIRMED'));
ALTER TABLE purchase_receipt DROP CONSTRAINT ck_purchase_receipt_confirmation;
ALTER TABLE purchase_receipt ADD CONSTRAINT ck_purchase_receipt_confirmation CHECK (
    (status = 'DRAFT' AND confirmed_at IS NULL)
    OR (status = 'PARTIALLY_CONFIRMED' AND confirmed_at IS NOT NULL)
    OR (status = 'CONFIRMED' AND confirmed_at IS NOT NULL)
);

CREATE UNIQUE INDEX uk_purchase_receipt_order_active
    ON purchase_receipt (purchase_order_id) WHERE deleted = FALSE;

ALTER TABLE purchase_receipt_item ALTER COLUMN received_quantity SET DEFAULT 0;
ALTER TABLE purchase_receipt_item DROP CONSTRAINT ck_purchase_receipt_item_quantity;
ALTER TABLE purchase_receipt_item ADD CONSTRAINT ck_purchase_receipt_item_quantity
    CHECK (received_quantity >= 0);

CREATE TABLE purchase_receipt_confirmation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    confirmation_no VARCHAR(64) NOT NULL,
    purchase_receipt_id BIGINT NOT NULL,
    idempotency_scope VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    total_quantity NUMERIC(18,4) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'CONFIRMED',
    operator VARCHAR(64) NOT NULL DEFAULT 'SYSTEM',
    confirmed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    result_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    CONSTRAINT ck_purchase_receipt_confirmation_total CHECK (total_quantity > 0),
    CONSTRAINT ck_purchase_receipt_confirmation_status CHECK (status = 'CONFIRMED'),
    CONSTRAINT ck_purchase_receipt_confirmation_result CHECK (
        result_data IS NULL OR jsonb_typeof(result_data) = 'object'
    )
);
CREATE UNIQUE INDEX uk_purchase_receipt_confirmation_key
    ON purchase_receipt_confirmation (idempotency_scope, idempotency_key);
CREATE UNIQUE INDEX uk_purchase_receipt_confirmation_no
    ON purchase_receipt_confirmation (confirmation_no);
CREATE INDEX idx_purchase_receipt_confirmation_receipt
    ON purchase_receipt_confirmation (purchase_receipt_id, confirmed_at DESC);

CREATE TABLE purchase_receipt_confirmation_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    confirmation_id BIGINT NOT NULL,
    purchase_receipt_item_id BIGINT NOT NULL,
    purchase_order_item_id BIGINT NOT NULL,
    planned_quantity NUMERIC(18,4) NOT NULL,
    effective_quantity NUMERIC(18,4) NOT NULL,
    actual_weight NUMERIC(18,4),
    unit VARCHAR(32) NOT NULL,
    weighing_source VARCHAR(20),
    correction_reason VARCHAR(500),
    weighing_record_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    CONSTRAINT ck_purchase_receipt_confirmation_item_planned CHECK (planned_quantity > 0),
    CONSTRAINT ck_purchase_receipt_confirmation_item_effective CHECK (effective_quantity > 0),
    CONSTRAINT ck_purchase_receipt_confirmation_item_weight CHECK (actual_weight IS NULL OR actual_weight > 0),
    CONSTRAINT ck_purchase_receipt_confirmation_item_source CHECK (
        weighing_source IS NULL OR weighing_source = 'MANUAL'
    )
);
CREATE UNIQUE INDEX uk_purchase_receipt_confirmation_item
    ON purchase_receipt_confirmation_item (confirmation_id, purchase_receipt_item_id);
CREATE INDEX idx_purchase_receipt_confirmation_item_receipt_item
    ON purchase_receipt_confirmation_item (purchase_receipt_item_id, confirmation_id);

DROP INDEX uk_inventory_movement_receipt_item;
ALTER TABLE inventory_movement ADD COLUMN confirmation_id BIGINT;
ALTER TABLE inventory_movement ADD CONSTRAINT ck_inventory_movement_confirmation CHECK (
    movement_type <> 'PURCHASE_IN' OR confirmation_id IS NOT NULL
);
CREATE UNIQUE INDEX uk_inventory_movement_receipt_confirmation
    ON inventory_movement (
        source_document_type, source_document_id, source_document_item_id, confirmation_id
    ) WHERE deleted = FALSE AND movement_type = 'PURCHASE_IN';
CREATE INDEX idx_inventory_movement_confirmation
    ON inventory_movement (confirmation_id) WHERE confirmation_id IS NOT NULL;
