CREATE TABLE sys_department
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id      BIGINT,
    code           VARCHAR(64)  NOT NULL,
    name           VARCHAR(100) NOT NULL,
    leader_user_id BIGINT,
    sort_order     INTEGER      NOT NULL DEFAULT 0,
    status         VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    version        INTEGER      NOT NULL DEFAULT 0,
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by     VARCHAR(64),
    updated_by     VARCHAR(64),
    CONSTRAINT ck_sys_department_parent CHECK (parent_id IS NULL OR parent_id <> id),
    CONSTRAINT ck_sys_department_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_sys_department_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_sys_department_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_sys_department_code_active
    ON sys_department (code) WHERE deleted = FALSE;
CREATE INDEX idx_sys_department_parent_active
    ON sys_department (parent_id, sort_order, id) WHERE deleted = FALSE;

ALTER TABLE sys_user
    ADD COLUMN password_hash VARCHAR(100),
    ADD COLUMN password_changed_at TIMESTAMPTZ,
    ADD COLUMN department_id BIGINT,
    ADD COLUMN email VARCHAR(254),
    ADD COLUMN phone VARCHAR(32),
    ADD COLUMN administrator BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN auth_version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN failed_login_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN locked_until TIMESTAMPTZ,
    ADD COLUMN last_login_at TIMESTAMPTZ;

ALTER TABLE sys_user
    ADD CONSTRAINT ck_sys_user_auth_version CHECK (auth_version >= 0),
    ADD CONSTRAINT ck_sys_user_failed_login_count CHECK (failed_login_count >= 0);

CREATE UNIQUE INDEX uk_sys_user_email_active
    ON sys_user (LOWER(email)) WHERE deleted = FALSE AND email IS NOT NULL;
CREATE UNIQUE INDEX uk_sys_user_phone_active
    ON sys_user (phone) WHERE deleted = FALSE AND phone IS NOT NULL;
CREATE INDEX idx_sys_user_department_active
    ON sys_user (department_id, id) WHERE deleted = FALSE;

CREATE TABLE sys_role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(100) NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status      VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    system_role BOOLEAN      NOT NULL DEFAULT FALSE,
    version     INTEGER      NOT NULL DEFAULT 0,
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  VARCHAR(64),
    updated_by  VARCHAR(64),
    CONSTRAINT ck_sys_role_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_sys_role_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_sys_role_code_active
    ON sys_role (code) WHERE deleted = FALSE;

CREATE TABLE sys_permission
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              VARCHAR(160) NOT NULL,
    name              VARCHAR(100) NOT NULL,
    module            VARCHAR(64)  NOT NULL,
    resource_type     VARCHAR(16)  NOT NULL,
    status            VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    system_permission BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order        INTEGER      NOT NULL DEFAULT 0,
    description       VARCHAR(500),
    version           INTEGER      NOT NULL DEFAULT 0,
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by        VARCHAR(64),
    updated_by        VARCHAR(64),
    CONSTRAINT ck_sys_permission_resource_type CHECK (resource_type IN ('PAGE', 'ACTION', 'API')),
    CONSTRAINT ck_sys_permission_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_sys_permission_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_sys_permission_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_sys_permission_code_active
    ON sys_permission (code) WHERE deleted = FALSE;
CREATE INDEX idx_sys_permission_module_active
    ON sys_permission (module, sort_order, id) WHERE deleted = FALSE;

CREATE TABLE sys_menu
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id                BIGINT,
    type                     VARCHAR(16)  NOT NULL,
    name                     VARCHAR(100) NOT NULL,
    path                     VARCHAR(255),
    route_key                VARCHAR(100),
    icon_key                 VARCHAR(64),
    required_permission_code VARCHAR(160),
    sort_order               INTEGER      NOT NULL DEFAULT 0,
    visible                  BOOLEAN      NOT NULL DEFAULT TRUE,
    status                   VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    version                  INTEGER      NOT NULL DEFAULT 0,
    deleted                  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64),
    updated_by               VARCHAR(64),
    CONSTRAINT ck_sys_menu_parent CHECK (parent_id IS NULL OR parent_id <> id),
    CONSTRAINT ck_sys_menu_type CHECK (type IN ('DIRECTORY', 'PAGE')),
    CONSTRAINT ck_sys_menu_page_fields CHECK (
        (type = 'PAGE' AND path IS NOT NULL AND route_key IS NOT NULL)
            OR type = 'DIRECTORY'
        ),
    CONSTRAINT ck_sys_menu_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_sys_menu_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_sys_menu_version CHECK (version >= 0)
);

CREATE INDEX idx_sys_menu_parent_active
    ON sys_menu (parent_id, sort_order, id) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_sys_menu_route_key_active
    ON sys_menu (route_key) WHERE deleted = FALSE AND route_key IS NOT NULL;

CREATE TABLE sys_user_role
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    role_id    BIGINT      NOT NULL,
    deleted    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64)
);

CREATE UNIQUE INDEX uk_sys_user_role_active
    ON sys_user_role (user_id, role_id) WHERE deleted = FALSE;
CREATE INDEX idx_sys_user_role_role_active
    ON sys_user_role (role_id, user_id) WHERE deleted = FALSE;

CREATE TABLE sys_role_permission
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id       BIGINT      NOT NULL,
    permission_id BIGINT      NOT NULL,
    deleted       BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(64)
);

CREATE UNIQUE INDEX uk_sys_role_permission_active
    ON sys_role_permission (role_id, permission_id) WHERE deleted = FALSE;
CREATE INDEX idx_sys_role_permission_permission_active
    ON sys_role_permission (permission_id, role_id) WHERE deleted = FALSE;

CREATE TABLE sys_role_menu
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id    BIGINT      NOT NULL,
    menu_id    BIGINT      NOT NULL,
    deleted    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64)
);

CREATE UNIQUE INDEX uk_sys_role_menu_active
    ON sys_role_menu (role_id, menu_id) WHERE deleted = FALSE;
CREATE INDEX idx_sys_role_menu_menu_active
    ON sys_role_menu (menu_id, role_id) WHERE deleted = FALSE;
