CREATE TABLE sys_login_log
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT,
    username_snapshot   VARCHAR(64) NOT NULL,
    result              VARCHAR(16) NOT NULL,
    failure_reason_code VARCHAR(64),
    ip                  VARCHAR(64),
    user_agent          VARCHAR(500),
    occurred_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_sys_login_log_result CHECK (result IN ('SUCCESS', 'FAILURE', 'LOCKED', 'LOGOUT'))
);

CREATE INDEX idx_sys_login_log_occurred_at
    ON sys_login_log (occurred_at DESC, id DESC);
CREATE INDEX idx_sys_login_log_user
    ON sys_login_log (user_id, occurred_at DESC) WHERE user_id IS NOT NULL;
CREATE INDEX idx_sys_login_log_username
    ON sys_login_log (username_snapshot, occurred_at DESC);

CREATE TABLE sys_operation_log
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id       BIGINT,
    actor_name_snapshot VARCHAR(100) NOT NULL,
    module              VARCHAR(64)  NOT NULL,
    operation_code      VARCHAR(100) NOT NULL,
    target_type         VARCHAR(100) NOT NULL,
    target_id           VARCHAR(100),
    http_method         VARCHAR(16),
    request_path        VARCHAR(500),
    request_id          VARCHAR(100),
    ip                  VARCHAR(64),
    user_agent          VARCHAR(500),
    success             BOOLEAN      NOT NULL,
    error_code          INTEGER,
    before_data         JSONB,
    after_data          JSONB,
    occurred_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sys_operation_log_occurred_at
    ON sys_operation_log (occurred_at DESC, id DESC);
CREATE INDEX idx_sys_operation_log_actor
    ON sys_operation_log (actor_user_id, occurred_at DESC) WHERE actor_user_id IS NOT NULL;
CREATE INDEX idx_sys_operation_log_operation
    ON sys_operation_log (operation_code, occurred_at DESC);
CREATE INDEX idx_sys_operation_log_target
    ON sys_operation_log (target_type, target_id, occurred_at DESC);

CREATE TABLE sys_dictionary
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(100) NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status      VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    version     INTEGER      NOT NULL DEFAULT 0,
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  VARCHAR(64),
    updated_by  VARCHAR(64),
    CONSTRAINT ck_sys_dictionary_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_sys_dictionary_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_sys_dictionary_code_active
    ON sys_dictionary (code) WHERE deleted = FALSE;

CREATE TABLE sys_dictionary_item
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dictionary_id BIGINT       NOT NULL,
    value         VARCHAR(100) NOT NULL,
    label         VARCHAR(100) NOT NULL,
    color         VARCHAR(32),
    style         VARCHAR(100),
    sort_order    INTEGER      NOT NULL DEFAULT 0,
    status        VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    version       INTEGER      NOT NULL DEFAULT 0,
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(64),
    updated_by    VARCHAR(64),
    CONSTRAINT ck_sys_dictionary_item_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_sys_dictionary_item_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_sys_dictionary_item_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_sys_dictionary_item_value_active
    ON sys_dictionary_item (dictionary_id, value) WHERE deleted = FALSE;
CREATE INDEX idx_sys_dictionary_item_dictionary_active
    ON sys_dictionary_item (dictionary_id, sort_order, id) WHERE deleted = FALSE;
