-- P1 purchase demand provenance, independent receipts, and configurable tolerance.
-- This migration is additive and does not rewrite historical receipt confirmations.

CREATE TABLE sys_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(150) NOT NULL,
    config_value VARCHAR(500) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_sys_config_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_sys_config_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_sys_config_key_active ON sys_config (config_key) WHERE deleted = FALSE;
INSERT INTO sys_config (config_key, config_value, description)
VALUES ('purchase.over_receipt_tolerance_percent', '10', '采购收货超收容差百分比')
ON CONFLICT DO NOTHING;

ALTER TABLE purchase_demand
    ADD COLUMN generation_batch_id BIGINT,
    ADD COLUMN target_warehouse_id BIGINT,
    ADD COLUMN source_confirmed_at TIMESTAMPTZ,
    ADD COLUMN calculate_inventory BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN original_required_quantity NUMERIC(18,4) NOT NULL DEFAULT 0,
    ADD COLUMN inventory_deducted_quantity NUMERIC(18,4) NOT NULL DEFAULT 0;
ALTER TABLE purchase_demand
    ADD CONSTRAINT ck_purchase_demand_original_quantity CHECK (original_required_quantity >= 0),
    ADD CONSTRAINT ck_purchase_demand_inventory_deducted CHECK (inventory_deducted_quantity >= 0),
    ADD CONSTRAINT ck_purchase_demand_generation_warehouse CHECK (target_warehouse_id IS NULL OR target_warehouse_id > 0);
CREATE INDEX idx_purchase_demand_generation_batch ON purchase_demand (generation_batch_id) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_demand_source_confirmed_at ON purchase_demand (source_confirmed_at) WHERE deleted = FALSE;

CREATE TABLE purchase_demand_generation_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_scope VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    warehouse_id BIGINT NOT NULL,
    calculate_inventory BOOLEAN NOT NULL DEFAULT TRUE,
    source_line_count INTEGER NOT NULL DEFAULT 0,
    created_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    original_quantity NUMERIC(18,4) NOT NULL DEFAULT 0,
    deducted_quantity NUMERIC(18,4) NOT NULL DEFAULT 0,
    result_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    CONSTRAINT ck_purchase_demand_batch_window CHECK (start_at < end_at),
    CONSTRAINT ck_purchase_demand_batch_counts CHECK (source_line_count >= 0 AND created_count >= 0 AND skipped_count >= 0),
    CONSTRAINT ck_purchase_demand_batch_quantities CHECK (original_quantity >= 0 AND deducted_quantity >= 0),
    CONSTRAINT ck_purchase_demand_batch_result CHECK (result_data IS NULL OR jsonb_typeof(result_data) = 'object')
);
CREATE UNIQUE INDEX uk_purchase_demand_batch_idempotency ON purchase_demand_generation_batch (idempotency_scope, idempotency_key);
CREATE INDEX idx_purchase_demand_batch_window ON purchase_demand_generation_batch (warehouse_id, start_at, end_at);

ALTER TABLE purchase_order
    DROP CONSTRAINT ck_purchase_order_status,
    ADD CONSTRAINT ck_purchase_order_status CHECK (status IN ('DRAFT', 'SUBMITTED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'SHORT_CLOSED', 'CANCELLED'));
ALTER TABLE purchase_order ADD COLUMN short_closed_at TIMESTAMPTZ, ADD COLUMN short_close_reason VARCHAR(500);
ALTER TABLE purchase_order ADD CONSTRAINT ck_purchase_order_short_close_reason CHECK
    (status <> 'SHORT_CLOSED' OR (short_closed_at IS NOT NULL AND short_close_reason IS NOT NULL AND btrim(short_close_reason) <> ''));

DROP INDEX uk_purchase_receipt_order_active;
ALTER TABLE purchase_receipt
    ADD COLUMN receipt_mode VARCHAR(16),
    ADD COLUMN putaway_status VARCHAR(24) NOT NULL DEFAULT 'NOT_APPLICABLE',
    ADD COLUMN putaway_at TIMESTAMPTZ,
    ADD COLUMN putaway_operator VARCHAR(64),
    ADD COLUMN reason VARCHAR(500);
ALTER TABLE purchase_receipt ADD CONSTRAINT ck_purchase_receipt_mode CHECK (receipt_mode IS NULL OR receipt_mode IN ('DIRECT', 'DEFERRED'));
ALTER TABLE purchase_receipt ADD CONSTRAINT ck_purchase_receipt_putaway_status CHECK (putaway_status IN ('NOT_APPLICABLE', 'PENDING_PUTAWAY', 'PUTAWAY_COMPLETED'));
CREATE INDEX idx_purchase_receipt_order_created ON purchase_receipt (purchase_order_id, created_at DESC) WHERE deleted = FALSE;

ALTER TABLE purchase_receipt_item
    ADD COLUMN planned_quantity NUMERIC(18,4),
    ADD COLUMN cumulative_received_quantity NUMERIC(18,4) NOT NULL DEFAULT 0,
    ADD COLUMN remaining_quantity NUMERIC(18,4) NOT NULL DEFAULT 0,
    ADD COLUMN over_receipt_quantity NUMERIC(18,4) NOT NULL DEFAULT 0,
    ADD COLUMN receipt_difference NUMERIC(18,4) NOT NULL DEFAULT 0;
ALTER TABLE purchase_receipt_item
    ADD CONSTRAINT ck_purchase_receipt_item_p1_quantities CHECK
    (planned_quantity IS NULL OR planned_quantity > 0) AND cumulative_received_quantity >= 0 AND remaining_quantity >= 0 AND over_receipt_quantity >= 0;

ALTER TABLE inventory_movement ADD COLUMN receipt_id BIGINT;
CREATE INDEX idx_inventory_movement_receipt_id ON inventory_movement (receipt_id) WHERE receipt_id IS NOT NULL;
INSERT INTO sys_permission(code, name, module, resource_type, system_permission, sort_order)
VALUES ('purchase:receipt:putaway', '采购收货二次入库', 'purchase', 'API', TRUE, 120)
ON CONFLICT DO NOTHING;
INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id FROM sys_role r CROSS JOIN sys_permission p
WHERE (r.system_role = TRUE OR r.code IN ('ADMIN', 'SUPER_ADMIN')) AND p.code = 'purchase:receipt:putaway'
ON CONFLICT DO NOTHING;
