-- 商城订单来源与收货地址快照。不修改已应用迁移，不创建外键。

ALTER TABLE sales_order
    DROP CONSTRAINT ck_sales_order_source;
ALTER TABLE sales_order
    ADD CONSTRAINT ck_sales_order_source CHECK (order_source IN ('NORMAL', 'SUPPLEMENT', 'MALL'));

CREATE TABLE mall_order_address
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT       NOT NULL,
    customer_id    BIGINT       NOT NULL,
    receiver_name  VARCHAR(100) NOT NULL,
    phone          VARCHAR(32)  NOT NULL,
    region         VARCHAR(200) NOT NULL,
    detail_address VARCHAR(300) NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by     VARCHAR(64)
);

CREATE UNIQUE INDEX uk_mall_order_address_order
    ON mall_order_address (order_id);
CREATE INDEX idx_mall_order_address_customer
    ON mall_order_address (customer_id, created_at DESC);
