-- 营销管理基础表：促销活动、首页板块、优惠券模板、客户优惠券、客户常用菜品。
-- 不创建数据库外键，仅保留检查约束、部分唯一索引与关系列索引。

CREATE TABLE marketing_promotion
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(120) NOT NULL,
    type             VARCHAR(16)  NOT NULL,
    scope_type       VARCHAR(16)  NOT NULL DEFAULT 'ALL',
    scope_ids        JSONB,
    threshold_amount NUMERIC(18, 4),
    discount_rate    NUMERIC(9, 4),
    reduce_amount    NUMERIC(18, 4),
    promo_price      NUMERIC(18, 4),
    gift_sku_id      BIGINT,
    gift_quantity    NUMERIC(18, 4),
    limit_quantity   NUMERIC(18, 4),
    start_at         TIMESTAMPTZ,
    end_at           TIMESTAMPTZ,
    status           VARCHAR(16)  NOT NULL DEFAULT 'DRAFT',
    priority         INTEGER      NOT NULL DEFAULT 0,
    description      VARCHAR(500),
    version          INTEGER      NOT NULL DEFAULT 0,
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(64),
    updated_by       VARCHAR(64),
    CONSTRAINT ck_marketing_promotion_type CHECK (type IN ('FLASH_SALE', 'FULL_REDUCE', 'FULL_GIFT', 'TIME_LIMIT')),
    CONSTRAINT ck_marketing_promotion_scope CHECK (scope_type IN ('ALL', 'CUSTOMER', 'CATEGORY', 'SKU')),
    CONSTRAINT ck_marketing_promotion_status CHECK (status IN ('DRAFT', 'ENABLED', 'DISABLED', 'EXPIRED')),
    CONSTRAINT ck_marketing_promotion_time CHECK (end_at IS NULL OR start_at IS NULL OR end_at >= start_at),
    CONSTRAINT ck_marketing_promotion_amount CHECK (threshold_amount IS NULL OR threshold_amount >= 0),
    CONSTRAINT ck_marketing_promotion_reduce CHECK (reduce_amount IS NULL OR reduce_amount >= 0),
    CONSTRAINT ck_marketing_promotion_price CHECK (promo_price IS NULL OR promo_price >= 0),
    CONSTRAINT ck_marketing_promotion_rate CHECK (discount_rate IS NULL OR (discount_rate > 0 AND discount_rate <= 10)),
    CONSTRAINT ck_marketing_promotion_version CHECK (version >= 0)
);

CREATE INDEX idx_marketing_promotion_type_active
    ON marketing_promotion (type, status) WHERE deleted = FALSE;
CREATE INDEX idx_marketing_promotion_time_active
    ON marketing_promotion (start_at, end_at) WHERE deleted = FALSE;

CREATE TABLE marketing_home_section
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_type VARCHAR(16)  NOT NULL,
    title        VARCHAR(120),
    promotion_id BIGINT,
    category_id  BIGINT,
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    status       VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    start_at     TIMESTAMPTZ,
    end_at       TIMESTAMPTZ,
    payload      JSONB,
    version      INTEGER      NOT NULL DEFAULT 0,
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by   VARCHAR(64),
    updated_by   VARCHAR(64),
    CONSTRAINT ck_marketing_home_section_type CHECK (section_type IN
        ('BANNER', 'FLASH_SALE', 'NEW_ARRIVAL', 'CATEGORY', 'RECOMMEND', 'CUSTOM')),
    CONSTRAINT ck_marketing_home_section_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_marketing_home_section_version CHECK (version >= 0)
);

CREATE INDEX idx_marketing_home_section_active
    ON marketing_home_section (sort_order, id) WHERE deleted = FALSE;

CREATE TABLE marketing_coupon
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(120) NOT NULL,
    coupon_type      VARCHAR(16)  NOT NULL,
    threshold_amount NUMERIC(18, 4),
    discount_rate    NUMERIC(9, 4),
    reduce_amount    NUMERIC(18, 4),
    total_quantity   INTEGER      NOT NULL DEFAULT 0,
    issued_quantity  INTEGER      NOT NULL DEFAULT 0,
    per_limit        INTEGER      NOT NULL DEFAULT 1,
    valid_from       TIMESTAMPTZ,
    valid_to         TIMESTAMPTZ,
    status           VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    version          INTEGER      NOT NULL DEFAULT 0,
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(64),
    updated_by       VARCHAR(64),
    CONSTRAINT ck_marketing_coupon_type CHECK (coupon_type IN ('FULL_REDUCE', 'DISCOUNT')),
    CONSTRAINT ck_marketing_coupon_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_marketing_coupon_quantity CHECK (total_quantity >= 0 AND issued_quantity >= 0 AND issued_quantity <= total_quantity),
    CONSTRAINT ck_marketing_coupon_per_limit CHECK (per_limit >= 1),
    CONSTRAINT ck_marketing_coupon_time CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from),
    CONSTRAINT ck_marketing_coupon_rate CHECK (discount_rate IS NULL OR (discount_rate > 0 AND discount_rate <= 10)),
    CONSTRAINT ck_marketing_coupon_reduce CHECK (reduce_amount IS NULL OR reduce_amount >= 0),
    CONSTRAINT ck_marketing_coupon_version CHECK (version >= 0)
);

CREATE INDEX idx_marketing_coupon_status_active
    ON marketing_coupon (status, created_at DESC) WHERE deleted = FALSE;

CREATE TABLE marketing_customer_coupon
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id    BIGINT       NOT NULL,
    customer_id  BIGINT       NOT NULL,
    coupon_no    VARCHAR(32)  NOT NULL,
    status       VARCHAR(16)  NOT NULL DEFAULT 'UNUSED',
    used_order_id BIGINT,
    used_at      TIMESTAMPTZ,
    obtained_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_from   TIMESTAMPTZ,
    valid_to     TIMESTAMPTZ,
    version      INTEGER      NOT NULL DEFAULT 0,
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by   VARCHAR(64),
    updated_by   VARCHAR(64),
    CONSTRAINT ck_marketing_customer_coupon_status CHECK (status IN ('UNUSED', 'USED', 'EXPIRED')),
    CONSTRAINT ck_marketing_customer_coupon_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_marketing_customer_coupon_no_active
    ON marketing_customer_coupon (coupon_no) WHERE deleted = FALSE;
CREATE INDEX idx_marketing_customer_coupon_customer_status
    ON marketing_customer_coupon (customer_id, status) WHERE deleted = FALSE;
CREATE INDEX idx_marketing_customer_coupon_coupon
    ON marketing_customer_coupon (coupon_id) WHERE deleted = FALSE;

CREATE TABLE marketing_frequent_sku
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    BIGINT       NOT NULL,
    sku_id         BIGINT       NOT NULL,
    buy_count      INTEGER      NOT NULL DEFAULT 0,
    last_order_id  BIGINT,
    last_ordered_at TIMESTAMPTZ,
    version        INTEGER      NOT NULL DEFAULT 0,
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by     VARCHAR(64),
    updated_by     VARCHAR(64),
    CONSTRAINT ck_marketing_frequent_sku_count CHECK (buy_count >= 0),
    CONSTRAINT ck_marketing_frequent_sku_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_marketing_frequent_sku_customer_sku
    ON marketing_frequent_sku (customer_id, sku_id) WHERE deleted = FALSE;
CREATE INDEX idx_marketing_frequent_sku_customer
    ON marketing_frequent_sku (customer_id, buy_count DESC) WHERE deleted = FALSE;
