CREATE SEQUENCE sales_order_no_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE order_return_no_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE order_refund_no_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE sales_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    customer_id BIGINT NOT NULL,
    customer_code_snapshot VARCHAR(64) NOT NULL,
    customer_name_snapshot VARCHAR(150) NOT NULL,
    order_source VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    original_order_id BIGINT,
    supplement_reason VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    ordered_total_amount NUMERIC(18,4) NOT NULL DEFAULT 0,
    settlement_total_amount NUMERIC(18,4),
    cancel_reason VARCHAR(500),
    submitted_at TIMESTAMPTZ,
    confirmed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_sales_order_source CHECK (order_source IN ('NORMAL', 'SUPPLEMENT')),
    CONSTRAINT ck_sales_order_supplement CHECK (
        (order_source = 'NORMAL' AND original_order_id IS NULL AND supplement_reason IS NULL)
        OR (order_source = 'SUPPLEMENT' AND supplement_reason IS NOT NULL AND btrim(supplement_reason) <> '')
    ),
    CONSTRAINT ck_sales_order_status CHECK (status IN ('DRAFT', 'PENDING', 'CONFIRMED', 'CANCELLED')),
    CONSTRAINT ck_sales_order_ordered_total_amount CHECK (ordered_total_amount >= 0),
    CONSTRAINT ck_sales_order_settlement_total_amount CHECK (
        settlement_total_amount IS NULL OR settlement_total_amount >= 0
    ),
    CONSTRAINT ck_sales_order_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_sales_order_no_active
    ON sales_order (order_no) WHERE deleted = FALSE;
CREATE INDEX idx_sales_order_customer_created
    ON sales_order (customer_id, created_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_sales_order_status_created
    ON sales_order (status, created_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_sales_order_original_order_id
    ON sales_order (original_order_id) WHERE original_order_id IS NOT NULL;

CREATE TABLE sales_order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    spu_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    spu_code_snapshot VARCHAR(64) NOT NULL,
    product_name_snapshot VARCHAR(150) NOT NULL,
    sku_code_snapshot VARCHAR(64) NOT NULL,
    spec_name_snapshot VARCHAR(150) NOT NULL,
    spec_values_snapshot JSONB NOT NULL DEFAULT '{}'::JSONB,
    sale_unit_snapshot VARCHAR(32) NOT NULL,
    product_type_snapshot VARCHAR(20) NOT NULL,
    ordered_quantity NUMERIC(18,4) NOT NULL,
    actual_quantity NUMERIC(18,4),
    actual_quantity_source VARCHAR(20),
    actual_quantity_reason VARCHAR(500),
    draft_unit_price NUMERIC(18,4) NOT NULL,
    draft_price_source VARCHAR(20) NOT NULL,
    draft_price_source_id BIGINT,
    manual_price_override BOOLEAN NOT NULL DEFAULT FALSE,
    manual_price_reason VARCHAR(500),
    locked_unit_price NUMERIC(18,4),
    locked_price_source VARCHAR(20),
    locked_price_source_id BIGINT,
    ordered_line_amount NUMERIC(18,4) NOT NULL DEFAULT 0,
    settlement_line_amount NUMERIC(18,4),
    sort_order INTEGER NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_sales_order_item_spec_values CHECK (jsonb_typeof(spec_values_snapshot) = 'object'),
    CONSTRAINT ck_sales_order_item_product_type CHECK (product_type_snapshot IN ('STANDARD', 'NON_STANDARD')),
    CONSTRAINT ck_sales_order_item_ordered_quantity CHECK (ordered_quantity > 0),
    CONSTRAINT ck_sales_order_item_actual_quantity CHECK (actual_quantity IS NULL OR actual_quantity > 0),
    CONSTRAINT ck_sales_order_item_actual_source CHECK (
        actual_quantity_source IS NULL OR actual_quantity_source IN ('SYSTEM', 'MANUAL')
    ),
    CONSTRAINT ck_sales_order_item_draft_price CHECK (draft_unit_price >= 0),
    CONSTRAINT ck_sales_order_item_draft_source CHECK (draft_price_source IN ('MARKET', 'AGREEMENT', 'OVERRIDE')),
    CONSTRAINT ck_sales_order_item_manual_price CHECK (
        (manual_price_override = FALSE AND draft_price_source <> 'OVERRIDE' AND manual_price_reason IS NULL)
        OR (manual_price_override = TRUE AND draft_price_source = 'OVERRIDE' AND manual_price_reason IS NOT NULL AND btrim(manual_price_reason) <> '')
    ),
    CONSTRAINT ck_sales_order_item_locked_price CHECK (locked_unit_price IS NULL OR locked_unit_price >= 0),
    CONSTRAINT ck_sales_order_item_locked_source CHECK (
        locked_price_source IS NULL OR locked_price_source IN ('MARKET', 'AGREEMENT', 'OVERRIDE')
    ),
    CONSTRAINT ck_sales_order_item_ordered_line_amount CHECK (ordered_line_amount >= 0),
    CONSTRAINT ck_sales_order_item_settlement_line_amount CHECK (
        settlement_line_amount IS NULL OR settlement_line_amount >= 0
    ),
    CONSTRAINT ck_sales_order_item_version CHECK (version >= 0)
);

CREATE INDEX idx_sales_order_item_order_id
    ON sales_order_item (order_id, sort_order) WHERE deleted = FALSE;
CREATE INDEX idx_sales_order_item_sku_id
    ON sales_order_item (sku_id) WHERE deleted = FALSE;

CREATE TABLE order_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    operation_type VARCHAR(40) NOT NULL,
    operator VARCHAR(64) NOT NULL DEFAULT 'SYSTEM',
    reason VARCHAR(500),
    before_data JSONB,
    after_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    CONSTRAINT ck_order_operation_log_before_data CHECK (
        before_data IS NULL OR jsonb_typeof(before_data) = 'object'
    ),
    CONSTRAINT ck_order_operation_log_after_data CHECK (
        after_data IS NULL OR jsonb_typeof(after_data) = 'object'
    )
);

CREATE INDEX idx_order_operation_log_order_created
    ON order_operation_log (order_id, created_at DESC);

CREATE TABLE idempotency_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_scope VARCHAR(100) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_hash VARCHAR(128) NOT NULL,
    result_type VARCHAR(100),
    result_id BIGINT,
    result_data JSONB,
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_idempotency_record_result_data CHECK (
        result_data IS NULL OR jsonb_typeof(result_data) = 'object'
    ),
    CONSTRAINT ck_idempotency_record_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_idempotency_record_scope_key_active
    ON idempotency_record (operation_scope, idempotency_key) WHERE deleted = FALSE;
