CREATE TABLE order_return
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_no       VARCHAR(64)    NOT NULL,
    order_id        BIGINT         NOT NULL,
    customer_id     BIGINT         NOT NULL,
    status          VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    reason          VARCHAR(500)   NOT NULL,
    decision_reason VARCHAR(500),
    approved_amount NUMERIC(18, 4) NOT NULL DEFAULT 0,
    approved_at     TIMESTAMPTZ,
    rejected_at     TIMESTAMPTZ,
    cancelled_at    TIMESTAMPTZ,
    version         INTEGER        NOT NULL DEFAULT 0,
    deleted         BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(64),
    updated_by      VARCHAR(64),
    CONSTRAINT ck_order_return_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT ck_order_return_reason CHECK (btrim(reason) <> ''),
    CONSTRAINT ck_order_return_decision_reason CHECK (
        status NOT IN ('REJECTED', 'CANCELLED')
            OR (decision_reason IS NOT NULL AND btrim(decision_reason) <> '')
        ),
    CONSTRAINT ck_order_return_approved_amount CHECK (approved_amount >= 0),
    CONSTRAINT ck_order_return_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_order_return_no_active
    ON order_return (return_no) WHERE deleted = FALSE;
CREATE INDEX idx_order_return_order_id
    ON order_return (order_id, created_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_order_return_status_created
    ON order_return (status, created_at DESC) WHERE deleted = FALSE;

CREATE TABLE order_return_item
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id          BIGINT         NOT NULL,
    order_item_id      BIGINT         NOT NULL,
    requested_quantity NUMERIC(18, 4) NOT NULL,
    approved_quantity  NUMERIC(18, 4),
    locked_unit_price  NUMERIC(18, 4) NOT NULL,
    approved_amount    NUMERIC(18, 4) NOT NULL DEFAULT 0,
    version            INTEGER        NOT NULL DEFAULT 0,
    deleted            BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(64),
    updated_by         VARCHAR(64),
    CONSTRAINT ck_order_return_item_requested_quantity CHECK (requested_quantity > 0),
    CONSTRAINT ck_order_return_item_approved_quantity CHECK (
        approved_quantity IS NULL OR (approved_quantity >= 0 AND approved_quantity <= requested_quantity)
        ),
    CONSTRAINT ck_order_return_item_locked_price CHECK (locked_unit_price >= 0),
    CONSTRAINT ck_order_return_item_approved_amount CHECK (approved_amount >= 0),
    CONSTRAINT ck_order_return_item_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_order_return_item_active
    ON order_return_item (return_id, order_item_id) WHERE deleted = FALSE;
CREATE INDEX idx_order_return_item_return_id
    ON order_return_item (return_id) WHERE deleted = FALSE;
CREATE INDEX idx_order_return_item_order_item_id
    ON order_return_item (order_item_id) WHERE deleted = FALSE;

CREATE TABLE order_refund
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_no          VARCHAR(64)    NOT NULL,
    return_id          BIGINT         NOT NULL,
    order_id           BIGINT         NOT NULL,
    customer_id        BIGINT         NOT NULL,
    refund_amount      NUMERIC(18, 4) NOT NULL,
    status             VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    external_reference VARCHAR(128),
    completed_at       TIMESTAMPTZ,
    version            INTEGER        NOT NULL DEFAULT 0,
    deleted            BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(64),
    updated_by         VARCHAR(64),
    CONSTRAINT ck_order_refund_amount CHECK (refund_amount > 0),
    CONSTRAINT ck_order_refund_status CHECK (status IN ('PENDING', 'COMPLETED')),
    CONSTRAINT ck_order_refund_completion CHECK (
        (status = 'PENDING' AND completed_at IS NULL)
            OR (status = 'COMPLETED' AND completed_at IS NOT NULL)
        ),
    CONSTRAINT ck_order_refund_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_order_refund_no_active
    ON order_refund (refund_no) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_order_refund_return_active
    ON order_refund (return_id) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_order_refund_external_reference_active
    ON order_refund (external_reference) WHERE deleted = FALSE AND external_reference IS NOT NULL;
CREATE INDEX idx_order_refund_order_id
    ON order_refund (order_id, created_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_order_refund_status_created
    ON order_refund (status, created_at DESC) WHERE deleted = FALSE;
