ALTER TABLE supplier ADD COLUMN remark VARCHAR(500);
ALTER TABLE warehouse ADD COLUMN address VARCHAR(500);
ALTER TABLE warehouse ADD COLUMN remark VARCHAR(500);

CREATE SEQUENCE purchase_order_no_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE purchase_receipt_no_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE inventory_movement_no_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE supplier_sku (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    supplier_code_snapshot VARCHAR(64) NOT NULL,
    supplier_name_snapshot VARCHAR(150) NOT NULL,
    sku_code_snapshot VARCHAR(64) NOT NULL,
    sku_name_snapshot VARCHAR(150) NOT NULL,
    spec_values_snapshot JSONB NOT NULL DEFAULT '{}'::JSONB,
    purchase_unit VARCHAR(32) NOT NULL,
    reference_price NUMERIC(18,4),
    purchaser_id BIGINT,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_supplier_sku_spec_values CHECK (jsonb_typeof(spec_values_snapshot) = 'object'),
    CONSTRAINT ck_supplier_sku_reference_price CHECK (reference_price IS NULL OR reference_price >= 0),
    CONSTRAINT ck_supplier_sku_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_supplier_sku_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_supplier_sku_active
    ON supplier_sku (supplier_id, sku_id) WHERE deleted = FALSE;
CREATE INDEX idx_supplier_sku_sku_id
    ON supplier_sku (sku_id) WHERE deleted = FALSE;
CREATE INDEX idx_supplier_sku_purchaser_id
    ON supplier_sku (purchaser_id) WHERE deleted = FALSE AND purchaser_id IS NOT NULL;

CREATE TABLE purchase_demand (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id BIGINT NOT NULL,
    sales_order_item_id BIGINT NOT NULL,
    spu_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    sales_order_no_snapshot VARCHAR(64) NOT NULL,
    spu_code_snapshot VARCHAR(64) NOT NULL,
    product_name_snapshot VARCHAR(150) NOT NULL,
    sku_code_snapshot VARCHAR(64) NOT NULL,
    sku_name_snapshot VARCHAR(150) NOT NULL,
    spec_values_snapshot JSONB NOT NULL DEFAULT '{}'::JSONB,
    purchase_unit_snapshot VARCHAR(32) NOT NULL,
    product_type_snapshot VARCHAR(20) NOT NULL,
    required_quantity NUMERIC(18,4) NOT NULL,
    allocated_quantity NUMERIC(18,4) NOT NULL DEFAULT 0,
    fulfilled_quantity NUMERIC(18,4) NOT NULL DEFAULT 0,
    supplier_id BIGINT,
    purchaser_id BIGINT,
    warehouse_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    demand_date DATE NOT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_purchase_demand_spec_values CHECK (jsonb_typeof(spec_values_snapshot) = 'object'),
    CONSTRAINT ck_purchase_demand_product_type CHECK (product_type_snapshot IN ('STANDARD', 'NON_STANDARD')),
    CONSTRAINT ck_purchase_demand_required_quantity CHECK (required_quantity > 0),
    CONSTRAINT ck_purchase_demand_allocated_quantity CHECK (
        allocated_quantity >= 0 AND allocated_quantity <= required_quantity
    ),
    CONSTRAINT ck_purchase_demand_fulfilled_quantity CHECK (
        fulfilled_quantity >= 0 AND fulfilled_quantity <= required_quantity
    ),
    CONSTRAINT ck_purchase_demand_status CHECK (status IN ('PENDING', 'PARTIALLY_ALLOCATED', 'ALLOCATED', 'FULFILLED', 'CANCELLED')),
    CONSTRAINT ck_purchase_demand_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_purchase_demand_source_active
    ON purchase_demand (sales_order_item_id) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_demand_sales_order_id
    ON purchase_demand (sales_order_id) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_demand_sku_status
    ON purchase_demand (sku_id, status) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_demand_assignment
    ON purchase_demand (supplier_id, purchaser_id, warehouse_id) WHERE deleted = FALSE;

CREATE TABLE purchase_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    supplier_id BIGINT NOT NULL,
    supplier_code_snapshot VARCHAR(64) NOT NULL,
    supplier_name_snapshot VARCHAR(150) NOT NULL,
    purchaser_id BIGINT,
    warehouse_id BIGINT NOT NULL,
    warehouse_code_snapshot VARCHAR(64) NOT NULL,
    warehouse_name_snapshot VARCHAR(150) NOT NULL,
    planned_arrival_date DATE,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    total_amount NUMERIC(18,4) NOT NULL DEFAULT 0,
    remark VARCHAR(500),
    cancel_reason VARCHAR(500),
    submitted_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_purchase_order_status CHECK (status IN ('DRAFT', 'SUBMITTED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED')),
    CONSTRAINT ck_purchase_order_total_amount CHECK (total_amount >= 0),
    CONSTRAINT ck_purchase_order_cancel_reason CHECK (
        status <> 'CANCELLED' OR (cancel_reason IS NOT NULL AND btrim(cancel_reason) <> '')
    ),
    CONSTRAINT ck_purchase_order_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_purchase_order_no_active
    ON purchase_order (order_no) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_order_status_supplier_warehouse
    ON purchase_order (status, supplier_id, warehouse_id) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_order_purchaser_created
    ON purchase_order (purchaser_id, created_at DESC) WHERE deleted = FALSE AND purchaser_id IS NOT NULL;

CREATE TABLE purchase_order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    spu_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    spu_code_snapshot VARCHAR(64) NOT NULL,
    product_name_snapshot VARCHAR(150) NOT NULL,
    sku_code_snapshot VARCHAR(64) NOT NULL,
    sku_name_snapshot VARCHAR(150) NOT NULL,
    spec_values_snapshot JSONB NOT NULL DEFAULT '{}'::JSONB,
    purchase_unit_snapshot VARCHAR(32) NOT NULL,
    product_type_snapshot VARCHAR(20) NOT NULL,
    planned_quantity NUMERIC(18,4) NOT NULL,
    received_quantity NUMERIC(18,4) NOT NULL DEFAULT 0,
    purchase_price NUMERIC(18,4) NOT NULL,
    line_amount NUMERIC(18,4) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_purchase_order_item_spec_values CHECK (jsonb_typeof(spec_values_snapshot) = 'object'),
    CONSTRAINT ck_purchase_order_item_product_type CHECK (product_type_snapshot IN ('STANDARD', 'NON_STANDARD')),
    CONSTRAINT ck_purchase_order_item_planned_quantity CHECK (planned_quantity > 0),
    CONSTRAINT ck_purchase_order_item_received_quantity CHECK (received_quantity >= 0),
    CONSTRAINT ck_purchase_order_item_purchase_price CHECK (purchase_price >= 0),
    CONSTRAINT ck_purchase_order_item_line_amount CHECK (line_amount >= 0),
    CONSTRAINT ck_purchase_order_item_version CHECK (version >= 0)
);

CREATE INDEX idx_purchase_order_item_order_id
    ON purchase_order_item (purchase_order_id, sort_order) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_order_item_sku_id
    ON purchase_order_item (sku_id) WHERE deleted = FALSE;

CREATE TABLE purchase_demand_allocation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_demand_id BIGINT NOT NULL,
    purchase_order_item_id BIGINT NOT NULL,
    sales_order_id BIGINT NOT NULL,
    sales_order_item_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    allocated_quantity NUMERIC(18,4) NOT NULL,
    demand_snapshot JSONB NOT NULL DEFAULT '{}'::JSONB,
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_purchase_demand_allocation_quantity CHECK (allocated_quantity > 0),
    CONSTRAINT ck_purchase_demand_allocation_snapshot CHECK (jsonb_typeof(demand_snapshot) = 'object'),
    CONSTRAINT ck_purchase_demand_allocation_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_purchase_demand_allocation_source_active
    ON purchase_demand_allocation (purchase_order_item_id, purchase_demand_id)
    WHERE deleted = FALSE;
CREATE INDEX idx_purchase_demand_allocation_demand_id
    ON purchase_demand_allocation (purchase_demand_id) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_demand_allocation_sales_order_item_id
    ON purchase_demand_allocation (sales_order_item_id) WHERE deleted = FALSE;

CREATE TABLE purchase_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    purchase_receipt_id BIGINT,
    operation_type VARCHAR(40) NOT NULL,
    operator VARCHAR(64) NOT NULL DEFAULT 'SYSTEM',
    reason VARCHAR(500),
    before_data JSONB,
    after_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    CONSTRAINT ck_purchase_operation_log_before_data CHECK (
        before_data IS NULL OR jsonb_typeof(before_data) = 'object'
    ),
    CONSTRAINT ck_purchase_operation_log_after_data CHECK (
        after_data IS NULL OR jsonb_typeof(after_data) = 'object'
    )
);

CREATE INDEX idx_purchase_operation_log_order_created
    ON purchase_operation_log (purchase_order_id, created_at DESC);
CREATE INDEX idx_purchase_operation_log_receipt_created
    ON purchase_operation_log (purchase_receipt_id, created_at DESC)
    WHERE purchase_receipt_id IS NOT NULL;

CREATE TABLE purchase_receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no VARCHAR(64) NOT NULL,
    purchase_order_id BIGINT NOT NULL,
    purchase_order_no_snapshot VARCHAR(64) NOT NULL,
    warehouse_id BIGINT NOT NULL,
    warehouse_code_snapshot VARCHAR(64) NOT NULL,
    warehouse_name_snapshot VARCHAR(150) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    received_at TIMESTAMPTZ,
    confirmed_at TIMESTAMPTZ,
    operator VARCHAR(64),
    remark VARCHAR(500),
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_purchase_receipt_status CHECK (status IN ('DRAFT', 'CONFIRMED')),
    CONSTRAINT ck_purchase_receipt_confirmation CHECK (
        (status = 'DRAFT' AND confirmed_at IS NULL)
        OR (status = 'CONFIRMED' AND confirmed_at IS NOT NULL AND operator IS NOT NULL AND btrim(operator) <> '')
    ),
    CONSTRAINT ck_purchase_receipt_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_purchase_receipt_no_active
    ON purchase_receipt (receipt_no) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_receipt_order_status
    ON purchase_receipt (purchase_order_id, status) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_receipt_warehouse_received
    ON purchase_receipt (warehouse_id, received_at DESC) WHERE deleted = FALSE;

CREATE TABLE purchase_receipt_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_receipt_id BIGINT NOT NULL,
    purchase_order_item_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    spu_code_snapshot VARCHAR(64) NOT NULL,
    product_name_snapshot VARCHAR(150) NOT NULL,
    sku_code_snapshot VARCHAR(64) NOT NULL,
    sku_name_snapshot VARCHAR(150) NOT NULL,
    spec_values_snapshot JSONB NOT NULL DEFAULT '{}'::JSONB,
    purchase_unit_snapshot VARCHAR(32) NOT NULL,
    product_type_snapshot VARCHAR(20) NOT NULL,
    received_quantity NUMERIC(18,4) NOT NULL,
    actual_weight NUMERIC(18,4),
    weight_unit VARCHAR(32),
    weighing_source VARCHAR(20),
    correction_reason VARCHAR(500),
    sort_order INTEGER NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_purchase_receipt_item_spec_values CHECK (jsonb_typeof(spec_values_snapshot) = 'object'),
    CONSTRAINT ck_purchase_receipt_item_product_type CHECK (product_type_snapshot IN ('STANDARD', 'NON_STANDARD')),
    CONSTRAINT ck_purchase_receipt_item_quantity CHECK (received_quantity > 0),
    CONSTRAINT ck_purchase_receipt_item_actual_weight CHECK (actual_weight IS NULL OR actual_weight > 0),
    CONSTRAINT ck_purchase_receipt_item_weight_source CHECK (
        weighing_source IS NULL OR weighing_source IN ('MANUAL', 'DEVICE')
    ),
    CONSTRAINT ck_purchase_receipt_item_weight_fields CHECK (
        (actual_weight IS NULL AND weight_unit IS NULL AND weighing_source IS NULL)
        OR (actual_weight IS NOT NULL AND weight_unit IS NOT NULL AND btrim(weight_unit) <> '' AND weighing_source IS NOT NULL)
    ),
    CONSTRAINT ck_purchase_receipt_item_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_purchase_receipt_item_order_item_active
    ON purchase_receipt_item (purchase_receipt_id, purchase_order_item_id)
    WHERE deleted = FALSE;
CREATE INDEX idx_purchase_receipt_item_receipt_id
    ON purchase_receipt_item (purchase_receipt_id, sort_order) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_receipt_item_order_item_id
    ON purchase_receipt_item (purchase_order_item_id) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_receipt_item_sku_id
    ON purchase_receipt_item (sku_id) WHERE deleted = FALSE;

CREATE TABLE receipt_weighing_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_receipt_item_id BIGINT NOT NULL,
    raw_reading NUMERIC(18,4) NOT NULL,
    confirmed_reading NUMERIC(18,4) NOT NULL,
    unit VARCHAR(32) NOT NULL,
    scale_precision NUMERIC(18,4),
    source VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    device_session_id VARCHAR(128),
    modification_reason VARCHAR(500),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    operator VARCHAR(64) NOT NULL DEFAULT 'SYSTEM',
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_receipt_weighing_record_raw CHECK (raw_reading > 0),
    CONSTRAINT ck_receipt_weighing_record_confirmed CHECK (confirmed_reading > 0),
    CONSTRAINT ck_receipt_weighing_record_precision CHECK (scale_precision IS NULL OR scale_precision > 0),
    CONSTRAINT ck_receipt_weighing_record_source CHECK (source IN ('MANUAL', 'DEVICE')),
    CONSTRAINT ck_receipt_weighing_record_version CHECK (version >= 0)
);

CREATE INDEX idx_receipt_weighing_record_item_recorded
    ON receipt_weighing_record (purchase_receipt_item_id, recorded_at DESC)
    WHERE deleted = FALSE;

CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    warehouse_code_snapshot VARCHAR(64) NOT NULL,
    warehouse_name_snapshot VARCHAR(150) NOT NULL,
    sku_code_snapshot VARCHAR(64) NOT NULL,
    sku_name_snapshot VARCHAR(150) NOT NULL,
    unit VARCHAR(32) NOT NULL,
    quantity NUMERIC(18,4) NOT NULL DEFAULT 0,
    average_cost NUMERIC(18,4),
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_inventory_quantity CHECK (quantity >= 0),
    CONSTRAINT ck_inventory_average_cost CHECK (average_cost IS NULL OR average_cost >= 0),
    CONSTRAINT ck_inventory_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_inventory_warehouse_sku_active
    ON inventory (warehouse_id, sku_id) WHERE deleted = FALSE;
CREATE INDEX idx_inventory_sku_id
    ON inventory (sku_id) WHERE deleted = FALSE;

CREATE TABLE inventory_movement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_no VARCHAR(64) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    warehouse_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    warehouse_code_snapshot VARCHAR(64) NOT NULL,
    warehouse_name_snapshot VARCHAR(150) NOT NULL,
    sku_code_snapshot VARCHAR(64) NOT NULL,
    sku_name_snapshot VARCHAR(150) NOT NULL,
    movement_type VARCHAR(30) NOT NULL,
    source_document_type VARCHAR(30) NOT NULL,
    source_document_id BIGINT NOT NULL,
    source_document_item_id BIGINT NOT NULL,
    quantity_before NUMERIC(18,4) NOT NULL,
    quantity_change NUMERIC(18,4) NOT NULL,
    quantity_after NUMERIC(18,4) NOT NULL,
    unit VARCHAR(32) NOT NULL,
    unit_cost NUMERIC(18,4),
    operator VARCHAR(64) NOT NULL DEFAULT 'SYSTEM',
    remark VARCHAR(500),
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_inventory_movement_type CHECK (movement_type IN (
        'PURCHASE_IN', 'SALES_OUT', 'RETURN_IN', 'PURCHASE_RETURN_OUT',
        'STOCKTAKE_IN', 'STOCKTAKE_OUT', 'LOSS', 'GAIN',
        'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUSTMENT'
    )),
    CONSTRAINT ck_inventory_movement_source_type CHECK (source_document_type IN ('PURCHASE_RECEIPT')),
    CONSTRAINT ck_inventory_movement_quantity_change CHECK (quantity_change <> 0),
    CONSTRAINT ck_inventory_movement_quantities CHECK (
        quantity_before >= 0 AND quantity_after >= 0
        AND quantity_after = quantity_before + quantity_change
    ),
    CONSTRAINT ck_inventory_movement_unit_cost CHECK (unit_cost IS NULL OR unit_cost >= 0),
    CONSTRAINT ck_inventory_movement_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uk_inventory_movement_no_active
    ON inventory_movement (movement_no) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_inventory_movement_receipt_item
    ON inventory_movement (source_document_type, source_document_item_id)
    WHERE deleted = FALSE AND source_document_type = 'PURCHASE_RECEIPT' AND movement_type = 'PURCHASE_IN';
CREATE INDEX idx_inventory_movement_warehouse_sku_occurred
    ON inventory_movement (warehouse_id, sku_id, occurred_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_inventory_movement_source
    ON inventory_movement (source_document_type, source_document_id, source_document_item_id)
    WHERE deleted = FALSE;
