/* W4 real PostgreSQL/API/browser acceptance. Account secrets stay in memory. */
import {test,expect,request,type APIRequestContext,type Page} from '@playwright/test';
import {randomBytes,randomUUID} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
import smCrypto from 'sm-crypto';
const apiUrl='http://127.0.0.1:18080';
const name='w4_e2e_'+Date.now().toString(36),password='W4@'+randomBytes(8).toString('hex');
const env={...process.env,W4_E2E_NAME:name,W4_E2E_PASSWORD:password};
let api:APIRequestContext,token:string,customerId:string,skuId:string,standardSkuId:string;
let confirmedOrder:any;
test.describe.configure({mode:'serial'});
async function login(account:string){const c=await request.newContext({baseURL:apiUrl});const captcha=(await(await c.get('/login/getCaptcha')).json()).data;const source=readFileSync('src/lib/encrypt.ts','utf8');const key=/const SM4_KEY = '([^']+)'/.exec(source)![1];const encrypted=Buffer.from(smCrypto.sm4.encrypt(password,Buffer.from(key).toString('hex'))).toString('base64');const r=await(await c.post('/login',{data:{loginName:account,password:encrypted,captchaUuid:captcha.captchaUuid,captchaCode:captcha.captchaText,loginDevice:1}})).json();expect(r.code).toBe(0);await c.dispose();return r.data.token;}
async function post(path:string,data:unknown,key=randomUUID()){const r=await(await api.post(path,{data,headers:{'Idempotency-Key':key}})).json();expect(r.code,`${path}: ${r.msg}`).toBe(0);return r.data;}
function draft(sku=skuId){return {customerId,orderSource:'ADMIN',address:{receiverName:'W4验收',receiverPhone:'13800000000',address:'验收地址'},remark:name,items:[{skuId:sku,orderedQuantity:'2.0000',manualPriceOverride:false}]};}
async function detail(id:string){const r=await(await api.get('/scm/order/detail/'+id)).json();expect(r.code).toBe(0);return r.data;}
async function browse(page:Page,path='/order/order-list'){await page.addInitScript(v=>localStorage.setItem('smart_admin_user_token',v),token);await page.goto('/#'+path);}
async function select(page:Page,label:string,value:string){const box=page.locator(`.ant-form-item:has(#form_item_${label}) .ant-select-selector`);await box.click();await box.locator('input').fill(value);await page.locator('.ant-select-dropdown:visible').getByText(value,{exact:false}).first().click();}
test.beforeAll(async()=>{
 execFileSync('python',['../tools/w4_e2e_accounts.py','setup'],{env,stdio:'pipe'});token=await login(name);api=await request.newContext({baseURL:apiUrl,extraHTTPHeaders:{Authorization:`Bearer ${token}`}});
 const types=(await(await api.post('/scm/customer/type/option/list',{data:{}})).json()).data;
 customerId=await post('/scm/customer/add',{customerCode:name.toUpperCase(),name:name,customerTypeId:types[0].typeId,settleMode:'INDEPENDENT',contactName:'W4验收',contactPhone:'13800000000',address:'验收地址'});
 const customer=(await(await api.get('/scm/customer/detail/'+customerId)).json()).data;await post('/scm/customer/updateStatus',{customerId,version:customer.version,status:'COOPERATING'});
 const tree=(await(await api.post('/scm/product/category/tree',{data:{}})).json()).data;const flatten=(rows:any[]):any[]=>rows.flatMap(x=>[x,...flatten(x.children??[])]);const category=flatten(tree).find(x=>x.level===3)??flatten(tree)[0];
 await post('/scm/product/add',{spuCode:name.toUpperCase(),name:name+'商品',categoryId:category.categoryId,status:'ON_SHELF',images:[],skuList:[{skuCode:name.toUpperCase()+'-KG',specName:'散装',specValues:{规格:'散装'},saleUnit:'kg',productType:'NON_STANDARD',marketPrice:'3.5000',status:'ON_SHELF',defaultFlag:true,sortOrder:0},{skuCode:name.toUpperCase()+'-BOX',specName:'整箱',specValues:{规格:'整箱'},saleUnit:'箱',productType:'STANDARD',marketPrice:'0.0000',status:'ON_SHELF',defaultFlag:false,sortOrder:1}]});
 const options=(await(await api.post('/scm/product/sku/option-list',{data:{keyword:name,limit:10}})).json()).data.options;skuId=options.find((x:any)=>x.specName==='散装').skuId;standardSkuId=options.find((x:any)=>x.specName==='整箱').skuId;
});
test.afterAll(async()=>{if(api){await api.get('/login/logout');await api.dispose();}execFileSync('python',['../tools/w4_e2e_accounts.py','cleanup'],{env,stdio:'pipe'});});

test('1 UI draft entry, diff identity, submit locks price',async({page})=>{
 const consoleErrors:string[]=[];page.on('pageerror',e=>consoleErrors.push(e.message));await browse(page);await expect(page.locator('#order-table')).toBeVisible();await page.getByRole('button',{name:'新建订单',exact:true}).click();await select(page,'customerId',name);
 await page.getByRole('button',{name:'添加商品',exact:true}).click();const skuSelect=page.locator('#order-item-table .ant-select-selector');await skuSelect.click();await skuSelect.locator('input').fill(name);await page.locator('.ant-select-dropdown:visible').getByText('散装',{exact:false}).first().click();await page.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(page.getByText('草稿已保存',{exact:true})).toBeVisible();
 const result=await post('/scm/order/query',{pageNum:1,pageSize:20,customerId});let o=await detail(result.list[0].orderId);const item=o.items[0];expect(item.draftUnitPrice).toBe('3.5000');
 o=await post('/scm/order/update',{...draft(),orderId:o.orderId,version:o.version,items:[{itemId:item.itemId,version:item.version,skuId,orderedQuantity:'3.0000',manualPriceOverride:false}]});expect(o.items[0].itemId).toBe(item.itemId);
 o=await post('/scm/order/submit',{orderId:o.orderId,version:o.version});expect(o.status).toBe('PENDING');expect(o.items[0].lockedUnitPrice).toBe('3.5000');expect(o.orderedTotalAmount).toBe('10.5000');await page.getByRole('button',{name:/^查\s*询$/}).click();await page.screenshot({path:'../.runtime/w4-order-list.png',fullPage:true});expect(consoleErrors).toEqual([]);
});
test('2 nonstandard weight UI, reason and final settlement',async({page})=>{
 let o=await post('/scm/order/create',draft());o=await post('/scm/order/submit',{orderId:o.orderId,version:o.version});expect(o.items[0].actualQuantity).toBeNull();const denied=await(await api.post('/scm/order/confirm',{data:{orderId:o.orderId,version:o.version},headers:{'Idempotency-Key':randomUUID()}})).json();expect(denied.code).toBe(40963);
 await browse(page);await page.getByPlaceholder('名称或订单号').fill(o.orderNo);await page.getByRole('button',{name:/^查\s*询$/}).click();await page.getByText(o.orderNo,{exact:true}).click();await page.getByRole('button',{name:'录入实重',exact:true}).click();await page.locator('#form_item_actualQuantity').fill('1.2500');await page.locator('#form_item_actualQuantityReason').fill('电子秤人工录入');await page.locator('.ant-modal:visible').getByRole('button',{name:'确 定'}).click();await expect(page.locator('.ant-modal:visible')).toHaveCount(0);await page.getByRole('button',{name:'确认订单',exact:true}).click();await page.locator('.ant-modal-confirm').getByRole('button',{name:'确 定'}).click();await expect(page.locator('.ant-drawer-body').getByText('已确认',{exact:true})).toBeVisible();confirmedOrder=await detail(o.orderId);expect(confirmedOrder.settlementTotalAmount).toBe('4.3750');await expect(page.locator('.ant-modal-confirm')).toHaveCount(0);await page.screenshot({path:'../.runtime/w4-order-detail.png',fullPage:true});
});
test('3 cancellation preserves terminal rules and zero-price standard order',async({page})=>{
 const o=await post('/scm/order/create',draft(standardSkuId));expect(o.orderedTotalAmount).toBe('0.0000');await browse(page);await page.getByPlaceholder('名称或订单号').fill(o.orderNo);await page.getByRole('button',{name:/^查\s*询$/}).click();await page.getByText(o.orderNo,{exact:true}).click();await page.getByRole('button',{name:'取消订单',exact:true}).click();await page.locator('#form_item_cancelReason').fill('客户取消');await page.locator('.ant-modal:visible').getByRole('button',{name:'确 定'}).click();await expect(page.locator('.ant-drawer-body').getByText('已取消',{exact:true})).toBeVisible();const denied=await(await api.post('/scm/order/cancel',{data:{orderId:confirmedOrder.orderId,version:confirmedOrder.version,reason:'不可取消'},headers:{'Idempotency-Key':randomUUID()}})).json();expect(denied.code).toBe(40960);
});
test('4 supplement reason, original identity and duplicate request',async()=>{
 const data={...draft(),orderSource:'SUPPLEMENT',originalOrderId:confirmedOrder.orderId};let r=await(await api.post('/scm/order/create',{data,headers:{'Idempotency-Key':randomUUID()}})).json();expect(r.code).toBe(40060);const key=randomUUID();const accepted={...data,supplementReason:'漏录补单'};const first=await post('/scm/order/create',accepted,key);const second=await post('/scm/order/create',accepted,key);expect(first.orderId).toBe(second.orderId);r=await(await api.post('/scm/order/create',{data:{...accepted,remark:'changed'},headers:{'Idempotency-Key':key}})).json();expect(r.code).toBe(40966);
});
test('5 audit page, error retry, empty results and read-only permission',async({page})=>{
 await browse(page,'/order/order-log-list');await expect(page.locator('#order-log-table')).toBeVisible();await page.getByRole('button',{name:'变更前后'}).first().click();await expect(page.locator('.ant-modal pre')).toContainText('after');await page.locator('.ant-modal-close').click();
 const readToken=await login(name+'_read');const read=await request.newContext({baseURL:apiUrl,extraHTTPHeaders:{Authorization:`Bearer ${readToken}`}});const denied=await(await read.post('/scm/order/create',{data:draft(),headers:{'Idempotency-Key':randomUUID()}})).json();expect(denied.code).toBe(30005);await read.get('/login/logout');await read.dispose();
 await browse(page);await page.route('**/scm/order/query',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({code:50000,msg:'验收模拟错误',ok:false})}));await page.getByRole('button',{name:/^查\s*询$/}).click();await expect(page.locator('.ant-alert-error')).toContainText('验收模拟错误');await page.unroute('**/scm/order/query');const recovered=page.waitForResponse(r=>r.url().endsWith('/scm/order/query')&&r.request().method()==='POST');await page.locator('.ant-alert').getByRole('button',{name:/^重\s*试$/}).click();await recovered;await expect(page.locator('.ant-alert-error')).toHaveCount(0);await expect(page.locator('#order-table .ant-spin-spinning')).toHaveCount(0);await page.getByPlaceholder('名称或订单号').fill('NO-SUCH-W4-ORDER');await page.getByPlaceholder('名称或订单号').press('Enter');await expect(page.locator('#order-table .ant-empty')).toBeVisible();await page.setViewportSize({width:1920,height:1080});await page.screenshot({path:'../.runtime/w4-order-empty-1920.png',fullPage:true});
});
test('6 return approval atomically generates refund and completes in UI',async({page})=>{
 const f={orderId:confirmedOrder.orderId,reason:'质量问题',items:[{orderItemId:confirmedOrder.items[0].itemId,requestedQuantity:'1.0000'}]};const r=await post('/scm/order/return/create',f);const excess=await(await api.post('/scm/order/return/create',{data:f,headers:{'Idempotency-Key':randomUUID()}})).json();expect(excess.code).toBe(40969);
 await browse(page,'/order/order-return-list');await expect(page.locator('#order-return-table')).toBeVisible();const row=page.locator('tr').filter({hasText:r.returnNo});await row.getByRole('button',{name:/^批\s*准$/}).click();await page.locator('.ant-modal:visible').getByRole('button',{name:'确 定'}).click();await expect(row).toContainText('已批准');
 const refunds=await post('/scm/order/refund/query',{pageNum:1,pageSize:20,orderId:confirmedOrder.orderId});expect(refunds.list).toHaveLength(1);await browse(page,'/order/order-refund-list');const refund=page.locator('tr').filter({hasText:refunds.list[0].refundNo});await refund.getByRole('button',{name:'登记退款完成'}).click();await page.locator('.ant-modal:visible input').fill(name+'-refund');await page.locator('.ant-modal:visible').getByRole('button',{name:'确 定'}).click();await expect(refund).toContainText('已完成');await expect(page.locator('.ant-modal:visible')).toHaveCount(0);await page.screenshot({path:'../.runtime/w4-refund-list.png',fullPage:true});expect((await detail(confirmedOrder.orderId)).status).toBe('CONFIRMED');
});
