package com.xianshuyuan.scm.purchase.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.xianshuyuan.scm.common.exception.BusinessException;
import com.xianshuyuan.scm.inventory.service.InventoryApplicationService;
import com.xianshuyuan.scm.inventory.service.PurchaseInCommand;
import com.xianshuyuan.scm.order.service.IdempotencyService;
import com.xianshuyuan.scm.product.entity.ProductType;
import com.xianshuyuan.scm.purchase.dto.*;
import com.xianshuyuan.scm.purchase.entity.*;
import com.xianshuyuan.scm.purchase.mapper.*;
import com.xianshuyuan.scm.purchase.vo.PurchaseReceiptConfirmResult;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.OffsetDateTime;
import java.util.*;

@Service
public class PurchaseReceiptApplicationService {
 private final PurchaseReceiptMapper receipts; private final PurchaseReceiptItemMapper receiptItems; private final PurchaseReceiptConfirmationMapper confirmations; private final PurchaseReceiptConfirmationItemMapper confirmationItems; private final PurchaseOrderMapper orders; private final PurchaseOrderItemMapper orderItems; private final PurchaseOperationLogMapper logs; private final PurchaseReceiptNumberGenerator numbers; private final InventoryApplicationService inventory; private final IdempotencyService idempotency; private final ObjectMapper json;
 public PurchaseReceiptApplicationService(PurchaseReceiptMapper receipts,PurchaseReceiptItemMapper receiptItems,PurchaseReceiptConfirmationMapper confirmations,PurchaseReceiptConfirmationItemMapper confirmationItems,PurchaseOrderMapper orders,PurchaseOrderItemMapper orderItems,PurchaseOperationLogMapper logs,PurchaseReceiptNumberGenerator numbers,InventoryApplicationService inventory,IdempotencyService idempotency,ObjectMapper json){this.receipts=receipts;this.receiptItems=receiptItems;this.confirmations=confirmations;this.confirmationItems=confirmationItems;this.orders=orders;this.orderItems=orderItems;this.logs=logs;this.numbers=numbers;this.inventory=inventory;this.idempotency=idempotency;this.json=json;}

 @Transactional public long create(PurchaseReceiptCreateRequest request){
  var order=orders.selectActiveByIdForUpdate(request.purchaseOrderId());
  if(order==null) throw new BusinessException(PurchaseOrderErrorCodes.NOT_FOUND);
  if(order.getStatus()!=PurchaseOrderStatus.SUBMITTED&&order.getStatus()!=PurchaseOrderStatus.PARTIALLY_RECEIVED) throw new BusinessException(PurchaseReceiptErrorCodes.INVALID_STATE);
  var existing=receipts.selectActiveByOrderIdForUpdate(order.getId()); if(existing!=null) return existing.getId();
  var receipt=new PurchaseReceiptEntity(); receipt.setReceiptNo(numbers.next()); receipt.setPurchaseOrderId(order.getId()); receipt.setPurchaseOrderNoSnapshot(order.getOrderNo()); receipt.setWarehouseId(order.getWarehouseId()); receipt.setWarehouseCodeSnapshot(order.getWarehouseCodeSnapshot()); receipt.setWarehouseNameSnapshot(order.getWarehouseNameSnapshot()); receipt.setStatus(PurchaseReceiptStatus.DRAFT); receipt.setRemark(request.remark()); receipt.setVersion(0); receipt.setDeleted(false); receipt.setCreatedBy("SYSTEM"); receipts.insert(receipt);
  int sort=0; for(var source:orderItems.selectActiveByOrderIdForUpdate(order.getId())){var row=new PurchaseReceiptItemEntity();row.setPurchaseReceiptId(receipt.getId());row.setPurchaseOrderItemId(source.getId());row.setSkuId(source.getSkuId());row.setSpuCodeSnapshot(source.getSpuCodeSnapshot());row.setProductNameSnapshot(source.getProductNameSnapshot());row.setSkuCodeSnapshot(source.getSkuCodeSnapshot());row.setSkuNameSnapshot(source.getSkuNameSnapshot());row.setSpecValuesSnapshot(source.getSpecValuesSnapshot());row.setPurchaseUnitSnapshot(source.getPurchaseUnitSnapshot());row.setProductTypeSnapshot(source.getProductTypeSnapshot());row.setReceivedQuantity(BigDecimal.ZERO.setScale(4));row.setSortOrder(sort++);row.setVersion(0);row.setDeleted(false);row.setCreatedBy("SYSTEM");receiptItems.insert(row);} log(order.getId(),receipt.getId(),"RECEIPT_CREATE",receipt.getStatus().name()); return receipt.getId();
 }

 @Transactional public PurchaseReceiptConfirmResult confirm(long receiptId,PurchaseReceiptConfirmRequest request,String key){
  String scope="PURCHASE_RECEIPT_CONFIRM:"+receiptId; var claim=idempotency.claim(scope,key,request); if(claim.replay()) return idempotency.replay(claim,PurchaseReceiptConfirmResult.class);
  var receipt=receipts.selectActiveByIdForUpdate(receiptId); if(receipt==null) throw new BusinessException(PurchaseReceiptErrorCodes.NOT_FOUND); if(receipt.getStatus()==PurchaseReceiptStatus.CONFIRMED) throw new BusinessException(PurchaseReceiptErrorCodes.INVALID_STATE); if(!Objects.equals(receipt.getVersion(),request.version())) throw new BusinessException(PurchaseReceiptErrorCodes.VERSION_CONFLICT);
  var order=orders.selectActiveByIdForUpdate(receipt.getPurchaseOrderId()); if(order==null||(order.getStatus()!=PurchaseOrderStatus.SUBMITTED&&order.getStatus()!=PurchaseOrderStatus.PARTIALLY_RECEIVED)) throw new BusinessException(PurchaseReceiptErrorCodes.INVALID_STATE);
  var purchaseRows=orderItems.selectActiveByOrderIdForUpdate(order.getId()); var purchaseById=new HashMap<Long,PurchaseOrderItemEntity>(); purchaseRows.forEach(x->purchaseById.put(x.getId(),x));
  var rows=receiptItems.selectActiveByReceiptIdForUpdate(receiptId); var byId=new HashMap<Long,PurchaseReceiptItemEntity>(); rows.forEach(x->byId.put(x.getId(),x)); var seen=new HashSet<Long>(); var quantities=new LinkedHashMap<PurchaseReceiptItemEntity,BigDecimal>(); BigDecimal total=BigDecimal.ZERO;
  for(var requested:request.items()){if(!seen.add(requested.receiptItemId())) throw new BusinessException(PurchaseReceiptErrorCodes.INVALID_QUANTITY);var row=byId.get(requested.receiptItemId());if(row==null||!Objects.equals(row.getVersion(),requested.version())) throw new BusinessException(row==null?PurchaseReceiptErrorCodes.ITEM_NOT_FOUND:PurchaseReceiptErrorCodes.VERSION_CONFLICT);var poItem=purchaseById.get(row.getPurchaseOrderItemId());if(poItem==null) throw new BusinessException(PurchaseReceiptErrorCodes.ITEM_NOT_FOUND);BigDecimal effective=effective(row,requested);BigDecimal remaining=poItem.getPlannedQuantity().subtract(poItem.getReceivedQuantity());if(effective.signum()<=0||effective.compareTo(remaining)>0) throw new BusinessException(PurchaseReceiptErrorCodes.OVER_RECEIVED);quantities.put(row,effective);total=total.add(effective);}
  var confirmation=new PurchaseReceiptConfirmationEntity();confirmation.setConfirmationNo(confirmations.nextNumber());confirmation.setPurchaseReceiptId(receiptId);confirmation.setIdempotencyScope(scope);confirmation.setIdempotencyKey(key.trim());confirmation.setRequestHash(claim.record().getRequestHash());confirmation.setTotalQuantity(total);confirmation.setStatus("CONFIRMED");confirmation.setOperator("SYSTEM");confirmation.setConfirmedAt(OffsetDateTime.now());confirmation.setCreatedBy("SYSTEM");confirmations.insert(confirmation);
  for(var entry:quantities.entrySet()){var row=entry.getKey();var requested=request.items().stream().filter(x->x.receiptItemId().equals(row.getId())).findFirst().orElseThrow();var effective=entry.getValue();var poItem=purchaseById.get(row.getPurchaseOrderItemId());var detail=new PurchaseReceiptConfirmationItemEntity();detail.setConfirmationId(confirmation.getId());detail.setPurchaseReceiptItemId(row.getId());detail.setPurchaseOrderItemId(poItem.getId());detail.setPlannedQuantity(new BigDecimal(requested.receivedQuantity()));detail.setEffectiveQuantity(effective);detail.setActualWeight(requested.actualWeight()==null?null:new BigDecimal(requested.actualWeight()));detail.setUnit(row.getPurchaseUnitSnapshot());detail.setWeighingSource(requested.weightSource());detail.setCorrectionReason(requested.correctionReason());detail.setCreatedBy("SYSTEM");confirmationItems.insert(detail);inventory.postPurchaseIn(new PurchaseInCommand(receiptId,row.getId(),confirmation.getId(),receipt.getWarehouseId(),row.getSkuId(),receipt.getWarehouseCodeSnapshot(),receipt.getWarehouseNameSnapshot(),row.getSkuCodeSnapshot(),row.getSkuNameSnapshot(),row.getPurchaseUnitSnapshot(),effective,poItem.getPurchasePrice()));poItem.setReceivedQuantity(poItem.getReceivedQuantity().add(effective));poItem.setVersion(poItem.getVersion());if(orderItems.updateById(poItem)!=1) throw new BusinessException(PurchaseOrderErrorCodes.VERSION_CONFLICT);row.setReceivedQuantity(row.getReceivedQuantity().add(effective));row.setActualWeight(detail.getActualWeight());row.setWeightUnit(detail.getActualWeight()==null?null:row.getPurchaseUnitSnapshot());row.setWeighingSource(detail.getWeighingSource());row.setCorrectionReason(detail.getCorrectionReason());row.setVersion(requested.version());if(receiptItems.updateById(row)!=1) throw new BusinessException(PurchaseReceiptErrorCodes.VERSION_CONFLICT);}
  boolean complete=purchaseRows.stream().allMatch(x->x.getReceivedQuantity().compareTo(x.getPlannedQuantity())==0);order.setStatus(complete?PurchaseOrderStatus.RECEIVED:PurchaseOrderStatus.PARTIALLY_RECEIVED);if(orders.updateById(order)!=1) throw new BusinessException(PurchaseOrderErrorCodes.VERSION_CONFLICT);receipt.setStatus(complete?PurchaseReceiptStatus.CONFIRMED:PurchaseReceiptStatus.PARTIALLY_CONFIRMED);receipt.setConfirmedAt(OffsetDateTime.now());receipt.setReceivedAt(receipt.getConfirmedAt());receipt.setOperator("SYSTEM");receipt.setVersion(request.version());if(receipts.updateById(receipt)!=1) throw new BusinessException(PurchaseReceiptErrorCodes.VERSION_CONFLICT);var result=new PurchaseReceiptConfirmResult(receiptId,confirmation.getId(),confirmation.getConfirmationNo(),receipt.getStatus().name(),order.getStatus().name(),decimal(total));confirmation.setResultData(json.valueToTree(result));confirmations.updateById(confirmation);log(order.getId(),receiptId,"RECEIPT_CONFIRM",confirmation.getConfirmationNo());idempotency.complete(claim,"PURCHASE_RECEIPT_CONFIRMATION",confirmation.getId(),result);return result;
 }
 private BigDecimal effective(PurchaseReceiptItemEntity row,PurchaseReceiptConfirmItemRequest request){if(request.receivedQuantity()==null) throw new BusinessException(PurchaseReceiptErrorCodes.INVALID_QUANTITY);BigDecimal planned=new BigDecimal(request.receivedQuantity());if(row.getProductTypeSnapshot()==ProductType.NON_STANDARD){if(request.actualWeight()==null||request.weightSource()!=ReceiptWeighingSource.MANUAL) throw new BusinessException(PurchaseReceiptErrorCodes.INVALID_QUANTITY);return new BigDecimal(request.actualWeight());}return planned;}
 private String decimal(BigDecimal value){return value.setScale(4,RoundingMode.HALF_UP).toPlainString();}
 private void log(long orderId,long receiptId,String type,String state){var row=new PurchaseOperationLogEntity();row.setPurchaseOrderId(orderId);row.setPurchaseReceiptId(receiptId);row.setOperationType(type);row.setOperator("SYSTEM");row.setAfterData(JsonNodeFactory.instance.objectNode().put("state",state));row.setCreatedBy("SYSTEM");logs.insert(row);}
 public PurchaseReceiptEntity require(long id){var row=receipts.selectActiveById(id);if(row==null) throw new BusinessException(PurchaseReceiptErrorCodes.NOT_FOUND);return row;} public List<PurchaseReceiptEntity> list(){return receipts.selectActiveList();} public List<PurchaseReceiptItemEntity> items(long id){require(id);return receiptItems.selectActiveByReceiptId(id);} public List<PurchaseReceiptConfirmationEntity> confirmations(long id){require(id);return confirmations.selectByReceiptId(id);} public List<PurchaseReceiptConfirmationItemEntity> confirmationItems(long id){require(id);return confirmationItems.selectByReceiptId(id);}
}
