#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate V3__sa_system_login_support_and_seed.sql for the V2 baseline.

Contents:
  * DDL (PostgreSQL) for the tables the login chain still needs:
      t_config, t_login_log, t_login_fail, t_password_log
  * Seed data:
      t_config (super password + level-3 protection config)
      t_department / t_position / t_employee  (curated single-admin seed)
      t_role / t_role_employee / t_role_menu
      t_menu   (converted from the SmartAdmin baseline, minus the ERP demo
                sub-tree whose Vue views were removed in V2)
      t_dict / t_dict_data

Run from the v2/ directory:
  python tools/gen_v3_migration.py
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
V2 = HERE.parent
DUMP = (V2 / ".." / "project-reference-examples" / "xsy-scm"
        / "数据库SQL脚本" / "mysql" / "smart_admin_v3.sql").resolve()
OUT = V2 / "xsy-scm-v2-server" / "sa-admin" / "src" / "main" / "resources" / "db" / "migration" / "V3__sa_system_login_support_and_seed.sql"

sys.path.insert(0, str(HERE))
from pg_seed_convert import find_inserts, split_tuple, to_pg_value, COLUMNS, BOOL_POSITIONS  # noqa: E402

# ERP demo menus whose Vue views were deleted in V2 (they conflict with the SCM
# product domain). Excluding them keeps the menu tree free of dangling components.
EXCLUDED_MENUS = {47, 48, 78, 79}

# Argon2id hash produced with the V2 baseline algorithm:
#   Argon2PasswordEncoder.defaultsForSpringSecurity_v5_8()
#       .encode(password + "_" + uid.toUpperCase() + "_" + uid.toLowerCase())
# password = Xsy@2026!Admin
ADMIN_UID = "a1b2c3d4e5f60718293a4b5c6d7e8f90"
ADMIN_PWD_HASH = ("$argon2id$v=19$m=16384,t=2,p=1$zOqzb+oOL6j61ObcGHgLIg"
                  "$UoCTPzsYdWxRnr3BF4OANDf9nSBQOsPf5e3wFgresy4")

HEADER = """-- =====================================================================
-- V2 系统表基线 · 登录支撑表 + 种子数据
--
-- 为什么需要这个文件：
--   V1 只建了 PoC 三表（t_employee / t_menu / t_dict + t_dict_data），
--   V2 只建了登录 RBAC 关联表。但 SmartAdmin 的登录链路还依赖：
--     t_config        -> ConfigService.getConfigValue(SUPER_PASSWORD) 与三级等保配置
--     t_login_log     -> LoginLogService.log / queryLastByUserId
--     t_login_fail    -> SecurityLoginService.checkLogin / recordLoginFail
--     t_password_log  -> SecurityPasswordService.checkNeedChangePassword
--   缺任意一张都会在登录或登录后取用户信息时抛 SQL 异常。
--
-- 转换规则见 V1 文件头（identity / BOOLEAN / TIMESTAMP / 命名约束）。
--
-- 种子数据来源：SmartAdmin v3.31 官方 MySQL 脚本，已转换：
--   - 菜单树保留系统/运维/监控/文档/代码生成等全部条目
--   - 排除 ERP 商品 Demo 子树（47/48/78/79），其 Vue 视图在 V2 已删除
--   - 部门/职务/员工/角色改为 V2 自建最小集（不引入官方演示账号）
-- =====================================================================

-- ---------------------------------------------------------------------
-- t_config 系统配置
-- ---------------------------------------------------------------------
CREATE TABLE t_config (
    config_id    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name  VARCHAR(255) NOT NULL,
    config_key   VARCHAR(255) NOT NULL,
    config_value TEXT         NOT NULL,
    remark       VARCHAR(255),
    update_time  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_config_key UNIQUE (config_key)
);

COMMENT ON TABLE t_config IS '系统配置';
COMMENT ON COLUMN t_config.config_name IS '参数名字';
COMMENT ON COLUMN t_config.config_key IS '参数key';
COMMENT ON COLUMN t_config.config_value IS '参数值';

-- ---------------------------------------------------------------------
-- t_login_log 用户登录日志
-- ---------------------------------------------------------------------
CREATE TABLE t_login_log (
    login_log_id    BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER       NOT NULL,
    user_type       INTEGER       NOT NULL,
    user_name       VARCHAR(1000) NOT NULL,
    login_ip        VARCHAR(1000),
    login_ip_region VARCHAR(1000),
    user_agent      TEXT,
    login_device    VARCHAR(1000),
    login_result    INTEGER       NOT NULL,
    remark          VARCHAR(2000),
    update_time     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_t_login_log_user_id ON t_login_log (user_id);

COMMENT ON TABLE t_login_log IS '用户登录日志';
COMMENT ON COLUMN t_login_log.login_result IS '登录结果：0成功 1失败 2退出';

-- ---------------------------------------------------------------------
-- t_login_fail 登录失败次数记录
-- ---------------------------------------------------------------------
CREATE TABLE t_login_fail (
    login_fail_id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT        NOT NULL,
    user_type               INTEGER       NOT NULL,
    login_name              VARCHAR(1000),
    login_fail_count        INTEGER,
    lock_flag               BOOLEAN       DEFAULT FALSE,
    login_lock_begin_time   TIMESTAMP,
    create_time             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_login_fail_user UNIQUE (user_id, user_type)
);

COMMENT ON TABLE t_login_fail IS '登录失败次数记录表';
COMMENT ON COLUMN t_login_fail.lock_flag IS '锁定状态:true锁定，false未锁定';

-- ---------------------------------------------------------------------
-- t_password_log 密码修改记录
-- ---------------------------------------------------------------------
CREATE TABLE t_password_log (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    user_type    SMALLINT     NOT NULL,
    old_password VARCHAR(255) NOT NULL,
    new_password VARCHAR(255),
    update_time  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_t_password_log_user ON t_password_log (user_id, user_type);

COMMENT ON TABLE t_password_log IS '密码修改记录';

-- =====================================================================
-- 种子数据
-- =====================================================================

-- ----------------------------
-- 系统配置
-- ----------------------------
INSERT INTO t_config (config_id, config_name, config_key, config_value, remark, update_time, create_time)
VALUES (1, '万能密码', 'super_password', '1024ok', 'V2 基线：仅运维应急使用，生产环境必须修改',
        '2026-09-14 00:00:00', '2026-09-14 00:00:00');

INSERT INTO t_config (config_id, config_name, config_key, config_value, remark, update_time, create_time)
VALUES (2, '三级等保', 'level3_protect_config',
        $cfg${
    "fileDetectFlag": true,
    "loginActiveTimeoutMinutes": 30,
    "loginFailLockMinutes": 30,
    "loginFailMaxTimes": 3,
    "maxUploadFileSizeMb": 30,
    "passwordComplexityEnabled": true,
    "regularChangePasswordMonths": 3,
    "regularChangePasswordNotAllowRepeatTimes": 3,
    "twoFactorLoginEnabled": false
}$cfg$,
        'V2 基线：关闭双因子登录，便于本地与自动化验证',
        '2026-09-14 00:00:00', '2026-09-14 00:00:00');

-- ----------------------------
-- 部门 / 职务 / 员工（V2 自建最小集）
-- ----------------------------
INSERT INTO t_department (department_id, department_name, manager_id, parent_id, sort, update_time, create_time)
VALUES (1, '鲜蔬源', 1, 0, 1, '2026-09-14 00:00:00', '2026-09-14 00:00:00');

INSERT INTO t_position (position_id, position_name, position_level, sort, remark, deleted_flag, create_time, update_time)
VALUES (1, '系统管理员', 'P1', 1, 'V2 基线内置职务', FALSE, '2026-09-14 00:00:00', '2026-09-14 00:00:00');

-- 登录口令：Xsy@2026!Admin
-- 哈希算法：Argon2PasswordEncoder.defaultsForSpringSecurity_v5_8()
-- 加盐规则：password + "_" + employee_uid.toUpperCase() + "_" + employee_uid.toLowerCase()
INSERT INTO t_employee
    (employee_id, employee_uid, login_name, login_pwd, actual_name, avatar, gender, phone,
     department_id, position_id, email, disabled_flag, deleted_flag, administrator_flag,
     remark, update_time, create_time)
VALUES
    (1, '{uid}', 'admin', '{pwd}', '系统管理员', NULL, 0, '13500000000',
     1, 1, NULL, FALSE, FALSE, TRUE,
     'V2 基线内置超级管理员', '2026-09-14 00:00:00', '2026-09-14 00:00:00');

-- ----------------------------
-- 角色
-- ----------------------------
INSERT INTO t_role (role_id, role_name, role_code, remark, update_time, create_time)
VALUES (1, '超级管理员', 'SUPER_ADMIN', 'V2 基线内置角色（员工1同时具备 administrator_flag，权限判定不受角色影响）',
        '2026-09-14 00:00:00', '2026-09-14 00:00:00');

INSERT INTO t_role_employee (role_id, employee_id, update_time, create_time)
VALUES (1, 1, '2026-09-14 00:00:00', '2026-09-14 00:00:00');
"""

FOOTER = """
-- =====================================================================
-- 序列校正
-- 使用显式 ID 插入后，identity 序列不会自动前进；
-- 不校正会导致后续 insert 主键冲突。pg_get_serial_sequence 同时支持
-- identity 列与 serial 列。
-- =====================================================================
SELECT setval(pg_get_serial_sequence('t_config', 'config_id'),        (SELECT MAX(config_id)        FROM t_config));
SELECT setval(pg_get_serial_sequence('t_department', 'department_id'),(SELECT MAX(department_id)    FROM t_department));
SELECT setval(pg_get_serial_sequence('t_position', 'position_id'),    (SELECT MAX(position_id)      FROM t_position));
SELECT setval(pg_get_serial_sequence('t_employee', 'employee_id'),    (SELECT MAX(employee_id)      FROM t_employee));
SELECT setval(pg_get_serial_sequence('t_role', 'role_id'),            (SELECT MAX(role_id)          FROM t_role));
SELECT setval(pg_get_serial_sequence('t_menu', 'menu_id'),            (SELECT MAX(menu_id)          FROM t_menu));
SELECT setval(pg_get_serial_sequence('t_dict', 'dict_id'),            (SELECT MAX(dict_id)          FROM t_dict));
SELECT setval(pg_get_serial_sequence('t_dict_data', 'dict_data_id'),  (SELECT MAX(dict_data_id)     FROM t_dict_data));
"""


def menu_inserts(text):
    cols = COLUMNS["t_menu"]
    bools = set(BOOL_POSITIONS["t_menu"])
    out, kept, skipped = [], 0, 0
    for icols, vals in find_inserts(text, "t_menu"):
        c = icols or cols
        menu_id = int(vals[0])
        if menu_id in EXCLUDED_MENUS:
            skipped += 1
            continue
        rendered = [to_pg_value(x, (i + 1) in bools) for i, x in enumerate(vals)]
        out.append("INSERT INTO t_menu (%s) VALUES (%s);" % (", ".join(c), ", ".join(rendered)))
        kept += 1
    return out, kept, skipped


def simple_inserts(text, table, cols=None, bools=()):
    out = []
    for icols, vals in find_inserts(text, table):
        c = icols or cols or COLUMNS.get(table)
        rendered = [to_pg_value(x, (i + 1) in set(bools)) for i, x in enumerate(vals)]
        out.append("INSERT INTO %s (%s) VALUES (%s);" % (table, ", ".join(c), ", ".join(rendered)))
    return out


def main():
    # The upstream dump uses CRLF; normalise so extracted literals (notably the
    # level3_protect_config JSON) do not carry stray \r into the PostgreSQL seed.
    text = DUMP.read_text(encoding="utf-8", errors="replace")
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    menus, kept, skipped = menu_inserts(text)
    print(f"t_menu: kept={kept} excluded={skipped}")

    dicts = simple_inserts(text, "t_dict", bools=BOOL_POSITIONS["t_dict"])
    dict_data = simple_inserts(text, "t_dict_data", bools=BOOL_POSITIONS["t_dict_data"])
    print(f"t_dict={len(dicts)} t_dict_data={len(dict_data)}")

    body = [HEADER.replace("{uid}", ADMIN_UID).replace("{pwd}", ADMIN_PWD_HASH)]

    body.append("\n-- ----------------------------\n-- 菜单（系统基线菜单树）\n-- ----------------------------\n")
    body.extend(menus)

    body.append("\n-- ----------------------------\n-- 角色-菜单（授予内置角色全部菜单）\n-- ----------------------------\n")
    for line in menus:
        m = re.search(r"VALUES \((\d+),", line)
        menu_id = m.group(1)
        body.append(
            "INSERT INTO t_role_menu (role_id, menu_id, update_time, create_time) "
            "VALUES (1, %s, '2026-09-14 00:00:00', '2026-09-14 00:00:00');" % menu_id
        )

    body.append("\n-- ----------------------------\n-- 字典\n-- ----------------------------\n")
    body.extend(dicts)
    body.extend(dict_data)

    body.append(FOOTER)

    OUT.write_text("\n".join(body) + "\n", encoding="utf-8")
    print(f"written: {OUT}")
    print(f"bytes: {OUT.stat().st_size}")


if __name__ == "__main__":
    main()
