#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate the V5 PostgreSQL migration (remaining SmartAdmin system tables) from the
upstream MySQL dump.

Why a generator instead of hand-written SQL:
  * 23 tables x ~15 columns is too much to transcribe by hand without drift;
  * column names AND types can be parsed straight out of the upstream CREATE TABLE,
    so the tinyint(1)->BOOLEAN decisions follow the DDL instead of a hand-kept list;
  * the INSERT statements must be extracted with a quote-aware scanner, because
    values such as the mail template contain ';' and escaped quotes.

Conversion rules (same contract as V1..V4):
  bigint AUTO_INCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
  int AUTO_INCREMENT    -> INTEGER GENERATED BY DEFAULT AS IDENTITY
  bigint / int / smallint -> BIGINT / INTEGER / SMALLINT   (unsigned is dropped)
  tinyint(1)            -> BOOLEAN          (0/1 flag columns)
  tinyint (other)       -> SMALLINT
  tinyint unsigned      -> SMALLINT
  varchar(n)            -> VARCHAR(n)
  text / longtext       -> TEXT
  datetime / datetime(n)-> TIMESTAMP
  date                  -> DATE
  decimal(a,b)          -> NUMERIC(a,b)
  json                  -> JSONB
  PRIMARY KEY (a, b)    -> CONSTRAINT pk_<table> PRIMARY KEY (a, b)
  UNIQUE INDEX n (c)    -> CONSTRAINT uk_<table>_<n> UNIQUE (c)
  INDEX n (c)           -> CREATE INDEX idx_<table>_<n> ON <table> (c)
  ENGINE/CHARSET/COLLATE/ROW_FORMAT/USING BTREE/display width -> dropped
  ON UPDATE CURRENT_TIMESTAMP -> dropped (see V4 header for rationale)
  COMMENT 'x'           -> COMMENT ON COLUMN ...
"""

import io
import re
import sys
from pathlib import Path

DUMP = Path(sys.argv[1])
OUT = Path(sys.argv[2])

# Tables emitted in this migration: every remaining upstream table that backs a
# seeded SmartAdmin menu, so the baseline has no menu pointing at a missing table.
TABLES = [
    # 系统设置 / 运维工具
    "t_code_generator_config",
    "t_table_column",
    "t_smart_job",
    "t_smart_job_log",
    "t_file",
    "t_heart_beat_record",
    "t_mail_template",
    # 监控 / 文档中心
    "t_change_log",
    "t_data_tracer",
    "t_feedback",
    "t_help_doc",
    "t_help_doc_catalog",
    "t_help_doc_relation",
    "t_help_doc_view_record",
    # 消息 / 通知
    "t_notice",
    "t_notice_type",
    "t_notice_view_record",
    "t_notice_visible_range",
    "t_message",
    # OA 示例模块（菜单树中存在对应页面，表必须存在）
    "t_oa_bank",
    "t_oa_enterprise",
    "t_oa_enterprise_employee",
    "t_oa_invoice",
]

# Seeds that are genuine reference/system data. Upstream demo rows
# (t_change_log 11 / t_data_tracer 10 / t_notice 12 / t_message 4 / t_oa_* / help-doc 内容)
# are deliberately NOT carried over: V2 is a clean baseline, not a demo copy.
SEED_TABLES = ["t_notice_type", "t_mail_template", "t_smart_job"]

TEXT = DUMP.read_text(encoding="utf-8", errors="replace")


# --------------------------------------------------------------------------
# DDL parsing
# --------------------------------------------------------------------------
def ddl_body(table: str) -> str:
    m = re.search(r"CREATE TABLE `%s`\s*\((.*?)\n\)\s*ENGINE" % re.escape(table), TEXT, re.S)
    if not m:
        raise SystemExit("DDL not found for " + table)
    return m.group(1)


def parse_columns(body: str):
    """Return [(col, mysql_type, nullable, default, comment)] in DDL order."""
    cols = []
    for raw in body.split("\n"):
        line = raw.strip().rstrip(",")
        if not line or line.upper().startswith(("PRIMARY KEY", "UNIQUE INDEX", "INDEX", "KEY ", "CONSTRAINT")):
            continue
        m = re.match(r"`([^`]+)`\s+([a-zA-Z]+(?:\(\d+(?:,\d+)?\))?(?:\s+unsigned)?)", line)
        if not m:
            continue
        col, mtype = m.group(1), m.group(2)
        nullable = "NOT NULL" not in line.upper()
        dm = re.search(r"DEFAULT\s+([^ ]+(?:\(\))?|'[^']*'|CURRENT_TIMESTAMP(?:\(\d+\))?)", line, re.I)
        default = dm.group(1) if dm else None
        cm = re.search(r"COMMENT\s+'((?:[^']|'')*)'", line)
        comment = cm.group(1) if cm else None
        cols.append((col, mtype.lower(), nullable, default, comment))
    return cols


def parse_keys(body: str):
    """Return (pk_cols, [ (name, cols, unique) ])."""
    pk = []
    idx = []
    m = re.search(r"PRIMARY KEY\s*\(([^)]*)\)", body)
    if m:
        pk = [c.strip().strip("`") for c in m.group(1).split(",")]
    for m in re.finditer(r"(UNIQUE\s+)?INDEX\s+`([^`]+)`\s*\(([^)]*)\)", body):
        unique = bool(m.group(1))
        idx.append((m.group(2), [c.strip().strip("`") for c in m.group(3).split(",")], unique))
    return pk, idx


# --------------------------------------------------------------------------
# type mapping
# --------------------------------------------------------------------------
def pg_type(mysql_type: str):
    t = mysql_type.lower()
    base = re.sub(r"\s*unsigned", "", t).strip()
    if base.startswith("tinyint(1)"):
        return "BOOLEAN"
    if base.startswith("tinyint"):
        return "SMALLINT"
    if base.startswith("smallint"):
        return "SMALLINT"
    if base.startswith("mediumint"):
        return "INTEGER"
    if base.startswith("bigint"):
        return "BIGINT"
    if base.startswith("int"):
        return "INTEGER"
    if base.startswith("decimal"):
        return base.replace("decimal", "NUMERIC")
    if base.startswith("numeric"):
        return base
    if base.startswith("varchar") or base.startswith("char"):
        return base.upper()
    if base in ("text", "longtext", "mediumtext", "tinytext"):
        return "TEXT"
    if base.startswith("datetime") or base.startswith("timestamp"):
        return "TIMESTAMP"
    if base == "date":
        return "DATE"
    if base == "time":
        return "TIME"
    if base == "json":
        return "JSONB"
    if base.startswith("blob") or base in ("longblob", "mediumblob", "tinyblob"):
        return "BYTEA"
    if base.startswith("double") or base.startswith("float"):
        return "DOUBLE PRECISION"
    raise SystemExit("unmapped mysql type: " + mysql_type)


def pg_default(default: str, pgtype: str):
    if default is None:
        return None
    d = default.strip()
    if re.match(r"CURRENT_TIMESTAMP", d, re.I):
        return "CURRENT_TIMESTAMP"
    if pgtype == "BOOLEAN":
        if d == "1":
            return "TRUE"
        if d == "0":
            return "FALSE"
    return d


# --------------------------------------------------------------------------
# DDL emit
# --------------------------------------------------------------------------
def emit_ddl(table: str) -> str:
    body = ddl_body(table)
    cols = parse_columns(body)
    pk, idx = parse_keys(body)

    lines = ["CREATE TABLE %s (" % table]
    rendered = []
    for col, mtype, nullable, default, _ in cols:
        pgtype = pg_type(mtype)
        is_identity = "AUTO_INCREMENT" in body_for_col(body, col)
        if is_identity:
            pgtype = "%s GENERATED BY DEFAULT AS IDENTITY" % pgtype
        part = "    %-30s %s" % (col, pgtype)
        if not nullable:
            part += " NOT NULL"
        d = pg_default(default, pg_type(mtype))
        if d is not None and not is_identity:
            part += " DEFAULT %s" % d
        rendered.append(part.rstrip())
    if pk:
        rendered.append("    CONSTRAINT pk_%s PRIMARY KEY (%s)" % (table, ", ".join(pk)))
    for name, ccols, unique in idx:
        if unique:
            rendered.append("    CONSTRAINT uk_%s_%s UNIQUE (%s)" % (table, name, ", ".join(ccols)))
    lines.append(",\n".join(rendered))
    lines.append(");")

    # COMMENT ON
    cmts = ["COMMENT ON TABLE  %s IS '%s';" % (table, table)]
    for col, _, _, _, comment in cols:
        if comment:
            cmts.append("COMMENT ON COLUMN %s.%s IS '%s';" % (table, col, comment.replace("'", "''")))
    out = "\n".join(lines) + "\n\n" + "\n".join(cmts)

    # non-unique indexes
    for name, ccols, unique in idx:
        if not unique:
            out += "\nCREATE INDEX idx_%s_%s ON %s (%s);" % (table, name, table, ", ".join(ccols))
    return out


def body_for_col(body: str, col: str) -> str:
    m = re.search(r"`%s`[^\n]*" % re.escape(col), body)
    return m.group(0) if m else ""


# --------------------------------------------------------------------------
# INSERT parsing (quote aware) + emit
# --------------------------------------------------------------------------
def extract_inserts(table: str):
    """Yield (cols_or_None, [value tuples]) with a quote-aware statement scanner."""
    results = []
    pos = 0
    needle = "INSERT INTO `%s`" % table
    while True:
        i = TEXT.find(needle, pos)
        if i < 0:
            break
        # scan to the terminating ';' outside of string literals
        j = i
        in_str = False
        while j < len(TEXT):
            ch = TEXT[j]
            if in_str:
                if ch == "\\":
                    j += 2
                    continue
                if ch == "'":
                    if j + 1 < len(TEXT) and TEXT[j + 1] == "'":
                        j += 2
                        continue
                    in_str = False
                j += 1
                continue
            if ch == "'":
                in_str = True
                j += 1
                continue
            if ch == ";":
                break
            j += 1
        stmt = TEXT[i:j]
        results.append(stmt)
        pos = j + 1

    out = []
    for stmt in results:
        m = re.match(r"INSERT INTO `[^`]+`\s*(\(([^)]*)\))?\s*VALUES\s*(.*)$", stmt, re.S | re.I)
        colblob, body = m.group(2), m.group(3)
        cols = [c.strip().strip("`") for c in colblob.split(",")] if colblob else None
        for tm in re.finditer(r"\(((?:[^'()]|'(?:\\.|''|[^'])*')*)\)", body, re.S):
            out.append((cols, split_tuple(tm.group(1))))
    return out


def split_tuple(s: str):
    out, buf, i, n = [], [], 0, len(s)
    in_str = False
    while i < n:
        ch = s[i]
        if in_str:
            if ch == "\\" and i + 1 < n:
                buf.append(s[i:i + 2]); i += 2; continue
            if ch == "'":
                if i + 1 < n and s[i + 1] == "'":
                    buf.append("''"); i += 2; continue
                in_str = False; buf.append(ch); i += 1; continue
            buf.append(ch); i += 1; continue
        if ch == "'":
            in_str = True; buf.append(ch); i += 1; continue
        if ch == ",":
            out.append("".join(buf).strip()); buf = []; i += 1; continue
        buf.append(ch); i += 1
    out.append("".join(buf).strip())
    return out


def to_pg_value(raw: str, is_bool: bool) -> str:
    raw = raw.strip()
    if raw.upper() == "NULL":
        return "NULL"
    if is_bool:
        if raw in ("1", "'1'"):
            return "TRUE"
        if raw in ("0", "'0'"):
            return "FALSE"
        return raw
    if raw.startswith("'"):
        # MySQL escape sequences -> PostgreSQL escape string (E'...')
        inner = raw[1:-1]
        if "\\" in inner:
            return "E'" + inner + "'"
        return raw
    return raw


def emit_seed(table: str) -> str:
    body = ddl_body(table)
    cols = parse_columns(body)
    names = [c[0] for c in cols]
    bool_cols = {c[0] for c in cols if c[1].lower().startswith("tinyint(1)")}
    chunks = []
    for icols, vals in extract_inserts(table):
        use = icols or names
        rendered = [to_pg_value(v, use[i] in bool_cols) for i, v in enumerate(vals)]
        chunks.append("INSERT INTO %s (%s) VALUES (%s);" % (table, ", ".join(use), ", ".join(rendered)))
    return "\n".join(chunks)


HEADER = """-- =====================================================================
-- V2 系统表基线 · 剩余系统表（补齐菜单树引用的全部表）
-- 来源：SmartAdmin v3.31 数据库SQL脚本/mysql/smart_admin_v3.sql
-- 转换目标：PostgreSQL 18（identity / BOOLEAN / TIMESTAMP / COMMENT）
--
-- 由 v2/tools/gen_v5_migration.py 生成，转换规则见 V1 头部说明。
--
-- 覆盖范围：SmartAdmin 菜单树中除 V1..V4 已建表之外引用的所有表，
-- 包括 系统设置(文件/定时任务/代码生成)、监控(心跳)、文档中心(更新日志/帮助文档/意见反馈)、
-- 消息通知、以及 OA 示例模块（菜单中存在对应页面）。
--
-- 种子数据策略：只保留真正的系统参考数据
--   t_notice_type(2) / t_mail_template(1) / t_smart_job(2)
-- 上游的演示内容（t_change_log 11 行、t_data_tracer 10 行、t_notice 12 行、
-- t_message 4 行、t_oa_* 及帮助文档正文）不迁移 —— V2 是干净基线，不是 demo 副本。
--
-- 有意保留的差异：
--   1. t_notice_visible_range 上游只有 UNIQUE INDEX uk_notice_data，无主键；
--      PG 保持无主键 + 唯一约束（与上游一致）。
--   2. t_notice_view_record / t_help_doc_view_record / t_help_doc_relation 使用
--      复合主键，PG 显式命名为 pk_<table>。
--   3. datetime ON UPDATE CURRENT_TIMESTAMP 不做触发器模拟（见 V4 头部）。
-- =====================================================================
"""


def main():
    parts = [HEADER]
    for t in TABLES:
        parts.append("-- " + "-" * 69)
        parts.append("-- %s" % t)
        parts.append("-- " + "-" * 69)
        parts.append(emit_ddl(t))
        parts.append("")
    for t in SEED_TABLES:
        seed = emit_seed(t)
        if seed.strip():
            parts.append("-- %s 种子数据" % t)
            parts.append(seed)
            parts.append("")

    # identity 序列校正
    parts.append("-- " + "-" * 69)
    parts.append("-- 校正 identity 序列（(MAX+1, is_called=false) 形式，空表从 1 开始）")
    parts.append("-- " + "-" * 69)
    for t in TABLES:
        body = ddl_body(t)
        for col, mtype, _, _, _ in parse_columns(body):
            if "AUTO_INCREMENT" in body_for_col(body, col):
                parts.append(
                    "SELECT setval(pg_get_serial_sequence('%s', '%s'), "
                    "(SELECT COALESCE(MAX(%s), 0) FROM %s) + 1, false);" % (t, col, col, t)
                )
    parts.append("")

    OUT.write_text("\n".join(parts).replace("\r\n", "\n"), encoding="utf-8", newline="\n")
    print("wrote %s (%d tables, %d seed tables)" % (OUT, len(TABLES), len(SEED_TABLES)))


if __name__ == "__main__":
    main()
