#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
SmartAdmin 系统表结构 diff：
  C 侧参考资产  project-reference-examples/xsy-scm/postgresql/01-系统基础表.sql  (44 表)
  对比对象      live PostgreSQL 的 xsy_v2 schema（= 当前 V1..V5 已验证行为）

严格只读：本脚本不写数据库、不写 migration。参考目录只读。

输出每张表一条结论：
  SAME                       完全一致
  INTENTIONAL_V2_DIFFERENCE  已声明的有意差异（见 KNOWN_DIFFS）
  POSSIBLE_DEFECT            V2 缺失 / 类型不一致 / 约束不一致

用法:
  python tools/verify_system_schema_diff.py [--json out.json]
"""
import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
C_SQL = ROOT / "project-reference-examples/xsy-scm/postgresql/01-系统基础表.sql"

PSQL = r"D:/PostgreSQL/bin/psql.exe"
DB = dict(host="127.0.0.1", port="15432", user="xsy_scm_app", dbname="xsy_scm", schema="xsy_v2")

# W0 已认定：SmartAdmin demo 业务表，当前 V2 无正式实体/菜单引用 -> 不迁
DEMO_TABLES = {"t_category", "t_goods"}

# 逐表裁决：已确认的 V2 有意差异。
# key = 表名，value = (理由, 该表允许出现的 detail 关键字元组)
# 只有当 details 全部命中关键字时，才把 POSSIBLE_DEFECT 降级为 INTENTIONAL_V2_DIFFERENCE。
ADJUDICATED_INTENTIONAL = {
    "t_config": ("V2 收紧 update_time 为 NOT NULL（写入路径由 MybatisPlusFillHandler 保证）；"
                 "config_key 提升为唯一约束（自然键，种子无重复）",
                 ("nullable update_time", "unique EXTRA in V2")),
    "t_department": ("V2 为 sort 补 DEFAULT 0，等价于 MySQL 非严格模式下的隐式默认值",
                     ("default sort",)),
    "t_dict_data": ("V2 为子表外键列 dict_id 补索引（V1 规则 7：显式命名索引）",
                    ("index EXTRA in V2",)),
    "t_employee": ("V2 为 disabled_flag/deleted_flag 补 DEFAULT FALSE；login_pwd 取上游 v3.31 的 "
                   "VARCHAR(100)（C 侧 255 来自线上库 alter，实测 argon2id 哈希 97 字符）；"
                   "另补 department_id / login_name 索引",
                   ("default deleted_flag", "default disabled_flag", "type login_pwd", "index EXTRA in V2")),
    "t_login_fail": ("V2 收紧 create_time / update_time 为 NOT NULL（写入路径由 MybatisPlusFillHandler 保证）",
                     ("nullable create_time", "nullable update_time")),
    "t_menu": ("V2 补 parent_id / menu_type 索引", ("index EXTRA in V2",)),
    "t_oa_enterprise_employee": (
        "D-1 方案 A（用户批准，V12）：enterprise_id / employee_id 取 Java 实体类型 BIGINT，"
        "与 t_oa_enterprise.enterprise_id / t_employee.employee_id 一致。"
        "C 侧的 varchar(100) 是上游 MySQL 线上库结构——MySQL 在 varchar 与 bigint 比较/JOIN 时"
        "隐式转数值，PostgreSQL 不会，故必须从 schema 根因修复，而不是在 mapper 里加 CAST。",
        ("type employee_id", "type enterprise_id")),
    "t_operate_log": ("V4 头部已声明：补 create_time 与 (operate_user_id, operate_user_type) 索引",
                      ("index EXTRA in V2",)),
    "t_reload_result": ("V4 头部已声明：上游无索引而唯一查询是 where tag = ?，补 (tag, create_time)",
                        ("index EXTRA in V2",)),
    "t_role_data_scope": ("V2 补 role_id 索引", ("index EXTRA in V2",)),
}


def psql(sql):
    """以 -At -F'\x1f' 执行只读查询并返回行列表。"""
    import os
    env = dict(os.environ)
    cmd = [PSQL, "-h", DB["host"], "-p", DB["port"], "-U", DB["user"],
           "-d", DB["dbname"], "-At", "-F", "\x1f", "-v", "ON_ERROR_STOP=1", "-c", sql]
    out = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8", env=env)
    if out.returncode != 0:
        raise SystemExit(f"psql failed:\n{out.stderr}")
    return [l.split("\x1f") for l in out.stdout.splitlines() if l != ""]


# --------------------------------------------------------------------------
# 1. 解析 C 侧参考 SQL
# --------------------------------------------------------------------------
RE_CREATE = re.compile(r'CREATE TABLE "([^"]+)" \((.*?)\n\);', re.S)
RE_INDEX = re.compile(r'CREATE (?:UNIQUE )?INDEX "([^"]+)" ON "([^"]+)" \(([^)]*)\)', re.S)


def parse_c_sql(text):
    tables = {}
    for m in RE_CREATE.finditer(text):
        name, body = m.group(1), m.group(2)
        cols, pk, uniques = [], [], []
        for raw in body.split("\n"):
            line = raw.strip().rstrip(",")
            if not line:
                continue
            if line.upper().startswith("PRIMARY KEY"):
                pk = re.findall(r'"([^"]+)"', line)
                continue
            if line.upper().startswith("CONSTRAINT"):
                cm = re.match(r'CONSTRAINT "([^"]+)" UNIQUE \((.*)\)', line)
                if cm:
                    uniques.append((cm.group(1), re.findall(r'"([^"]+)"', cm.group(2))))
                continue
            cm = re.match(r'"([^"]+)"\s+(.*)$', line)
            if not cm:
                continue
            col, rest = cm.group(1), cm.group(2)
            identity = "GENERATED BY DEFAULT AS IDENTITY" in rest.upper()
            rest_wo_ident = re.sub(r"GENERATED\s+BY\s+DEFAULT\s+AS\s+IDENTITY", "", rest, flags=re.I)
            notnull = bool(re.search(r"\bNOT NULL\b", rest_wo_ident, re.I))
            dm = re.search(r"\bDEFAULT\s+(.+?)(?:\s+(?:NOT NULL|GENERATED)\b|$)", rest_wo_ident, re.I)
            default = dm.group(1).strip() if dm else None
            tm = re.match(r"^([a-zA-Z]+(?:\([^)]*\))?)", rest_wo_ident)
            cols.append(dict(name=col, type=(tm.group(1) if tm else "").lower(),
                             notnull=notnull, default=default, identity=identity))
        # 行内 UNIQUE (col) 形式
        for um in re.finditer(r'(?:^|\n)\s*UNIQUE \((.*?)\)', body):
            uniques.append((None, re.findall(r'"([^"]+)"', um.group(1))))
        tables[name] = dict(columns=cols, pk=sorted(pk),
                            uniques=sorted([sorted(c) for _, c in uniques]), indexes=[])
    for m in RE_INDEX.finditer(text):
        iname, tname, cols = m.group(1), m.group(2), re.findall(r'"([^"]+)"', m.group(3))
        if tname in tables:
            tables[tname]["indexes"].append((iname, sorted(cols)))
    for t in tables.values():
        t["indexes"].sort()
    return tables


# --------------------------------------------------------------------------
# 2. 从 live PG 读取 V2 事实
# --------------------------------------------------------------------------
def read_v2():
    cols = psql(f"""
        SELECT table_name, column_name, data_type,
               COALESCE(character_maximum_length::text,''), is_nullable,
               COALESCE(column_default,''), is_identity
        FROM information_schema.columns
        WHERE table_schema='{DB['schema']}'
        ORDER BY table_name, ordinal_position
    """)
    tables = {}
    for tn, cn, dt, len_, nullable, dflt, ident in cols:
        t = tables.setdefault(tn, dict(columns=[], pk=[], uniques=[], indexes=[]))
        t["columns"].append(dict(name=cn, type=dt + (f"({len_})" if len_ else ""),
                                 notnull=(nullable == "NO"), default=dflt or None,
                                 identity=(ident == "YES")))
    cons = psql(f"""
        SELECT c.relname AS tbl, con.contype, con.conname,
               (SELECT string_agg(a.attname, ',' ORDER BY a.attname)
                  FROM unnest(con.conkey) k JOIN pg_attribute a
                    ON a.attrelid=con.conrelid AND a.attnum=k)
        FROM pg_constraint con JOIN pg_class c ON c.oid=con.conrelid
        JOIN pg_namespace n ON n.oid=c.relnamespace
        WHERE n.nspname='{DB['schema']}' AND con.contype IN ('p','u')
    """)
    for tbl, ctype, cname, colstr in cons:
        if tbl not in tables:
            continue
        c = sorted((colstr or "").split(","))
        if ctype == "p":
            tables[tbl]["pk"] = c
        else:
            tables[tbl]["uniques"].append(c)
    idx = psql(f"""
        SELECT tablename, indexname,
               (SELECT string_agg(a.attname, ',' ORDER BY a.attname)
                  FROM pg_index i JOIN pg_attribute a
                    ON a.attrelid=i.indrelid AND a.attnum=ANY(i.indkey)
                 WHERE i.indexrelid=pg_class.oid)
        FROM pg_indexes JOIN pg_class ON pg_class.relname=indexname
        WHERE schemaname='{DB['schema']}'
          AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conname=pg_class.relname)
    """)
    for tbl, iname, colstr in idx:
        if tbl in tables:
            tables[tbl]["indexes"].append((iname, sorted((colstr or "").split(","))))
    for t in tables.values():
        t["uniques"].sort()
        t["indexes"].sort()
    return tables


# --------------------------------------------------------------------------
# 3. 类型归一
# --------------------------------------------------------------------------
def norm_type(t):
    """把两种合法取舍归一，避免把有意的 BOOLEAN 取舍误报为差异。

    C  : tinyint / tinyint(1) -> SMALLINT
    V2 : tinyint(1) 0/1       -> BOOLEAN ; 其他 tinyint -> SMALLINT
    两者都正确，故统一归到同一"类型族"。
    """
    t = re.sub(r"\s+", " ", t.lower().strip())
    if t in ("smallint", "int2", "boolean", "bool"):
        return "BOOL_OR_SMALLINT"
    if t in ("timestamp without time zone", "timestamp"):
        return "TIMESTAMP"
    if t in ("character varying", "varchar"):
        return "VARCHAR"
    if t.startswith("character varying(") or t.startswith("varchar("):
        return "VARCHAR" + t[t.index("("):]
    return t


RE_NULL_CAST = re.compile(r"^NULL::[a-z ]+(\(\d+\))?$", re.I)
RE_STR_CAST = re.compile(r"^(.*?)::(character varying|text|varchar)(\(\d+\))?$", re.I)


def norm_default(d, coltype):
    """归一默认值写法：NULL / 'x'::type / 0|false / CURRENT_TIMESTAMP|now()。"""
    if d is None:
        return None
    s = d.strip()
    if s == "" or RE_NULL_CAST.match(s) or s.upper() == "NULL":
        return None
    m = RE_STR_CAST.match(s)
    if m:
        s = m.group(1).strip()
    if re.fullmatch(r"CURRENT_TIMESTAMP|now\(\)|NOW", s, re.I):
        return "NOW"
    s = s.strip()
    if s.startswith("'") and s.endswith("'"):
        inner = s[1:-1].replace("''", "'")
        # BOOLEAN 族：'0'/'1' 与 false/true 等价
        if coltype == "BOOL_OR_SMALLINT" and inner in ("0", "1"):
            return inner
        return inner
    if s.lower() in ("true", "false"):
        if coltype == "BOOL_OR_SMALLINT":
            return "1" if s.lower() == "true" else "0"
        return s.lower()
    if re.fullmatch(r"0\.0+", s):
        return "0"
    return s


def col_key(c):
    return c["name"]


# --------------------------------------------------------------------------
# 4. 比较
# --------------------------------------------------------------------------
def compare(c_tables, v2_tables):
    report = []
    for tname in sorted(c_tables):
        c = c_tables[tname]
        if tname in DEMO_TABLES:
            report.append(dict(table=tname, verdict="INTENTIONAL_V2_DIFFERENCE",
                               reason="SmartAdmin demo 业务表，W0 已认定不迁（V2 由 product_* 取代）",
                               details=[]))
            continue
        if tname not in v2_tables:
            report.append(dict(table=tname, verdict="POSSIBLE_DEFECT",
                               reason="V2 缺失该表", details=[]))
            continue
        v = v2_tables[tname]
        details = []
        cmap = {c["name"]: c for c in c["columns"]}
        vmap = {c["name"]: c for c in v["columns"]}
        for cn in sorted(set(cmap) | set(vmap)):
            if cn not in vmap:
                details.append(f"column MISSING in V2: {cn} ({cmap[cn]['type']})")
                continue
            if cn not in cmap:
                details.append(f"column EXTRA in V2: {cn} ({vmap[cn]['type']})")
                continue
            a, b = cmap[cn], vmap[cn]
            ta, tb = norm_type(a["type"]), norm_type(b["type"])
            if ta != tb:
                details.append(f"type {cn}: C={a['type']} V2={b['type']}")
            if a["notnull"] != b["notnull"]:
                details.append(f"nullable {cn}: C={'NOT NULL' if a['notnull'] else 'NULL'} "
                               f"V2={'NOT NULL' if b['notnull'] else 'NULL'}")
            # identity 列的隐式默认值不参与比较
            if a["identity"] and b["identity"]:
                pass
            elif a["identity"] != b["identity"]:
                details.append(f"identity {cn}: C={a['identity']} V2={b['identity']}")
            else:
                da = norm_default(a["default"], ta)
                db_ = norm_default(b["default"], tb)
                if da != db_:
                    details.append(f"default {cn}: C={a['default']!r} V2={b['default']!r}")
        if c["pk"] != v["pk"]:
            details.append(f"pk: C={c['pk']} V2={v['pk']}")
        cu, vu = set(map(tuple, c["uniques"])), set(map(tuple, v["uniques"]))
        for x in sorted(cu - vu):
            details.append(f"unique MISSING in V2: {list(x)}")
        for x in sorted(vu - cu):
            details.append(f"unique EXTRA in V2: {list(x)}")
        ci = {(n, tuple(cs)) for n, cs in c["indexes"]}
        vi = {(n, tuple(cs)) for n, cs in v["indexes"]}
        for x in sorted(ci - vi):
            # 索引名在 PG 内全局唯一，C 侧重名时被改名为 表名_原名，需按列组合比对
            if not any(cols == x[1] for _, cols in vi):
                details.append(f"index MISSING in V2: {x[0]}{list(x[1])}")
        for x in sorted(vi - ci):
            if not any(cols == x[1] for _, cols in ci):
                details.append(f"index EXTRA in V2: {x[0]}{list(x[1])}")

        verdict = "SAME" if not details else "POSSIBLE_DEFECT"
        reason = "" if verdict == "SAME" else "见 details"
        if verdict == "POSSIBLE_DEFECT" and tname in ADJUDICATED_INTENTIONAL:
            adj_reason, allowed = ADJUDICATED_INTENTIONAL[tname]
            if all(any(a in d for a in allowed) for d in details):
                verdict = "INTENTIONAL_V2_DIFFERENCE"
                reason = adj_reason
        report.append(dict(table=tname, verdict=verdict, reason=reason, details=details))
    return report


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--json")
    args = ap.parse_args()

    text = C_SQL.read_text(encoding="utf-8")
    c_tables = parse_c_sql(text)
    v2_tables = read_v2()

    report = compare(c_tables, v2_tables)
    order = {"POSSIBLE_DEFECT": 0, "INTENTIONAL_V2_DIFFERENCE": 1, "SAME": 2}
    report.sort(key=lambda r: (order[r["verdict"]], r["table"]))

    n_defect = sum(1 for r in report if r["verdict"] == "POSSIBLE_DEFECT")
    n_intent = sum(1 for r in report if r["verdict"] == "INTENTIONAL_V2_DIFFERENCE")
    n_same = sum(1 for r in report if r["verdict"] == "SAME")

    print(f"C 参考表数 = {len(c_tables)}   V2 实测 t_* 表数 = "
          f"{len([t for t in v2_tables if t.startswith('t_')])}")
    print(f"SAME={n_same}  INTENTIONAL_V2_DIFFERENCE={n_intent}  POSSIBLE_DEFECT={n_defect}")
    print("-" * 72)
    for r in report:
        if r["verdict"] == "SAME":
            continue
        print(f"[{r['verdict']}] {r['table']}")
        if r["reason"]:
            print(f"    reason: {r['reason']}")
        for d in r["details"][:40]:
            print(f"    - {d}")
        if len(r["details"]) > 40:
            print(f"    ... ({len(r['details'])} total)")
    print("-" * 72)
    print("SAME 表: " + ", ".join(r["table"] for r in report if r["verdict"] == "SAME"))

    if args.json:
        Path(args.json).write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"\nJSON -> {args.json}")

    return 1 if n_defect else 0


if __name__ == "__main__":
    sys.exit(main())
