-- ADM-12 3-12a：客户余额核心账本（追加式流水）。
--
-- 口径（ADR-009 + 负责人 2026-10-03 裁决）：
--   * **余额不落"当前值"字段**。账户表只作稳定的**并发锁锚点**；余额恒等于
--     SUM(CREDIT) − SUM(DEBIT)，是流水推导出来的，不是维护出来的。
--   * 流水**append-only**：改余额靠追加一条反向流水，绝不 UPDATE/DELETE 历史行。
--   * 金额恒正、方向独立表达（CREDIT / DEBIT），与 Finance 的 `quantity 恒正 + 方向编码在类型里`
--     同一套风格。
--   * 钱包归属**结算主体**（`settlement_customer_id`）：集团下属单位共享集团的钱包，
--     同时流水保留实际业务客户（`customer_id`）以便追溯是哪家单位花的。
--
-- 与 Finance 的边界（本片刻意不跨越）：
--   * 余额消费**不是新的实际资金进入**，因此**不生成** `finance_receipt`。
--     充值 100 时渠道真实收到 100，已经有一条 ONLINE_PAYMENT 收款；之后用余额买 60
--     若再记一条收款，账上就有 160 而公司只进来 100 —— 同一笔钱记两遍。
--   * 因此 3-11a 预埋的 `BALANCE` 收款方式已在本片撤销。
--   * 本片**不接** PaymentIntent.BALANCE、不接 FinanceWriteOff、不接余额退款资金事实。

-- ============================================================================
-- 1. customer_balance_account —— 钱包账户（锁锚点，**不存余额**）
-- ============================================================================
CREATE TABLE customer_balance_account (
    id                               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 钱包所有者是**结算主体**：集团下属单位共用集团钱包
    settlement_customer_id           BIGINT       NOT NULL,
    settlement_customer_name_snapshot VARCHAR(150) NOT NULL
        CHECK (btrim(settlement_customer_name_snapshot) <> ''),
    -- 刻意**没有** balance 字段：余额由流水汇总，存一份就会与流水漂移
    version                          INTEGER      NOT NULL DEFAULT 0 CHECK (version >= 0),
    deleted                          BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at                       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by                       VARCHAR(64),
    updated_by                       VARCHAR(64)
);
-- 一个结算主体一个钱包
CREATE UNIQUE INDEX uk_customer_balance_account_settlement
    ON customer_balance_account (settlement_customer_id) WHERE deleted = FALSE;

-- ============================================================================
-- 2. customer_balance_movement —— 余额流水（append-only）
-- ============================================================================
CREATE TABLE customer_balance_movement (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_no            VARCHAR(64)  NOT NULL CHECK (btrim(movement_no) <> ''),
    account_id             BIGINT       NOT NULL,
    settlement_customer_id BIGINT       NOT NULL,
    -- 本次业务发生在哪个客户：集团场景下与钱包所有者不同，用于追溯
    customer_id            BIGINT,
    type                   VARCHAR(16)  NOT NULL
        CONSTRAINT ck_customer_balance_movement_type CHECK (
            type IN ('RECHARGE', 'CONSUME', 'REFUND', 'CORRECTION')),
    direction              VARCHAR(8)   NOT NULL
        CONSTRAINT ck_customer_balance_movement_direction CHECK (direction IN ('CREDIT', 'DEBIT')),
    -- 金额恒正，方向由 direction 表达（与 Finance 的数量/方向纪律一致）
    amount                 NUMERIC(18, 4) NOT NULL CHECK (amount > 0),
    source_type            VARCHAR(32),
    source_id              BIGINT,
    reason                 VARCHAR(500),
    occurred_at            TIMESTAMPTZ  NOT NULL,
    version                INTEGER      NOT NULL DEFAULT 0 CHECK (version >= 0),
    deleted                BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by             VARCHAR(64),
    updated_by             VARCHAR(64),
    -- 类型与方向的合法组合：充值只能进、消费只能出、退款只能进；更正两个方向都可以
    CONSTRAINT ck_customer_balance_movement_type_direction CHECK (
        (type = 'RECHARGE' AND direction = 'CREDIT')
            OR (type = 'CONSUME' AND direction = 'DEBIT')
            OR (type = 'REFUND' AND direction = 'CREDIT')
            OR (type = 'CORRECTION')
        ),
    -- 来源要么都空、要么都齐（人工更正没有来源）
    CONSTRAINT ck_customer_balance_movement_source_pairing CHECK (
        (source_type IS NULL AND source_id IS NULL)
            OR (source_type IS NOT NULL AND source_id IS NOT NULL)
        ),
    -- 来源类型白名单：不允许自由填写，否则下面的来源唯一索引形同虚设
    CONSTRAINT ck_customer_balance_movement_source_type CHECK (
        source_type IS NULL OR source_type IN ('PAYMENT_TRANSACTION', 'ORDER_REFUND')
        ),
    -- 人工更正必须写原因：动的是客户的钱，没有理由的更正不可接受
    CONSTRAINT ck_customer_balance_movement_correction_reason CHECK (
        type <> 'CORRECTION' OR btrim(COALESCE(reason, '')) <> ''
        ),
    -- append-only：改余额靠追加反向流水，不靠改历史
    CONSTRAINT ck_customer_balance_movement_append_only CHECK (deleted = FALSE)
);
CREATE UNIQUE INDEX uk_customer_balance_movement_no
    ON customer_balance_movement (movement_no) WHERE deleted = FALSE;
-- 来源唯一：同一笔支付交易只能充值一次、同一张退款单只能返还一次。
-- 重复回调靠它兜住，与 Finance 侧的来源键同一套纪律。
CREATE UNIQUE INDEX uk_customer_balance_movement_source
    ON customer_balance_movement (source_type, source_id)
    WHERE deleted = FALSE AND source_type IS NOT NULL;
-- 对账与列表的主查询路径：按账户倒序取最近流水
CREATE INDEX idx_customer_balance_movement_account
    ON customer_balance_movement (account_id, occurred_at DESC, id DESC) WHERE deleted = FALSE;
CREATE INDEX idx_customer_balance_movement_settlement
    ON customer_balance_movement (settlement_customer_id, occurred_at DESC) WHERE deleted = FALSE;
-- 追溯「哪家下属单位花掉的」
CREATE INDEX idx_customer_balance_movement_customer
    ON customer_balance_movement (customer_id) WHERE deleted = FALSE AND customer_id IS NOT NULL;

CREATE SEQUENCE customer_balance_movement_seq;

COMMENT ON TABLE customer_balance_account IS
    'ADM-12 3-12a 客户余额账户：锁锚点，**不存余额**（余额 = CREDIT − DEBIT 流水汇总）';
COMMENT ON TABLE customer_balance_movement IS
    'ADM-12 3-12a 客户余额流水（append-only）：金额恒正、方向独立表达';
COMMENT ON COLUMN customer_balance_movement.settlement_customer_id IS
    '钱包所有者（结算主体）；集团下属单位共用集团钱包';
COMMENT ON COLUMN customer_balance_movement.customer_id IS
    '本次业务实际发生的客户；用于追溯是哪家下属单位花掉的';
