-- ADM-12 3-12b：在线充值。
--
-- 链路：
--   POST /scm/balance/recharge/create → customer_balance_recharge（业务事实）
--        → PaymentIntent（method=ONLINE、source_type=BALANCE_RECHARGE、source_id=recharge.id）
--        → PaymentTransaction SUCCEEDED
--        ├─ FinanceReceipt   ONLINE_PAYMENT + PAYMENT_TRANSACTION  ← 公司实际进账
--        └─ BalanceMovement  RECHARGE/CREDIT + PAYMENT_TRANSACTION ← 钱包权益增加
--
-- 两条事实回答两个不同问题，**不是重复记账**：
--   FinanceReceipt   ：公司实际收了多少钱
--   BalanceMovement  ：这笔钱当前有多少还能作为钱包权益使用
--
-- 为什么 source_id 不指 customer / settlementCustomer / balanceAccount：
--   同一集团连续充 100、200、500，三次支付的业务来源会是同一个客户 ID —— 既回答不了
--   「这笔 PaymentIntent 是哪一次充值」，也没法对单次充值做幂等与审计。
--   因此新增一条独立的充值事实，source_id 指向它。

-- ============================================================================
-- 1. customer_balance_recharge —— 充值请求事实（**只有业务身份，没有支付状态机**）
-- ============================================================================
-- 刻意没有 CREATED / PAYING / SUCCESS / FAILED：那些状态已经由 PaymentIntent 与
-- PaymentTransaction 表达。这张表只回答「谁准备往哪个钱包充多少钱、业务编号是什么」。
-- 再造一套状态机就会出现「两个地方都说自己知道充值成没成功」。
CREATE SEQUENCE customer_balance_recharge_seq;

CREATE TABLE customer_balance_recharge (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recharge_no            VARCHAR(64)  NOT NULL CHECK (btrim(recharge_no) <> ''),
    -- 钱包所有者：集团下属单位充值进集团钱包
    settlement_customer_id BIGINT       NOT NULL,
    settlement_customer_name_snapshot VARCHAR(150) NOT NULL
        CHECK (btrim(settlement_customer_name_snapshot) <> ''),
    -- 实际发起充值的业务客户（用于追溯是哪家单位充的）
    customer_id            BIGINT       NOT NULL,
    customer_name_snapshot VARCHAR(150) NOT NULL CHECK (btrim(customer_name_snapshot) <> ''),
    amount                 NUMERIC(18, 4) NOT NULL CHECK (amount > 0),
    remark                 VARCHAR(500),
    version                INTEGER      NOT NULL DEFAULT 0 CHECK (version >= 0),
    deleted                BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by             VARCHAR(64),
    updated_by             VARCHAR(64)
);
CREATE UNIQUE INDEX uk_customer_balance_recharge_no
    ON customer_balance_recharge (recharge_no) WHERE deleted = FALSE;
CREATE INDEX idx_customer_balance_recharge_settlement
    ON customer_balance_recharge (settlement_customer_id, created_at DESC) WHERE deleted = FALSE;

-- ============================================================================
-- 2. payment_intent.source_type 扩白名单
-- ============================================================================
ALTER TABLE payment_intent DROP CONSTRAINT ck_payment_intent_source_type;
ALTER TABLE payment_intent ADD CONSTRAINT ck_payment_intent_source_type
    CHECK (source_type IN ('SALES_ORDER', 'BALANCE_RECHARGE'));

-- ============================================================================
-- 3. 一条充值请求只能创建一个 PaymentIntent
-- ============================================================================
-- **只针对充值来源**：销售订单完全可能拆成多次支付（订单 500 → 在线付 300 + 再付 200），
-- 给整张表的 (source_type, source_id) 加唯一会把正常业务堵死。
-- 客户端超时重试靠 Idempotency-Key 回放，这里是数据库层的最终兜底。
CREATE UNIQUE INDEX uk_payment_intent_balance_recharge
    ON payment_intent (source_type, source_id)
    WHERE deleted = FALSE AND source_type = 'BALANCE_RECHARGE';

COMMENT ON TABLE customer_balance_recharge IS
    'ADM-12 3-12b 充值请求事实：只有业务身份，支付状态由 PaymentIntent/Transaction 表达';
COMMENT ON COLUMN customer_balance_recharge.settlement_customer_id IS
    '钱包所有者（结算主体）；集团下属单位充值进集团钱包';

-- ============================================================================
-- 4. 3-12b 权限（只落按钮权限，继续不建页面菜单）
-- ============================================================================
-- menu_id 已核对：1710–1717 支付、1718–1721 余额，1722 起空闲。
-- 3-12a 刻意没预占 recharge 权限；本片真的开放了充值入口，现在才落。
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type,
                   api_perms, web_perms, icon, context_menu_id, visible_flag, create_user_id)
VALUES (1722, '余额充值', 3, 1718, 1722, NULL, NULL, 1,
        'scm:balance:recharge', 'scm:balance:recharge', NULL, NULL, TRUE, 1)
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO t_role_menu(role_id, menu_id)
SELECT 1, 1722
WHERE NOT EXISTS (SELECT 1 FROM t_role_menu rm WHERE rm.role_id = 1 AND rm.menu_id = 1722);

SELECT setval(pg_get_serial_sequence('t_menu', 'menu_id'), (SELECT MAX(menu_id) + 1 FROM t_menu), false);
