-- W4 Sales Order, approved 2026-09-16. PostgreSQL; no foreign keys.
-- Global sequences never reset daily; formatting pads to at least six digits.
CREATE SEQUENCE sales_order_no_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE order_return_no_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE order_refund_no_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE sales_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    customer_id BIGINT NOT NULL,
    customer_code_snapshot VARCHAR(64) NOT NULL,
    customer_name_snapshot VARCHAR(150) NOT NULL,
    order_source VARCHAR(20) NOT NULL DEFAULT 'ADMIN',
    original_order_id BIGINT,
    supplement_reason VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    ordered_total_amount NUMERIC(18,4),
    settlement_total_amount NUMERIC(18,4),
    settle_mode_snapshot VARCHAR(20) NOT NULL,
    expect_delivery_time TIMESTAMPTZ,
    seller_id BIGINT,
    remark VARCHAR(500),
    cancel_reason VARCHAR(500),
    submitted_at TIMESTAMPTZ,
    confirmed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64), updated_by VARCHAR(64),
    CONSTRAINT ck_sales_order_source CHECK (order_source IN ('ADMIN', 'MALL', 'SUPPLEMENT')),
    CONSTRAINT ck_sales_order_status CHECK (status IN ('DRAFT', 'PENDING', 'CONFIRMED', 'CANCELLED')),
    CONSTRAINT ck_sales_order_supplement CHECK (
        (order_source <> 'SUPPLEMENT' AND original_order_id IS NULL AND supplement_reason IS NULL)
        OR (order_source = 'SUPPLEMENT' AND supplement_reason IS NOT NULL AND btrim(supplement_reason) <> '')
    ),
    CONSTRAINT ck_sales_order_ordered_total_amount CHECK (ordered_total_amount >= 0),
    CONSTRAINT ck_sales_order_settlement_total_amount CHECK (settlement_total_amount IS NULL OR settlement_total_amount >= 0),
    CONSTRAINT ck_sales_order_cancel_reason CHECK (status <> 'CANCELLED' OR (cancel_reason IS NOT NULL AND btrim(cancel_reason) <> '')),
    CONSTRAINT ck_sales_order_version CHECK (version >= 0)
);

CREATE TABLE sales_order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    spu_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    spu_code_snapshot VARCHAR(64) NOT NULL,
    product_name_snapshot VARCHAR(150) NOT NULL,
    sku_code_snapshot VARCHAR(64) NOT NULL,
    spec_name_snapshot VARCHAR(150) NOT NULL,
    spec_values_snapshot JSONB NOT NULL DEFAULT '{}'::JSONB,
    sale_unit_snapshot VARCHAR(32) NOT NULL,
    product_type_snapshot VARCHAR(20) NOT NULL,
    ordered_quantity NUMERIC(18,4) NOT NULL,
    actual_quantity NUMERIC(18,4),
    actual_quantity_source VARCHAR(20),
    actual_quantity_reason VARCHAR(500),
    draft_unit_price NUMERIC(18,4),
    draft_price_source VARCHAR(20),
    draft_price_source_id BIGINT,
    manual_price_override BOOLEAN NOT NULL DEFAULT FALSE,
    manual_price_reason VARCHAR(500),
    locked_unit_price NUMERIC(18,4),
    locked_price_source VARCHAR(20),
    locked_price_source_id BIGINT,
    ordered_line_amount NUMERIC(18,4),
    settlement_line_amount NUMERIC(18,4),
    sort_order INTEGER NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64), updated_by VARCHAR(64),
    CONSTRAINT ck_sales_order_item_spec_values CHECK (jsonb_typeof(spec_values_snapshot) = 'object'),
    CONSTRAINT ck_sales_order_item_product_type CHECK (product_type_snapshot IN ('STANDARD', 'NON_STANDARD')),
    CONSTRAINT ck_sales_order_item_ordered_quantity CHECK (ordered_quantity > 0),
    CONSTRAINT ck_sales_order_item_actual_quantity CHECK (actual_quantity IS NULL OR actual_quantity > 0),
    CONSTRAINT ck_sales_order_item_actual_source CHECK (actual_quantity_source IS NULL OR actual_quantity_source IN ('SYSTEM', 'MANUAL')),
    -- 修 A-D11：MANUAL 必须有 reason；非 MANUAL 不得有 reason
    CONSTRAINT ck_sales_order_item_actual_reason CHECK (
        (actual_quantity_source = 'MANUAL' AND actual_quantity_reason IS NOT NULL AND btrim(actual_quantity_reason) <> '')
        OR (actual_quantity_source IS DISTINCT FROM 'MANUAL' AND actual_quantity_reason IS NULL)
    ),
    CONSTRAINT ck_sales_order_item_draft_price CHECK (draft_unit_price >= 0),
    -- 修 A-D1：白名单补全 CUSTOMER_TYPE（A 源 V4 漏了）
    CONSTRAINT ck_sales_order_item_draft_source CHECK (draft_price_source IN ('AGREEMENT', 'CUSTOMER_TYPE', 'MARKET', 'OVERRIDE')),
    CONSTRAINT ck_sales_order_item_draft_pair CHECK ((draft_unit_price IS NULL) = (draft_price_source IS NULL)),
    CONSTRAINT ck_sales_order_item_draft_amount CHECK ((draft_unit_price IS NULL) = (ordered_line_amount IS NULL)),
    CONSTRAINT ck_sales_order_item_manual_price CHECK (
        (manual_price_override = FALSE AND draft_price_source IS DISTINCT FROM 'OVERRIDE' AND manual_price_reason IS NULL)
        OR (manual_price_override = TRUE AND draft_unit_price IS NOT NULL AND draft_price_source IS NOT NULL AND draft_price_source = 'OVERRIDE'
            AND manual_price_reason IS NOT NULL AND btrim(manual_price_reason) <> '')
    ),
    CONSTRAINT ck_sales_order_item_locked_price CHECK (locked_unit_price IS NULL OR locked_unit_price >= 0),
    CONSTRAINT ck_sales_order_item_locked_source CHECK (locked_price_source IS NULL OR locked_price_source IN ('AGREEMENT', 'CUSTOMER_TYPE', 'MARKET', 'OVERRIDE')),
    CONSTRAINT ck_sales_order_item_ordered_line_amount CHECK (ordered_line_amount >= 0),
    CONSTRAINT ck_sales_order_item_settlement_line_amount CHECK (settlement_line_amount IS NULL OR settlement_line_amount >= 0),
    CONSTRAINT ck_sales_order_item_version CHECK (version >= 0)
);

CREATE TABLE order_address_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    receiver_name VARCHAR(100) NOT NULL,
    receiver_phone VARCHAR(32) NOT NULL,
    address VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64)
);

CREATE TABLE order_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    operation_type VARCHAR(40) NOT NULL,
    operator VARCHAR(64) NOT NULL,
    reason VARCHAR(500),
    before_data JSONB,
    after_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    CONSTRAINT ck_order_operation_log_type CHECK (
        operation_type IN ('CREATE', 'UPDATE', 'SUBMIT', 'ACTUAL_QUANTITY', 'CONFIRM', 'CANCEL')
    ),
    CONSTRAINT ck_order_operation_log_before_data CHECK (before_data IS NULL OR jsonb_typeof(before_data) = 'object'),
    CONSTRAINT ck_order_operation_log_after_data CHECK (after_data IS NULL OR jsonb_typeof(after_data) = 'object')
);

CREATE TABLE idempotency_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_scope VARCHAR(100) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_hash VARCHAR(128) NOT NULL,
    result_type VARCHAR(100),
    result_id BIGINT,
    result_data JSONB,
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64), updated_by VARCHAR(64),
    CONSTRAINT ck_idempotency_record_result_data CHECK (result_data IS NULL OR jsonb_typeof(result_data) = 'object'),
    CONSTRAINT ck_idempotency_record_version CHECK (version >= 0)
);

CREATE TABLE order_return (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_no VARCHAR(64) NOT NULL,
    order_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    reason VARCHAR(500) NOT NULL,
    decision_reason VARCHAR(500),
    approved_amount NUMERIC(18,4) NOT NULL DEFAULT 0,
    approved_at TIMESTAMPTZ, rejected_at TIMESTAMPTZ, cancelled_at TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64), updated_by VARCHAR(64),
    CONSTRAINT ck_order_return_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT ck_order_return_reason CHECK (btrim(reason) <> ''),
    CONSTRAINT ck_order_return_decision_reason CHECK (
        status NOT IN ('REJECTED', 'CANCELLED') OR (decision_reason IS NOT NULL AND btrim(decision_reason) <> '')
    ),
    CONSTRAINT ck_order_return_approved_amount CHECK (approved_amount >= 0),
    CONSTRAINT ck_order_return_version CHECK (version >= 0)
);

CREATE TABLE order_return_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    requested_quantity NUMERIC(18,4) NOT NULL,
    approved_quantity NUMERIC(18,4),
    locked_unit_price NUMERIC(18,4) NOT NULL,
    approved_amount NUMERIC(18,4) NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64), updated_by VARCHAR(64),
    CONSTRAINT ck_order_return_item_requested_quantity CHECK (requested_quantity > 0),
    CONSTRAINT ck_order_return_item_approved_quantity CHECK (approved_quantity IS NULL OR (approved_quantity >= 0 AND approved_quantity <= requested_quantity)),
    CONSTRAINT ck_order_return_item_locked_price CHECK (locked_unit_price >= 0),
    CONSTRAINT ck_order_return_item_approved_amount CHECK (approved_amount >= 0),
    CONSTRAINT ck_order_return_item_version CHECK (version >= 0)
);

CREATE TABLE order_refund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_no VARCHAR(64) NOT NULL,
    return_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    refund_amount NUMERIC(18,4) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    external_reference VARCHAR(128),
    completed_at TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64), updated_by VARCHAR(64),
    CONSTRAINT ck_order_refund_amount CHECK (refund_amount > 0),
    CONSTRAINT ck_order_refund_status CHECK (status IN ('PENDING', 'COMPLETED')),
    CONSTRAINT ck_order_refund_completion CHECK (
        (status = 'PENDING' AND completed_at IS NULL) OR (status = 'COMPLETED' AND completed_at IS NOT NULL)
    ),
    CONSTRAINT ck_order_refund_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_sales_order_no_active ON sales_order (order_no) WHERE deleted = FALSE;
CREATE INDEX idx_sales_order_customer_created ON sales_order (customer_id, created_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_sales_order_status_created ON sales_order (status, created_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_sales_order_original_order_id ON sales_order (original_order_id) WHERE original_order_id IS NOT NULL;
CREATE INDEX idx_sales_order_source_created ON sales_order (order_source, created_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_sales_order_item_order_id ON sales_order_item (order_id, sort_order) WHERE deleted = FALSE;
CREATE INDEX idx_sales_order_item_sku_id ON sales_order_item (sku_id) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_sales_order_item_order_sku_active ON sales_order_item (order_id, sku_id) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_order_address_snapshot_order ON order_address_snapshot (order_id);
CREATE INDEX idx_order_address_snapshot_customer ON order_address_snapshot (customer_id, created_at DESC);
CREATE INDEX idx_order_operation_log_order_created ON order_operation_log (order_id, created_at DESC);
CREATE INDEX idx_order_operation_log_type_created ON order_operation_log (operation_type, created_at DESC);
CREATE UNIQUE INDEX uk_idempotency_record_scope_key_active ON idempotency_record (operation_scope, idempotency_key) WHERE deleted = FALSE;
CREATE INDEX idx_idempotency_record_created ON idempotency_record (created_at DESC);
CREATE UNIQUE INDEX uk_order_return_no_active ON order_return (return_no) WHERE deleted = FALSE;
CREATE INDEX idx_order_return_order_id ON order_return (order_id, created_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_order_return_status_created ON order_return (status, created_at DESC) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_order_return_item_active ON order_return_item (return_id, order_item_id) WHERE deleted = FALSE;
CREATE INDEX idx_order_return_item_return_id ON order_return_item (return_id) WHERE deleted = FALSE;
CREATE INDEX idx_order_return_item_order_item_id ON order_return_item (order_item_id) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_order_refund_no_active ON order_refund (refund_no) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_order_refund_return_active ON order_refund (return_id) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_order_refund_external_reference_active ON order_refund (external_reference) WHERE deleted = FALSE AND external_reference IS NOT NULL;
CREATE INDEX idx_order_refund_order_id ON order_refund (order_id, created_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_order_refund_status_created ON order_refund (status, created_at DESC) WHERE deleted = FALSE;
COMMENT ON TABLE sales_order IS 'W4 销售订单域：sales_order';
COMMENT ON COLUMN sales_order.id IS '订单域 id';
COMMENT ON COLUMN sales_order.order_no IS '订单域 order_no';
COMMENT ON COLUMN sales_order.customer_id IS '订单域 customer_id';
COMMENT ON COLUMN sales_order.customer_code_snapshot IS '订单域 customer_code_snapshot';
COMMENT ON COLUMN sales_order.customer_name_snapshot IS '订单域 customer_name_snapshot';
COMMENT ON COLUMN sales_order.order_source IS '订单域 order_source';
COMMENT ON COLUMN sales_order.original_order_id IS '订单域 original_order_id';
COMMENT ON COLUMN sales_order.supplement_reason IS '订单域 supplement_reason';
COMMENT ON COLUMN sales_order.status IS '订单域 status';
COMMENT ON COLUMN sales_order.ordered_total_amount IS '订单域 ordered_total_amount';
COMMENT ON COLUMN sales_order.settlement_total_amount IS '订单域 settlement_total_amount';
COMMENT ON COLUMN sales_order.settle_mode_snapshot IS '订单域 settle_mode_snapshot';
COMMENT ON COLUMN sales_order.expect_delivery_time IS '订单域 expect_delivery_time';
COMMENT ON COLUMN sales_order.seller_id IS '订单域 seller_id';
COMMENT ON COLUMN sales_order.remark IS '订单域 remark';
COMMENT ON COLUMN sales_order.cancel_reason IS '订单域 cancel_reason';
COMMENT ON COLUMN sales_order.submitted_at IS '订单域 submitted_at';
COMMENT ON COLUMN sales_order.confirmed_at IS '订单域 confirmed_at';
COMMENT ON COLUMN sales_order.cancelled_at IS '订单域 cancelled_at';
COMMENT ON COLUMN sales_order.version IS '订单域 version';
COMMENT ON COLUMN sales_order.deleted IS '订单域 deleted';
COMMENT ON COLUMN sales_order.created_at IS '订单域 created_at';
COMMENT ON COLUMN sales_order.updated_at IS '订单域 updated_at';
COMMENT ON COLUMN sales_order.created_by IS '订单域 created_by';
COMMENT ON TABLE sales_order_item IS 'W4 销售订单域：sales_order_item';
COMMENT ON COLUMN sales_order_item.id IS '订单域 id';
COMMENT ON COLUMN sales_order_item.order_id IS '订单域 order_id';
COMMENT ON COLUMN sales_order_item.spu_id IS '订单域 spu_id';
COMMENT ON COLUMN sales_order_item.sku_id IS '订单域 sku_id';
COMMENT ON COLUMN sales_order_item.spu_code_snapshot IS '订单域 spu_code_snapshot';
COMMENT ON COLUMN sales_order_item.product_name_snapshot IS '订单域 product_name_snapshot';
COMMENT ON COLUMN sales_order_item.sku_code_snapshot IS '订单域 sku_code_snapshot';
COMMENT ON COLUMN sales_order_item.spec_name_snapshot IS '订单域 spec_name_snapshot';
COMMENT ON COLUMN sales_order_item.spec_values_snapshot IS '订单域 spec_values_snapshot';
COMMENT ON COLUMN sales_order_item.sale_unit_snapshot IS '订单域 sale_unit_snapshot';
COMMENT ON COLUMN sales_order_item.product_type_snapshot IS '订单域 product_type_snapshot';
COMMENT ON COLUMN sales_order_item.ordered_quantity IS '订单域 ordered_quantity';
COMMENT ON COLUMN sales_order_item.actual_quantity IS '订单域 actual_quantity';
COMMENT ON COLUMN sales_order_item.actual_quantity_source IS '订单域 actual_quantity_source';
COMMENT ON COLUMN sales_order_item.actual_quantity_reason IS '订单域 actual_quantity_reason';
COMMENT ON COLUMN sales_order_item.draft_unit_price IS '订单域 draft_unit_price';
COMMENT ON COLUMN sales_order_item.draft_price_source IS '订单域 draft_price_source';
COMMENT ON COLUMN sales_order_item.draft_price_source_id IS '订单域 draft_price_source_id';
COMMENT ON COLUMN sales_order_item.manual_price_override IS '订单域 manual_price_override';
COMMENT ON COLUMN sales_order_item.manual_price_reason IS '订单域 manual_price_reason';
COMMENT ON COLUMN sales_order_item.locked_unit_price IS '订单域 locked_unit_price';
COMMENT ON COLUMN sales_order_item.locked_price_source IS '订单域 locked_price_source';
COMMENT ON COLUMN sales_order_item.locked_price_source_id IS '订单域 locked_price_source_id';
COMMENT ON COLUMN sales_order_item.ordered_line_amount IS '订单域 ordered_line_amount';
COMMENT ON COLUMN sales_order_item.settlement_line_amount IS '订单域 settlement_line_amount';
COMMENT ON COLUMN sales_order_item.sort_order IS '订单域 sort_order';
COMMENT ON COLUMN sales_order_item.version IS '订单域 version';
COMMENT ON COLUMN sales_order_item.deleted IS '订单域 deleted';
COMMENT ON COLUMN sales_order_item.created_at IS '订单域 created_at';
COMMENT ON COLUMN sales_order_item.updated_at IS '订单域 updated_at';
COMMENT ON COLUMN sales_order_item.created_by IS '订单域 created_by';
COMMENT ON TABLE order_address_snapshot IS 'W4 销售订单域：order_address_snapshot';
COMMENT ON COLUMN order_address_snapshot.id IS '订单域 id';
COMMENT ON COLUMN order_address_snapshot.order_id IS '订单域 order_id';
COMMENT ON COLUMN order_address_snapshot.customer_id IS '订单域 customer_id';
COMMENT ON COLUMN order_address_snapshot.receiver_name IS '订单域 receiver_name';
COMMENT ON COLUMN order_address_snapshot.receiver_phone IS '订单域 receiver_phone';
COMMENT ON COLUMN order_address_snapshot.address IS '订单域 address';
COMMENT ON COLUMN order_address_snapshot.created_at IS '订单域 created_at';
COMMENT ON COLUMN order_address_snapshot.created_by IS '订单域 created_by';
COMMENT ON TABLE order_operation_log IS 'W4 销售订单域：order_operation_log';
COMMENT ON COLUMN order_operation_log.id IS '订单域 id';
COMMENT ON COLUMN order_operation_log.order_id IS '订单域 order_id';
COMMENT ON COLUMN order_operation_log.operation_type IS '订单域 operation_type';
COMMENT ON COLUMN order_operation_log.operator IS '订单域 operator';
COMMENT ON COLUMN order_operation_log.reason IS '订单域 reason';
COMMENT ON COLUMN order_operation_log.before_data IS '订单域 before_data';
COMMENT ON COLUMN order_operation_log.after_data IS '订单域 after_data';
COMMENT ON COLUMN order_operation_log.created_at IS '订单域 created_at';
COMMENT ON COLUMN order_operation_log.created_by IS '订单域 created_by';
COMMENT ON TABLE idempotency_record IS 'W4 销售订单域：idempotency_record';
COMMENT ON COLUMN idempotency_record.id IS '订单域 id';
COMMENT ON COLUMN idempotency_record.operation_scope IS '订单域 operation_scope';
COMMENT ON COLUMN idempotency_record.idempotency_key IS '订单域 idempotency_key';
COMMENT ON COLUMN idempotency_record.request_hash IS '订单域 request_hash';
COMMENT ON COLUMN idempotency_record.result_type IS '订单域 result_type';
COMMENT ON COLUMN idempotency_record.result_id IS '订单域 result_id';
COMMENT ON COLUMN idempotency_record.result_data IS '订单域 result_data';
COMMENT ON COLUMN idempotency_record.version IS '订单域 version';
COMMENT ON COLUMN idempotency_record.deleted IS '订单域 deleted';
COMMENT ON COLUMN idempotency_record.created_at IS '订单域 created_at';
COMMENT ON COLUMN idempotency_record.updated_at IS '订单域 updated_at';
COMMENT ON COLUMN idempotency_record.created_by IS '订单域 created_by';
COMMENT ON TABLE order_return IS 'W4 销售订单域：order_return';
COMMENT ON COLUMN order_return.id IS '订单域 id';
COMMENT ON COLUMN order_return.return_no IS '订单域 return_no';
COMMENT ON COLUMN order_return.order_id IS '订单域 order_id';
COMMENT ON COLUMN order_return.customer_id IS '订单域 customer_id';
COMMENT ON COLUMN order_return.status IS '订单域 status';
COMMENT ON COLUMN order_return.reason IS '订单域 reason';
COMMENT ON COLUMN order_return.decision_reason IS '订单域 decision_reason';
COMMENT ON COLUMN order_return.approved_amount IS '订单域 approved_amount';
COMMENT ON COLUMN order_return.approved_at IS '订单域 approved_at';
COMMENT ON COLUMN order_return.version IS '订单域 version';
COMMENT ON COLUMN order_return.created_at IS '订单域 created_at';
COMMENT ON COLUMN order_return.updated_at IS '订单域 updated_at';
COMMENT ON COLUMN order_return.created_by IS '订单域 created_by';
COMMENT ON TABLE order_return_item IS 'W4 销售订单域：order_return_item';
COMMENT ON COLUMN order_return_item.id IS '订单域 id';
COMMENT ON COLUMN order_return_item.return_id IS '订单域 return_id';
COMMENT ON COLUMN order_return_item.order_item_id IS '订单域 order_item_id';
COMMENT ON COLUMN order_return_item.requested_quantity IS '订单域 requested_quantity';
COMMENT ON COLUMN order_return_item.approved_quantity IS '订单域 approved_quantity';
COMMENT ON COLUMN order_return_item.locked_unit_price IS '订单域 locked_unit_price';
COMMENT ON COLUMN order_return_item.approved_amount IS '订单域 approved_amount';
COMMENT ON COLUMN order_return_item.version IS '订单域 version';
COMMENT ON COLUMN order_return_item.created_at IS '订单域 created_at';
COMMENT ON COLUMN order_return_item.updated_at IS '订单域 updated_at';
COMMENT ON COLUMN order_return_item.created_by IS '订单域 created_by';
COMMENT ON TABLE order_refund IS 'W4 销售订单域：order_refund';
COMMENT ON COLUMN order_refund.id IS '订单域 id';
COMMENT ON COLUMN order_refund.refund_no IS '订单域 refund_no';
COMMENT ON COLUMN order_refund.return_id IS '订单域 return_id';
COMMENT ON COLUMN order_refund.order_id IS '订单域 order_id';
COMMENT ON COLUMN order_refund.customer_id IS '订单域 customer_id';
COMMENT ON COLUMN order_refund.refund_amount IS '订单域 refund_amount';
COMMENT ON COLUMN order_refund.status IS '订单域 status';
COMMENT ON COLUMN order_refund.external_reference IS '订单域 external_reference';
COMMENT ON COLUMN order_refund.completed_at IS '订单域 completed_at';
COMMENT ON COLUMN order_refund.version IS '订单域 version';
COMMENT ON COLUMN order_refund.created_at IS '订单域 created_at';
COMMENT ON COLUMN order_refund.updated_at IS '订单域 updated_at';
COMMENT ON COLUMN order_refund.created_by IS '订单域 created_by';
