-- W5 Purchase; see docs/progress.md for the current stage record.
-- PostgreSQL; NO foreign keys (AGENTS.md). Global sequences never reset daily; padding is >= 6 digits.
-- Scope: warehouse + purchase demand/order/receipt. NO inventory tables, NO inventory writes (Q5).
-- Seeds: 1 default warehouse (G-03 single warehouse) + 1 t_config row (Q3a over-receipt tolerance).

CREATE SEQUENCE purchase_order_no_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE purchase_receipt_no_seq START WITH 1 INCREMENT BY 1;

-- ---------------------------------------------------------------------------
-- warehouse (Q1): minimal master data, single-warehouse expressed by seed data
-- ---------------------------------------------------------------------------
CREATE TABLE warehouse (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_code VARCHAR(64)  NOT NULL,
    name           VARCHAR(150) NOT NULL,
    status         VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    address        VARCHAR(255),
    remark         VARCHAR(500),
    version        INTEGER      NOT NULL DEFAULT 0,
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by     VARCHAR(64),
    updated_by     VARCHAR(64),
    CONSTRAINT ck_warehouse_status  CHECK (status IN ('ENABLED','DISABLED')),
    CONSTRAINT ck_warehouse_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_warehouse_code_active ON warehouse (warehouse_code) WHERE deleted = FALSE;
CREATE INDEX idx_warehouse_name   ON warehouse (name);
CREATE INDEX idx_warehouse_status ON warehouse (status) WHERE deleted = FALSE;

INSERT INTO warehouse(warehouse_code, name, status, remark)
VALUES ('WH001','默认仓库','ENABLED','G-03 单仓库口径：系统仅维护一个启用仓库')
ON CONFLICT DO NOTHING;

-- Q3a: runtime parameter lives in SmartAdmin native t_config (created by V3), NOT in a SCM table.
INSERT INTO t_config (config_name, config_key, config_value, remark)
VALUES ('采购超收容差百分比', 'scm.purchase.over_receipt_tolerance_percent', '10',
        'W5 采购收货超收容差，合法范围 0-100，缺失时回退 10')
ON CONFLICT (config_key) DO NOTHING;

-- ---------------------------------------------------------------------------
-- purchase_demand: one active demand per sales order line, aggregated by window
-- ---------------------------------------------------------------------------
CREATE TABLE purchase_demand (
    id                      BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id          BIGINT        NOT NULL,
    sales_order_item_id     BIGINT        NOT NULL,
    spu_id                  BIGINT        NOT NULL,
    sku_id                  BIGINT        NOT NULL,
    sales_order_no_snapshot VARCHAR(64)   NOT NULL,
    spu_code_snapshot       VARCHAR(64)   NOT NULL,
    product_name_snapshot   VARCHAR(150)  NOT NULL,
    sku_code_snapshot       VARCHAR(64)   NOT NULL,
    sku_name_snapshot       VARCHAR(150)  NOT NULL,
    spec_values_snapshot    JSONB         NOT NULL DEFAULT '{}'::JSONB,
    demand_unit_snapshot    VARCHAR(32)   NOT NULL,
    product_type_snapshot   VARCHAR(20)   NOT NULL,
    required_quantity       NUMERIC(18,4) NOT NULL,
    allocated_quantity      NUMERIC(18,4) NOT NULL DEFAULT 0,
    supplier_id             BIGINT,
    warehouse_id            BIGINT,
    purchaser_id            BIGINT,
    status                  VARCHAR(24)   NOT NULL DEFAULT 'PENDING',
    demand_date             DATE          NOT NULL,
    source_confirmed_at     TIMESTAMPTZ   NOT NULL,
    version                 INTEGER       NOT NULL DEFAULT 0,
    deleted                 BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              VARCHAR(64),
    updated_by              VARCHAR(64),
    CONSTRAINT ck_purchase_demand_spec_values CHECK (jsonb_typeof(spec_values_snapshot) = 'object'),
    CONSTRAINT ck_purchase_demand_product_type CHECK (product_type_snapshot IN ('STANDARD','NON_STANDARD')),
    CONSTRAINT ck_purchase_demand_required    CHECK (required_quantity > 0),
    CONSTRAINT ck_purchase_demand_allocated   CHECK (allocated_quantity >= 0 AND allocated_quantity <= required_quantity),
    CONSTRAINT ck_purchase_demand_status      CHECK (status IN ('PENDING','PARTIALLY_ALLOCATED','ALLOCATED')),
    -- Once allocated, both supplier and warehouse must be present.
    -- Unallocated does NOT require them to be NULL: generate requires warehouseId, so a fresh
    -- demand already carries warehouse_id before its first allocation.
    CONSTRAINT ck_purchase_demand_assignment  CHECK (
        allocated_quantity = 0
        OR (supplier_id IS NOT NULL AND warehouse_id IS NOT NULL)
    ),
    -- Q6a: demand_date is the source order's confirmation date in Asia/Shanghai, never date(startAt).
    CONSTRAINT ck_purchase_demand_date        CHECK (
        demand_date = (source_confirmed_at AT TIME ZONE 'Asia/Shanghai')::date),
    CONSTRAINT ck_purchase_demand_version     CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_purchase_demand_source_active
    ON purchase_demand (sales_order_item_id) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_demand_sales_order_id
    ON purchase_demand (sales_order_id) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_demand_sku_status
    ON purchase_demand (sku_id, status) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_demand_assignment
    ON purchase_demand (supplier_id, warehouse_id) WHERE deleted = FALSE AND supplier_id IS NOT NULL;
CREATE INDEX idx_purchase_demand_created
    ON purchase_demand (created_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_demand_source_confirmed_at
    ON purchase_demand (source_confirmed_at) WHERE deleted = FALSE;

-- ---------------------------------------------------------------------------
-- purchase_demand_allocation: N allocations per purchase order item (Q13)
-- ---------------------------------------------------------------------------
CREATE TABLE purchase_demand_allocation (
    id                     BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_demand_id     BIGINT        NOT NULL,
    purchase_order_item_id BIGINT        NOT NULL,
    sales_order_id         BIGINT        NOT NULL,
    sales_order_item_id    BIGINT        NOT NULL,
    sku_id                 BIGINT        NOT NULL,
    allocated_quantity     NUMERIC(18,4) NOT NULL,
    demand_snapshot        JSONB         NOT NULL DEFAULT '{}'::JSONB,
    version                INTEGER       NOT NULL DEFAULT 0,
    deleted                BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by             VARCHAR(64),
    updated_by             VARCHAR(64),
    CONSTRAINT ck_purchase_demand_allocation_quantity CHECK (allocated_quantity > 0),
    CONSTRAINT ck_purchase_demand_allocation_snapshot CHECK (jsonb_typeof(demand_snapshot) = 'object'),
    CONSTRAINT ck_purchase_demand_allocation_version  CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_purchase_demand_allocation_source_active
    ON purchase_demand_allocation (purchase_order_item_id, purchase_demand_id) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_demand_allocation_demand_id
    ON purchase_demand_allocation (purchase_demand_id) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_demand_allocation_sales_order_item_id
    ON purchase_demand_allocation (sales_order_item_id) WHERE deleted = FALSE;

-- ---------------------------------------------------------------------------
-- purchase_order
-- ---------------------------------------------------------------------------
CREATE TABLE purchase_order (
    id                      BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no                VARCHAR(64)   NOT NULL,
    supplier_id             BIGINT        NOT NULL,
    supplier_code_snapshot  VARCHAR(64)   NOT NULL,
    supplier_name_snapshot  VARCHAR(150)  NOT NULL,
    purchaser_id            BIGINT,
    warehouse_id            BIGINT        NOT NULL,
    warehouse_code_snapshot VARCHAR(64)   NOT NULL,
    warehouse_name_snapshot VARCHAR(150)  NOT NULL,
    planned_arrival_date    DATE,
    status                  VARCHAR(24)   NOT NULL DEFAULT 'DRAFT',
    total_amount            NUMERIC(18,4) NOT NULL DEFAULT 0,
    remark                  VARCHAR(500),
    cancel_reason           VARCHAR(500),
    short_close_reason      VARCHAR(500),
    submitted_at            TIMESTAMPTZ,
    cancelled_at            TIMESTAMPTZ,
    short_closed_at         TIMESTAMPTZ,
    version                 INTEGER       NOT NULL DEFAULT 0,
    deleted                 BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              VARCHAR(64),
    updated_by              VARCHAR(64),
    CONSTRAINT ck_purchase_order_status CHECK (status IN (
        'DRAFT','SUBMITTED','PARTIALLY_RECEIVED','RECEIVED','SHORT_CLOSED','CANCELLED')),
    CONSTRAINT ck_purchase_order_total_amount CHECK (total_amount >= 0),
    CONSTRAINT ck_purchase_order_cancel_reason CHECK (
        status <> 'CANCELLED' OR (cancel_reason IS NOT NULL AND btrim(cancel_reason) <> '')),
    CONSTRAINT ck_purchase_order_short_close_reason CHECK (
        status <> 'SHORT_CLOSED' OR (short_close_reason IS NOT NULL AND btrim(short_close_reason) <> '')),
    -- State/timestamp consistency. submitted_at is NOT guarded by status='DRAFT' because a DRAFT
    -- order may be cancelled directly, leaving status='CANCELLED' with submitted_at NULL.
    CONSTRAINT ck_purchase_order_submitted_at CHECK (
        status NOT IN ('SUBMITTED','PARTIALLY_RECEIVED','RECEIVED','SHORT_CLOSED')
        OR submitted_at IS NOT NULL),
    CONSTRAINT ck_purchase_order_cancelled_at CHECK (
        status <> 'CANCELLED' OR cancelled_at IS NOT NULL),
    CONSTRAINT ck_purchase_order_short_closed_at CHECK (
        status <> 'SHORT_CLOSED' OR short_closed_at IS NOT NULL),
    CONSTRAINT ck_purchase_order_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_purchase_order_no_active ON purchase_order (order_no) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_order_status_supplier_warehouse
    ON purchase_order (status, supplier_id, warehouse_id) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_order_purchaser_created
    ON purchase_order (purchaser_id, created_at DESC) WHERE deleted = FALSE AND purchaser_id IS NOT NULL;
CREATE INDEX idx_purchase_order_created
    ON purchase_order (created_at DESC) WHERE deleted = FALSE;

-- ---------------------------------------------------------------------------
-- purchase_order_item: one line per SKU (Q13); carries N allocations via the table above
-- ---------------------------------------------------------------------------
CREATE TABLE purchase_order_item (
    id                     BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id      BIGINT        NOT NULL,
    spu_id                 BIGINT        NOT NULL,
    sku_id                 BIGINT        NOT NULL,
    spu_code_snapshot      VARCHAR(64)   NOT NULL,
    product_name_snapshot  VARCHAR(150)  NOT NULL,
    sku_code_snapshot      VARCHAR(64)   NOT NULL,
    sku_name_snapshot      VARCHAR(150)  NOT NULL,
    spec_values_snapshot   JSONB         NOT NULL DEFAULT '{}'::JSONB,
    purchase_unit_snapshot VARCHAR(32)   NOT NULL,
    product_type_snapshot  VARCHAR(20)   NOT NULL,
    planned_quantity       NUMERIC(18,4) NOT NULL,
    received_quantity      NUMERIC(18,4) NOT NULL DEFAULT 0,
    purchase_price         NUMERIC(18,4) NOT NULL,
    line_amount            NUMERIC(18,4) NOT NULL,
    sort_order             INTEGER       NOT NULL DEFAULT 0,
    version                INTEGER       NOT NULL DEFAULT 0,
    deleted                BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by             VARCHAR(64),
    updated_by             VARCHAR(64),
    CONSTRAINT ck_purchase_order_item_spec_values CHECK (jsonb_typeof(spec_values_snapshot) = 'object'),
    CONSTRAINT ck_purchase_order_item_product_type CHECK (product_type_snapshot IN ('STANDARD','NON_STANDARD')),
    CONSTRAINT ck_purchase_order_item_planned_quantity  CHECK (planned_quantity > 0),
    CONSTRAINT ck_purchase_order_item_received_quantity CHECK (received_quantity >= 0),
    CONSTRAINT ck_purchase_order_item_purchase_price    CHECK (purchase_price >= 0),
    CONSTRAINT ck_purchase_order_item_line_amount       CHECK (line_amount >= 0),
    CONSTRAINT ck_purchase_order_item_version           CHECK (version >= 0)
);
CREATE INDEX idx_purchase_order_item_order_id
    ON purchase_order_item (purchase_order_id, sort_order) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_order_item_sku_id
    ON purchase_order_item (sku_id) WHERE deleted = FALSE;
-- Q13: one line per SKU per order (same shape as W4 uk_sales_order_item_order_sku_active).
-- NOTE: received_quantity is intentionally NOT capped by planned_quantity here; the over-receipt
-- ceiling is a runtime t_config value (planned * (1 + tolerance/100)) and cannot be a static CHECK.
CREATE UNIQUE INDEX uk_purchase_order_item_order_sku_active
    ON purchase_order_item (purchase_order_id, sku_id) WHERE deleted = FALSE;

-- ---------------------------------------------------------------------------
-- purchase_receipt: one purchase order -> many independent receipts (Q7)
-- ---------------------------------------------------------------------------
CREATE TABLE purchase_receipt (
    id                         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no                 VARCHAR(64)  NOT NULL,
    purchase_order_id          BIGINT       NOT NULL,
    purchase_order_no_snapshot VARCHAR(64)  NOT NULL,
    supplier_id                BIGINT       NOT NULL,
    supplier_code_snapshot     VARCHAR(64)  NOT NULL,
    supplier_name_snapshot     VARCHAR(150) NOT NULL,
    warehouse_id               BIGINT       NOT NULL,
    warehouse_code_snapshot    VARCHAR(64)  NOT NULL,
    warehouse_name_snapshot    VARCHAR(150) NOT NULL,
    status                     VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    received_at                TIMESTAMPTZ,
    confirmed_at               TIMESTAMPTZ,
    operator                   VARCHAR(64),
    remark                     VARCHAR(500),
    version                    INTEGER      NOT NULL DEFAULT 0,
    deleted                    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at                 TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by                 VARCHAR(64),
    updated_by                 VARCHAR(64),
    CONSTRAINT ck_purchase_receipt_status CHECK (status IN ('DRAFT','CONFIRMED')),
    CONSTRAINT ck_purchase_receipt_confirmation CHECK (
        (status = 'DRAFT'     AND confirmed_at IS NULL     AND operator IS NULL)
        OR (status = 'CONFIRMED' AND confirmed_at IS NOT NULL AND operator IS NOT NULL AND btrim(operator) <> '')),
    CONSTRAINT ck_purchase_receipt_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_purchase_receipt_no_active ON purchase_receipt (receipt_no) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_receipt_order_created
    ON purchase_receipt (purchase_order_id, created_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_receipt_warehouse_received
    ON purchase_receipt (warehouse_id, received_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_receipt_status_created
    ON purchase_receipt (status, created_at DESC) WHERE deleted = FALSE;

-- ---------------------------------------------------------------------------
-- purchase_receipt_item: per-line reconciliation snapshot (P24 identity by DB CHECK)
-- ---------------------------------------------------------------------------
CREATE TABLE purchase_receipt_item (
    id                           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_receipt_id          BIGINT        NOT NULL,
    purchase_order_item_id       BIGINT        NOT NULL,
    sku_id                       BIGINT        NOT NULL,
    spu_code_snapshot            VARCHAR(64)   NOT NULL,
    product_name_snapshot        VARCHAR(150)  NOT NULL,
    sku_code_snapshot            VARCHAR(64)   NOT NULL,
    sku_name_snapshot            VARCHAR(150)  NOT NULL,
    spec_values_snapshot         JSONB         NOT NULL DEFAULT '{}'::JSONB,
    purchase_unit_snapshot       VARCHAR(32)   NOT NULL,
    product_type_snapshot        VARCHAR(20)   NOT NULL,
    planned_quantity             NUMERIC(18,4) NOT NULL,
    received_quantity            NUMERIC(18,4) NOT NULL DEFAULT 0,
    cumulative_received_quantity NUMERIC(18,4) NOT NULL DEFAULT 0,
    remaining_quantity           NUMERIC(18,4) NOT NULL DEFAULT 0,
    over_receipt_quantity        NUMERIC(18,4) NOT NULL DEFAULT 0,
    receipt_difference           NUMERIC(18,4) NOT NULL DEFAULT 0,
    actual_weight                NUMERIC(18,4),
    weight_unit                  VARCHAR(32),
    weighing_source              VARCHAR(20),
    correction_reason            VARCHAR(500),
    sort_order                   INTEGER       NOT NULL DEFAULT 0,
    version                      INTEGER       NOT NULL DEFAULT 0,
    deleted                      BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at                   TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                   TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by                   VARCHAR(64),
    updated_by                   VARCHAR(64),
    CONSTRAINT ck_purchase_receipt_item_spec_values  CHECK (jsonb_typeof(spec_values_snapshot) = 'object'),
    CONSTRAINT ck_purchase_receipt_item_product_type CHECK (product_type_snapshot IN ('STANDARD','NON_STANDARD')),
    CONSTRAINT ck_purchase_receipt_item_planned      CHECK (planned_quantity > 0),
    CONSTRAINT ck_purchase_receipt_item_received     CHECK (received_quantity >= 0),
    CONSTRAINT ck_purchase_receipt_item_actual_weight CHECK (actual_weight IS NULL OR actual_weight > 0),
    CONSTRAINT ck_purchase_receipt_item_weight_source CHECK (weighing_source IS NULL OR weighing_source = 'MANUAL'),
    -- Three weight columns live and die together (dual of V2's draft_*/locked_* discipline).
    CONSTRAINT ck_purchase_receipt_item_weight_fields CHECK (
        (actual_weight IS NULL AND weight_unit IS NULL AND weighing_source IS NULL)
        OR (actual_weight IS NOT NULL AND weight_unit IS NOT NULL AND btrim(weight_unit) <> ''
            AND weighing_source IS NOT NULL)),
    -- P24: the five reconciliation quantities are tied by this identity.
    CONSTRAINT ck_purchase_receipt_item_reconciliation CHECK (
        cumulative_received_quantity >= 0
        AND remaining_quantity = GREATEST(planned_quantity - cumulative_received_quantity, 0)
        AND over_receipt_quantity = GREATEST(cumulative_received_quantity - planned_quantity, 0)
        AND receipt_difference = cumulative_received_quantity - planned_quantity),
    CONSTRAINT ck_purchase_receipt_item_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_purchase_receipt_item_receipt_order_item_active
    ON purchase_receipt_item (purchase_receipt_id, purchase_order_item_id) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_receipt_item_receipt_id
    ON purchase_receipt_item (purchase_receipt_id, sort_order) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_receipt_item_order_item_id
    ON purchase_receipt_item (purchase_order_item_id) WHERE deleted = FALSE;
CREATE INDEX idx_purchase_receipt_item_sku_id
    ON purchase_receipt_item (sku_id) WHERE deleted = FALSE;

-- ---------------------------------------------------------------------------
-- receipt_weighing_record: append-only audit fact (Q15: no version/deleted; Q16: no scale_precision)
-- ---------------------------------------------------------------------------
CREATE TABLE receipt_weighing_record (
    id                       BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_receipt_item_id BIGINT        NOT NULL,
    raw_reading              NUMERIC(18,4) NOT NULL,
    confirmed_reading        NUMERIC(18,4) NOT NULL,
    unit                     VARCHAR(32)   NOT NULL,
    source                   VARCHAR(20)   NOT NULL DEFAULT 'MANUAL',
    device_session_id        VARCHAR(128),
    modification_reason      VARCHAR(500),
    recorded_at              TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    operator                 VARCHAR(64)   NOT NULL,
    created_at               TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64),
    CONSTRAINT ck_receipt_weighing_record_raw       CHECK (raw_reading > 0),
    CONSTRAINT ck_receipt_weighing_record_confirmed CHECK (confirmed_reading > 0),
    CONSTRAINT ck_receipt_weighing_record_source    CHECK (source = 'MANUAL')
);
CREATE INDEX idx_receipt_weighing_record_item_recorded
    ON receipt_weighing_record (purchase_receipt_item_id, recorded_at DESC);

-- ---------------------------------------------------------------------------
-- purchase_operation_log: append-only audit (Q14: owner is decided by operation_type)
-- ---------------------------------------------------------------------------
CREATE TABLE purchase_operation_log (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id   BIGINT,
    purchase_receipt_id BIGINT,
    operation_type      VARCHAR(40)  NOT NULL,
    operator            VARCHAR(64)  NOT NULL,
    reason              VARCHAR(500),
    before_data         JSONB,
    after_data          JSONB,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          VARCHAR(64),
    CONSTRAINT ck_purchase_operation_log_type CHECK (operation_type IN (
        'CREATE','UPDATE','SUBMIT','CANCEL','SHORT_CLOSE','DELETE',
        'DEMAND_GENERATE','DEMAND_ALLOCATE',
        'RECEIPT_CREATE','RECEIPT_UPDATE','RECEIPT_CONFIRM','RECEIPT_DELETE')),
    -- Owner is operation-type aware. A plain "at least one id is not null" rule is WRONG:
    -- DEMAND_GENERATE happens before any purchase order exists, so BOTH ids are null there.
    CONSTRAINT ck_purchase_operation_log_owner CHECK (
        (operation_type = 'DEMAND_GENERATE'
             AND purchase_order_id IS NULL     AND purchase_receipt_id IS NULL)
     OR (operation_type = 'DEMAND_ALLOCATE'
             AND purchase_order_id IS NOT NULL AND purchase_receipt_id IS NULL)
     OR (operation_type IN ('CREATE','UPDATE','SUBMIT','CANCEL','SHORT_CLOSE','DELETE')
             AND purchase_order_id IS NOT NULL AND purchase_receipt_id IS NULL)
     OR (operation_type IN ('RECEIPT_CREATE','RECEIPT_UPDATE','RECEIPT_CONFIRM','RECEIPT_DELETE')
             AND purchase_order_id IS NOT NULL AND purchase_receipt_id IS NOT NULL)),
    CONSTRAINT ck_purchase_operation_log_before CHECK (before_data IS NULL OR jsonb_typeof(before_data) = 'object'),
    CONSTRAINT ck_purchase_operation_log_after  CHECK (after_data  IS NULL OR jsonb_typeof(after_data)  = 'object')
);
CREATE INDEX idx_purchase_operation_log_order_created
    ON purchase_operation_log (purchase_order_id, created_at DESC);
CREATE INDEX idx_purchase_operation_log_receipt_created
    ON purchase_operation_log (purchase_receipt_id, created_at DESC) WHERE purchase_receipt_id IS NOT NULL;
CREATE INDEX idx_purchase_operation_log_type_created
    ON purchase_operation_log (operation_type, created_at DESC);

-- ---------------------------------------------------------------------------
-- Comments (one per table and per column, same style as V13)
-- ---------------------------------------------------------------------------
COMMENT ON TABLE warehouse IS 'W5 采购域：warehouse';
COMMENT ON COLUMN warehouse.id IS '采购域 id';
COMMENT ON COLUMN warehouse.warehouse_code IS '采购域 warehouse_code';
COMMENT ON COLUMN warehouse.name IS '采购域 name';
COMMENT ON COLUMN warehouse.status IS '采购域 status';
COMMENT ON COLUMN warehouse.address IS '采购域 address';
COMMENT ON COLUMN warehouse.remark IS '采购域 remark';
COMMENT ON COLUMN warehouse.version IS '采购域 version';
COMMENT ON COLUMN warehouse.deleted IS '采购域 deleted';
COMMENT ON COLUMN warehouse.created_at IS '采购域 created_at';
COMMENT ON COLUMN warehouse.updated_at IS '采购域 updated_at';
COMMENT ON COLUMN warehouse.created_by IS '采购域 created_by';
COMMENT ON COLUMN warehouse.updated_by IS '采购域 updated_by';

COMMENT ON TABLE purchase_demand IS 'W5 采购域：purchase_demand';
COMMENT ON COLUMN purchase_demand.id IS '采购域 id';
COMMENT ON COLUMN purchase_demand.sales_order_id IS '采购域 sales_order_id';
COMMENT ON COLUMN purchase_demand.sales_order_item_id IS '采购域 sales_order_item_id';
COMMENT ON COLUMN purchase_demand.spu_id IS '采购域 spu_id';
COMMENT ON COLUMN purchase_demand.sku_id IS '采购域 sku_id';
COMMENT ON COLUMN purchase_demand.sales_order_no_snapshot IS '采购域 sales_order_no_snapshot';
COMMENT ON COLUMN purchase_demand.spu_code_snapshot IS '采购域 spu_code_snapshot';
COMMENT ON COLUMN purchase_demand.product_name_snapshot IS '采购域 product_name_snapshot';
COMMENT ON COLUMN purchase_demand.sku_code_snapshot IS '采购域 sku_code_snapshot';
COMMENT ON COLUMN purchase_demand.sku_name_snapshot IS '采购域 sku_name_snapshot';
COMMENT ON COLUMN purchase_demand.spec_values_snapshot IS '采购域 spec_values_snapshot';
COMMENT ON COLUMN purchase_demand.demand_unit_snapshot IS '采购域 demand_unit_snapshot';
COMMENT ON COLUMN purchase_demand.product_type_snapshot IS '采购域 product_type_snapshot';
COMMENT ON COLUMN purchase_demand.required_quantity IS '采购域 required_quantity';
COMMENT ON COLUMN purchase_demand.allocated_quantity IS '采购域 allocated_quantity';
COMMENT ON COLUMN purchase_demand.supplier_id IS '采购域 supplier_id';
COMMENT ON COLUMN purchase_demand.warehouse_id IS '采购域 warehouse_id';
COMMENT ON COLUMN purchase_demand.purchaser_id IS '采购域 purchaser_id';
COMMENT ON COLUMN purchase_demand.status IS '采购域 status';
COMMENT ON COLUMN purchase_demand.demand_date IS '采购域 demand_date';
COMMENT ON COLUMN purchase_demand.source_confirmed_at IS '采购域 source_confirmed_at';
COMMENT ON COLUMN purchase_demand.version IS '采购域 version';
COMMENT ON COLUMN purchase_demand.deleted IS '采购域 deleted';
COMMENT ON COLUMN purchase_demand.created_at IS '采购域 created_at';
COMMENT ON COLUMN purchase_demand.updated_at IS '采购域 updated_at';
COMMENT ON COLUMN purchase_demand.created_by IS '采购域 created_by';
COMMENT ON COLUMN purchase_demand.updated_by IS '采购域 updated_by';

COMMENT ON TABLE purchase_demand_allocation IS 'W5 采购域：purchase_demand_allocation';
COMMENT ON COLUMN purchase_demand_allocation.id IS '采购域 id';
COMMENT ON COLUMN purchase_demand_allocation.purchase_demand_id IS '采购域 purchase_demand_id';
COMMENT ON COLUMN purchase_demand_allocation.purchase_order_item_id IS '采购域 purchase_order_item_id';
COMMENT ON COLUMN purchase_demand_allocation.sales_order_id IS '采购域 sales_order_id';
COMMENT ON COLUMN purchase_demand_allocation.sales_order_item_id IS '采购域 sales_order_item_id';
COMMENT ON COLUMN purchase_demand_allocation.sku_id IS '采购域 sku_id';
COMMENT ON COLUMN purchase_demand_allocation.allocated_quantity IS '采购域 allocated_quantity';
COMMENT ON COLUMN purchase_demand_allocation.demand_snapshot IS '采购域 demand_snapshot';
COMMENT ON COLUMN purchase_demand_allocation.version IS '采购域 version';
COMMENT ON COLUMN purchase_demand_allocation.deleted IS '采购域 deleted';
COMMENT ON COLUMN purchase_demand_allocation.created_at IS '采购域 created_at';
COMMENT ON COLUMN purchase_demand_allocation.updated_at IS '采购域 updated_at';
COMMENT ON COLUMN purchase_demand_allocation.created_by IS '采购域 created_by';
COMMENT ON COLUMN purchase_demand_allocation.updated_by IS '采购域 updated_by';

COMMENT ON TABLE purchase_order IS 'W5 采购域：purchase_order';
COMMENT ON COLUMN purchase_order.id IS '采购域 id';
COMMENT ON COLUMN purchase_order.order_no IS '采购域 order_no';
COMMENT ON COLUMN purchase_order.supplier_id IS '采购域 supplier_id';
COMMENT ON COLUMN purchase_order.supplier_code_snapshot IS '采购域 supplier_code_snapshot';
COMMENT ON COLUMN purchase_order.supplier_name_snapshot IS '采购域 supplier_name_snapshot';
COMMENT ON COLUMN purchase_order.purchaser_id IS '采购域 purchaser_id';
COMMENT ON COLUMN purchase_order.warehouse_id IS '采购域 warehouse_id';
COMMENT ON COLUMN purchase_order.warehouse_code_snapshot IS '采购域 warehouse_code_snapshot';
COMMENT ON COLUMN purchase_order.warehouse_name_snapshot IS '采购域 warehouse_name_snapshot';
COMMENT ON COLUMN purchase_order.planned_arrival_date IS '采购域 planned_arrival_date';
COMMENT ON COLUMN purchase_order.status IS '采购域 status';
COMMENT ON COLUMN purchase_order.total_amount IS '采购域 total_amount';
COMMENT ON COLUMN purchase_order.remark IS '采购域 remark';
COMMENT ON COLUMN purchase_order.cancel_reason IS '采购域 cancel_reason';
COMMENT ON COLUMN purchase_order.short_close_reason IS '采购域 short_close_reason';
COMMENT ON COLUMN purchase_order.submitted_at IS '采购域 submitted_at';
COMMENT ON COLUMN purchase_order.cancelled_at IS '采购域 cancelled_at';
COMMENT ON COLUMN purchase_order.short_closed_at IS '采购域 short_closed_at';
COMMENT ON COLUMN purchase_order.version IS '采购域 version';
COMMENT ON COLUMN purchase_order.deleted IS '采购域 deleted';
COMMENT ON COLUMN purchase_order.created_at IS '采购域 created_at';
COMMENT ON COLUMN purchase_order.updated_at IS '采购域 updated_at';
COMMENT ON COLUMN purchase_order.created_by IS '采购域 created_by';
COMMENT ON COLUMN purchase_order.updated_by IS '采购域 updated_by';

COMMENT ON TABLE purchase_order_item IS 'W5 采购域：purchase_order_item';
COMMENT ON COLUMN purchase_order_item.id IS '采购域 id';
COMMENT ON COLUMN purchase_order_item.purchase_order_id IS '采购域 purchase_order_id';
COMMENT ON COLUMN purchase_order_item.spu_id IS '采购域 spu_id';
COMMENT ON COLUMN purchase_order_item.sku_id IS '采购域 sku_id';
COMMENT ON COLUMN purchase_order_item.spu_code_snapshot IS '采购域 spu_code_snapshot';
COMMENT ON COLUMN purchase_order_item.product_name_snapshot IS '采购域 product_name_snapshot';
COMMENT ON COLUMN purchase_order_item.sku_code_snapshot IS '采购域 sku_code_snapshot';
COMMENT ON COLUMN purchase_order_item.sku_name_snapshot IS '采购域 sku_name_snapshot';
COMMENT ON COLUMN purchase_order_item.spec_values_snapshot IS '采购域 spec_values_snapshot';
COMMENT ON COLUMN purchase_order_item.purchase_unit_snapshot IS '采购域 purchase_unit_snapshot';
COMMENT ON COLUMN purchase_order_item.product_type_snapshot IS '采购域 product_type_snapshot';
COMMENT ON COLUMN purchase_order_item.planned_quantity IS '采购域 planned_quantity';
COMMENT ON COLUMN purchase_order_item.received_quantity IS '采购域 received_quantity';
COMMENT ON COLUMN purchase_order_item.purchase_price IS '采购域 purchase_price';
COMMENT ON COLUMN purchase_order_item.line_amount IS '采购域 line_amount';
COMMENT ON COLUMN purchase_order_item.sort_order IS '采购域 sort_order';
COMMENT ON COLUMN purchase_order_item.version IS '采购域 version';
COMMENT ON COLUMN purchase_order_item.deleted IS '采购域 deleted';
COMMENT ON COLUMN purchase_order_item.created_at IS '采购域 created_at';
COMMENT ON COLUMN purchase_order_item.updated_at IS '采购域 updated_at';
COMMENT ON COLUMN purchase_order_item.created_by IS '采购域 created_by';
COMMENT ON COLUMN purchase_order_item.updated_by IS '采购域 updated_by';

COMMENT ON TABLE purchase_receipt IS 'W5 采购域：purchase_receipt';
COMMENT ON COLUMN purchase_receipt.id IS '采购域 id';
COMMENT ON COLUMN purchase_receipt.receipt_no IS '采购域 receipt_no';
COMMENT ON COLUMN purchase_receipt.purchase_order_id IS '采购域 purchase_order_id';
COMMENT ON COLUMN purchase_receipt.purchase_order_no_snapshot IS '采购域 purchase_order_no_snapshot';
COMMENT ON COLUMN purchase_receipt.supplier_id IS '采购域 supplier_id';
COMMENT ON COLUMN purchase_receipt.supplier_code_snapshot IS '采购域 supplier_code_snapshot';
COMMENT ON COLUMN purchase_receipt.supplier_name_snapshot IS '采购域 supplier_name_snapshot';
COMMENT ON COLUMN purchase_receipt.warehouse_id IS '采购域 warehouse_id';
COMMENT ON COLUMN purchase_receipt.warehouse_code_snapshot IS '采购域 warehouse_code_snapshot';
COMMENT ON COLUMN purchase_receipt.warehouse_name_snapshot IS '采购域 warehouse_name_snapshot';
COMMENT ON COLUMN purchase_receipt.status IS '采购域 status';
COMMENT ON COLUMN purchase_receipt.received_at IS '采购域 received_at';
COMMENT ON COLUMN purchase_receipt.confirmed_at IS '采购域 confirmed_at';
COMMENT ON COLUMN purchase_receipt.operator IS '采购域 operator';
COMMENT ON COLUMN purchase_receipt.remark IS '采购域 remark';
COMMENT ON COLUMN purchase_receipt.version IS '采购域 version';
COMMENT ON COLUMN purchase_receipt.deleted IS '采购域 deleted';
COMMENT ON COLUMN purchase_receipt.created_at IS '采购域 created_at';
COMMENT ON COLUMN purchase_receipt.updated_at IS '采购域 updated_at';
COMMENT ON COLUMN purchase_receipt.created_by IS '采购域 created_by';
COMMENT ON COLUMN purchase_receipt.updated_by IS '采购域 updated_by';

COMMENT ON TABLE purchase_receipt_item IS 'W5 采购域：purchase_receipt_item';
COMMENT ON COLUMN purchase_receipt_item.id IS '采购域 id';
COMMENT ON COLUMN purchase_receipt_item.purchase_receipt_id IS '采购域 purchase_receipt_id';
COMMENT ON COLUMN purchase_receipt_item.purchase_order_item_id IS '采购域 purchase_order_item_id';
COMMENT ON COLUMN purchase_receipt_item.sku_id IS '采购域 sku_id';
COMMENT ON COLUMN purchase_receipt_item.spu_code_snapshot IS '采购域 spu_code_snapshot';
COMMENT ON COLUMN purchase_receipt_item.product_name_snapshot IS '采购域 product_name_snapshot';
COMMENT ON COLUMN purchase_receipt_item.sku_code_snapshot IS '采购域 sku_code_snapshot';
COMMENT ON COLUMN purchase_receipt_item.sku_name_snapshot IS '采购域 sku_name_snapshot';
COMMENT ON COLUMN purchase_receipt_item.spec_values_snapshot IS '采购域 spec_values_snapshot';
COMMENT ON COLUMN purchase_receipt_item.purchase_unit_snapshot IS '采购域 purchase_unit_snapshot';
COMMENT ON COLUMN purchase_receipt_item.product_type_snapshot IS '采购域 product_type_snapshot';
COMMENT ON COLUMN purchase_receipt_item.planned_quantity IS '采购域 planned_quantity';
COMMENT ON COLUMN purchase_receipt_item.received_quantity IS '采购域 received_quantity';
COMMENT ON COLUMN purchase_receipt_item.cumulative_received_quantity IS '采购域 cumulative_received_quantity';
COMMENT ON COLUMN purchase_receipt_item.remaining_quantity IS '采购域 remaining_quantity';
COMMENT ON COLUMN purchase_receipt_item.over_receipt_quantity IS '采购域 over_receipt_quantity';
COMMENT ON COLUMN purchase_receipt_item.receipt_difference IS '采购域 receipt_difference';
COMMENT ON COLUMN purchase_receipt_item.actual_weight IS '采购域 actual_weight';
COMMENT ON COLUMN purchase_receipt_item.weight_unit IS '采购域 weight_unit';
COMMENT ON COLUMN purchase_receipt_item.weighing_source IS '采购域 weighing_source';
COMMENT ON COLUMN purchase_receipt_item.correction_reason IS '采购域 correction_reason';
COMMENT ON COLUMN purchase_receipt_item.sort_order IS '采购域 sort_order';
COMMENT ON COLUMN purchase_receipt_item.version IS '采购域 version';
COMMENT ON COLUMN purchase_receipt_item.deleted IS '采购域 deleted';
COMMENT ON COLUMN purchase_receipt_item.created_at IS '采购域 created_at';
COMMENT ON COLUMN purchase_receipt_item.updated_at IS '采购域 updated_at';
COMMENT ON COLUMN purchase_receipt_item.created_by IS '采购域 created_by';
COMMENT ON COLUMN purchase_receipt_item.updated_by IS '采购域 updated_by';

COMMENT ON TABLE receipt_weighing_record IS 'W5 采购域：receipt_weighing_record';
COMMENT ON COLUMN receipt_weighing_record.id IS '采购域 id';
COMMENT ON COLUMN receipt_weighing_record.purchase_receipt_item_id IS '采购域 purchase_receipt_item_id';
COMMENT ON COLUMN receipt_weighing_record.raw_reading IS '采购域 raw_reading';
COMMENT ON COLUMN receipt_weighing_record.confirmed_reading IS '采购域 confirmed_reading';
COMMENT ON COLUMN receipt_weighing_record.unit IS '采购域 unit';
COMMENT ON COLUMN receipt_weighing_record.source IS '采购域 source';
COMMENT ON COLUMN receipt_weighing_record.device_session_id IS '采购域 device_session_id';
COMMENT ON COLUMN receipt_weighing_record.modification_reason IS '采购域 modification_reason';
COMMENT ON COLUMN receipt_weighing_record.recorded_at IS '采购域 recorded_at';
COMMENT ON COLUMN receipt_weighing_record.operator IS '采购域 operator';
COMMENT ON COLUMN receipt_weighing_record.created_at IS '采购域 created_at';
COMMENT ON COLUMN receipt_weighing_record.created_by IS '采购域 created_by';

COMMENT ON TABLE purchase_operation_log IS 'W5 采购域：purchase_operation_log';
COMMENT ON COLUMN purchase_operation_log.id IS '采购域 id';
COMMENT ON COLUMN purchase_operation_log.purchase_order_id IS '采购域 purchase_order_id';
COMMENT ON COLUMN purchase_operation_log.purchase_receipt_id IS '采购域 purchase_receipt_id';
COMMENT ON COLUMN purchase_operation_log.operation_type IS '采购域 operation_type';
COMMENT ON COLUMN purchase_operation_log.operator IS '采购域 operator';
COMMENT ON COLUMN purchase_operation_log.reason IS '采购域 reason';
COMMENT ON COLUMN purchase_operation_log.before_data IS '采购域 before_data';
COMMENT ON COLUMN purchase_operation_log.after_data IS '采购域 after_data';
COMMENT ON COLUMN purchase_operation_log.created_at IS '采购域 created_at';
COMMENT ON COLUMN purchase_operation_log.created_by IS '采购域 created_by';
