-- W6 Inventory phase 1 (W6-1), approved 2026-09-18.
-- See docs/progress.md and docs/decisions.md for the current W6 scope.
-- PostgreSQL; NO foreign keys (AGENTS.md).
--
-- Scope: inventory_balance + inventory_movement, plus the one-shot bootstrap backfill of
--        historical CONFIRMED purchase receipt lines (Q5: data-only, same migration file,
--        executed before the W6 application starts serving business requests).
-- NOT in scope (W6-1 exclusions): outbound/reserve, stocktake, loss/gain, transfer,
--        unit conversion, warning thresholds, moving-average costing, mini program.
--
-- Q7 (hardening): inventory_movement keeps `deleted` (so the W5 reserved partial unique index
--        matches verbatim) AND adds CHECK (deleted = FALSE) so append-only is enforced by the
--        DATABASE, not by service-layer discipline. Reversals must be NEW reverse movements.
-- Q13 (unit invariant): inventory_balance carries `unit`; one (warehouse, sku) locks exactly one
--        bookkeeping unit. Mixing units fails loudly (41001) instead of silently summing.
-- Q10: quantity >= 0 is frozen for this phase; the negative-stock decision belongs to the
--        outbound wave and must be made explicitly there.
--
-- Idempotency: every INSERT is ON CONFLICT DO NOTHING against a partial unique index, so a
--        re-run (or an overlap with the online confirm path) never double-counts.

-- ---------------------------------------------------------------------------
-- inventory_balance: one row per (warehouse_id, sku_id); derived from movements
-- ---------------------------------------------------------------------------
CREATE TABLE inventory_balance (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id  BIGINT        NOT NULL,
    sku_id        BIGINT        NOT NULL,
    unit          VARCHAR(32)   NOT NULL,
    quantity      NUMERIC(18,4) NOT NULL DEFAULT 0,
    version       INTEGER       NOT NULL DEFAULT 0,
    deleted       BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(64),
    updated_by    VARCHAR(64),
    -- Q13: the bookkeeping unit is never blank. `unit` is deliberately NOT part of the unique
    -- key: one (warehouse, sku) may only ever hold ONE unit, and a second unit is an error
    -- (41001), not a second balance row.
    CONSTRAINT ck_inventory_balance_unit     CHECK (btrim(unit) <> ''),
    -- Q10: frozen for W6-1. W6-1 only writes positive increments, so this cannot fire today;
    -- it exists so a future outbound wave must decide the negative-stock policy explicitly.
    CONSTRAINT ck_inventory_balance_quantity CHECK (quantity >= 0),
    CONSTRAINT ck_inventory_balance_version  CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_inventory_balance_wh_sku_active
    ON inventory_balance (warehouse_id, sku_id) WHERE deleted = FALSE;
CREATE INDEX idx_inventory_balance_sku ON inventory_balance (sku_id);

-- ---------------------------------------------------------------------------
-- inventory_movement: append-only ledger; no version / updated_* columns
-- ---------------------------------------------------------------------------
CREATE TABLE inventory_movement (
    id                      BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id            BIGINT        NOT NULL,
    sku_id                  BIGINT        NOT NULL,
    movement_type           VARCHAR(32)   NOT NULL,
    source_document_type    VARCHAR(64)   NOT NULL,
    source_document_id      BIGINT        NOT NULL,
    source_document_item_id BIGINT        NOT NULL,
    quantity                NUMERIC(18,4) NOT NULL,
    unit_snapshot           VARCHAR(32)   NOT NULL,
    unit_cost               NUMERIC(18,4),
    before_quantity         NUMERIC(18,4) NOT NULL,
    after_quantity          NUMERIC(18,4) NOT NULL,
    occurred_at             TIMESTAMPTZ   NOT NULL,
    operator                VARCHAR(64),
    deleted                 BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              VARCHAR(64),
    -- W6-1 only ships PURCHASE_IN; future waves extend this whitelist by a new migration.
    CONSTRAINT ck_inventory_movement_type   CHECK (movement_type IN ('PURCHASE_IN')),
    -- Direction is encoded in the type, so quantity is always positive (no `direction` column).
    CONSTRAINT ck_inventory_movement_qty    CHECK (quantity > 0),
    -- The traceability identity of every movement, enforced by the database.
    CONSTRAINT ck_inventory_movement_snap   CHECK (after_quantity = before_quantity + quantity),
    CONSTRAINT ck_inventory_movement_unit   CHECK (btrim(unit_snapshot) <> ''),
    -- NULL only for future no-cost movement types (e.g. stock gain); PURCHASE_IN always carries it.
    CONSTRAINT ck_inventory_movement_cost   CHECK (unit_cost IS NULL OR unit_cost >= 0),
    -- Q7 hardening: append-only as a DB constraint. Any UPDATE that would soft-delete a
    -- historical row (or set deleted = TRUE) fails at the database level.
    CONSTRAINT ck_inventory_movement_append_only CHECK (deleted = FALSE)
);

-- source_document_type constant value = PurchaseInventoryContract.SOURCE_DOCUMENT_TYPE
--                                   = 'PURCHASE_RECEIPT_ITEM'
-- W5 TD 8.5 reserved SQL, landed verbatim (Q7). The `source_document_item_id IS NOT NULL`
-- predicate is redundant against the NOT NULL column constraint, but it is kept so the index
-- definition stays character-for-character identical to the frozen W5 contract. The
-- ON CONFLICT target in the application layer must repeat this predicate exactly (Q11).
CREATE UNIQUE INDEX uk_inventory_movement_source_active
    ON inventory_movement (source_document_type, source_document_item_id)
    WHERE deleted = FALSE AND source_document_item_id IS NOT NULL;

CREATE INDEX idx_inventory_movement_wh_sku_occurred
    ON inventory_movement (warehouse_id, sku_id, occurred_at);
CREATE INDEX idx_inventory_movement_occurred ON inventory_movement (occurred_at);
CREATE INDEX idx_inventory_movement_source
    ON inventory_movement (source_document_type, source_document_id);

-- ===========================================================================
-- Q5 bootstrap backfill: replay historical CONFIRMED purchase receipt lines
-- ===========================================================================
-- Replay order (Q5 correction): receipt.confirmed_at ASC, receipt.id ASC, receipt_item.id ASC.
-- Ordering by receipt_item.id alone is WRONG: a receipt created later can be confirmed earlier,
-- which would make the before/after replay order disagree with the occurred_at order.
-- The window SUM below therefore uses the SAME ordering as the INSERT output.

-- Step 1 (pre-check, Q13): refuse to run when one (warehouse, sku) mixes purchase units.
-- Failing the migration is the intended behaviour: silently summing 箱 + kg would produce a
-- balance with no physical meaning, and the damage would only surface at the next stocktake.
DO $$
DECLARE
    conflicting integer;
    detail      text;
BEGIN
    SELECT count(*), COALESCE(string_agg(conflict, '; '), '')
    INTO conflicting, detail
    FROM (
        SELECT format('warehouse_id=%s sku_id=%s units=[%s]',
                      h.warehouse_id, h.sku_id,
                      string_agg(DISTINCT h.unit, ', ' ORDER BY h.unit)) AS conflict
        FROM (
            SELECT ro.warehouse_id, ri.sku_id, ri.purchase_unit_snapshot AS unit
            FROM purchase_receipt_item ri
            JOIN purchase_receipt r       ON r.id  = ri.purchase_receipt_id    AND r.deleted  = FALSE
            JOIN purchase_order ro        ON ro.id = r.purchase_order_id       AND ro.deleted = FALSE
            WHERE r.status = 'CONFIRMED' AND ri.deleted = FALSE AND ri.received_quantity > 0
        ) h
        GROUP BY h.warehouse_id, h.sku_id
        HAVING count(DISTINCT h.unit) > 1
    ) c;

    IF conflicting > 0 THEN
        RAISE EXCEPTION
            'V19 backfill aborted: % (warehouse, sku) pair(s) mix purchase units and cannot be '
            'aggregated into one inventory balance (Q13 inventory unit invariant). Details: %',
            conflicting, detail;
    END IF;
END $$;

-- Step 2: movements. occurred_at = receipt.confirmed_at, operator = receipt.operator
-- (the frozen收货确认 fact, never now()/ambient operator).
INSERT INTO inventory_movement (
    warehouse_id, sku_id, movement_type,
    source_document_type, source_document_id, source_document_item_id,
    quantity, unit_snapshot, unit_cost,
    before_quantity, after_quantity, occurred_at, operator,
    deleted, created_at, created_by)
SELECT replayed.warehouse_id,
       replayed.sku_id,
       'PURCHASE_IN',
       'PURCHASE_RECEIPT_ITEM',
       replayed.receipt_id,
       replayed.receipt_item_id,
       replayed.quantity,
       replayed.unit,
       replayed.unit_cost,
       replayed.before_quantity,
       replayed.before_quantity + replayed.quantity,
       replayed.confirmed_at,
       replayed.operator,
       FALSE,
       CURRENT_TIMESTAMP,
       'migration:V19'
FROM (
    SELECT h.*,
           -- Same ORDER BY as the outer ORDER BY / the INSERT output order.
           COALESCE(SUM(h.quantity) OVER (
               PARTITION BY h.warehouse_id, h.sku_id
               ORDER BY h.confirmed_at ASC, h.receipt_id ASC, h.receipt_item_id ASC
               ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING), 0) AS before_quantity
    FROM (
        SELECT ri.id                     AS receipt_item_id,
               r.id                      AS receipt_id,
               r.confirmed_at            AS confirmed_at,
               r.operator                AS operator,
               ro.warehouse_id           AS warehouse_id,
               ri.sku_id                 AS sku_id,
               ri.purchase_unit_snapshot AS unit,
               ri.received_quantity      AS quantity,
               oi.purchase_price         AS unit_cost
        FROM purchase_receipt_item ri
        JOIN purchase_receipt r     ON r.id  = ri.purchase_receipt_id       AND r.deleted  = FALSE
        JOIN purchase_order ro      ON ro.id = r.purchase_order_id          AND ro.deleted = FALSE
        JOIN purchase_order_item oi ON oi.id = ri.purchase_order_item_id    AND oi.deleted = FALSE
        WHERE r.status = 'CONFIRMED'
          AND ri.deleted = FALSE
          -- Defensive: confirm() guarantees effective > 0 (40083), and the movement CHECK
          -- requires quantity > 0. A zero line moves nothing, so it produces no movement.
          AND ri.received_quantity > 0
    ) h
) replayed
ORDER BY replayed.confirmed_at ASC, replayed.receipt_id ASC, replayed.receipt_item_id ASC
ON CONFLICT (source_document_type, source_document_item_id)
    WHERE deleted = FALSE AND source_document_item_id IS NOT NULL
DO NOTHING;

-- Step 3: balances derived from the movements just written. `min(unit_snapshot)` is exact because
-- the step-1 pre-check guarantees exactly one distinct unit per (warehouse_id, sku_id).
-- (The column is `unit_snapshot`, not `unit`: inventory_movement stores the frozen confirmation
-- snapshot, while inventory_balance holds the single live bookkeeping unit.)
INSERT INTO inventory_balance (
    warehouse_id, sku_id, unit, quantity,
    version, deleted, created_at, updated_at, created_by, updated_by)
SELECT m.warehouse_id,
       m.sku_id,
       min(m.unit_snapshot),
       sum(m.quantity),
       0,
       FALSE,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP,
       'migration:V19',
       'migration:V19'
FROM inventory_movement m
WHERE m.deleted = FALSE
GROUP BY m.warehouse_id, m.sku_id
ON CONFLICT (warehouse_id, sku_id) WHERE deleted = FALSE DO NOTHING;

-- Step 4: reconciliation assertions. The migration fails rather than leaving an unbalanced ledger.
DO $$
DECLARE
    missing_movements integer;
    balance_mismatch  integer;
BEGIN
    -- Every historical CONFIRMED receipt line must have exactly one matching movement.
    SELECT count(*) INTO missing_movements
    FROM purchase_receipt_item ri
    JOIN purchase_receipt r ON r.id = ri.purchase_receipt_id AND r.deleted = FALSE
    WHERE r.status = 'CONFIRMED'
      AND ri.deleted = FALSE
      AND ri.received_quantity > 0
      AND NOT EXISTS (
          SELECT 1 FROM inventory_movement m
          WHERE m.source_document_type = 'PURCHASE_RECEIPT_ITEM'
            AND m.source_document_item_id = ri.id
            AND m.deleted = FALSE
            AND m.quantity = ri.received_quantity);
    IF missing_movements > 0 THEN
        RAISE EXCEPTION
            'V19 backfill reconciliation failed: % confirmed receipt line(s) have no matching '
            'PURCHASE_IN movement', missing_movements;
    END IF;

    -- Ledger total per (warehouse, sku) must equal the balance row.
    SELECT count(*) INTO balance_mismatch
    FROM (
        SELECT m.warehouse_id, m.sku_id, sum(m.quantity) AS movement_total
        FROM inventory_movement m
        WHERE m.deleted = FALSE
        GROUP BY m.warehouse_id, m.sku_id
    ) mv
    FULL OUTER JOIN (
        SELECT b.warehouse_id, b.sku_id, b.quantity AS balance_total
        FROM inventory_balance b
        WHERE b.deleted = FALSE
    ) bal ON mv.warehouse_id = bal.warehouse_id AND mv.sku_id = bal.sku_id
    WHERE mv.movement_total IS DISTINCT FROM bal.balance_total;
    IF balance_mismatch > 0 THEN
        RAISE EXCEPTION
            'V19 backfill reconciliation failed: % (warehouse, sku) balance row(s) do not equal '
            'the movement ledger total', balance_mismatch;
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Comments (one per table and per column, same style as V13/V15)
-- ---------------------------------------------------------------------------
COMMENT ON TABLE inventory_balance IS 'W6 库存域：inventory_balance';
COMMENT ON COLUMN inventory_balance.id IS '库存域 id';
COMMENT ON COLUMN inventory_balance.warehouse_id IS '库存域 warehouse_id';
COMMENT ON COLUMN inventory_balance.sku_id IS '库存域 sku_id';
COMMENT ON COLUMN inventory_balance.unit IS '库存域 unit（Q13 记账单位，一个仓库+SKU 只允许一个）';
COMMENT ON COLUMN inventory_balance.quantity IS '库存域 quantity（Q10 冻结 >= 0）';
COMMENT ON COLUMN inventory_balance.version IS '库存域 version';
COMMENT ON COLUMN inventory_balance.deleted IS '库存域 deleted';
COMMENT ON COLUMN inventory_balance.created_at IS '库存域 created_at';
COMMENT ON COLUMN inventory_balance.updated_at IS '库存域 updated_at';
COMMENT ON COLUMN inventory_balance.created_by IS '库存域 created_by';
COMMENT ON COLUMN inventory_balance.updated_by IS '库存域 updated_by';

COMMENT ON TABLE inventory_movement IS 'W6 库存域：inventory_movement（append-only，Q7）';
COMMENT ON COLUMN inventory_movement.id IS '库存域 id';
COMMENT ON COLUMN inventory_movement.warehouse_id IS '库存域 warehouse_id';
COMMENT ON COLUMN inventory_movement.sku_id IS '库存域 sku_id';
COMMENT ON COLUMN inventory_movement.movement_type IS '库存域 movement_type（W6-1 仅 PURCHASE_IN）';
COMMENT ON COLUMN inventory_movement.source_document_type IS '库存域 source_document_type';
COMMENT ON COLUMN inventory_movement.source_document_id IS '库存域 source_document_id（头级溯源）';
COMMENT ON COLUMN inventory_movement.source_document_item_id IS '库存域 source_document_item_id（防重锚点）';
COMMENT ON COLUMN inventory_movement.quantity IS '库存域 quantity（恒为正）';
COMMENT ON COLUMN inventory_movement.unit_snapshot IS '库存域 unit_snapshot';
COMMENT ON COLUMN inventory_movement.unit_cost IS '库存域 unit_cost（采购成本事实快照，Q3）';
COMMENT ON COLUMN inventory_movement.before_quantity IS '库存域 before_quantity';
COMMENT ON COLUMN inventory_movement.after_quantity IS '库存域 after_quantity';
COMMENT ON COLUMN inventory_movement.occurred_at IS '库存域 occurred_at（= receipt.confirmed_at）';
COMMENT ON COLUMN inventory_movement.operator IS '库存域 operator（= receipt.operator）';
COMMENT ON COLUMN inventory_movement.deleted IS '库存域 deleted（CHECK 恒为 FALSE）';
COMMENT ON COLUMN inventory_movement.created_at IS '库存域 created_at';
COMMENT ON COLUMN inventory_movement.created_by IS '库存域 created_by';
