-- =====================================================================
-- V2 系统表基线 · PoC 核心表
-- 来源：SmartAdmin v3.31 数据库SQL脚本/mysql/smart_admin_v3.sql
-- 转换目标：PostgreSQL 18（identity / BOOLEAN / TIMESTAMP / COMMENT）
--
-- 转换规则（本文件及后续系统表转换统一遵守）：
--   1. bigint AUTO_INCREMENT  -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   2. tinyint(1) 0/1 标志位  -> BOOLEAN（与 Java Boolean 直接映射）
--   3. tinyint 非 0/1 枚举值  -> SMALLINT
--   4. int                    -> INTEGER
--   5. datetime ON UPDATE     -> TIMESTAMP（更新时间由 MybatisPlusFillHandler 维护）
--   6. 移除 ENGINE / CHARSET / COLLATE / ROW_FORMAT / USING BTREE / 显示宽度
--   7. UNIQUE KEY / INDEX    -> 显式命名约束与索引（PG 中索引名全局唯一）
--
-- PoC 范围：t_employee、t_menu、t_dict（+ t_dict_data 作为 t_dict 的子表，
-- 缺少它字典能力无法端到端验证）。
-- =====================================================================

-- ---------------------------------------------------------------------
-- t_employee 员工表
-- ---------------------------------------------------------------------
CREATE TABLE t_employee (
    employee_id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_uid       VARCHAR(100),
    login_name         VARCHAR(30)  NOT NULL,
    login_pwd          VARCHAR(100) NOT NULL,
    actual_name        VARCHAR(30)  NOT NULL,
    avatar             VARCHAR(200),
    gender             SMALLINT     NOT NULL DEFAULT 0,
    phone              VARCHAR(15),
    department_id      BIGINT       NOT NULL,
    position_id        BIGINT,
    email              VARCHAR(100),
    disabled_flag      BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_flag       BOOLEAN      NOT NULL DEFAULT FALSE,
    administrator_flag BOOLEAN      NOT NULL DEFAULT FALSE,
    remark             VARCHAR(200),
    update_time        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_employee_uid UNIQUE (employee_uid)
);

CREATE INDEX idx_t_employee_department_id ON t_employee (department_id);
CREATE INDEX idx_t_employee_login_name ON t_employee (login_name);

COMMENT ON TABLE t_employee IS '员工表';
COMMENT ON COLUMN t_employee.employee_id IS '主键';
COMMENT ON COLUMN t_employee.employee_uid IS '员工uuid';
COMMENT ON COLUMN t_employee.login_name IS '登录帐号';
COMMENT ON COLUMN t_employee.login_pwd IS '登录密码';
COMMENT ON COLUMN t_employee.actual_name IS '员工名称';
COMMENT ON COLUMN t_employee.gender IS '性别 0男 1女 2未知';
COMMENT ON COLUMN t_employee.department_id IS '部门id';
COMMENT ON COLUMN t_employee.position_id IS '职务ID';
COMMENT ON COLUMN t_employee.disabled_flag IS '是否被禁用';
COMMENT ON COLUMN t_employee.deleted_flag IS '是否删除';
COMMENT ON COLUMN t_employee.administrator_flag IS '是否为超级管理员';

-- ---------------------------------------------------------------------
-- t_menu 菜单表（菜单 + 功能点）
-- ---------------------------------------------------------------------
CREATE TABLE t_menu (
    menu_id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_name       VARCHAR(200)  NOT NULL,
    menu_type       INTEGER       NOT NULL,
    parent_id       BIGINT        NOT NULL,
    sort            INTEGER,
    path            VARCHAR(255),
    component       VARCHAR(255),
    perms_type      INTEGER,
    api_perms       VARCHAR(5000),
    web_perms       VARCHAR(5000),
    icon            VARCHAR(100),
    context_menu_id BIGINT,
    frame_flag      BOOLEAN       NOT NULL DEFAULT FALSE,
    frame_url       TEXT,
    cache_flag      BOOLEAN       NOT NULL DEFAULT FALSE,
    visible_flag    BOOLEAN       NOT NULL DEFAULT TRUE,
    disabled_flag   BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_flag    BOOLEAN       NOT NULL DEFAULT FALSE,
    create_user_id  BIGINT        NOT NULL,
    create_time     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_user_id  BIGINT,
    update_time     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_t_menu_parent_id ON t_menu (parent_id);
CREATE INDEX idx_t_menu_menu_type ON t_menu (menu_type);

COMMENT ON TABLE t_menu IS '菜单表';
COMMENT ON COLUMN t_menu.menu_type IS '类型 1目录 2菜单 3功能点';
COMMENT ON COLUMN t_menu.parent_id IS '父菜单ID';
COMMENT ON COLUMN t_menu.component IS '组件路径';
COMMENT ON COLUMN t_menu.perms_type IS '权限类型';
COMMENT ON COLUMN t_menu.api_perms IS '后端权限字符串';
COMMENT ON COLUMN t_menu.web_perms IS '前端权限字符串';
COMMENT ON COLUMN t_menu.context_menu_id IS '功能点关联菜单ID';
COMMENT ON COLUMN t_menu.frame_flag IS '是否为外链';
COMMENT ON COLUMN t_menu.cache_flag IS '是否缓存';
COMMENT ON COLUMN t_menu.visible_flag IS '显示状态';
COMMENT ON COLUMN t_menu.disabled_flag IS '禁用状态';
COMMENT ON COLUMN t_menu.deleted_flag IS '删除状态';

-- ---------------------------------------------------------------------
-- t_dict 字典表
-- ---------------------------------------------------------------------
CREATE TABLE t_dict (
    dict_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_name     VARCHAR(500)  NOT NULL,
    dict_code     VARCHAR(500)  NOT NULL,
    remark        VARCHAR(1000),
    disabled_flag BOOLEAN       NOT NULL DEFAULT FALSE,
    create_time   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_dict_code UNIQUE (dict_code)
);

COMMENT ON TABLE t_dict IS '字典表';
COMMENT ON COLUMN t_dict.dict_name IS '字典名字';
COMMENT ON COLUMN t_dict.dict_code IS '字典编码';
COMMENT ON COLUMN t_dict.disabled_flag IS '禁用状态';

-- ---------------------------------------------------------------------
-- t_dict_data 字典数据表（t_dict 的子表）
-- ---------------------------------------------------------------------
CREATE TABLE t_dict_data (
    dict_data_id  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_id       BIGINT        NOT NULL,
    data_value    VARCHAR(500)  NOT NULL,
    data_label    VARCHAR(500)  NOT NULL,
    data_style    VARCHAR(500),
    remark        VARCHAR(1000),
    sort_order    INTEGER       NOT NULL,
    disabled_flag BOOLEAN       NOT NULL DEFAULT FALSE,
    create_time   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_t_dict_data_dict_id ON t_dict_data (dict_id);

COMMENT ON TABLE t_dict_data IS '字典数据表';
COMMENT ON COLUMN t_dict_data.dict_id IS '字典id';
COMMENT ON COLUMN t_dict_data.data_value IS '字典项值';
COMMENT ON COLUMN t_dict_data.data_label IS '字典项显示名称';
COMMENT ON COLUMN t_dict_data.data_style IS '字典项样式';
COMMENT ON COLUMN t_dict_data.sort_order IS '排序（越大越靠前）';
