-- V25: 库存出库（独立出库单）与预留，2026-09-19。
--
-- 背景：W6-1 的 excludes 是阶段范围控制，不是需求否决。本轮把「出库 / 预留」纳入范围，
-- 其余（盘点、报损报溢、调拨、单位转换、阈值预警、成本核算）留待后续波次。
--
-- 本迁移做四件事，全部是**新增**，不改任何既有行：
--   1. 扩 inventory_movement 的类型白名单：加 SALES_OUT（销售出库）；
--   2. 重建 ck_inventory_movement_snap —— V19 写死了入库方向（after = before + quantity），
--      出库是减，必须改成方向感知，否则出库流水插不进去；
--   3. inventory_balance 增加 reserved_quantity，并强制「可用量不为负」；
--   4. 新建 inventory_outbound / inventory_outbound_item / inventory_reservation。
--
-- 口径说明：
--   * Q7 append-only 不变：出库也是**新增**流水，绝不改删历史行。
--   * Q10 不变：ck_inventory_balance_quantity (quantity >= 0) 继续生效 —— 本波次明确
--     「不允许负库存」，出库超量直接失败，不引入欠交。
--   * Q13 不变：出库单位必须与该 (warehouse, sku) 的记账单位一致，异单位失败（41001）。
--   * 预留**不进 inventory_movement**：那张表是物理数量账本（quantity 恒为正、方向编码在类型里），
--     预留不改变物理数量，塞进去会破坏 ck_inventory_movement_snap 的语义。预留单独建表，
--     并在 inventory_balance.reserved_quantity 上维护活状态计数。

-- ---------------------------------------------------------------------------
-- 1. 流水类型白名单：加 SALES_OUT
-- ---------------------------------------------------------------------------
ALTER TABLE inventory_movement DROP CONSTRAINT ck_inventory_movement_type;
ALTER TABLE inventory_movement ADD CONSTRAINT ck_inventory_movement_type
    CHECK (movement_type IN ('PURCHASE_IN', 'SALES_OUT'));

-- ---------------------------------------------------------------------------
-- 2. 快照约束改为方向感知（V19 只考虑了入库）
-- ---------------------------------------------------------------------------
ALTER TABLE inventory_movement DROP CONSTRAINT ck_inventory_movement_snap;
ALTER TABLE inventory_movement ADD CONSTRAINT ck_inventory_movement_snap
    CHECK (
        (movement_type = 'PURCHASE_IN' AND after_quantity = before_quantity + quantity)
        OR (movement_type = 'SALES_OUT' AND after_quantity = before_quantity - quantity)
    );

-- ---------------------------------------------------------------------------
-- 3. 余额：预留量 + 可用量不为负
-- ---------------------------------------------------------------------------
ALTER TABLE inventory_balance ADD COLUMN reserved_quantity NUMERIC(18,4) NOT NULL DEFAULT 0;

-- 预留量本身不为负
ALTER TABLE inventory_balance ADD CONSTRAINT ck_inventory_balance_reserved
    CHECK (reserved_quantity >= 0);

-- 可用量 = quantity - reserved_quantity >= 0，即「已预留的货不能被出库吃掉」。
-- 出库若会使可用量为负，DB 层直接拒绝；业务层会先给出可读的错误码。
ALTER TABLE inventory_balance ADD CONSTRAINT ck_inventory_balance_available
    CHECK (reserved_quantity <= quantity);

-- ---------------------------------------------------------------------------
-- 4a. 出库单（独立出库单，不依赖尚未开发的发货模块）
-- ---------------------------------------------------------------------------
CREATE TABLE inventory_outbound (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbound_no   VARCHAR(64)   NOT NULL,
    warehouse_id  BIGINT        NOT NULL,
    status        VARCHAR(20)   NOT NULL,
    remark        VARCHAR(500),
    confirmed_at  TIMESTAMPTZ,
    operator      VARCHAR(64),
    version       INTEGER       NOT NULL DEFAULT 0,
    deleted       BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(64),
    updated_by    VARCHAR(64),
    CONSTRAINT ck_inventory_outbound_status  CHECK (status IN ('DRAFT', 'CONFIRMED', 'CANCELLED')),
    CONSTRAINT ck_inventory_outbound_version CHECK (version >= 0),
    -- 已确认的出库单必须留下确认时刻与操作者（occurred_at 的来源，禁止用 now() 顶替）
    CONSTRAINT ck_inventory_outbound_confirm CHECK (
        status <> 'CONFIRMED'
        OR (confirmed_at IS NOT NULL AND operator IS NOT NULL AND btrim(operator) <> '')
    )
);
CREATE UNIQUE INDEX uk_inventory_outbound_no_active
    ON inventory_outbound (outbound_no) WHERE deleted = FALSE;
CREATE INDEX idx_inventory_outbound_warehouse ON inventory_outbound (warehouse_id);
CREATE INDEX idx_inventory_outbound_status ON inventory_outbound (status);

CREATE TABLE inventory_outbound_item (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbound_id    BIGINT        NOT NULL,
    sku_id         BIGINT        NOT NULL,
    quantity       NUMERIC(18,4) NOT NULL,
    unit_snapshot  VARCHAR(32),
    remark         VARCHAR(500),
    version        INTEGER       NOT NULL DEFAULT 0,
    deleted        BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by     VARCHAR(64),
    updated_by     VARCHAR(64),
    CONSTRAINT ck_inventory_outbound_item_qty     CHECK (quantity > 0),
    CONSTRAINT ck_inventory_outbound_item_version CHECK (version >= 0)
);
CREATE INDEX idx_inventory_outbound_item_outbound ON inventory_outbound_item (outbound_id);
CREATE INDEX idx_inventory_outbound_item_sku ON inventory_outbound_item (sku_id);

-- 出库单号序列：与 purchase_order_no_seq 等同一口径 —— 全局单调递增、不按日 reset。
-- 日期段只是可读性装饰，唯一性由序列本身保证；跳号（事务回滚）可接受。
CREATE SEQUENCE inventory_outbound_no_seq;

-- ---------------------------------------------------------------------------
-- 4b. 预留（挂在来源单据行上；本波次来源为销售订单行）
-- ---------------------------------------------------------------------------
-- 预留是**有状态记录**（ACTIVE → RELEASED / CONSUMED），不是 append-only 账本，
-- 因此它有 version / updated_* —— 与 inventory_movement 的只追加纪律不同，这是刻意的。
CREATE TABLE inventory_reservation (
    id                       BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id             BIGINT        NOT NULL,
    sku_id                   BIGINT        NOT NULL,
    source_document_type     VARCHAR(64)   NOT NULL,
    source_document_id       BIGINT        NOT NULL,
    source_document_item_id  BIGINT        NOT NULL,
    quantity                 NUMERIC(18,4) NOT NULL,
    unit_snapshot            VARCHAR(32)   NOT NULL,
    status                   VARCHAR(20)   NOT NULL,
    occurred_at              TIMESTAMPTZ   NOT NULL,
    operator                 VARCHAR(64),
    version                  INTEGER       NOT NULL DEFAULT 0,
    deleted                  BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at               TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64),
    updated_by               VARCHAR(64),
    CONSTRAINT ck_inventory_reservation_qty     CHECK (quantity > 0),
    CONSTRAINT ck_inventory_reservation_status  CHECK (status IN ('ACTIVE', 'RELEASED', 'CONSUMED')),
    CONSTRAINT ck_inventory_reservation_unit    CHECK (btrim(unit_snapshot) <> ''),
    CONSTRAINT ck_inventory_reservation_version CHECK (version >= 0)
);
-- 一条来源行只能有一条有效预留（防重锚点，与 movement 的索引同思路）
CREATE UNIQUE INDEX uk_inventory_reservation_source_active
    ON inventory_reservation (source_document_type, source_document_item_id)
    WHERE deleted = FALSE AND source_document_item_id IS NOT NULL;
CREATE INDEX idx_inventory_reservation_wh_sku ON inventory_reservation (warehouse_id, sku_id);
CREATE INDEX idx_inventory_reservation_source
    ON inventory_reservation (source_document_type, source_document_id);

-- ---------------------------------------------------------------------------
-- 5. 菜单与权限（data-only）
-- ---------------------------------------------------------------------------
-- menu_id 已核对：当前最大 824，故 803/804/812/813/825-829 均空闲。
--   803  出库单      页面 (parent 800 库存管理)
--   804  库存预留    页面 (parent 800 库存管理)
--   812  查询        (parent 803)
--   825  新建        (parent 803)
--   826  编辑        (parent 803)
--   827  确认出库    (parent 803)
--   828  删除        (parent 803)
--   813  查询        (parent 804)
--   829  释放        (parent 804)
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (803,'出库单',2,800,803,'/inventory/inventory-outbound-list','/business/scm/inventory/inventory-outbound-list.vue',NULL,NULL,NULL,'ExportOutlined',NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (804,'库存预留',2,800,804,'/inventory/inventory-reservation-list','/business/scm/inventory/inventory-reservation-list.vue',NULL,NULL,NULL,'LockOutlined',NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;

INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (812,'查询',3,803,812,NULL,NULL,1,'scm:inventory:outbound:query','scm:inventory:outbound:query',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (825,'新建',3,803,825,NULL,NULL,1,'scm:inventory:outbound:add','scm:inventory:outbound:add',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (826,'编辑',3,803,826,NULL,NULL,1,'scm:inventory:outbound:update','scm:inventory:outbound:update',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (827,'确认出库',3,803,827,NULL,NULL,1,'scm:inventory:outbound:confirm','scm:inventory:outbound:confirm',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (828,'删除',3,803,828,NULL,NULL,1,'scm:inventory:outbound:delete','scm:inventory:outbound:delete',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;

INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (813,'查询',3,804,813,NULL,NULL,1,'scm:inventory:reservation:query','scm:inventory:reservation:query',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (829,'释放',3,804,829,NULL,NULL,1,'scm:inventory:reservation:release','scm:inventory:reservation:release',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;

INSERT INTO t_role_menu(role_id,menu_id)
SELECT 1, m.menu_id FROM t_menu m
WHERE m.menu_id IN (803,804,812,813,825,826,827,828,829)
  AND NOT EXISTS (SELECT 1 FROM t_role_menu r WHERE r.role_id = 1 AND r.menu_id = m.menu_id);

SELECT setval(pg_get_serial_sequence('t_menu','menu_id'), (SELECT MAX(menu_id)+1 FROM t_menu), false);
