-- V29: 库存盘点（stocktake），2026-09-19。
--
-- 背景：出库 / 预留（V25）之后，「库存管理深化」的下一项是盘点。盘点单记录
-- 「账面量 vs 实盘量」的差异，并把差异转成不可变流水。本迁移**纯新增**，不改任何既有行。
--
-- 口径说明：
--   * Q7 append-only 不变：盘盈 / 盘亏都是**新增**流水，绝不改删历史行。
--   * 方向编码不变：quantity 恒为正，方向由 movement_type 表达 ——
--     STOCKTAKE_GAIN 入（盘盈）、STOCKTAKE_LOSS 出（盘亏）。
--   * Q10 不变：不允许负库存。盘亏导致调整后数量为负时直接失败（41024），
--     不引入「欠交」概念 —— 盘亏到负数说明盘点或入库记录本身有问题。
--   * Q13 不变：盘点的记账单位取该 (warehouse_id, sku_id) 的余额单位，
--     不允许在盘点里做单位换算。
--   * 预留不受影响：盘点只改 quantity，不动 reserved_quantity；
--     但调整后必须满足 quantity >= reserved_quantity（41025 兜底）。
--
-- 差异语义（本波次的核心裁决）：
--   delta = actual_quantity - book_quantity        -- 清点发现的差异（账面量快照取自保存草稿那一刻）
--   after = live_quantity  + delta                 -- live 是确认瞬间持锁读到的账面量
--   即：**把「清点发现的差异」施加到当前账面量上**，而不是直接把账面量改写成实盘数。
--   这样在「保存草稿 → 确认」之间发生的收货 / 出库不会被盘点悄悄抹掉。
--   若期间无任何变动（live == book_quantity），after 恰好等于实盘数 —— 符合直觉。
--   两种量都在单据行上留痕（book_quantity / actual_quantity），
--   流水的 before/after 则是确认瞬间的真实账面，漂移完全可审计。

-- ---------------------------------------------------------------------------
-- 1. 流水类型白名单：加 STOCKTAKE_GAIN / STOCKTAKE_LOSS
-- ---------------------------------------------------------------------------
ALTER TABLE inventory_movement DROP CONSTRAINT ck_inventory_movement_type;
ALTER TABLE inventory_movement ADD CONSTRAINT ck_inventory_movement_type
    CHECK (movement_type IN ('PURCHASE_IN', 'SALES_OUT', 'STOCKTAKE_GAIN', 'STOCKTAKE_LOSS'));

-- ---------------------------------------------------------------------------
-- 2. 快照约束扩到四个方向分支（V19 只有入库分支，V25 补了出库分支）
-- ---------------------------------------------------------------------------
ALTER TABLE inventory_movement DROP CONSTRAINT ck_inventory_movement_snap;
ALTER TABLE inventory_movement ADD CONSTRAINT ck_inventory_movement_snap
    CHECK (
        (movement_type = 'PURCHASE_IN'     AND after_quantity = before_quantity + quantity)
        OR (movement_type = 'SALES_OUT'      AND after_quantity = before_quantity - quantity)
        OR (movement_type = 'STOCKTAKE_GAIN' AND after_quantity = before_quantity + quantity)
        OR (movement_type = 'STOCKTAKE_LOSS' AND after_quantity = before_quantity - quantity)
    );

-- ---------------------------------------------------------------------------
-- 3a. 盘点单
-- ---------------------------------------------------------------------------
-- 状态机刻意最小（与出库单同构）：DRAFT → CONFIRMED，草稿可 → CANCELLED。
-- 已确认不可回退 —— 流水 append-only，冲销必须新增反向流水。
CREATE TABLE inventory_stocktake (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stocktake_no  VARCHAR(64)   NOT NULL,
    warehouse_id  BIGINT        NOT NULL,
    status        VARCHAR(20)   NOT NULL,
    remark        VARCHAR(500),
    confirmed_at  TIMESTAMPTZ,
    operator      VARCHAR(64),
    version       INTEGER       NOT NULL DEFAULT 0,
    deleted       BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(64),
    updated_by    VARCHAR(64),
    CONSTRAINT ck_inventory_stocktake_status  CHECK (status IN ('DRAFT', 'CONFIRMED', 'CANCELLED')),
    CONSTRAINT ck_inventory_stocktake_version CHECK (version >= 0),
    -- 已确认的盘点单必须留下确认时刻与操作者（流水 occurred_at 的来源，禁止用 now() 顶替）
    CONSTRAINT ck_inventory_stocktake_confirm CHECK (
        status <> 'CONFIRMED'
        OR (confirmed_at IS NOT NULL AND operator IS NOT NULL AND btrim(operator) <> '')
    )
);
CREATE UNIQUE INDEX uk_inventory_stocktake_no_active
    ON inventory_stocktake (stocktake_no) WHERE deleted = FALSE;
CREATE INDEX idx_inventory_stocktake_warehouse ON inventory_stocktake (warehouse_id);
CREATE INDEX idx_inventory_stocktake_status ON inventory_stocktake (status);

CREATE TABLE inventory_stocktake_item (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stocktake_id     BIGINT        NOT NULL,
    sku_id           BIGINT        NOT NULL,
    -- 账面量快照：保存草稿那一刻该 (仓库, SKU) 的余额数量。既是清点时的参考值，
    -- 也是 delta 的基线。允许为 0（余额行存在但数量为 0 时仍可盘盈）。
    book_quantity    NUMERIC(18,4) NOT NULL,
    -- 实盘量：清点结果。允许为 0（确实一件不剩），但不允许为负。
    actual_quantity  NUMERIC(18,4) NOT NULL,
    unit_snapshot    VARCHAR(32),
    remark           VARCHAR(500),
    version          INTEGER       NOT NULL DEFAULT 0,
    deleted          BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(64),
    updated_by       VARCHAR(64),
    CONSTRAINT ck_inventory_stocktake_item_book   CHECK (book_quantity >= 0),
    CONSTRAINT ck_inventory_stocktake_item_actual CHECK (actual_quantity >= 0),
    CONSTRAINT ck_inventory_stocktake_item_version CHECK (version >= 0)
);
CREATE INDEX idx_inventory_stocktake_item_stocktake ON inventory_stocktake_item (stocktake_id);
CREATE INDEX idx_inventory_stocktake_item_sku ON inventory_stocktake_item (sku_id);

-- 盘点单号序列：与 inventory_outbound_no_seq 同一口径 —— 全局单调递增、不按日 reset。
-- 日期段只是可读性装饰，唯一性由序列本身保证；跳号（事务回滚）可接受。
CREATE SEQUENCE inventory_stocktake_no_seq;

-- ---------------------------------------------------------------------------
-- 4. 表与列注释（V24 建立的 100% 覆盖纪律，新表必须自带）
-- ---------------------------------------------------------------------------
COMMENT ON TABLE inventory_stocktake IS '库存盘点单（头）';
COMMENT ON COLUMN inventory_stocktake.id IS '主键';
COMMENT ON COLUMN inventory_stocktake.stocktake_no IS '盘点单号，业务唯一（软删范围内）';
COMMENT ON COLUMN inventory_stocktake.warehouse_id IS '盘点仓库';
COMMENT ON COLUMN inventory_stocktake.status IS '状态：DRAFT 草稿 / CONFIRMED 已确认 / CANCELLED 已取消';
COMMENT ON COLUMN inventory_stocktake.remark IS '备注';
COMMENT ON COLUMN inventory_stocktake.confirmed_at IS '确认时刻，仅已确认非空';
COMMENT ON COLUMN inventory_stocktake.operator IS '确认人，仅已确认非空';
COMMENT ON COLUMN inventory_stocktake.version IS '乐观锁版本号';
COMMENT ON COLUMN inventory_stocktake.deleted IS '逻辑删除标记';
COMMENT ON COLUMN inventory_stocktake.created_at IS '创建时间';
COMMENT ON COLUMN inventory_stocktake.updated_at IS '更新时间';
COMMENT ON COLUMN inventory_stocktake.created_by IS '创建人';
COMMENT ON COLUMN inventory_stocktake.updated_by IS '更新人';

COMMENT ON TABLE inventory_stocktake_item IS '库存盘点单明细（账面量 vs 实盘量）';
COMMENT ON COLUMN inventory_stocktake_item.id IS '主键';
COMMENT ON COLUMN inventory_stocktake_item.stocktake_id IS '所属盘点单 id';
COMMENT ON COLUMN inventory_stocktake_item.sku_id IS '盘点 SKU';
COMMENT ON COLUMN inventory_stocktake_item.book_quantity IS '账面量快照（保存草稿那一刻的余额数量），差异计算的基线';
COMMENT ON COLUMN inventory_stocktake_item.actual_quantity IS '实盘量，清点结果，不允许为负';
COMMENT ON COLUMN inventory_stocktake_item.unit_snapshot IS '记账单位快照，确认时按余额单位写入';
COMMENT ON COLUMN inventory_stocktake_item.remark IS '备注';
COMMENT ON COLUMN inventory_stocktake_item.version IS '乐观锁版本号';
COMMENT ON COLUMN inventory_stocktake_item.deleted IS '逻辑删除标记';
COMMENT ON COLUMN inventory_stocktake_item.created_at IS '创建时间';
COMMENT ON COLUMN inventory_stocktake_item.updated_at IS '更新时间';
COMMENT ON COLUMN inventory_stocktake_item.created_by IS '创建人';
COMMENT ON COLUMN inventory_stocktake_item.updated_by IS '更新人';

-- ---------------------------------------------------------------------------
-- 5. 菜单与权限（data-only）
-- ---------------------------------------------------------------------------
-- menu_id 已核对：查询时库中最大为 829，故 830-835 空闲。
--   830  盘点单      页面 (parent 800 库存管理)
--   831  查询        (parent 830)
--   832  新建        (parent 830)
--   833  编辑        (parent 830)
--   834  确认盘点    (parent 830)
--   835  删除        (parent 830)
-- 取消复用 :update 权限（与出库单同一取向）。
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (830,'盘点单',2,800,830,'/inventory/inventory-stocktake-list','/business/scm/inventory/inventory-stocktake-list.vue',NULL,NULL,NULL,'AuditOutlined',NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;

INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (831,'查询',3,830,831,NULL,NULL,1,'scm:inventory:stocktake:query','scm:inventory:stocktake:query',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (832,'新建',3,830,832,NULL,NULL,1,'scm:inventory:stocktake:add','scm:inventory:stocktake:add',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (833,'编辑',3,830,833,NULL,NULL,1,'scm:inventory:stocktake:update','scm:inventory:stocktake:update',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (834,'确认盘点',3,830,834,NULL,NULL,1,'scm:inventory:stocktake:confirm','scm:inventory:stocktake:confirm',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (835,'删除',3,830,835,NULL,NULL,1,'scm:inventory:stocktake:delete','scm:inventory:stocktake:delete',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;

INSERT INTO t_role_menu(role_id,menu_id)
SELECT 1, m.menu_id FROM t_menu m
WHERE m.menu_id IN (830,831,832,833,834,835)
  AND NOT EXISTS (SELECT 1 FROM t_role_menu r WHERE r.role_id = 1 AND r.menu_id = m.menu_id);

SELECT setval(pg_get_serial_sequence('t_menu','menu_id'), (SELECT MAX(menu_id)+1 FROM t_menu), false);
