-- V30: 库存报损 / 报溢，2026-09-19。
--
-- 背景：盘点（V29）之后，「库存管理深化」的下一项是报损报溢。它复用盘点的
-- 「审批 → 方向编码流水」骨架，但语义不同：
--   * 盘点 = 账面 vs 实盘的**对比**，差异是算出来的；
--   * 报损 / 报溢 = 对损耗 / 溢余的**直接申报**，数量是申报的，而且必须写明原因。
-- 因此本波次引入**审批状态机**（待审核 → 已完成 / 已驳回），这是盘点没有的环节。
--
-- 参考口径：参考项目 `t_stock_adjust`（`adjust_type` 报损 / 报溢 / 盘点调整 / 规格转换；
-- 状态 待审核 / 已完成 / 已驳回；单号 BSD / BYD / ZHD + yyyyMMdd + 流水）。
-- 本波次**有意与参考项目不同**的四处（都是刻意的，不是遗漏）：
--   1. 报损报溢**单独建表**，不与盘点调整 / 规格转换混在一张表里 ——
--      V2 的盘点是独立模块（`inventory_stocktake`，状态机 DRAFT/CONFIRMED），
--      规格转换尚未开发。把三种语义塞回一张表会让状态机无法统一。
--   2. **多行明细**（头 + 行）而不是参考的单行单据：一次报损往往覆盖多个 SKU
--      （同一批到货一起变质），逐 SKU 开单会让仓库无法一次录完。
--   3. 不含 `weight`：Q2 裁决「数量 = 采购单位口径（非标品实重即数量）」，
--      双记账属分拣波次，本表不提前引入重量列。
--   4. 参考项目允许在**任意状态**下 update / delete（无状态守卫），这会让
--      「已完成的单据」被改内容或被删掉，而流水已经写入 —— 账与单从此对不上。
--      本波次对 update / delete 都加状态守卫（仅 PENDING 可改可删）。
--
-- 口径说明：
--   * Q7 append-only 不变：报损 / 报溢都是**新增**流水，绝不改删历史行。
--   * 方向编码不变：quantity 恒为正，`LOSS_REPORT` 出、`GAIN_REPORT` 入。
--   * Q10 不变：报损不得把库存推成负数（41033），也不得吃掉已预留的货（41034）。
--   * Q13 不变：记账单位取该 (warehouse_id, sku_id) 的余额单位，不做换算。
--   * 不建零余额行：记账单位只能来自余额行，从未入库的 SKU 报 41032。

-- ---------------------------------------------------------------------------
-- 1. 流水类型白名单：加 LOSS_REPORT / GAIN_REPORT
-- ---------------------------------------------------------------------------
ALTER TABLE inventory_movement DROP CONSTRAINT ck_inventory_movement_type;
ALTER TABLE inventory_movement ADD CONSTRAINT ck_inventory_movement_type
    CHECK (movement_type IN ('PURCHASE_IN', 'SALES_OUT', 'STOCKTAKE_GAIN', 'STOCKTAKE_LOSS',
                             'LOSS_REPORT', 'GAIN_REPORT'));

-- ---------------------------------------------------------------------------
-- 2. 快照约束扩到六个方向分支
-- ---------------------------------------------------------------------------
-- 这次改成「按方向分组」的写法而不是逐类型 OR：
--   每个类型必须**恰好落在一个方向组里**。若有人扩了白名单却忘了在本约束里分类，
--   两个分支都不成立 → 该类型的流水根本插不进去，是**响亮的失败**而不是静默错账。
ALTER TABLE inventory_movement DROP CONSTRAINT ck_inventory_movement_snap;
ALTER TABLE inventory_movement ADD CONSTRAINT ck_inventory_movement_snap
    CHECK (
        (movement_type IN ('PURCHASE_IN', 'STOCKTAKE_GAIN', 'GAIN_REPORT')
             AND after_quantity = before_quantity + quantity)
        OR (movement_type IN ('SALES_OUT', 'STOCKTAKE_LOSS', 'LOSS_REPORT')
             AND after_quantity = before_quantity - quantity)
    );

-- ---------------------------------------------------------------------------
-- 3a. 报损报溢单（头）
-- ---------------------------------------------------------------------------
CREATE TABLE inventory_loss_gain (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loss_gain_no   VARCHAR(64)   NOT NULL,
    warehouse_id   BIGINT        NOT NULL,
    adjust_type    VARCHAR(20)   NOT NULL,
    status         VARCHAR(20)   NOT NULL,
    reason         VARCHAR(200)  NOT NULL,
    remark         VARCHAR(500),
    audited_at     TIMESTAMPTZ,
    auditor        VARCHAR(64),
    audit_opinion  VARCHAR(500),
    version        INTEGER       NOT NULL DEFAULT 0,
    deleted        BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by     VARCHAR(64),
    updated_by     VARCHAR(64),
    CONSTRAINT ck_inventory_loss_gain_type    CHECK (adjust_type IN ('LOSS', 'OVERFLOW')),
    CONSTRAINT ck_inventory_loss_gain_status  CHECK (status IN ('PENDING', 'COMPLETED', 'REJECTED')),
    -- 报损报溢必须写明原因：没有原因的单据无法审计，「留痕」也就没有内容。
    -- 在 DB 层再挡一次是因为这个字段是审批人唯一的判断依据，不能只靠表单校验。
    CONSTRAINT ck_inventory_loss_gain_reason  CHECK (btrim(reason) <> ''),
    -- 已审核（通过或驳回）必须留下审核时刻与审核人；待审核则必须为空。
    CONSTRAINT ck_inventory_loss_gain_audit   CHECK (
        (status = 'PENDING' AND audited_at IS NULL AND auditor IS NULL)
        OR (status <> 'PENDING' AND audited_at IS NOT NULL
            AND auditor IS NOT NULL AND btrim(auditor) <> '')
    ),
    CONSTRAINT ck_inventory_loss_gain_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_inventory_loss_gain_no_active
    ON inventory_loss_gain (loss_gain_no) WHERE deleted = FALSE;
CREATE INDEX idx_inventory_loss_gain_warehouse ON inventory_loss_gain (warehouse_id);
CREATE INDEX idx_inventory_loss_gain_status ON inventory_loss_gain (status);
CREATE INDEX idx_inventory_loss_gain_type ON inventory_loss_gain (adjust_type);

CREATE TABLE inventory_loss_gain_item (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loss_gain_id  BIGINT        NOT NULL,
    sku_id        BIGINT        NOT NULL,
    quantity      NUMERIC(18,4) NOT NULL,
    unit_snapshot VARCHAR(32),
    remark        VARCHAR(500),
    version       INTEGER       NOT NULL DEFAULT 0,
    deleted       BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(64),
    updated_by    VARCHAR(64),
    -- 申报数量恒为正：方向由单据的 adjust_type 决定，不由数量正负表达
    CONSTRAINT ck_inventory_loss_gain_item_qty     CHECK (quantity > 0),
    CONSTRAINT ck_inventory_loss_gain_item_version CHECK (version >= 0)
);
CREATE INDEX idx_inventory_loss_gain_item_doc ON inventory_loss_gain_item (loss_gain_id);
CREATE INDEX idx_inventory_loss_gain_item_sku ON inventory_loss_gain_item (sku_id);

-- 单号序列：与 inventory_outbound_no_seq / inventory_stocktake_no_seq 同一口径 ——
-- 全局单调递增、不按日 reset；日期段只是可读性装饰，跳号（事务回滚）可接受。
CREATE SEQUENCE inventory_loss_gain_no_seq;

-- ---------------------------------------------------------------------------
-- 4. 表与列注释（V24 建立的 100% 覆盖纪律，新表必须自带）
-- ---------------------------------------------------------------------------
COMMENT ON TABLE inventory_loss_gain IS '库存报损报溢单（头），含审批状态机';
COMMENT ON COLUMN inventory_loss_gain.id IS '主键';
COMMENT ON COLUMN inventory_loss_gain.loss_gain_no IS '单据号，业务唯一（软删范围内）';
COMMENT ON COLUMN inventory_loss_gain.warehouse_id IS '仓库';
COMMENT ON COLUMN inventory_loss_gain.adjust_type IS '调整类型：LOSS 报损 / OVERFLOW 报溢';
COMMENT ON COLUMN inventory_loss_gain.status IS '状态：PENDING 待审核 / COMPLETED 已完成 / REJECTED 已驳回';
COMMENT ON COLUMN inventory_loss_gain.reason IS '报损报溢原因，必填（审批判断依据）';
COMMENT ON COLUMN inventory_loss_gain.remark IS '备注';
COMMENT ON COLUMN inventory_loss_gain.audited_at IS '审核时刻，仅已审核非空';
COMMENT ON COLUMN inventory_loss_gain.auditor IS '审核人，仅已审核非空';
COMMENT ON COLUMN inventory_loss_gain.audit_opinion IS '审核意见（驳回理由）';
COMMENT ON COLUMN inventory_loss_gain.version IS '乐观锁版本号，审批时用于防「读后被改」';
COMMENT ON COLUMN inventory_loss_gain.deleted IS '逻辑删除标记';
COMMENT ON COLUMN inventory_loss_gain.created_at IS '创建时间';
COMMENT ON COLUMN inventory_loss_gain.updated_at IS '更新时间';
COMMENT ON COLUMN inventory_loss_gain.created_by IS '创建人';
COMMENT ON COLUMN inventory_loss_gain.updated_by IS '更新人';

COMMENT ON TABLE inventory_loss_gain_item IS '库存报损报溢单明细';
COMMENT ON COLUMN inventory_loss_gain_item.id IS '主键';
COMMENT ON COLUMN inventory_loss_gain_item.loss_gain_id IS '所属单据 id';
COMMENT ON COLUMN inventory_loss_gain_item.sku_id IS 'SKU';
COMMENT ON COLUMN inventory_loss_gain_item.quantity IS '申报数量，恒为正，方向由单据 adjust_type 决定';
COMMENT ON COLUMN inventory_loss_gain_item.unit_snapshot IS '记账单位快照，审批通过时按余额单位写入';
COMMENT ON COLUMN inventory_loss_gain_item.remark IS '备注';
COMMENT ON COLUMN inventory_loss_gain_item.version IS '乐观锁版本号';
COMMENT ON COLUMN inventory_loss_gain_item.deleted IS '逻辑删除标记';
COMMENT ON COLUMN inventory_loss_gain_item.created_at IS '创建时间';
COMMENT ON COLUMN inventory_loss_gain_item.updated_at IS '更新时间';
COMMENT ON COLUMN inventory_loss_gain_item.created_by IS '创建人';
COMMENT ON COLUMN inventory_loss_gain_item.updated_by IS '更新人';

-- ---------------------------------------------------------------------------
-- 5. 菜单与权限（data-only）
-- ---------------------------------------------------------------------------
-- menu_id 已核对：查询时库中最大为 901（900/901 属数据大屏），故 840-846 空闲。
--   840  报损报溢    页面 (parent 800 库存管理)
--   841  查询        (parent 840)
--   842  新建        (parent 840)
--   843  编辑        (parent 840)
--   844  审批        (parent 840)
--   845  驳回        (parent 840)
--   846  删除        (parent 840)
-- 「审批」与「驳回」是**两个独立权限**（与参考项目一致）：允许主管审批、
-- 由另一角色驳回是常见分工；合成一个「审核」权限会让这两件事无法分权。
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (840,'报损报溢',2,800,840,'/inventory/inventory-loss-gain-list','/business/scm/inventory/inventory-loss-gain-list.vue',NULL,NULL,NULL,'WarningOutlined',NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;

INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (841,'查询',3,840,841,NULL,NULL,1,'scm:inventory:loss-gain:query','scm:inventory:loss-gain:query',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (842,'新建',3,840,842,NULL,NULL,1,'scm:inventory:loss-gain:add','scm:inventory:loss-gain:add',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (843,'编辑',3,840,843,NULL,NULL,1,'scm:inventory:loss-gain:update','scm:inventory:loss-gain:update',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (844,'审批',3,840,844,NULL,NULL,1,'scm:inventory:loss-gain:approve','scm:inventory:loss-gain:approve',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (845,'驳回',3,840,845,NULL,NULL,1,'scm:inventory:loss-gain:reject','scm:inventory:loss-gain:reject',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id,menu_name,menu_type,parent_id,sort,path,component,perms_type,api_perms,web_perms,icon,context_menu_id,visible_flag,create_user_id)
VALUES (846,'删除',3,840,846,NULL,NULL,1,'scm:inventory:loss-gain:delete','scm:inventory:loss-gain:delete',NULL,NULL,true,1) ON CONFLICT(menu_id) DO NOTHING;

INSERT INTO t_role_menu(role_id,menu_id)
SELECT 1, m.menu_id FROM t_menu m
WHERE m.menu_id IN (840,841,842,843,844,845,846)
  AND NOT EXISTS (SELECT 1 FROM t_role_menu r WHERE r.role_id = 1 AND r.menu_id = m.menu_id);

SELECT setval(pg_get_serial_sequence('t_menu','menu_id'), (SELECT MAX(menu_id)+1 FROM t_menu), false);
