-- V31: 库存调拨（跨仓，含在途状态），2026-09-19。
--
-- 背景：报损报溢（V30）之后，「库存管理深化」的下一项是调拨。
-- **参考项目里没有任何调拨实现**（`t_stock_adjust` 的 adjust_type 只有报损 / 报溢 /
-- 盘点调整 / 规格转换，也没有 transfer 表），因此本波次是 **V2 原创设计**，
-- 下面每一条口径都是裁决结果而不是沿袭。
--
-- 核心裁决：**两步式（发出 → 在途 → 收货）**，而不是一次事务内两边同时改。
--   1. 语义正确：货在卡车上时，既不在源仓也不在目标仓。一步式会让「发出」那一刻
--      目标仓就凭空多出库存，而货还没到 —— 那正是仓库最不能接受的账实不符。
--   2. 并发安全：两步各自只锁**一个仓库**的余额行，因此既有的
--      「按 (warehouse_id, sku_id) 升序锁余额」纪律完全不用改。
--      若做成一步式，同一事务要锁两个仓库的行，锁序规则就得升级为跨仓排序 ——
--      而那是四条既有写入路径都要跟着改的事。两步式把这个风险降到零。
--
-- 在途期的账面含义（**必须知道的事实**）：`inventory_balance` 只表达「在仓库里的货」，
-- 没有虚拟的「在途仓」。因此 SHIPPED 期间这批货**不在任何余额行里**，
-- 全仓总库存会暂时减少。这是两步式的必然结果，不是缺陷；要让它可见需要引入
-- 「在途仓」这个虚拟仓库，属未决事项（见 docs/decisions.md）。
--
-- 单位口径（Q13 的延伸）：
--   * 发出时取**源仓**的记账单位写入明细行快照；
--   * 收货时断言**目标仓**的记账单位与快照一致，不一致直接失败（41044），
--     绝不做隐式换算 —— 换算属「单位转换」波次，不在本波次。
--   * 目标仓若从没有过该 SKU 的余额行，则由本次调入**建立**该行（单位取快照），
--     与采购入库同一取向：入是唯一允许建零余额行的方向。
--
-- 状态机：
--   DRAFT ──ship──▶ SHIPPED（在途）──receive──▶ RECEIVED
--     │
--     └──cancel──▶ CANCELLED
--   已发出（SHIPPED）**不可取消**：货已经物理离开了源仓，账上只能靠一张反向调拨单冲回，
--   不能把状态改回草稿再删流水（那会被 trg_inventory_movement_append_only 拒绝）。
--
-- 其余口径：
--   * Q7 append-only 不变：转出 / 转入都是**新增**流水。
--   * Q10 不变：转出不得让源仓变负（41043 兜底），也不得吃掉源仓已预留的货。
--   * 源仓 == 目标仓直接拒绝（41042）：那不是调拨，是把货搬来搬去。

-- ---------------------------------------------------------------------------
-- 1. 流水类型白名单：加 TRANSFER_OUT / TRANSFER_IN
-- ---------------------------------------------------------------------------
ALTER TABLE inventory_movement
    DROP CONSTRAINT ck_inventory_movement_type;
ALTER TABLE inventory_movement
    ADD CONSTRAINT ck_inventory_movement_type
        CHECK (movement_type IN ('PURCHASE_IN', 'SALES_OUT', 'STOCKTAKE_GAIN', 'STOCKTAKE_LOSS',
                                 'LOSS_REPORT', 'GAIN_REPORT', 'TRANSFER_OUT', 'TRANSFER_IN'));

-- ---------------------------------------------------------------------------
-- 2. 快照约束扩到八个方向分组
-- ---------------------------------------------------------------------------
ALTER TABLE inventory_movement
    DROP CONSTRAINT ck_inventory_movement_snap;
ALTER TABLE inventory_movement
    ADD CONSTRAINT ck_inventory_movement_snap
        CHECK (
            (movement_type IN ('PURCHASE_IN', 'STOCKTAKE_GAIN', 'GAIN_REPORT', 'TRANSFER_IN')
                AND after_quantity = before_quantity + quantity)
                OR (movement_type IN ('SALES_OUT', 'STOCKTAKE_LOSS', 'LOSS_REPORT', 'TRANSFER_OUT')
                AND after_quantity = before_quantity - quantity)
            );

-- ---------------------------------------------------------------------------
-- 3a. 调拨单（头）
-- ---------------------------------------------------------------------------
CREATE TABLE inventory_transfer
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_no       VARCHAR(64) NOT NULL,
    from_warehouse_id BIGINT      NOT NULL,
    to_warehouse_id   BIGINT      NOT NULL,
    status            VARCHAR(20) NOT NULL,
    remark            VARCHAR(500),
    shipped_at        TIMESTAMPTZ,
    shipped_by        VARCHAR(64),
    received_at       TIMESTAMPTZ,
    received_by       VARCHAR(64),
    version           INTEGER     NOT NULL DEFAULT 0,
    deleted           BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by        VARCHAR(64),
    updated_by        VARCHAR(64),
    CONSTRAINT ck_inventory_transfer_status CHECK (
        status IN ('DRAFT', 'SHIPPED', 'RECEIVED', 'CANCELLED')),
    -- 源仓与目标仓必须不同：相同的话那不是调拨，是把货在同一行余额上来回加减，
    -- 净效果为零却留下两条流水，纯属噪声。
    CONSTRAINT ck_inventory_transfer_distinct CHECK (from_warehouse_id <> to_warehouse_id),
    -- 已发出（含已收货）必须留下发出时刻与发出人 —— 转出流水的 occurred_at / operator 来源；
    -- 反向也必须成立：草稿 / 已取消**不得**带发出信息，否则「谁发的」可以被预先写脏。
    -- （V31 初版只写了正向，被 ScmInventoryMigrationIT 的第 5 个用例抓出来 —— 单侧判据
    --   在「草稿 + 预填发出人」这种组合下会通过，那正是要挡的情形。）
    CONSTRAINT ck_inventory_transfer_shipped CHECK (
        (status IN ('DRAFT', 'CANCELLED') AND shipped_at IS NULL AND shipped_by IS NULL)
            OR (status IN ('SHIPPED', 'RECEIVED') AND shipped_at IS NOT NULL
            AND shipped_by IS NOT NULL AND btrim(shipped_by) <> '')
        ),
    -- 已收货必须留下收货时刻与收货人；未收货时两者必须为空（同样是双侧判据）
    CONSTRAINT ck_inventory_transfer_received CHECK (
        (status = 'RECEIVED' AND received_at IS NOT NULL
            AND received_by IS NOT NULL AND btrim(received_by) <> '')
            OR (status <> 'RECEIVED' AND received_at IS NULL AND received_by IS NULL)
        ),
    CONSTRAINT ck_inventory_transfer_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_inventory_transfer_no_active
    ON inventory_transfer (transfer_no) WHERE deleted = FALSE;
CREATE INDEX idx_inventory_transfer_from ON inventory_transfer (from_warehouse_id);
CREATE INDEX idx_inventory_transfer_to ON inventory_transfer (to_warehouse_id);
CREATE INDEX idx_inventory_transfer_status ON inventory_transfer (status);

CREATE TABLE inventory_transfer_item
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id   BIGINT         NOT NULL,
    sku_id        BIGINT         NOT NULL,
    quantity      NUMERIC(18, 4) NOT NULL,
    unit_snapshot VARCHAR(32),
    remark        VARCHAR(500),
    version       INTEGER        NOT NULL DEFAULT 0,
    deleted       BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(64),
    updated_by    VARCHAR(64),
    -- 调拨数量恒为正：方向由「发出 / 收货」这个动作决定，不由数量正负表达
    CONSTRAINT ck_inventory_transfer_item_qty CHECK (quantity > 0),
    CONSTRAINT ck_inventory_transfer_item_version CHECK (version >= 0)
);
CREATE INDEX idx_inventory_transfer_item_doc ON inventory_transfer_item (transfer_id);
CREATE INDEX idx_inventory_transfer_item_sku ON inventory_transfer_item (sku_id);

-- 单号序列：与出库 / 盘点 / 报损报溢同一口径 —— 全局单调递增、不按日 reset。
CREATE SEQUENCE inventory_transfer_no_seq;

-- ---------------------------------------------------------------------------
-- 4. 表与列注释（V24 建立的 100% 覆盖纪律，新表必须自带）
-- ---------------------------------------------------------------------------
COMMENT ON TABLE inventory_transfer IS '库存调拨单（跨仓，两步式：发出 → 在途 → 收货）';
COMMENT ON COLUMN inventory_transfer.id IS '主键';
COMMENT ON COLUMN inventory_transfer.transfer_no IS '调拨单号，业务唯一（软删范围内）';
COMMENT ON COLUMN inventory_transfer.from_warehouse_id IS '源仓库（转出方）';
COMMENT ON COLUMN inventory_transfer.to_warehouse_id IS '目标仓库（转入方），必须与源仓不同';
COMMENT ON COLUMN inventory_transfer.status IS '状态：DRAFT 草稿 / SHIPPED 在途 / RECEIVED 已收货 / CANCELLED 已取消';
COMMENT ON COLUMN inventory_transfer.remark IS '备注';
COMMENT ON COLUMN inventory_transfer.shipped_at IS '发出时刻（= TRANSFER_OUT 流水的 occurred_at），仅已发出非空';
COMMENT ON COLUMN inventory_transfer.shipped_by IS '发出人（= TRANSFER_OUT 流水的 operator），仅已发出非空';
COMMENT ON COLUMN inventory_transfer.received_at IS '收货时刻（= TRANSFER_IN 流水的 occurred_at），仅已收货非空';
COMMENT ON COLUMN inventory_transfer.received_by IS '收货人（= TRANSFER_IN 流水的 operator），仅已收货非空';
COMMENT ON COLUMN inventory_transfer.version IS '乐观锁版本号';
COMMENT ON COLUMN inventory_transfer.deleted IS '逻辑删除标记';
COMMENT ON COLUMN inventory_transfer.created_at IS '创建时间';
COMMENT ON COLUMN inventory_transfer.updated_at IS '更新时间';
COMMENT ON COLUMN inventory_transfer.created_by IS '创建人';
COMMENT ON COLUMN inventory_transfer.updated_by IS '更新人';

COMMENT ON TABLE inventory_transfer_item IS '库存调拨单明细';
COMMENT ON COLUMN inventory_transfer_item.id IS '主键';
COMMENT ON COLUMN inventory_transfer_item.transfer_id IS '所属调拨单 id';
COMMENT ON COLUMN inventory_transfer_item.sku_id IS 'SKU';
COMMENT ON COLUMN inventory_transfer_item.quantity IS '调拨数量，恒为正';
COMMENT ON COLUMN inventory_transfer_item.unit_snapshot IS '记账单位快照，发出时取源仓单位；收货时断言目标仓单位与之一致';
COMMENT ON COLUMN inventory_transfer_item.remark IS '备注';
COMMENT ON COLUMN inventory_transfer_item.version IS '乐观锁版本号';
COMMENT ON COLUMN inventory_transfer_item.deleted IS '逻辑删除标记';
COMMENT ON COLUMN inventory_transfer_item.created_at IS '创建时间';
COMMENT ON COLUMN inventory_transfer_item.updated_at IS '更新时间';
COMMENT ON COLUMN inventory_transfer_item.created_by IS '创建人';
COMMENT ON COLUMN inventory_transfer_item.updated_by IS '更新人';

-- ---------------------------------------------------------------------------
-- 5. 菜单与权限（data-only）
-- ---------------------------------------------------------------------------
-- menu_id 已核对：查询时库中 847-899 空闲（900/901 属数据大屏），故 850-856 可用。
--   850  调拨单      页面 (parent 800 库存管理)
--   851  查询        (parent 850)
--   852  新建        (parent 850)
--   853  编辑        (parent 850)
--   854  发出        (parent 850)
--   855  收货        (parent 850)
--   856  删除        (parent 850)
-- 「发出」与「收货」是两个独立权限：跨仓调拨的常见分工是源仓发货、目标仓点收，
-- 由同一个人两头都确认会让在途数量失去复核。
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (850, '调拨单', 2, 800, 850, '/inventory/inventory-transfer-list',
        '/business/scm/inventory/inventory-transfer-list.vue', NULL, NULL, NULL, 'SwapOutlined', NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;

INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (851, '查询', 3, 850, 851, NULL, NULL, 1, 'scm:inventory:transfer:query', 'scm:inventory:transfer:query', NULL,
        NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (852, '新建', 3, 850, 852, NULL, NULL, 1, 'scm:inventory:transfer:add', 'scm:inventory:transfer:add', NULL, NULL,
        true, 1)
ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (853, '编辑', 3, 850, 853, NULL, NULL, 1, 'scm:inventory:transfer:update', 'scm:inventory:transfer:update', NULL,
        NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (854, '发出', 3, 850, 854, NULL, NULL, 1, 'scm:inventory:transfer:ship', 'scm:inventory:transfer:ship', NULL,
        NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (855, '收货', 3, 850, 855, NULL, NULL, 1, 'scm:inventory:transfer:receive', 'scm:inventory:transfer:receive',
        NULL, NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (856, '删除', 3, 850, 856, NULL, NULL, 1, 'scm:inventory:transfer:delete', 'scm:inventory:transfer:delete', NULL,
        NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;

INSERT INTO t_role_menu(role_id, menu_id)
SELECT 1, m.menu_id
FROM t_menu m
WHERE m.menu_id IN (850, 851, 852, 853, 854, 855, 856)
  AND NOT EXISTS (SELECT 1 FROM t_role_menu r WHERE r.role_id = 1 AND r.menu_id = m.menu_id);

SELECT setval(pg_get_serial_sequence('t_menu', 'menu_id'), (SELECT MAX(menu_id) + 1 FROM t_menu), false);
