-- V32: 库存阈值预警（配置 + 预警列表），2026-09-19。
--
-- 背景：调拨（V31）之后，「库存管理深化」的下一项是阈值预警。它是本阶段**唯一不改变库存**
-- 的能力：只有一张配置表 + 一个只读的预警列表，没有任何写入路径碰 inventory_balance。
--
-- 参考口径：参考项目把 `warn_min` / `warn_max` 放在 `t_stock_balance`（余额行）上，
-- 配 `NORMAL / LOW / HIGH` 三态，并注明「按商品 / 规格配置上下限（当前单仓库，无需按仓库分别配置）」。
-- 本波次**有意与参考项目不同**的四处（都是刻意的，不是遗漏）：
--
--   1. **阈值不放在 `inventory_balance` 上，单独建表**。
--      余额行是**派生状态**：它只能由流水产生，`InventoryBalanceDao` 里没有任何「建行 / 赋值」
--      方法（唯一的建行入口是入库与调拨转入的 `insertOnConflictDoNothing`）。
--      若把阈值放进余额表，配置路径就必须**为了写阈值而创建余额行** ——
--      那会造出「没有任何流水支撑的余额行」，直接破坏「余额是流水的净和」这条不变量。
--      单独建表后，配置路径完全不碰余额表。
--      （V19 的 W6-1 契约本来就有断言「inventory_balance 不含 warn_min / warn_max」，
--        本波次没有削弱它 —— 那条断言现在的含义更明确了：**预警配置刻意不在余额表上**。）
--
--   2. **按 (warehouse_id, sku_id) 配置，不是只按 SKU**。
--      参考项目的「单仓库」是 G-03 的范围限制，不是业务规则；V2 已经有跨仓调拨能力，
--      两仓的合理下限本来就可能不同（前置仓 vs 中心仓）。
--
--   3. **预警状态不落库，读时计算**。
--      参考项目写「余额变动后校验」。落库就意味着**六条**余额写入路径都要顺手维护这个状态，
--      而它完全可以由 (阈值, 余额) 推导出来 —— 落库只会多一个会漂移的副本。
--      因此 `NORMAL / LOW / HIGH` 是查询期算出来的派生值，不建列、不写表。
--
--   4. **比较基准是「可用量」而不是「现有量」**（可用量 = 现有量 − 预留量）。
--      下限预警的业务含义是「还够不够发货」：20 kg 在库但 18 kg 已预留给明天的订单，
--      可用只有 2 kg —— 这时**必须**触发补货预警。上限预警同理：货已经被订走就不算积压。
--      列表同时展示现有量 / 预留量 / 可用量，用户能看出预警为什么触发。
--
-- 口径说明：
--   * **预警列表由配置驱动**：只列出「配置了阈值的 (仓库, SKU)」。没有配置就没有预警 ——
--     否则每个 SKU × 每个仓库都会因为「没有余额行 = 0 < 下限」而刷屏。
--   * 配置了阈值但**没有余额行**时，现有量按 0 计 —— 那正是「设了下限却一件没有」，
--     应该预警，而且这是本波次能表达「还没进过货就要补货」的唯一方式。
--   * 上下限至少要有一个（都没有的配置没有意义）；下限不得大于上限（那会让所有状态都异常）。
--   * 本波次**不做推送 / 通知**：没有任何消息机制，`提醒` 落地为「一个随时可查的预警列表」。
--     推送采购 / 销售属未决事项。

-- ---------------------------------------------------------------------------
-- 1. 预警阈值配置
-- ---------------------------------------------------------------------------
CREATE TABLE inventory_warning_threshold
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT      NOT NULL,
    sku_id       BIGINT      NOT NULL,
    warn_min     NUMERIC(18, 4),
    warn_max     NUMERIC(18, 4),
    remark       VARCHAR(500),
    version      INTEGER     NOT NULL DEFAULT 0,
    deleted      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by   VARCHAR(64),
    updated_by   VARCHAR(64),
    -- 一条判据把四件事一次说清：至少一个边界存在、两个边界都非负、下限不高于上限。
    -- 分开写会变成四个约束，其中任何一个漏写都不会被其它约束发现。
    CONSTRAINT ck_inventory_warning_threshold_range CHECK (
        (warn_min IS NOT NULL OR warn_max IS NOT NULL)
            AND (warn_min IS NULL OR warn_min >= 0)
            AND (warn_max IS NULL OR warn_max >= 0)
            AND (warn_min IS NULL OR warn_max IS NULL OR warn_min <= warn_max)
        ),
    CONSTRAINT ck_inventory_warning_threshold_version CHECK (version >= 0)
);
-- 一个 (仓库, SKU) 只能有一条有效配置：两条配置会让「按哪条判断」变得没有答案。
CREATE UNIQUE INDEX uk_inventory_warning_threshold_wh_sku_active
    ON inventory_warning_threshold (warehouse_id, sku_id) WHERE deleted = FALSE;
CREATE INDEX idx_inventory_warning_threshold_warehouse
    ON inventory_warning_threshold (warehouse_id);
CREATE INDEX idx_inventory_warning_threshold_sku ON inventory_warning_threshold (sku_id);

-- ---------------------------------------------------------------------------
-- 2. 表与列注释（V24 建立的 100% 覆盖纪律）
-- ---------------------------------------------------------------------------
COMMENT ON TABLE inventory_warning_threshold IS '库存预警阈值配置（按仓库 + SKU；只读预警列表的数据来源）';
COMMENT ON COLUMN inventory_warning_threshold.id IS '主键';
COMMENT ON COLUMN inventory_warning_threshold.warehouse_id IS '仓库';
COMMENT ON COLUMN inventory_warning_threshold.sku_id IS 'SKU';
COMMENT ON COLUMN inventory_warning_threshold.warn_min IS '预警下限（可用量低于它触发 LOW）；可为空表示不设下限';
COMMENT ON COLUMN inventory_warning_threshold.warn_max IS '预警上限（可用量高于它触发 HIGH）；可为空表示不设上限';
COMMENT ON COLUMN inventory_warning_threshold.remark IS '备注';
COMMENT ON COLUMN inventory_warning_threshold.version IS '乐观锁版本号';
COMMENT ON COLUMN inventory_warning_threshold.deleted IS '逻辑删除标记';
COMMENT ON COLUMN inventory_warning_threshold.created_at IS '创建时间';
COMMENT ON COLUMN inventory_warning_threshold.updated_at IS '更新时间';
COMMENT ON COLUMN inventory_warning_threshold.created_by IS '创建人';
COMMENT ON COLUMN inventory_warning_threshold.updated_by IS '更新人';

-- ---------------------------------------------------------------------------
-- 3. 菜单与权限（data-only）
-- ---------------------------------------------------------------------------
-- menu_id 已核对：857-899 空闲（900/901 属数据大屏），故 860-866 可用。
--   860  库存预警      预警列表页 (parent 800 库存管理)
--   861  查询          (parent 860)
--   862  预警阈值      阈值配置页 (parent 800 库存管理)
--   863  查询          (parent 862)
--   864  新增          (parent 862)
--   865  编辑          (parent 862)
--   866  删除          (parent 862)
-- 两个页面 + 两组权限：预警列表是**只读**的日常查看（仓管每天看），
-- 阈值配置是**改规则**（改错了会让预警失效或刷屏），因此分开授权。
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (860, '库存预警', 2, 800, 860, '/inventory/inventory-warning-list',
        '/business/scm/inventory/inventory-warning-list.vue', NULL, NULL, NULL, 'AlertOutlined', NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (862, '预警阈值', 2, 800, 862, '/inventory/inventory-warning-threshold-list',
        '/business/scm/inventory/inventory-warning-threshold-list.vue', NULL, NULL, NULL, 'SettingOutlined', NULL, true,
        1)
ON CONFLICT(menu_id) DO NOTHING;

INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (861, '查询', 3, 860, 861, NULL, NULL, 1, 'scm:inventory:warning:query', 'scm:inventory:warning:query', NULL,
        NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;

INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (863, '查询', 3, 862, 863, NULL, NULL, 1, 'scm:inventory:threshold:query', 'scm:inventory:threshold:query', NULL,
        NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (864, '新增', 3, 862, 864, NULL, NULL, 1, 'scm:inventory:threshold:add', 'scm:inventory:threshold:add', NULL,
        NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (865, '编辑', 3, 862, 865, NULL, NULL, 1, 'scm:inventory:threshold:update', 'scm:inventory:threshold:update',
        NULL, NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (866, '删除', 3, 862, 866, NULL, NULL, 1, 'scm:inventory:threshold:delete', 'scm:inventory:threshold:delete',
        NULL, NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;

INSERT INTO t_role_menu(role_id, menu_id)
SELECT 1, m.menu_id
FROM t_menu m
WHERE m.menu_id IN (860, 861, 862, 863, 864, 865, 866)
  AND NOT EXISTS (SELECT 1 FROM t_role_menu r WHERE r.role_id = 1 AND r.menu_id = m.menu_id);

SELECT setval(pg_get_serial_sequence('t_menu', 'menu_id'), (SELECT MAX(menu_id) + 1 FROM t_menu), false);
