-- V33: 规格转换（整件拆零 / 组合拆分），2026-09-20。
--
-- 背景：阈值预警（V32）之后，「库存深化」的最后一项库存动作是规格转换。
-- 设计口径见 docs/requirements/2026-09-20-规格转换与成本核算设计.md。
--
-- **先更正一处既有错误口径**：此前在需求清单与 decisions.md 里写着「单位转换会推翻 Q13」。
-- 那是错的 —— 参考项目的规格转换（ConvertTypeEnum: SPLIT 整件拆零 / COMBINE 组合拆分）
-- 是**跨 SKU** 的（源规格 → 目标规格），两个 SKU 各自仍然只锁一个记账单位，
-- 因此 **Q13 不受影响、不需要重述**。
-- 真正会推翻 Q13 的是「同一 (warehouse_id, sku_id) 多单位记账」——需求里从未提出过它，
-- 本波次**明确排除**（引入后可用量 / 预留量 / 预警基准都要按单位分别维护，复杂度与收益不成比例）。
--
-- 业务形态：一次转换 = 一个仓库内、一张单、多行；每行是
-- 「源 SKU 出 N（单位 U₁） → 目标 SKU 入 M（单位 U₂）」。
-- 折算关系 N : M **由单据显式声明**，不做自动推断 —— 折算率是业务事实
-- （一箱到底是 9.5 kg 还是 10 kg 取决于供应商与批次），系统猜不出来，猜错会直接污染两边余额。
--
-- 状态机与报损报溢**刻意同构**（PENDING → COMPLETED / REJECTED）：
-- 参考项目也是三态；而且转换会把**两个 SKU** 的余额同时改掉，影响面比单纯报损更大，更需要制衡。
--
-- 口径说明：
--   * Q7 append-only 不变：转换出 / 转换入都是**新增**流水，修正靠反向转换单。
--   * Q10 不变：源 SKU 的可用量必须足够，不得变负、不得吃掉源 SKU 已预留的货。
--   * 源 SKU 的余额单位必须等于单据声明的 source_unit（不做隐式换算）。
--   * 目标 SKU 已有余额行时其单位必须等于 target_unit；没有则由本次转换**建立**
--     （入方向才允许建行，与采购入库 / 调拨转入同一取向）。
--   * 本波次**只保证数量按声明的折算关系变化**，不宣称重量或金额守恒
--     （V2 没有重量列（Q2）、也还没有成本核算（Q3））。

-- ---------------------------------------------------------------------------
-- 1. 流水类型白名单：加 CONVERT_OUT / CONVERT_IN
-- ---------------------------------------------------------------------------
ALTER TABLE inventory_movement
    DROP CONSTRAINT ck_inventory_movement_type;
ALTER TABLE inventory_movement
    ADD CONSTRAINT ck_inventory_movement_type
        CHECK (movement_type IN ('PURCHASE_IN', 'SALES_OUT', 'STOCKTAKE_GAIN', 'STOCKTAKE_LOSS',
                                 'LOSS_REPORT', 'GAIN_REPORT', 'TRANSFER_OUT', 'TRANSFER_IN',
                                 'CONVERT_OUT', 'CONVERT_IN'));

-- ---------------------------------------------------------------------------
-- 2. 快照约束扩到十个方向分组（每组 5 个）
-- ---------------------------------------------------------------------------
ALTER TABLE inventory_movement
    DROP CONSTRAINT ck_inventory_movement_snap;
ALTER TABLE inventory_movement
    ADD CONSTRAINT ck_inventory_movement_snap
        CHECK (
            (movement_type IN ('PURCHASE_IN', 'STOCKTAKE_GAIN', 'GAIN_REPORT', 'TRANSFER_IN', 'CONVERT_IN')
                AND after_quantity = before_quantity + quantity)
                OR (movement_type IN ('SALES_OUT', 'STOCKTAKE_LOSS', 'LOSS_REPORT', 'TRANSFER_OUT', 'CONVERT_OUT')
                AND after_quantity = before_quantity - quantity)
            );

-- ---------------------------------------------------------------------------
-- 3a. 规格转换单（头）
-- ---------------------------------------------------------------------------
CREATE TABLE inventory_conversion
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversion_no VARCHAR(64) NOT NULL,
    warehouse_id  BIGINT      NOT NULL,
    convert_type  VARCHAR(20) NOT NULL,
    status        VARCHAR(20) NOT NULL,
    reason        VARCHAR(200),
    remark        VARCHAR(500),
    audited_at    TIMESTAMPTZ,
    auditor       VARCHAR(64),
    audit_opinion VARCHAR(500),
    version       INTEGER     NOT NULL DEFAULT 0,
    deleted       BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(64),
    updated_by    VARCHAR(64),
    CONSTRAINT ck_inventory_conversion_type CHECK (convert_type IN ('SPLIT', 'COMBINE')),
    CONSTRAINT ck_inventory_conversion_status CHECK (status IN ('PENDING', 'COMPLETED', 'REJECTED')),
    -- 审核信息**双侧判据**：待审核不得带审核信息，其它状态必须带。
    -- （单侧写法在「待审核 + 预填审核人」这种组合下会通过，而那正是要挡的情形 ——
    --   V31 的 transfer_shipped 就在这里踩过一次。）
    CONSTRAINT ck_inventory_conversion_audit CHECK (
        (status = 'PENDING' AND audited_at IS NULL AND auditor IS NULL)
            OR (status <> 'PENDING' AND audited_at IS NOT NULL
            AND auditor IS NOT NULL AND btrim(auditor) <> '')
        ),
    CONSTRAINT ck_inventory_conversion_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_inventory_conversion_no_active
    ON inventory_conversion (conversion_no) WHERE deleted = FALSE;
CREATE INDEX idx_inventory_conversion_warehouse ON inventory_conversion (warehouse_id);
CREATE INDEX idx_inventory_conversion_status ON inventory_conversion (status);

CREATE TABLE inventory_conversion_item
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversion_id   BIGINT         NOT NULL,
    source_sku_id   BIGINT         NOT NULL,
    source_quantity NUMERIC(18, 4) NOT NULL,
    source_unit     VARCHAR(32)    NOT NULL,
    target_sku_id   BIGINT         NOT NULL,
    target_quantity NUMERIC(18, 4) NOT NULL,
    target_unit     VARCHAR(32)    NOT NULL,
    remark          VARCHAR(500),
    version         INTEGER        NOT NULL DEFAULT 0,
    deleted         BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(64),
    updated_by      VARCHAR(64),
    -- 源与目标必须是**两个不同的 SKU**：相同的话那不是转换，是把货在原地来回加减
    CONSTRAINT ck_inventory_conversion_item_distinct CHECK (source_sku_id <> target_sku_id),
    -- 两个数量都恒为正：方向由「出 / 入」决定，不由正负表达
    CONSTRAINT ck_inventory_conversion_item_qty CHECK (source_quantity > 0 AND target_quantity > 0),
    -- 单位快照不能是空白（折算关系本身就含单位，空单位等于没声明）
    CONSTRAINT ck_inventory_conversion_item_unit CHECK (
        btrim(source_unit) <> '' AND btrim(target_unit) <> ''),
    CONSTRAINT ck_inventory_conversion_item_version CHECK (version >= 0)
);
CREATE INDEX idx_inventory_conversion_item_doc ON inventory_conversion_item (conversion_id);
CREATE INDEX idx_inventory_conversion_item_source ON inventory_conversion_item (source_sku_id);
CREATE INDEX idx_inventory_conversion_item_target ON inventory_conversion_item (target_sku_id);

-- 单号序列：与出库 / 盘点 / 报损报溢 / 调拨同一口径 —— 全局单调递增、不按日 reset。
CREATE SEQUENCE inventory_conversion_no_seq;

-- ---------------------------------------------------------------------------
-- 4. 表与列注释（V24 建立的 100% 覆盖纪律）
-- ---------------------------------------------------------------------------
COMMENT ON TABLE inventory_conversion IS '规格转换单（整件拆零 / 组合拆分，跨 SKU、同仓库）';
COMMENT ON COLUMN inventory_conversion.id IS '主键';
COMMENT ON COLUMN inventory_conversion.conversion_no IS '转换单号，业务唯一（软删范围内）';
COMMENT ON COLUMN inventory_conversion.warehouse_id IS '仓库（源与目标 SKU 必须在同一仓库）';
COMMENT ON COLUMN inventory_conversion.convert_type IS '转换类型：SPLIT 整件拆零 / COMBINE 组合拆分';
COMMENT ON COLUMN inventory_conversion.status IS '状态：PENDING 待审核 / COMPLETED 已完成 / REJECTED 已驳回';
COMMENT ON COLUMN inventory_conversion.reason IS '转换原因';
COMMENT ON COLUMN inventory_conversion.remark IS '备注';
COMMENT ON COLUMN inventory_conversion.audited_at IS '审核时刻，仅已审核非空';
COMMENT ON COLUMN inventory_conversion.auditor IS '审核人，仅已审核非空';
COMMENT ON COLUMN inventory_conversion.audit_opinion IS '审核意见（驳回理由）';
COMMENT ON COLUMN inventory_conversion.version IS '乐观锁版本号，审批时用于防「读后被改」';
COMMENT ON COLUMN inventory_conversion.deleted IS '逻辑删除标记';
COMMENT ON COLUMN inventory_conversion.created_at IS '创建时间';
COMMENT ON COLUMN inventory_conversion.updated_at IS '更新时间';
COMMENT ON COLUMN inventory_conversion.created_by IS '创建人';
COMMENT ON COLUMN inventory_conversion.updated_by IS '更新人';

COMMENT ON TABLE inventory_conversion_item IS '规格转换单明细（每行 = 源 SKU 出 → 目标 SKU 入）';
COMMENT ON COLUMN inventory_conversion_item.id IS '主键';
COMMENT ON COLUMN inventory_conversion_item.conversion_id IS '所属转换单 id';
COMMENT ON COLUMN inventory_conversion_item.source_sku_id IS '源 SKU（转出方）';
COMMENT ON COLUMN inventory_conversion_item.source_quantity IS '源数量，恒为正';
COMMENT ON COLUMN inventory_conversion_item.source_unit IS '源单位（单据显式声明，必须与源 SKU 余额单位一致）';
COMMENT ON COLUMN inventory_conversion_item.target_sku_id IS '目标 SKU（转入方），必须与源 SKU 不同';
COMMENT ON COLUMN inventory_conversion_item.target_quantity IS '目标数量，恒为正；与源数量构成折算关系';
COMMENT ON COLUMN inventory_conversion_item.target_unit IS '目标单位（单据显式声明；目标 SKU 无余额行时用它建行）';
COMMENT ON COLUMN inventory_conversion_item.remark IS '备注';
COMMENT ON COLUMN inventory_conversion_item.version IS '乐观锁版本号';
COMMENT ON COLUMN inventory_conversion_item.deleted IS '逻辑删除标记';
COMMENT ON COLUMN inventory_conversion_item.created_at IS '创建时间';
COMMENT ON COLUMN inventory_conversion_item.updated_at IS '更新时间';
COMMENT ON COLUMN inventory_conversion_item.created_by IS '创建人';
COMMENT ON COLUMN inventory_conversion_item.updated_by IS '更新人';

-- ---------------------------------------------------------------------------
-- 5. 菜单与权限（data-only）
-- ---------------------------------------------------------------------------
-- menu_id 已核对：867-899 空闲（900/901 属数据大屏），故 870-876 可用。
--   870  规格转换    页面 (parent 800 库存管理)
--   871  查询 / 872 新建 / 873 编辑 / 874 审批 / 875 驳回 / 876 删除
-- 「审批」与「驳回」是两个独立权限（与报损报溢一致）：允许主管审批、由另一角色驳回是常见分工。
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (870, '规格转换', 2, 800, 870, '/inventory/inventory-conversion-list',
        '/business/scm/inventory/inventory-conversion-list.vue', NULL, NULL, NULL, 'SplitCellsOutlined', NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;

INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (871, '查询', 3, 870, 871, NULL, NULL, 1, 'scm:inventory:conversion:query', 'scm:inventory:conversion:query',
        NULL, NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (872, '新建', 3, 870, 872, NULL, NULL, 1, 'scm:inventory:conversion:add', 'scm:inventory:conversion:add', NULL,
        NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (873, '编辑', 3, 870, 873, NULL, NULL, 1, 'scm:inventory:conversion:update', 'scm:inventory:conversion:update',
        NULL, NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (874, '审批', 3, 870, 874, NULL, NULL, 1, 'scm:inventory:conversion:approve', 'scm:inventory:conversion:approve',
        NULL, NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (875, '驳回', 3, 870, 875, NULL, NULL, 1, 'scm:inventory:conversion:reject', 'scm:inventory:conversion:reject',
        NULL, NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type, api_perms, web_perms,
                   icon, context_menu_id, visible_flag, create_user_id)
VALUES (876, '删除', 3, 870, 876, NULL, NULL, 1, 'scm:inventory:conversion:delete', 'scm:inventory:conversion:delete',
        NULL, NULL, true, 1)
ON CONFLICT(menu_id) DO NOTHING;

INSERT INTO t_role_menu(role_id, menu_id)
SELECT 1, m.menu_id
FROM t_menu m
WHERE m.menu_id IN (870, 871, 872, 873, 874, 875, 876)
  AND NOT EXISTS (SELECT 1 FROM t_role_menu r WHERE r.role_id = 1 AND r.menu_id = m.menu_id);

SELECT setval(pg_get_serial_sequence('t_menu', 'menu_id'), (SELECT MAX(menu_id) + 1 FROM t_menu), false);
