-- V38: PCO-1 商品主档增强（product_spu 扩展标量 + master_status + 计量单位字典 + 商品标签），2026-09-20。
--
-- 方案见 docs/product-center-optimization-plan.md §8 / §10 / §12 / §13 / §18 / §36。
-- 本迁移只加**主数据**，不碰订单 / 采购 / 库存 / 价格任何一张事实表：
--   * master_status 与既有 status 正交 —— status 继续只表达「是否在售」，
--     master_status 表达「主数据是否可用」，两者组合才是完整语义（§10.3）。
--   * 计量单位字典只做**取值来源**：product_sku.sale_unit、supplier_sku.purchase_unit、
--     inventory_balance.unit 全部继续存字符串快照，本迁移不回写、不改类型（§8）。
--     因此 scm_uom 的 name 必须在其活动行内唯一，否则「按名称记账」会产生歧义。
--   * 标签是独立关系表，禁止退化成 product_spu.tag1/tag2（§12）。
-- 全部表沿用本项目约定：无外键、逻辑删除、乐观锁 version、TIMESTAMPTZ、
-- 金额与比率用 NUMERIC，关系列显式建索引。

-- ---------------------------------------------------------------------------
-- Step 1: product_spu 扩展为「供应链商品主档」
-- ---------------------------------------------------------------------------
-- 一对一稳定标量直接放行级：单独建扩展表只会让每次商品查询多一次 join，
-- 而这些字段本身就是商品主档属性（方案 §13.1）。
ALTER TABLE product_spu
    ADD COLUMN mnemonic_code         VARCHAR(64),
    ADD COLUMN brand_name            VARCHAR(100),
    ADD COLUMN origin                VARCHAR(100),
    ADD COLUMN storage_method        VARCHAR(20),
    ADD COLUMN shelf_life_days       INTEGER,
    ADD COLUMN loss_rate             NUMERIC(8, 4),
    ADD COLUMN purchase_warning_days INTEGER,
    ADD COLUMN invoice_name          VARCHAR(100),
    ADD COLUMN tax_category_code     VARCHAR(32),
    ADD COLUMN tax_exempt            BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN tax_rate              NUMERIC(8, 4),
    ADD COLUMN master_status         VARCHAR(16) NOT NULL DEFAULT 'ENABLED';

ALTER TABLE product_spu
    ADD CONSTRAINT ck_product_spu_master_status
        CHECK (master_status IN ('ENABLED', 'DISABLED', 'ARCHIVED'));
-- 归档即退出经营，不存在「已归档还在架」的商品；这条 CHECK 是 §10.3 禁止组合的 DB 级兜底，
-- 服务层的同名校验只为给出可解释的业务错误。
ALTER TABLE product_spu
    ADD CONSTRAINT ck_product_spu_archived_off_shelf
        CHECK (master_status <> 'ARCHIVED' OR status = 'OFF_SHELF');
ALTER TABLE product_spu
    ADD CONSTRAINT ck_product_spu_storage_method
        CHECK (storage_method IS NULL OR storage_method IN ('AMBIENT', 'CHILLED', 'FROZEN'));
ALTER TABLE product_spu
    ADD CONSTRAINT ck_product_spu_shelf_life
        CHECK (shelf_life_days IS NULL OR shelf_life_days >= 0);
ALTER TABLE product_spu
    ADD CONSTRAINT ck_product_spu_purchase_warning
        CHECK (purchase_warning_days IS NULL OR purchase_warning_days >= 0);
ALTER TABLE product_spu
    ADD CONSTRAINT ck_product_spu_loss_rate
        CHECK (loss_rate IS NULL OR (loss_rate >= 0 AND loss_rate <= 100));
ALTER TABLE product_spu
    ADD CONSTRAINT ck_product_spu_tax_rate
        CHECK (tax_rate IS NULL OR (tax_rate >= 0 AND tax_rate <= 100));

COMMENT ON COLUMN product_spu.mnemonic_code IS '助记码，运营维护的拼音/缩写，用于商品列表模糊搜索；系统不自动生成';
COMMENT ON COLUMN product_spu.brand_name IS '品牌名，首轮为自由文本，业务确认后再字典化';
COMMENT ON COLUMN product_spu.origin IS '商品产地，自由文本';
COMMENT ON COLUMN product_spu.storage_method IS '储存方式：AMBIENT 常温 / CHILLED 冷藏 / FROZEN 冷冻';
COMMENT ON COLUMN product_spu.shelf_life_days IS '保质期天数，NULL 表示未维护';
COMMENT ON COLUMN product_spu.loss_rate IS '损耗率百分比（0-100），仅主数据参考，不参与任何金额计算';
COMMENT ON COLUMN product_spu.purchase_warning_days IS '采购预警天数，供后续采购建议读取，本波次无消费方';
COMMENT ON COLUMN product_spu.invoice_name IS '开票品名';
COMMENT ON COLUMN product_spu.tax_category_code IS '税收分类编码';
COMMENT ON COLUMN product_spu.tax_exempt IS '是否免税';
COMMENT ON COLUMN product_spu.tax_rate IS '税率百分比（0-100），财务模块未上线，不改变订单金额口径';
COMMENT ON COLUMN product_spu.master_status IS '主档生命周期状态：ENABLED 可用 / DISABLED 停止新引用 / ARCHIVED 已归档；与 status（是否在售）正交';
-- 商品列表新增「创建时间区间」筛选；master_status / storage_method 选择性低，故意不建索引。
CREATE INDEX idx_product_spu_created_at ON product_spu (created_at DESC) WHERE deleted = FALSE;

-- ---------------------------------------------------------------------------
-- Step 2: 计量单位字典（只作为取值来源，不改变既有字符串快照字段）
-- ---------------------------------------------------------------------------
CREATE TABLE scm_uom
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uom_code        VARCHAR(64) NOT NULL,
    name            VARCHAR(32) NOT NULL,
    category        VARCHAR(16) NOT NULL,
    precision_scale SMALLINT    NOT NULL DEFAULT 4,
    status          VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
    sort_order      INTEGER     NOT NULL DEFAULT 0,
    version         INTEGER     NOT NULL DEFAULT 0,
    deleted         BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(64),
    updated_by      VARCHAR(64),
    CONSTRAINT ck_scm_uom_category CHECK (category IN ('WEIGHT', 'COUNT', 'VOLUME', 'LENGTH', 'OTHER')),
    CONSTRAINT ck_scm_uom_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_scm_uom_precision CHECK (precision_scale BETWEEN 0 AND 6),
    CONSTRAINT ck_scm_uom_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_scm_uom_code_active ON scm_uom (uom_code) WHERE deleted = FALSE;
-- 名称同样要唯一：现有业务字段记账的就是单位名称字符串，重名会让「按名称记账」出现两个真值来源。
CREATE UNIQUE INDEX uk_scm_uom_name_active ON scm_uom (name) WHERE deleted = FALSE;

COMMENT ON TABLE scm_uom IS '计量单位辅助资料，供商品销售单位/采购单位等字符串字段选择取值';
COMMENT ON COLUMN scm_uom.uom_code IS '单位编码，活动行内唯一';
COMMENT ON COLUMN scm_uom.name IS '单位名称，活动行内唯一；业务表按这个字符串记账';
COMMENT ON COLUMN scm_uom.category IS '量纲分类：WEIGHT 重量 / COUNT 计数 / VOLUME 体积 / LENGTH 长度 / OTHER 其他';
COMMENT ON COLUMN scm_uom.precision_scale IS '建议小数位数，仅用于前端输入约束，不改变数据库精度';
COMMENT ON COLUMN scm_uom.status IS 'ENABLED 可被新配置选用 / DISABLED 只保留历史引用';

-- 种子：既覆盖生鲜配送常用单位，也必须覆盖当前库与既有测试已经在用的字符串
-- （kg / 箱 / 件 等），否则历史商品一改就撞「单位不可用」校验。
INSERT INTO scm_uom(uom_code, name, category, precision_scale, sort_order)
VALUES ('UOM-G', '克', 'WEIGHT', 2, 10),
       ('UOM-KG', 'kg', 'WEIGHT', 4, 20),
       ('UOM-GONGJIN', '公斤', 'WEIGHT', 4, 30),
       ('UOM-JIN', '斤', 'WEIGHT', 4, 40),
       ('UOM-TON', '吨', 'WEIGHT', 4, 50),
       ('UOM-GE', '个', 'COUNT', 0, 110),
       ('UOM-JIAN', '件', 'COUNT', 0, 120),
       ('UOM-BAO', '包', 'COUNT', 0, 130),
       ('UOM-DAI', '袋', 'COUNT', 0, 140),
       ('UOM-XIANG', '箱', 'COUNT', 0, 150),
       ('UOM-PING', '瓶', 'COUNT', 0, 160),
       ('UOM-GUAN', '罐', 'COUNT', 0, 170),
       ('UOM-TONG', '桶', 'COUNT', 0, 180),
       ('UOM-HE', '盒', 'COUNT', 0, 190),
       ('UOM-KUANG', '筐', 'COUNT', 0, 200),
       ('UOM-GEN', '根', 'COUNT', 0, 210),
       ('UOM-BA', '把', 'COUNT', 0, 220),
       ('UOM-KE', '颗', 'COUNT', 0, 230),
       ('UOM-ZHA', '扎', 'COUNT', 0, 240),
       ('UOM-FEN', '份', 'COUNT', 0, 250),
       ('UOM-TUO', '托', 'COUNT', 0, 260),
       ('UOM-ML', 'mL', 'VOLUME', 0, 310),
       ('UOM-L', 'L', 'VOLUME', 2, 320),
       ('UOM-M', 'm', 'LENGTH', 2, 410);

-- ---------------------------------------------------------------------------
-- Step 3: 商品标签
-- ---------------------------------------------------------------------------
CREATE TABLE product_tag
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_code   VARCHAR(64) NOT NULL,
    name       VARCHAR(64) NOT NULL,
    status     VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
    sort_order INTEGER     NOT NULL DEFAULT 0,
    version    INTEGER     NOT NULL DEFAULT 0,
    deleted    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_product_tag_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_product_tag_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_product_tag_code_active ON product_tag (tag_code) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_product_tag_name_active ON product_tag (name) WHERE deleted = FALSE;
CREATE INDEX idx_product_tag_status ON product_tag (status) WHERE deleted = FALSE;

COMMENT ON TABLE product_tag IS '商品标签字典（有机 / 进口 / 学校专供等），用于列表筛选与后续商城、采购、报表';
COMMENT ON COLUMN product_tag.status IS 'ENABLED 可继续打标 / DISABLED 只保留历史关系，不再出现在可选标签里';

CREATE TABLE product_tag_relation
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spu_id     BIGINT      NOT NULL,
    tag_id     BIGINT      NOT NULL,
    version    INTEGER     NOT NULL DEFAULT 0,
    deleted    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_product_tag_relation_version CHECK (version >= 0)
);
-- 同一商品同一标签只能有一条活动关系；ON CONFLICT 目标与本索引逐字一致（Q11）。
CREATE UNIQUE INDEX uk_product_tag_relation_active ON product_tag_relation (spu_id, tag_id) WHERE deleted = FALSE;
CREATE INDEX idx_product_tag_relation_tag_id ON product_tag_relation (tag_id) WHERE deleted = FALSE;
CREATE INDEX idx_product_tag_relation_spu_id ON product_tag_relation (spu_id) WHERE deleted = FALSE;

COMMENT ON TABLE product_tag_relation IS '商品 SPU 与标签的多对多关系，打标入口在商品档案与批量维护';
COMMENT ON COLUMN product_tag_relation.spu_id IS '商品 SPU id，无外键，完整性由应用层保证';
COMMENT ON COLUMN product_tag_relation.tag_id IS '标签 id，无外键，标签被引用后禁止删除';
