-- L0-L2 static delivery plans; origin/main baseline 304e0c5 verified 2026-09-21.
-- Planning never writes inventory. No FK. No city centroid substitution.
ALTER TABLE order_address_snapshot
 ADD COLUMN province_code INTEGER, ADD COLUMN province_name VARCHAR(32),
 ADD COLUMN city_code INTEGER, ADD COLUMN city_name VARCHAR(64),
 ADD COLUMN district_code INTEGER, ADD COLUMN district_name VARCHAR(64),
 ADD COLUMN longitude NUMERIC(11,8), ADD COLUMN latitude NUMERIC(10,8), ADD COLUMN geom_crs VARCHAR(8);
ALTER TABLE customer ADD CONSTRAINT ck_customer_location_complete CHECK ((longitude IS NULL AND latitude IS NULL AND geom_crs IS NULL) OR (longitude IS NOT NULL AND latitude IS NOT NULL AND geom_crs IS NOT NULL AND longitude BETWEEN -180 AND 180 AND latitude BETWEEN -90 AND 90 AND geom_crs IN ('GCJ02','WGS84')));
ALTER TABLE warehouse ADD CONSTRAINT ck_warehouse_location_complete CHECK ((longitude IS NULL AND latitude IS NULL AND geom_crs IS NULL) OR (longitude IS NOT NULL AND latitude IS NOT NULL AND geom_crs IS NOT NULL AND longitude BETWEEN -180 AND 180 AND latitude BETWEEN -90 AND 90 AND geom_crs IN ('GCJ02','WGS84')));
ALTER TABLE order_address_snapshot ADD CONSTRAINT ck_order_address_snapshot_location_complete CHECK ((longitude IS NULL AND latitude IS NULL AND geom_crs IS NULL) OR (longitude IS NOT NULL AND latitude IS NOT NULL AND geom_crs IS NOT NULL AND longitude BETWEEN -180 AND 180 AND latitude BETWEEN -90 AND 90 AND geom_crs IN ('GCJ02','WGS84')));
-- Exact address equality only; no guessing of historical locations.
UPDATE order_address_snapshot a SET
 province_code=c.province_code, province_name=c.province_name,
 city_code=c.city_code, city_name=c.city_name, district_code=c.district_code, district_name=c.district_name,
 longitude=c.longitude, latitude=c.latitude, geom_crs=c.geom_crs
FROM customer c WHERE c.id=a.customer_id AND c.deleted=FALSE AND a.address=c.address AND btrim(a.address)<>'';
CREATE TABLE delivery_driver (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 driver_code VARCHAR(64) NOT NULL CHECK(btrim(driver_code)<>''),
 driver_name VARCHAR(100) NOT NULL CHECK(btrim(driver_name)<>''),
 phone VARCHAR(32) NOT NULL,
 status VARCHAR(16) NOT NULL DEFAULT 'ENABLED' CHECK(status IN ('ENABLED','DISABLED')),
 remark VARCHAR(500),
 version INTEGER NOT NULL DEFAULT 0 CHECK(version>=0), deleted BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 created_by VARCHAR(64), updated_by VARCHAR(64)
);
COMMENT ON TABLE delivery_driver IS '物流配送静态计划 Driver';
COMMENT ON COLUMN delivery_driver.id IS '主键';
COMMENT ON COLUMN delivery_driver.driver_code IS '司机编码，活动行忽略大小写唯一';
COMMENT ON COLUMN delivery_driver.driver_name IS '司机姓名';
COMMENT ON COLUMN delivery_driver.phone IS '联系电话';
COMMENT ON COLUMN delivery_driver.status IS '业务状态';
COMMENT ON COLUMN delivery_driver.remark IS '备注';
COMMENT ON COLUMN delivery_driver.version IS '乐观锁版本';
COMMENT ON COLUMN delivery_driver.deleted IS '逻辑删除标识';
COMMENT ON COLUMN delivery_driver.created_at IS '创建时间';
COMMENT ON COLUMN delivery_driver.updated_at IS '最后修改时间';
COMMENT ON COLUMN delivery_driver.created_by IS '创建人';
COMMENT ON COLUMN delivery_driver.updated_by IS '最后修改人';
CREATE TABLE delivery_vehicle (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 vehicle_no VARCHAR(32) NOT NULL CHECK(btrim(vehicle_no)<>''),
 vehicle_type VARCHAR(64),
 load_weight NUMERIC(18,4) CHECK(load_weight>=0),
 load_volume NUMERIC(18,4) CHECK(load_volume>=0),
 status VARCHAR(16) NOT NULL DEFAULT 'ENABLED' CHECK(status IN ('ENABLED','DISABLED')),
 remark VARCHAR(500),
 version INTEGER NOT NULL DEFAULT 0 CHECK(version>=0), deleted BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 created_by VARCHAR(64), updated_by VARCHAR(64)
);
COMMENT ON TABLE delivery_vehicle IS '物流配送静态计划 Vehicle';
COMMENT ON COLUMN delivery_vehicle.id IS '主键';
COMMENT ON COLUMN delivery_vehicle.vehicle_no IS '车牌号，活动行忽略大小写唯一';
COMMENT ON COLUMN delivery_vehicle.vehicle_type IS '车型';
COMMENT ON COLUMN delivery_vehicle.load_weight IS '额定载重 kg，仅作资料，不参与排线';
COMMENT ON COLUMN delivery_vehicle.load_volume IS '额定容积 m3，仅作资料，不参与排线';
COMMENT ON COLUMN delivery_vehicle.status IS '业务状态';
COMMENT ON COLUMN delivery_vehicle.remark IS '备注';
COMMENT ON COLUMN delivery_vehicle.version IS '乐观锁版本';
COMMENT ON COLUMN delivery_vehicle.deleted IS '逻辑删除标识';
COMMENT ON COLUMN delivery_vehicle.created_at IS '创建时间';
COMMENT ON COLUMN delivery_vehicle.updated_at IS '最后修改时间';
COMMENT ON COLUMN delivery_vehicle.created_by IS '创建人';
COMMENT ON COLUMN delivery_vehicle.updated_by IS '最后修改人';
CREATE TABLE delivery_route (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 route_no VARCHAR(64) NOT NULL UNIQUE,
 route_name VARCHAR(100) NOT NULL CHECK(btrim(route_name)<>''),
 delivery_date DATE NOT NULL,
 warehouse_id BIGINT NOT NULL,
 warehouse_name_snapshot VARCHAR(150) NOT NULL,
 warehouse_address_snapshot VARCHAR(255),
 start_longitude NUMERIC(11,8),
 start_latitude NUMERIC(10,8),
 start_geom_crs VARCHAR(8),
 driver_id BIGINT,
 driver_name_snapshot VARCHAR(100),
 driver_phone_snapshot VARCHAR(32),
 vehicle_id BIGINT,
 vehicle_no_snapshot VARCHAR(32),
 planned_departure_time TIMESTAMPTZ,
 status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','PLANNED','DISPATCHED','COMPLETED','CANCELLED')),
 outbound_id BIGINT,
 remark VARCHAR(500),
 cancel_reason VARCHAR(500),
 version INTEGER NOT NULL DEFAULT 0 CHECK(version>=0), deleted BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 created_by VARCHAR(64), updated_by VARCHAR(64)
);
COMMENT ON TABLE delivery_route IS '物流配送静态计划 Route';
COMMENT ON COLUMN delivery_route.id IS '主键';
COMMENT ON COLUMN delivery_route.route_no IS '线路编号 DR+配送日期+全局递增序号';
COMMENT ON COLUMN delivery_route.route_name IS '线路名称';
COMMENT ON COLUMN delivery_route.delivery_date IS '计划配送日期';
COMMENT ON COLUMN delivery_route.warehouse_id IS '起点仓库ID';
COMMENT ON COLUMN delivery_route.warehouse_name_snapshot IS '起点仓库名称快照';
COMMENT ON COLUMN delivery_route.warehouse_address_snapshot IS '起点仓库地址快照';
COMMENT ON COLUMN delivery_route.start_longitude IS '起点经度快照';
COMMENT ON COLUMN delivery_route.start_latitude IS '起点纬度快照';
COMMENT ON COLUMN delivery_route.start_geom_crs IS '起点坐标系 GCJ02 或 WGS84';
COMMENT ON COLUMN delivery_route.driver_id IS '司机ID，可暂不分配';
COMMENT ON COLUMN delivery_route.driver_name_snapshot IS '司机姓名快照';
COMMENT ON COLUMN delivery_route.driver_phone_snapshot IS '司机电话快照';
COMMENT ON COLUMN delivery_route.vehicle_id IS '车辆ID，可暂不分配';
COMMENT ON COLUMN delivery_route.vehicle_no_snapshot IS '车牌快照';
COMMENT ON COLUMN delivery_route.planned_departure_time IS '计划发车时间';
COMMENT ON COLUMN delivery_route.status IS '业务状态';
COMMENT ON COLUMN delivery_route.outbound_id IS '后续L3库存出库单ID，本期不写';
COMMENT ON COLUMN delivery_route.remark IS '备注';
COMMENT ON COLUMN delivery_route.cancel_reason IS '取消原因';
COMMENT ON COLUMN delivery_route.version IS '乐观锁版本';
COMMENT ON COLUMN delivery_route.deleted IS '逻辑删除标识';
COMMENT ON COLUMN delivery_route.created_at IS '创建时间';
COMMENT ON COLUMN delivery_route.updated_at IS '最后修改时间';
COMMENT ON COLUMN delivery_route.created_by IS '创建人';
COMMENT ON COLUMN delivery_route.updated_by IS '最后修改人';
CREATE TABLE delivery_route_stop (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 route_id BIGINT NOT NULL,
 stop_seq INTEGER NOT NULL CHECK(stop_seq>0),
 customer_id BIGINT NOT NULL,
 customer_name_snapshot VARCHAR(150) NOT NULL,
 receiver_name_snapshot VARCHAR(100),
 receiver_phone_snapshot VARCHAR(32),
 address_snapshot VARCHAR(255) NOT NULL,
 province_code INTEGER,
 province_name VARCHAR(32),
 city_code INTEGER,
 city_name VARCHAR(64),
 district_code INTEGER,
 district_name VARCHAR(64),
 longitude NUMERIC(11,8),
 latitude NUMERIC(10,8),
 geom_crs VARCHAR(8),
 planned_arrival_time TIMESTAMPTZ,
 remark VARCHAR(500),
 version INTEGER NOT NULL DEFAULT 0 CHECK(version>=0), deleted BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 created_by VARCHAR(64), updated_by VARCHAR(64)
);
COMMENT ON TABLE delivery_route_stop IS '物流配送静态计划 RouteStop';
COMMENT ON COLUMN delivery_route_stop.id IS '主键';
COMMENT ON COLUMN delivery_route_stop.route_id IS '所属线路ID';
COMMENT ON COLUMN delivery_route_stop.stop_seq IS '停靠顺序，从1开始，活动行线路内唯一';
COMMENT ON COLUMN delivery_route_stop.customer_id IS '客户ID';
COMMENT ON COLUMN delivery_route_stop.customer_name_snapshot IS '客户名称快照';
COMMENT ON COLUMN delivery_route_stop.receiver_name_snapshot IS '同客户同地址首张订单收货人快照';
COMMENT ON COLUMN delivery_route_stop.receiver_phone_snapshot IS '同客户同地址首张订单联系电话快照';
COMMENT ON COLUMN delivery_route_stop.address_snapshot IS '配送地址快照，不随客户主档回写';
COMMENT ON COLUMN delivery_route_stop.province_code IS '省级区划编码';
COMMENT ON COLUMN delivery_route_stop.province_name IS '省级区划名称快照';
COMMENT ON COLUMN delivery_route_stop.city_code IS '市级区划编码';
COMMENT ON COLUMN delivery_route_stop.city_name IS '市级区划名称快照';
COMMENT ON COLUMN delivery_route_stop.district_code IS '区县编码';
COMMENT ON COLUMN delivery_route_stop.district_name IS '区县名称快照';
COMMENT ON COLUMN delivery_route_stop.longitude IS '实际地址经度，不是区划质心';
COMMENT ON COLUMN delivery_route_stop.latitude IS '实际地址纬度，不是区划质心';
COMMENT ON COLUMN delivery_route_stop.geom_crs IS '坐标系 GCJ02 或 WGS84，与经纬度成组';
COMMENT ON COLUMN delivery_route_stop.planned_arrival_time IS '计划到达时间，仅人工填写';
COMMENT ON COLUMN delivery_route_stop.remark IS '备注';
COMMENT ON COLUMN delivery_route_stop.version IS '乐观锁版本';
COMMENT ON COLUMN delivery_route_stop.deleted IS '逻辑删除标识';
COMMENT ON COLUMN delivery_route_stop.created_at IS '创建时间';
COMMENT ON COLUMN delivery_route_stop.updated_at IS '最后修改时间';
COMMENT ON COLUMN delivery_route_stop.created_by IS '创建人';
COMMENT ON COLUMN delivery_route_stop.updated_by IS '最后修改人';
CREATE TABLE delivery_route_order (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 route_id BIGINT NOT NULL,
 stop_id BIGINT NOT NULL,
 order_id BIGINT NOT NULL,
 customer_id BIGINT NOT NULL,
 order_no_snapshot VARCHAR(64) NOT NULL,
 order_amount_snapshot NUMERIC(18,4) CHECK(order_amount_snapshot>=0),
 expect_delivery_time_snapshot TIMESTAMPTZ,
 assignment_status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' CHECK(assignment_status IN ('ACTIVE','RELEASED')),
 version INTEGER NOT NULL DEFAULT 0 CHECK(version>=0), deleted BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 created_by VARCHAR(64), updated_by VARCHAR(64)
);
COMMENT ON TABLE delivery_route_order IS '物流配送静态计划 RouteOrder';
COMMENT ON COLUMN delivery_route_order.id IS '主键';
COMMENT ON COLUMN delivery_route_order.route_id IS '所属线路ID';
COMMENT ON COLUMN delivery_route_order.stop_id IS '所属停靠点ID';
COMMENT ON COLUMN delivery_route_order.order_id IS '销售订单ID';
COMMENT ON COLUMN delivery_route_order.customer_id IS '客户ID';
COMMENT ON COLUMN delivery_route_order.order_no_snapshot IS '销售订单编号快照';
COMMENT ON COLUMN delivery_route_order.order_amount_snapshot IS '订购总金额快照，非发货结算金额';
COMMENT ON COLUMN delivery_route_order.expect_delivery_time_snapshot IS '订单期望配送时间快照';
COMMENT ON COLUMN delivery_route_order.assignment_status IS 'ACTIVE 独占订单；取消或移除改 RELEASED';
COMMENT ON COLUMN delivery_route_order.version IS '乐观锁版本';
COMMENT ON COLUMN delivery_route_order.deleted IS '逻辑删除标识';
COMMENT ON COLUMN delivery_route_order.created_at IS '创建时间';
COMMENT ON COLUMN delivery_route_order.updated_at IS '最后修改时间';
COMMENT ON COLUMN delivery_route_order.created_by IS '创建人';
COMMENT ON COLUMN delivery_route_order.updated_by IS '最后修改人';
ALTER TABLE delivery_route ADD CONSTRAINT ck_delivery_route_location CHECK ((start_longitude IS NULL AND start_latitude IS NULL AND start_geom_crs IS NULL) OR (start_longitude IS NOT NULL AND start_latitude IS NOT NULL AND start_geom_crs IS NOT NULL AND start_longitude BETWEEN -180 AND 180 AND start_latitude BETWEEN -90 AND 90 AND start_geom_crs IN ('GCJ02','WGS84')));
ALTER TABLE delivery_route_stop ADD CONSTRAINT ck_delivery_route_stop_location CHECK ((longitude IS NULL AND latitude IS NULL AND geom_crs IS NULL) OR (longitude IS NOT NULL AND latitude IS NOT NULL AND geom_crs IS NOT NULL AND longitude BETWEEN -180 AND 180 AND latitude BETWEEN -90 AND 90 AND geom_crs IN ('GCJ02','WGS84')));
CREATE UNIQUE INDEX uk_delivery_driver_code ON delivery_driver(upper(driver_code)) WHERE deleted=FALSE;
CREATE UNIQUE INDEX uk_delivery_vehicle_no ON delivery_vehicle(upper(vehicle_no)) WHERE deleted=FALSE;
CREATE UNIQUE INDEX uk_delivery_stop_seq ON delivery_route_stop(route_id,stop_seq) WHERE deleted=FALSE;
CREATE UNIQUE INDEX uk_delivery_stop_address ON delivery_route_stop(route_id,customer_id,address_snapshot) WHERE deleted=FALSE;
CREATE UNIQUE INDEX uk_delivery_order_active ON delivery_route_order(order_id) WHERE deleted=FALSE AND assignment_status='ACTIVE';
CREATE INDEX idx_delivery_route_date ON delivery_route(delivery_date,status) WHERE deleted=FALSE;
CREATE INDEX idx_delivery_route_warehouse ON delivery_route(warehouse_id) WHERE deleted=FALSE;
CREATE INDEX idx_delivery_route_driver ON delivery_route(driver_id) WHERE deleted=FALSE;
CREATE INDEX idx_delivery_route_vehicle ON delivery_route(vehicle_id) WHERE deleted=FALSE;
CREATE INDEX idx_delivery_stop_customer ON delivery_route_stop(customer_id) WHERE deleted=FALSE;
CREATE INDEX idx_delivery_stop_region ON delivery_route_stop(province_code,city_code,district_code) WHERE deleted=FALSE;
CREATE INDEX idx_delivery_order_route ON delivery_route_order(route_id,stop_id) WHERE deleted=FALSE;
CREATE INDEX idx_delivery_order_customer ON delivery_route_order(customer_id) WHERE deleted=FALSE;
CREATE SEQUENCE delivery_route_no_seq;
COMMENT ON COLUMN delivery_route.outbound_id IS 'L3 出库衔接预留，本期不写';
COMMENT ON COLUMN delivery_route_stop.address_snapshot IS '订单配送地址快照，客户主档修改不回写';
COMMENT ON COLUMN delivery_route_order.assignment_status IS 'ACTIVE 独占订单；移除或取消改 RELEASED，保留历史';
COMMENT ON COLUMN order_address_snapshot.province_code IS '订单创建时冻结的配送地址 province_code，仅与客户地址完全一致才继承';
COMMENT ON COLUMN order_address_snapshot.province_name IS '订单创建时冻结的配送地址 province_name，仅与客户地址完全一致才继承';
COMMENT ON COLUMN order_address_snapshot.city_code IS '订单创建时冻结的配送地址 city_code，仅与客户地址完全一致才继承';
COMMENT ON COLUMN order_address_snapshot.city_name IS '订单创建时冻结的配送地址 city_name，仅与客户地址完全一致才继承';
COMMENT ON COLUMN order_address_snapshot.district_code IS '订单创建时冻结的配送地址 district_code，仅与客户地址完全一致才继承';
COMMENT ON COLUMN order_address_snapshot.district_name IS '订单创建时冻结的配送地址 district_name，仅与客户地址完全一致才继承';
COMMENT ON COLUMN order_address_snapshot.longitude IS '订单创建时冻结的配送地址 longitude，仅与客户地址完全一致才继承';
COMMENT ON COLUMN order_address_snapshot.latitude IS '订单创建时冻结的配送地址 latitude，仅与客户地址完全一致才继承';
COMMENT ON COLUMN order_address_snapshot.geom_crs IS '订单创建时冻结的配送地址 geom_crs，仅与客户地址完全一致才继承';
