-- =====================================================================
-- V2 系统表基线 · 剩余系统表（补齐菜单树引用的全部表）
-- 来源：SmartAdmin v3.31 数据库SQL脚本/mysql/smart_admin_v3.sql
-- 转换目标：PostgreSQL 18（identity / BOOLEAN / TIMESTAMP / COMMENT）
--
-- 由 v2/tools/gen_v5_migration.py 生成，转换规则见 V1 头部说明。
--
-- 覆盖范围：SmartAdmin 菜单树中除 V1..V4 已建表之外引用的所有表，
-- 包括 系统设置(文件/定时任务/代码生成)、监控(心跳)、文档中心(更新日志/帮助文档/意见反馈)、
-- 消息通知、以及 OA 示例模块（菜单中存在对应页面）。
--
-- 种子数据策略：只保留真正的系统参考数据
--   t_notice_type(2) / t_mail_template(1) / t_smart_job(2)
-- 上游的演示内容（t_change_log 11 行、t_data_tracer 10 行、t_notice 12 行、
-- t_message 4 行、t_oa_* 及帮助文档正文）不迁移 —— V2 是干净基线，不是 demo 副本。
--
-- 有意保留的差异：
--   1. t_notice_visible_range 上游只有 UNIQUE INDEX uk_notice_data，无主键；
--      PG 保持无主键 + 唯一约束（与上游一致）。
--   2. t_notice_view_record / t_help_doc_view_record / t_help_doc_relation 使用
--      复合主键，PG 显式命名为 pk_<table>。
--   3. datetime ON UPDATE CURRENT_TIMESTAMP 不做触发器模拟（见 V4 头部）。
-- =====================================================================

-- ---------------------------------------------------------------------
-- t_code_generator_config
-- ---------------------------------------------------------------------
CREATE TABLE t_code_generator_config
(
    table_name        VARCHAR(255) NOT NULL,
    basic             TEXT,
    fields            TEXT,
    insert_and_update TEXT,
    delete_info       TEXT,
    query_fields      TEXT,
    table_fields      TEXT,
    detail            TEXT,
    create_time       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_code_generator_config PRIMARY KEY (table_name)
);

COMMENT ON TABLE t_code_generator_config IS 't_code_generator_config';
COMMENT ON COLUMN t_code_generator_config.table_name IS '表名';
COMMENT ON COLUMN t_code_generator_config.basic IS '基础命名信息';
COMMENT ON COLUMN t_code_generator_config.fields IS '字段列表';
COMMENT ON COLUMN t_code_generator_config.insert_and_update IS '新建、修改';
COMMENT ON COLUMN t_code_generator_config.delete_info IS '删除';
COMMENT ON COLUMN t_code_generator_config.query_fields IS '查询';
COMMENT ON COLUMN t_code_generator_config.table_fields IS '列表';
COMMENT ON COLUMN t_code_generator_config.detail IS '详情';
COMMENT ON COLUMN t_code_generator_config.create_time IS '创建时间';
COMMENT ON COLUMN t_code_generator_config.update_time IS '更新时间';

-- ---------------------------------------------------------------------
-- t_table_column
-- ---------------------------------------------------------------------
CREATE TABLE t_table_column
(
    table_column_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    user_type       INTEGER                                 NOT NULL,
    table_id        INTEGER                                 NOT NULL,
    columns         TEXT,
    create_time     TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_table_column PRIMARY KEY (table_column_id),
    CONSTRAINT uk_t_table_column_uni_employee_table UNIQUE (user_id, table_id)
);

COMMENT ON TABLE t_table_column IS 't_table_column';
COMMENT ON COLUMN t_table_column.user_id IS '用户id';
COMMENT ON COLUMN t_table_column.user_type IS '用户类型';
COMMENT ON COLUMN t_table_column.table_id IS '表格id';
COMMENT ON COLUMN t_table_column.columns IS '具体的表格列，存入的json';

-- ---------------------------------------------------------------------
-- t_smart_job
-- ---------------------------------------------------------------------
CREATE TABLE t_smart_job
(
    job_id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_name            VARCHAR(50)                              NOT NULL,
    job_class           VARCHAR(200)                             NOT NULL,
    trigger_type        VARCHAR(30)                              NOT NULL,
    trigger_value       VARCHAR(200)                             NOT NULL,
    enabled_flag        BOOLEAN                                  NOT NULL DEFAULT FALSE,
    param               VARCHAR(1000)                                     DEFAULT NULL,
    last_execute_time   TIMESTAMP                                         DEFAULT NULL,
    last_execute_log_id INTEGER                                           DEFAULT NULL,
    sort                INTEGER                                  NOT NULL DEFAULT 0,
    remark              VARCHAR(255)                                      DEFAULT NULL,
    deleted_flag        BOOLEAN                                  NOT NULL DEFAULT FALSE,
    update_name         VARCHAR(50)                              NOT NULL,
    create_time         TIMESTAMP                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_smart_job PRIMARY KEY (job_id)
);

COMMENT ON TABLE t_smart_job IS 't_smart_job';
COMMENT ON COLUMN t_smart_job.job_id IS '任务id';
COMMENT ON COLUMN t_smart_job.job_name IS '任务名称';
COMMENT ON COLUMN t_smart_job.job_class IS '任务执行类';
COMMENT ON COLUMN t_smart_job.trigger_type IS '触发类型';
COMMENT ON COLUMN t_smart_job.trigger_value IS '触发配置';
COMMENT ON COLUMN t_smart_job.enabled_flag IS '是否开启';
COMMENT ON COLUMN t_smart_job.param IS '参数';
COMMENT ON COLUMN t_smart_job.last_execute_time IS '最后一次执行时间';
COMMENT ON COLUMN t_smart_job.last_execute_log_id IS '最后一次执行记录id';
COMMENT ON COLUMN t_smart_job.sort IS '排序';
COMMENT ON COLUMN t_smart_job.remark IS '描述';
COMMENT ON COLUMN t_smart_job.deleted_flag IS '删除状态';
COMMENT ON COLUMN t_smart_job.update_name IS '更新人';

-- ---------------------------------------------------------------------
-- t_smart_job_log
-- ---------------------------------------------------------------------
CREATE TABLE t_smart_job_log
(
    log_id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_id              INTEGER                                  NOT NULL,
    job_name            VARCHAR(100)                             NOT NULL,
    param               VARCHAR(2000)                                     DEFAULT NULL,
    success_flag        BOOLEAN                                  NOT NULL,
    execute_start_time  TIMESTAMP                                NOT NULL,
    execute_time_millis INTEGER                                           DEFAULT NULL,
    execute_end_time    TIMESTAMP                                         DEFAULT NULL,
    execute_result      VARCHAR(2000)                                     DEFAULT NULL,
    ip                  VARCHAR(50)                              NOT NULL,
    process_id          VARCHAR(50)                              NOT NULL,
    program_path        VARCHAR(255)                             NOT NULL,
    create_name         VARCHAR(100)                             NOT NULL,
    create_time         TIMESTAMP                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_smart_job_log PRIMARY KEY (log_id)
);

COMMENT ON TABLE t_smart_job_log IS 't_smart_job_log';
COMMENT ON COLUMN t_smart_job_log.job_id IS '任务id';
COMMENT ON COLUMN t_smart_job_log.job_name IS '任务名称';
COMMENT ON COLUMN t_smart_job_log.param IS '执行参数';
COMMENT ON COLUMN t_smart_job_log.success_flag IS '是否成功';
COMMENT ON COLUMN t_smart_job_log.execute_start_time IS '执行开始时间';
COMMENT ON COLUMN t_smart_job_log.execute_time_millis IS '执行时长';
COMMENT ON COLUMN t_smart_job_log.execute_end_time IS '执行结束时间';
COMMENT ON COLUMN t_smart_job_log.ip IS 'ip';
COMMENT ON COLUMN t_smart_job_log.process_id IS '进程id';
COMMENT ON COLUMN t_smart_job_log.program_path IS '程序目录';
COMMENT ON COLUMN t_smart_job_log.create_name IS '创建人';
CREATE INDEX idx_t_smart_job_log_idx_job_id ON t_smart_job_log (job_id);

-- ---------------------------------------------------------------------
-- t_file
-- ---------------------------------------------------------------------
CREATE TABLE t_file
(
    file_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    folder_type       SMALLINT                                NOT NULL,
    file_name         VARCHAR(100)                                     DEFAULT NULL,
    file_size         INTEGER                                          DEFAULT NULL,
    file_key          VARCHAR(200)                            NOT NULL,
    file_type         VARCHAR(50)                             NOT NULL,
    creator_id        BIGINT                                           DEFAULT NULL,
    creator_user_type INTEGER                                          DEFAULT NULL,
    creator_name      VARCHAR(100)                                     DEFAULT NULL,
    update_time       TIMESTAMP                                        DEFAULT CURRENT_TIMESTAMP,
    create_time       TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_file PRIMARY KEY (file_id),
    CONSTRAINT uk_t_file_uk_file_key UNIQUE (file_key)
);

COMMENT ON TABLE t_file IS 't_file';
COMMENT ON COLUMN t_file.file_id IS '主键ID';
COMMENT ON COLUMN t_file.folder_type IS '文件夹类型';
COMMENT ON COLUMN t_file.file_name IS '文件名称';
COMMENT ON COLUMN t_file.file_size IS '文件大小';
COMMENT ON COLUMN t_file.file_key IS '文件key，用于文件下载';
COMMENT ON COLUMN t_file.file_type IS '文件类型';
COMMENT ON COLUMN t_file.creator_id IS '创建人，即上传人';
COMMENT ON COLUMN t_file.creator_user_type IS '创建人用户类型';
COMMENT ON COLUMN t_file.creator_name IS '创建人姓名';
COMMENT ON COLUMN t_file.update_time IS '上次更新时间';
COMMENT ON COLUMN t_file.create_time IS '创建时间';
CREATE INDEX idx_t_file_module_id_module_type ON t_file (folder_type);

-- ---------------------------------------------------------------------
-- t_heart_beat_record
-- ---------------------------------------------------------------------
CREATE TABLE t_heart_beat_record
(
    heart_beat_record_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_path         VARCHAR(100)                             NOT NULL,
    server_ip            VARCHAR(200)                             NOT NULL,
    process_no           INTEGER                                  NOT NULL,
    process_start_time   TIMESTAMP                                NOT NULL,
    heart_beat_time      TIMESTAMP                                NOT NULL,
    CONSTRAINT pk_t_heart_beat_record PRIMARY KEY (heart_beat_record_id)
);

COMMENT ON TABLE t_heart_beat_record IS 't_heart_beat_record';
COMMENT ON COLUMN t_heart_beat_record.heart_beat_record_id IS '自增id';
COMMENT ON COLUMN t_heart_beat_record.project_path IS '项目名称';
COMMENT ON COLUMN t_heart_beat_record.server_ip IS '服务器ip';
COMMENT ON COLUMN t_heart_beat_record.process_no IS '进程号';
COMMENT ON COLUMN t_heart_beat_record.process_start_time IS '进程开启时间';
COMMENT ON COLUMN t_heart_beat_record.heart_beat_time IS '心跳时间';

-- ---------------------------------------------------------------------
-- t_mail_template
-- ---------------------------------------------------------------------
CREATE TABLE t_mail_template
(
    template_code    VARCHAR(200) NOT NULL,
    template_subject VARCHAR(100) NOT NULL,
    template_content TEXT         NOT NULL,
    template_type    VARCHAR(50)  NOT NULL,
    disable_flag     BOOLEAN      NOT NULL DEFAULT FALSE,
    update_time      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_mail_template PRIMARY KEY (template_code)
);

COMMENT ON TABLE t_mail_template IS 't_mail_template';
COMMENT ON COLUMN t_mail_template.template_subject IS '模板名称';
COMMENT ON COLUMN t_mail_template.template_content IS '模板内容';
COMMENT ON COLUMN t_mail_template.template_type IS '解析类型 string，freemarker';
COMMENT ON COLUMN t_mail_template.disable_flag IS '是否禁用';
COMMENT ON COLUMN t_mail_template.update_time IS '创建时间';
COMMENT ON COLUMN t_mail_template.create_time IS '创建时间';

-- ---------------------------------------------------------------------
-- t_change_log
-- ---------------------------------------------------------------------
CREATE TABLE t_change_log
(
    change_log_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    update_version VARCHAR(255)                            NOT NULL,
    type           INTEGER                                 NOT NULL,
    publish_author VARCHAR(255)                            NOT NULL,
    public_date    DATE                                    NOT NULL,
    content        TEXT                                    NOT NULL,
    link           TEXT,
    create_time    TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time    TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_change_log PRIMARY KEY (change_log_id),
    CONSTRAINT uk_t_change_log_version_unique UNIQUE (update_version)
);

COMMENT ON TABLE t_change_log IS 't_change_log';
COMMENT ON COLUMN t_change_log.change_log_id IS '更新日志id';
COMMENT ON COLUMN t_change_log.update_version IS '版本';
COMMENT ON COLUMN t_change_log.type IS '更新类型:[1:特大版本功能更新;2:功能更新;3:bug修复]';
COMMENT ON COLUMN t_change_log.publish_author IS '发布人';
COMMENT ON COLUMN t_change_log.public_date IS '发布日期';
COMMENT ON COLUMN t_change_log.content IS '更新内容';
COMMENT ON COLUMN t_change_log.link IS '跳转链接';
COMMENT ON COLUMN t_change_log.create_time IS '创建时间';
COMMENT ON COLUMN t_change_log.update_time IS '更新时间';

-- ---------------------------------------------------------------------
-- t_data_tracer
-- ---------------------------------------------------------------------
CREATE TABLE t_data_tracer
(
    data_tracer_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_id        BIGINT                                  NOT NULL,
    type           INTEGER                                 NOT NULL,
    content        TEXT,
    diff_old       TEXT,
    diff_new       TEXT,
    extra_data     TEXT,
    user_id        BIGINT                                  NOT NULL,
    user_type      INTEGER                                 NOT NULL,
    user_name      VARCHAR(50)                             NOT NULL,
    ip             VARCHAR(50)                                      DEFAULT NULL,
    ip_region      VARCHAR(1000)                                    DEFAULT NULL,
    user_agent     VARCHAR(2000)                                    DEFAULT NULL,
    update_time    TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time    TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_data_tracer PRIMARY KEY (data_tracer_id)
);

COMMENT ON TABLE t_data_tracer IS 't_data_tracer';
COMMENT ON COLUMN t_data_tracer.data_id IS '各种单据的id';
COMMENT ON COLUMN t_data_tracer.type IS '单据类型';
COMMENT ON COLUMN t_data_tracer.content IS '操作内容';
COMMENT ON COLUMN t_data_tracer.diff_old IS '差异：旧的数据';
COMMENT ON COLUMN t_data_tracer.diff_new IS '差异：新的数据';
COMMENT ON COLUMN t_data_tracer.extra_data IS '额外信息';
COMMENT ON COLUMN t_data_tracer.user_id IS '用户id';
COMMENT ON COLUMN t_data_tracer.user_type IS '用户类型：1 后管用户 ';
COMMENT ON COLUMN t_data_tracer.user_name IS '用户名称';
COMMENT ON COLUMN t_data_tracer.ip IS 'ip';
COMMENT ON COLUMN t_data_tracer.ip_region IS 'ip地区';
COMMENT ON COLUMN t_data_tracer.user_agent IS '用户ua';
COMMENT ON COLUMN t_data_tracer.update_time IS '更新时间';
COMMENT ON COLUMN t_data_tracer.create_time IS '创建时间';
CREATE INDEX idx_t_data_tracer_order_id_order_type ON t_data_tracer (data_id, type);

-- ---------------------------------------------------------------------
-- t_feedback
-- ---------------------------------------------------------------------
CREATE TABLE t_feedback
(
    feedback_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    feedback_content    TEXT,
    feedback_attachment VARCHAR(500)                                     DEFAULT NULL,
    user_id             BIGINT                                  NOT NULL,
    user_type           INTEGER                                 NOT NULL,
    user_name           VARCHAR(50)                             NOT NULL,
    create_time         TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_feedback PRIMARY KEY (feedback_id)
);

COMMENT ON TABLE t_feedback IS 't_feedback';
COMMENT ON COLUMN t_feedback.feedback_id IS '主键';
COMMENT ON COLUMN t_feedback.feedback_content IS '反馈内容';
COMMENT ON COLUMN t_feedback.feedback_attachment IS '反馈图片';
COMMENT ON COLUMN t_feedback.user_id IS '创建人id';
COMMENT ON COLUMN t_feedback.user_type IS '创建人用户类型';
COMMENT ON COLUMN t_feedback.user_name IS '创建人姓名';
COMMENT ON COLUMN t_feedback.create_time IS '创建时间';
COMMENT ON COLUMN t_feedback.update_time IS '更新时间';

-- ---------------------------------------------------------------------
-- t_help_doc
-- ---------------------------------------------------------------------
CREATE TABLE t_help_doc
(
    help_doc_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    help_doc_catalog_id BIGINT                                  NOT NULL,
    title               VARCHAR(200)                            NOT NULL,
    content_text        TEXT                                    NOT NULL,
    content_html        TEXT                                    NOT NULL,
    attachment          VARCHAR(1000)                                    DEFAULT NULL,
    sort                INTEGER                                 NOT NULL DEFAULT 0,
    page_view_count     INTEGER                                 NOT NULL DEFAULT 0,
    user_view_count     INTEGER                                 NOT NULL DEFAULT 0,
    author              VARCHAR(1000)                                    DEFAULT NULL,
    update_time         TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time         TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_help_doc PRIMARY KEY (help_doc_id)
);

COMMENT ON TABLE t_help_doc IS 't_help_doc';
COMMENT ON COLUMN t_help_doc.help_doc_catalog_id IS '类型1公告 2动态';
COMMENT ON COLUMN t_help_doc.title IS '标题';
COMMENT ON COLUMN t_help_doc.content_text IS '文本内容';
COMMENT ON COLUMN t_help_doc.content_html IS 'html内容';
COMMENT ON COLUMN t_help_doc.attachment IS '附件';
COMMENT ON COLUMN t_help_doc.sort IS '排序';
COMMENT ON COLUMN t_help_doc.page_view_count IS '页面浏览量，传说中的pv';
COMMENT ON COLUMN t_help_doc.user_view_count IS '用户浏览量，传说中的uv';
COMMENT ON COLUMN t_help_doc.author IS '作者';

-- ---------------------------------------------------------------------
-- t_help_doc_catalog
-- ---------------------------------------------------------------------
CREATE TABLE t_help_doc_catalog
(
    help_doc_catalog_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(1000)                           NOT NULL,
    sort                INTEGER                                 NOT NULL DEFAULT 0,
    parent_id           BIGINT                                  NOT NULL,
    create_time         TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_help_doc_catalog PRIMARY KEY (help_doc_catalog_id)
);

COMMENT ON TABLE t_help_doc_catalog IS 't_help_doc_catalog';
COMMENT ON COLUMN t_help_doc_catalog.help_doc_catalog_id IS '帮助文档目录';
COMMENT ON COLUMN t_help_doc_catalog.name IS '名称';
COMMENT ON COLUMN t_help_doc_catalog.sort IS '排序字段';
COMMENT ON COLUMN t_help_doc_catalog.parent_id IS '父级id';

-- ---------------------------------------------------------------------
-- t_help_doc_relation
-- ---------------------------------------------------------------------
CREATE TABLE t_help_doc_relation
(
    relation_id   BIGINT NOT NULL,
    relation_name VARCHAR(255) DEFAULT NULL,
    help_doc_id   BIGINT NOT NULL,
    create_time   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    update_time   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_help_doc_relation PRIMARY KEY (relation_id, help_doc_id)
);

COMMENT ON TABLE t_help_doc_relation IS 't_help_doc_relation';
COMMENT ON COLUMN t_help_doc_relation.relation_id IS '关联id';
COMMENT ON COLUMN t_help_doc_relation.relation_name IS '关联名称';
COMMENT ON COLUMN t_help_doc_relation.help_doc_id IS '文档id';

-- ---------------------------------------------------------------------
-- t_help_doc_view_record
-- ---------------------------------------------------------------------
CREATE TABLE t_help_doc_view_record
(
    help_doc_id      BIGINT    NOT NULL,
    user_id          BIGINT    NOT NULL,
    user_name        VARCHAR(255)       DEFAULT NULL,
    page_view_count  INTEGER            DEFAULT 0,
    first_ip         VARCHAR(255)       DEFAULT NULL,
    first_user_agent VARCHAR(1000)      DEFAULT NULL,
    last_ip          VARCHAR(255)       DEFAULT NULL,
    last_user_agent  VARCHAR(1000)      DEFAULT NULL,
    create_time      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_help_doc_view_record PRIMARY KEY (help_doc_id, user_id)
);

COMMENT ON TABLE t_help_doc_view_record IS 't_help_doc_view_record';
COMMENT ON COLUMN t_help_doc_view_record.help_doc_id IS '通知公告id';
COMMENT ON COLUMN t_help_doc_view_record.user_id IS '用户id';
COMMENT ON COLUMN t_help_doc_view_record.user_name IS '用户名称';
COMMENT ON COLUMN t_help_doc_view_record.page_view_count IS '查看次数';
COMMENT ON COLUMN t_help_doc_view_record.first_ip IS '首次ip';
COMMENT ON COLUMN t_help_doc_view_record.first_user_agent IS '首次用户设备等标识';
COMMENT ON COLUMN t_help_doc_view_record.last_ip IS '最后一次ip';
COMMENT ON COLUMN t_help_doc_view_record.last_user_agent IS '最后一次用户设备等标识';

-- ---------------------------------------------------------------------
-- t_notice
-- ---------------------------------------------------------------------
CREATE TABLE t_notice
(
    notice_id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    notice_type_id         BIGINT                                  NOT NULL,
    title                  VARCHAR(200)                            NOT NULL,
    all_visible_flag       BOOLEAN                                 NOT NULL,
    scheduled_publish_flag BOOLEAN                                 NOT NULL,
    publish_time           TIMESTAMP                               NOT NULL,
    content_text           TEXT                                    NOT NULL,
    content_html           TEXT                                    NOT NULL,
    attachment             VARCHAR(1000)                                    DEFAULT NULL,
    page_view_count        INTEGER                                 NOT NULL DEFAULT 0,
    user_view_count        INTEGER                                 NOT NULL DEFAULT 0,
    source                 VARCHAR(1000)                                    DEFAULT NULL,
    author                 VARCHAR(1000)                                    DEFAULT NULL,
    document_number        VARCHAR(1000)                                    DEFAULT NULL,
    deleted_flag           BOOLEAN                                 NOT NULL DEFAULT FALSE,
    create_user_id         BIGINT                                           DEFAULT NULL,
    update_time            TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time            TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_notice PRIMARY KEY (notice_id)
);

COMMENT ON TABLE t_notice IS 't_notice';
COMMENT ON COLUMN t_notice.notice_type_id IS '类型1公告 2动态';
COMMENT ON COLUMN t_notice.title IS '标题';
COMMENT ON COLUMN t_notice.all_visible_flag IS '是否全部可见';
COMMENT ON COLUMN t_notice.scheduled_publish_flag IS '是否定时发布';
COMMENT ON COLUMN t_notice.publish_time IS '发布时间';
COMMENT ON COLUMN t_notice.content_text IS '文本内容';
COMMENT ON COLUMN t_notice.content_html IS 'html内容';
COMMENT ON COLUMN t_notice.attachment IS '附件';
COMMENT ON COLUMN t_notice.page_view_count IS '页面浏览量，传说中的pv';
COMMENT ON COLUMN t_notice.user_view_count IS '用户浏览量，传说中的uv';
COMMENT ON COLUMN t_notice.source IS '来源';
COMMENT ON COLUMN t_notice.author IS '作者';
COMMENT ON COLUMN t_notice.document_number IS '文号，如：1024创新实验室发〔2022〕字第36号';
COMMENT ON COLUMN t_notice.create_user_id IS '创建人';

-- ---------------------------------------------------------------------
-- t_notice_type
-- ---------------------------------------------------------------------
CREATE TABLE t_notice_type
(
    notice_type_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    notice_type_name VARCHAR(1000)                           NOT NULL,
    create_time      TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_notice_type PRIMARY KEY (notice_type_id)
);

COMMENT ON TABLE t_notice_type IS 't_notice_type';
COMMENT ON COLUMN t_notice_type.notice_type_id IS '通知类型';
COMMENT ON COLUMN t_notice_type.notice_type_name IS '类型名称';

-- ---------------------------------------------------------------------
-- t_notice_view_record
-- ---------------------------------------------------------------------
CREATE TABLE t_notice_view_record
(
    notice_id        BIGINT    NOT NULL,
    employee_id      BIGINT    NOT NULL,
    page_view_count  INTEGER            DEFAULT 0,
    first_ip         VARCHAR(255)       DEFAULT NULL,
    first_user_agent VARCHAR(1000)      DEFAULT NULL,
    last_ip          VARCHAR(255)       DEFAULT NULL,
    last_user_agent  VARCHAR(1000)      DEFAULT NULL,
    create_time      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP          DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_notice_view_record PRIMARY KEY (notice_id, employee_id)
);

COMMENT ON TABLE t_notice_view_record IS 't_notice_view_record';
COMMENT ON COLUMN t_notice_view_record.notice_id IS '通知公告id';
COMMENT ON COLUMN t_notice_view_record.employee_id IS '员工id';
COMMENT ON COLUMN t_notice_view_record.page_view_count IS '查看次数';
COMMENT ON COLUMN t_notice_view_record.first_ip IS '首次ip';
COMMENT ON COLUMN t_notice_view_record.first_user_agent IS '首次用户设备等标识';
COMMENT ON COLUMN t_notice_view_record.last_ip IS '最后一次ip';
COMMENT ON COLUMN t_notice_view_record.last_user_agent IS '最后一次用户设备等标识';

-- ---------------------------------------------------------------------
-- t_notice_visible_range
-- ---------------------------------------------------------------------
CREATE TABLE t_notice_visible_range
(
    notice_id   BIGINT    NOT NULL,
    data_type   SMALLINT  NOT NULL,
    data_id     BIGINT    NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_t_notice_visible_range_uk_notice_data UNIQUE (notice_id, data_type, data_id)
);

COMMENT ON TABLE t_notice_visible_range IS 't_notice_visible_range';
COMMENT ON COLUMN t_notice_visible_range.notice_id IS '资讯id';
COMMENT ON COLUMN t_notice_visible_range.data_type IS '数据类型1员工 2部门';
COMMENT ON COLUMN t_notice_visible_range.data_id IS '员工or部门id';

-- ---------------------------------------------------------------------
-- t_message
-- ---------------------------------------------------------------------
CREATE TABLE t_message
(
    message_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_type       SMALLINT                                NOT NULL,
    receiver_user_type INTEGER                                 NOT NULL,
    receiver_user_id   BIGINT                                  NOT NULL,
    data_id            VARCHAR(500)                                     DEFAULT '',
    title              VARCHAR(1000)                           NOT NULL,
    content            TEXT                                    NOT NULL,
    read_flag          BOOLEAN                                 NOT NULL DEFAULT FALSE,
    read_time          TIMESTAMP                                        DEFAULT NULL,
    create_time        TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time        TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_message PRIMARY KEY (message_id)
);

COMMENT ON TABLE t_message IS 't_message';
COMMENT ON COLUMN t_message.message_id IS '消息id';
COMMENT ON COLUMN t_message.message_type IS '消息类型';
COMMENT ON COLUMN t_message.receiver_user_type IS '接收者用户类型';
COMMENT ON COLUMN t_message.receiver_user_id IS '接收者用户id';
COMMENT ON COLUMN t_message.data_id IS '相关数据id';
COMMENT ON COLUMN t_message.title IS '标题';
COMMENT ON COLUMN t_message.content IS '内容';
COMMENT ON COLUMN t_message.read_flag IS '是否已读';
COMMENT ON COLUMN t_message.read_time IS '已读时间';
COMMENT ON COLUMN t_message.create_time IS '创建时间';
COMMENT ON COLUMN t_message.update_time IS '更新时间';
CREATE INDEX idx_t_message_idx_msg ON t_message (message_type, receiver_user_type, receiver_user_id);

-- ---------------------------------------------------------------------
-- t_oa_bank
-- ---------------------------------------------------------------------
CREATE TABLE t_oa_bank
(
    bank_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bank_name        VARCHAR(255)                            NOT NULL,
    account_name     VARCHAR(255)                            NOT NULL,
    account_number   VARCHAR(255)                            NOT NULL,
    remark           VARCHAR(255)                                     DEFAULT NULL,
    business_flag    BOOLEAN                                 NOT NULL,
    enterprise_id    BIGINT                                  NOT NULL,
    disabled_flag    BOOLEAN                                 NOT NULL DEFAULT FALSE,
    deleted_flag     BOOLEAN                                 NOT NULL DEFAULT FALSE,
    create_user_id   BIGINT                                  NOT NULL,
    create_user_name VARCHAR(50)                             NOT NULL,
    create_time      TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_oa_bank PRIMARY KEY (bank_id)
);

COMMENT ON TABLE t_oa_bank IS 't_oa_bank';
COMMENT ON COLUMN t_oa_bank.bank_id IS '银行信息ID';
COMMENT ON COLUMN t_oa_bank.bank_name IS '开户银行';
COMMENT ON COLUMN t_oa_bank.account_name IS '账户名称';
COMMENT ON COLUMN t_oa_bank.account_number IS '账号';
COMMENT ON COLUMN t_oa_bank.remark IS '备注';
COMMENT ON COLUMN t_oa_bank.business_flag IS '是否对公';
COMMENT ON COLUMN t_oa_bank.enterprise_id IS '企业ID';
COMMENT ON COLUMN t_oa_bank.disabled_flag IS '禁用状态';
COMMENT ON COLUMN t_oa_bank.deleted_flag IS '删除状态';
COMMENT ON COLUMN t_oa_bank.create_user_id IS '创建人ID';
COMMENT ON COLUMN t_oa_bank.create_user_name IS '创建人';
COMMENT ON COLUMN t_oa_bank.create_time IS '创建时间';
COMMENT ON COLUMN t_oa_bank.update_time IS '更新时间';
CREATE INDEX idx_t_oa_bank_idx_enterprise_id ON t_oa_bank (enterprise_id);

-- ---------------------------------------------------------------------
-- t_oa_enterprise
-- ---------------------------------------------------------------------
CREATE TABLE t_oa_enterprise
(
    enterprise_id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    enterprise_name            VARCHAR(255)                            NOT NULL,
    enterprise_logo            VARCHAR(255)                                     DEFAULT NULL,
    type                       INTEGER                                 NOT NULL DEFAULT 1,
    unified_social_credit_code VARCHAR(255)                            NOT NULL,
    contact                    VARCHAR(100)                            NOT NULL,
    contact_phone              VARCHAR(100)                            NOT NULL,
    email                      VARCHAR(100)                                     DEFAULT NULL,
    province                   VARCHAR(100)                                     DEFAULT NULL,
    province_name              VARCHAR(100)                                     DEFAULT NULL,
    city                       VARCHAR(100)                                     DEFAULT NULL,
    city_name                  VARCHAR(100)                                     DEFAULT NULL,
    district                   VARCHAR(100)                                     DEFAULT NULL,
    district_name              VARCHAR(100)                                     DEFAULT NULL,
    address                    VARCHAR(255)                                     DEFAULT NULL,
    business_license           VARCHAR(255)                                     DEFAULT NULL,
    disabled_flag              BOOLEAN                                 NOT NULL DEFAULT FALSE,
    deleted_flag               BOOLEAN                                 NOT NULL DEFAULT FALSE,
    create_user_id             BIGINT                                  NOT NULL,
    create_user_name           VARCHAR(50)                             NOT NULL,
    create_time                TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time                TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_oa_enterprise PRIMARY KEY (enterprise_id)
);

COMMENT ON TABLE t_oa_enterprise IS 't_oa_enterprise';
COMMENT ON COLUMN t_oa_enterprise.enterprise_id IS '企业ID';
COMMENT ON COLUMN t_oa_enterprise.enterprise_name IS '企业名称';
COMMENT ON COLUMN t_oa_enterprise.enterprise_logo IS '企业logo';
COMMENT ON COLUMN t_oa_enterprise.type IS '类型（1:有限公司;2:合伙公司）';
COMMENT ON COLUMN t_oa_enterprise.unified_social_credit_code IS '统一社会信用代码';
COMMENT ON COLUMN t_oa_enterprise.contact IS '联系人';
COMMENT ON COLUMN t_oa_enterprise.contact_phone IS '联系人电话';
COMMENT ON COLUMN t_oa_enterprise.email IS '邮箱';
COMMENT ON COLUMN t_oa_enterprise.province IS '省份';
COMMENT ON COLUMN t_oa_enterprise.province_name IS '省份名称';
COMMENT ON COLUMN t_oa_enterprise.city IS '市';
COMMENT ON COLUMN t_oa_enterprise.city_name IS '城市名称';
COMMENT ON COLUMN t_oa_enterprise.district IS '区县';
COMMENT ON COLUMN t_oa_enterprise.district_name IS '区县名称';
COMMENT ON COLUMN t_oa_enterprise.address IS '详细地址';
COMMENT ON COLUMN t_oa_enterprise.business_license IS '营业执照';
COMMENT ON COLUMN t_oa_enterprise.disabled_flag IS '禁用状态';
COMMENT ON COLUMN t_oa_enterprise.deleted_flag IS '删除状态';
COMMENT ON COLUMN t_oa_enterprise.create_user_id IS '创建人ID';
COMMENT ON COLUMN t_oa_enterprise.create_user_name IS '创建人';
COMMENT ON COLUMN t_oa_enterprise.create_time IS '创建时间';
COMMENT ON COLUMN t_oa_enterprise.update_time IS '更新时间';

-- ---------------------------------------------------------------------
-- t_oa_enterprise_employee
-- ---------------------------------------------------------------------
CREATE TABLE t_oa_enterprise_employee
(
    enterprise_employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    enterprise_id          VARCHAR(100)                            NOT NULL,
    employee_id            VARCHAR(100)                            NOT NULL,
    update_time            TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time            TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_oa_enterprise_employee PRIMARY KEY (enterprise_employee_id),
    CONSTRAINT uk_t_oa_enterprise_employee_uk_enterprise_employee UNIQUE (enterprise_id, employee_id)
);

COMMENT ON TABLE t_oa_enterprise_employee IS 't_oa_enterprise_employee';
COMMENT ON COLUMN t_oa_enterprise_employee.enterprise_employee_id IS '主键ID';
COMMENT ON COLUMN t_oa_enterprise_employee.enterprise_id IS '订单ID';
COMMENT ON COLUMN t_oa_enterprise_employee.employee_id IS '货物名称';
COMMENT ON COLUMN t_oa_enterprise_employee.update_time IS '更新时间';
COMMENT ON COLUMN t_oa_enterprise_employee.create_time IS '创建时间';
CREATE INDEX idx_t_oa_enterprise_employee_idx_employee_id ON t_oa_enterprise_employee (employee_id);
CREATE INDEX idx_t_oa_enterprise_employee_idx_enterprise_id ON t_oa_enterprise_employee (enterprise_id);

-- ---------------------------------------------------------------------
-- t_oa_invoice
-- ---------------------------------------------------------------------
CREATE TABLE t_oa_invoice
(
    invoice_id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    invoice_heads                  VARCHAR(255)                            NOT NULL,
    taxpayer_identification_number VARCHAR(255)                            NOT NULL,
    account_number                 VARCHAR(255)                            NOT NULL,
    bank_name                      VARCHAR(255)                            NOT NULL,
    remark                         VARCHAR(255)                                     DEFAULT NULL,
    enterprise_id                  BIGINT                                  NOT NULL,
    disabled_flag                  BOOLEAN                                 NOT NULL DEFAULT FALSE,
    deleted_flag                   BOOLEAN                                 NOT NULL DEFAULT FALSE,
    create_user_id                 BIGINT                                  NOT NULL,
    create_user_name               VARCHAR(50)                             NOT NULL,
    create_time                    TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time                    TIMESTAMP                               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t_oa_invoice PRIMARY KEY (invoice_id)
);

COMMENT ON TABLE t_oa_invoice IS 't_oa_invoice';
COMMENT ON COLUMN t_oa_invoice.invoice_id IS '发票信息ID';
COMMENT ON COLUMN t_oa_invoice.invoice_heads IS '开票抬头';
COMMENT ON COLUMN t_oa_invoice.taxpayer_identification_number IS '纳税人识别号';
COMMENT ON COLUMN t_oa_invoice.account_number IS '银行账户';
COMMENT ON COLUMN t_oa_invoice.bank_name IS '开户行';
COMMENT ON COLUMN t_oa_invoice.remark IS '备注';
COMMENT ON COLUMN t_oa_invoice.enterprise_id IS '企业ID';
COMMENT ON COLUMN t_oa_invoice.disabled_flag IS '禁用状态';
COMMENT ON COLUMN t_oa_invoice.deleted_flag IS '删除状态';
COMMENT ON COLUMN t_oa_invoice.create_user_id IS '创建人ID';
COMMENT ON COLUMN t_oa_invoice.create_user_name IS '创建人';
COMMENT ON COLUMN t_oa_invoice.create_time IS '创建时间';
COMMENT ON COLUMN t_oa_invoice.update_time IS '更新时间';
CREATE INDEX idx_t_oa_invoice_idx_enterprise_id ON t_oa_invoice (enterprise_id);

-- t_notice_type 种子数据
INSERT INTO t_notice_type (notice_type_id, notice_type_name, create_time, update_time)
VALUES (1, '新闻', '2022-08-16 20:29:15', '2024-09-03 21:44:42');
INSERT INTO t_notice_type (notice_type_id, notice_type_name, create_time, update_time)
VALUES (2, '通知', '2022-08-16 20:29:20', '2022-08-16 20:29:20');

-- t_mail_template 种子数据
INSERT INTO t_mail_template (template_code, template_subject, template_content, template_type, disable_flag,
                             update_time, create_time)
VALUES ('login_verification_code', '登录验证码',
        E'<!DOCTYPE HTML>\r\n<html>\r\n<head>\r\n  <title>登录提醒</title>\r\n  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n  <style>\r\n      * {\r\n          font-family: SimSun;\r\n          /* 4号字体 */\r\n          font-size: 18px;\r\n          /* 22磅行间距 */\r\n          line-height: 29px;\r\n      }\r\n\r\n      .main_font_size {\r\n          font-size: 12.0pt;\r\n      }\r\n\r\n      .mainContent {\r\n          line-height: 28px;\r\n      }\r\n\r\n      p {\r\n          margin: 0 auto;\r\n          text-align: justify;\r\n      }\r\n  </style>\r\n\r\n</head>\r\n<body>\r\n<div>\r\n  <div style=\"margin: 0px auto;width: 690px;\">\r\n    <div class=\"mainContent\">\r\n      <h1>验证码</h1>\r\n      <p>请在验证页面输入此验证码</p>\r\n      <p><b>${code}</b></p>\r\n      <p>验证码将于此电子邮件发出 5 分钟后过期。</p>\r\n      <p>如果你未曾提出此请求，可以忽略这封电子邮件。</p>\r\n    </div>\r\n\r\n  </div>\r\n</div>\r\n</body>\r\n</html>',
        'freemarker', FALSE, '2024-08-06 09:13:08', '2024-07-28 13:56:06');

-- t_smart_job 种子数据
INSERT INTO t_smart_job (job_id, job_name, job_class, trigger_type, trigger_value, enabled_flag, param,
                         last_execute_time, last_execute_log_id, sort, remark, deleted_flag, update_name, create_time,
                         update_time)
VALUES (1, '示例任务1', 'net.lab1024.sa.base.module.support.job.sample.SmartJobSample1', 'cron', '10 15 0/1 * * *',
        TRUE, '执行示例任务1', '2025-01-05 19:15:10', 7988, 1, '执行示例任务1', FALSE, '管理员', '2024-06-17 20:00:46',
        '2025-01-08 20:07:51');
INSERT INTO t_smart_job (job_id, job_name, job_class, trigger_type, trigger_value, enabled_flag, param,
                         last_execute_time, last_execute_log_id, sort, remark, deleted_flag, update_name, create_time,
                         update_time)
VALUES (2, '示例任务2', 'net.lab1024.sa.base.module.support.job.sample.SmartJobSample2', 'fixed_delay', '120', TRUE,
        '执行示例任务2', '2025-01-08 19:56:59', 8144, 2, '执行示例任务2', FALSE, '管理员', '2024-06-18 20:45:35',
        '2025-01-08 19:57:00');

-- ---------------------------------------------------------------------
-- 校正 identity 序列（(MAX+1, is_called=false) 形式，空表从 1 开始）
-- ---------------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('t_table_column', 'table_column_id'),
              (SELECT COALESCE(MAX(table_column_id), 0) FROM t_table_column) + 1, false);
SELECT setval(pg_get_serial_sequence('t_smart_job', 'job_id'), (SELECT COALESCE(MAX(job_id), 0) FROM t_smart_job) + 1,
              false);
SELECT setval(pg_get_serial_sequence('t_smart_job_log', 'log_id'),
              (SELECT COALESCE(MAX(log_id), 0) FROM t_smart_job_log) + 1, false);
SELECT setval(pg_get_serial_sequence('t_file', 'file_id'), (SELECT COALESCE(MAX(file_id), 0) FROM t_file) + 1, false);
SELECT setval(pg_get_serial_sequence('t_heart_beat_record', 'heart_beat_record_id'),
              (SELECT COALESCE(MAX(heart_beat_record_id), 0) FROM t_heart_beat_record) + 1, false);
SELECT setval(pg_get_serial_sequence('t_change_log', 'change_log_id'),
              (SELECT COALESCE(MAX(change_log_id), 0) FROM t_change_log) + 1, false);
SELECT setval(pg_get_serial_sequence('t_data_tracer', 'data_tracer_id'),
              (SELECT COALESCE(MAX(data_tracer_id), 0) FROM t_data_tracer) + 1, false);
SELECT setval(pg_get_serial_sequence('t_feedback', 'feedback_id'),
              (SELECT COALESCE(MAX(feedback_id), 0) FROM t_feedback) + 1, false);
SELECT setval(pg_get_serial_sequence('t_help_doc', 'help_doc_id'),
              (SELECT COALESCE(MAX(help_doc_id), 0) FROM t_help_doc) + 1, false);
SELECT setval(pg_get_serial_sequence('t_help_doc_catalog', 'help_doc_catalog_id'),
              (SELECT COALESCE(MAX(help_doc_catalog_id), 0) FROM t_help_doc_catalog) + 1, false);
SELECT setval(pg_get_serial_sequence('t_notice', 'notice_id'), (SELECT COALESCE(MAX(notice_id), 0) FROM t_notice) + 1,
              false);
SELECT setval(pg_get_serial_sequence('t_notice_type', 'notice_type_id'),
              (SELECT COALESCE(MAX(notice_type_id), 0) FROM t_notice_type) + 1, false);
SELECT setval(pg_get_serial_sequence('t_message', 'message_id'),
              (SELECT COALESCE(MAX(message_id), 0) FROM t_message) + 1, false);
SELECT setval(pg_get_serial_sequence('t_oa_bank', 'bank_id'), (SELECT COALESCE(MAX(bank_id), 0) FROM t_oa_bank) + 1,
              false);
SELECT setval(pg_get_serial_sequence('t_oa_enterprise', 'enterprise_id'),
              (SELECT COALESCE(MAX(enterprise_id), 0) FROM t_oa_enterprise) + 1, false);
SELECT setval(pg_get_serial_sequence('t_oa_enterprise_employee', 'enterprise_employee_id'),
              (SELECT COALESCE(MAX(enterprise_employee_id), 0) FROM t_oa_enterprise_employee) + 1, false);
SELECT setval(pg_get_serial_sequence('t_oa_invoice', 'invoice_id'),
              (SELECT COALESCE(MAX(invoice_id), 0) FROM t_oa_invoice) + 1, false);
