-- P1 分拣管理数据地基：分拣任务与任务明细。裁决依据 docs/decisions.md
-- 「P1 分拣管理裁决（2026-09-24）」第 1、2、3、8、9、16、17 条与补充第 15–20 条。
--
-- 边界（越界即违反裁决）：
--   * 分拣只写自己这两张表：不动 sales_order_item 的 actual_quantity / settlement_*，
--     不写 inventory_balance / inventory_movement，不创建出库单，也不移动预留触发点。
--   * 计划量是**进入分拣那一刻冻结的快照**，取自订单行的 actual_quantity；
--     标品在提交时按订购量落值、非标在确认前必须已录实重，因此 CONFIRMED 订单的
--     有效行必然 > 0，本表据此把快照定为 NOT NULL 且 > 0。
--   * 一条订单行最多被一条**活动**明细占用：占用位写在明细行自己身上
--     （与 delivery_route_order.assignment_status 同形态），因此部分唯一索引不需要跨表判断。
--     取消任务与置明细 RELEASED 必须在同一事务里完成，这是索引与任务状态不漂移的唯一前提。
--   * 无外键（项目级口径），关系完整性由服务层与下列 CHECK / 唯一索引共同保证。
CREATE SEQUENCE sorting_task_no_seq;

CREATE TABLE sorting_task (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 task_no VARCHAR(40) NOT NULL CHECK(btrim(task_no)<>''),
 warehouse_id BIGINT NOT NULL,
 warehouse_name_snapshot VARCHAR(100) NOT NULL CHECK(btrim(warehouse_name_snapshot)<>''),
 assignee_employee_id BIGINT,
 status VARCHAR(16) NOT NULL DEFAULT 'PENDING'
   CHECK(status IN ('PENDING','SORTING','COMPLETED','CANCELLED')),
 remark VARCHAR(500),
 started_at TIMESTAMPTZ,
 completed_at TIMESTAMPTZ,
 cancelled_at TIMESTAMPTZ,
 print_count INTEGER NOT NULL DEFAULT 0 CHECK(print_count>=0),
 last_printed_at TIMESTAMPTZ,
 last_printed_by VARCHAR(64),
 version INTEGER NOT NULL DEFAULT 0 CHECK(version>=0), deleted BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 created_by VARCHAR(64), updated_by VARCHAR(64)
);

CREATE TABLE sorting_task_item (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 task_id BIGINT NOT NULL,
 sales_order_id BIGINT NOT NULL,
 sales_order_item_id BIGINT NOT NULL,
 order_no_snapshot VARCHAR(40) NOT NULL,
 customer_id BIGINT NOT NULL,
 customer_name_snapshot VARCHAR(100) NOT NULL,
 spu_id BIGINT NOT NULL,
 sku_id BIGINT NOT NULL,
 spu_code_snapshot VARCHAR(64),
 product_name_snapshot VARCHAR(200) NOT NULL,
 sku_code_snapshot VARCHAR(64),
 spec_name_snapshot VARCHAR(100),
 sale_unit_snapshot VARCHAR(32) NOT NULL,
 product_type_snapshot VARCHAR(16) NOT NULL
   CHECK(product_type_snapshot IN ('STANDARD','NON_STANDARD')),
 planned_quantity_snapshot NUMERIC(18,4) NOT NULL CHECK(planned_quantity_snapshot>0),
 sorted_quantity NUMERIC(18,4) CHECK(sorted_quantity IS NULL OR sorted_quantity>=0),
 result VARCHAR(20) CHECK(result IS NULL OR result IN ('NORMAL','SHORT','OUT_OF_STOCK','OVER')),
 reason VARCHAR(500),
 sorted_by VARCHAR(64),
 sorted_at TIMESTAMPTZ,
 occupation_status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'
   CHECK(occupation_status IN ('ACTIVE','RELEASED')),
 version INTEGER NOT NULL DEFAULT 0 CHECK(version>=0), deleted BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 created_by VARCHAR(64), updated_by VARCHAR(64),
 -- 结果与分拣量成对出现：只有「未处理」和「已处理」两态，不存在有量无结果或有结果无量。
 CONSTRAINT ck_sorting_task_item_processed_pairing CHECK
  ((result IS NULL AND sorted_quantity IS NULL) OR (result IS NOT NULL AND sorted_quantity IS NOT NULL)),
 -- 任何与计划量不一致的结果都要写原因（P1 不设容差阈值，也没有自动重新结算）。
 CONSTRAINT ck_sorting_task_item_diff_reason CHECK
  (result IS NULL OR result = 'NORMAL' OR btrim(COALESCE(reason,''))<>'')
);

COMMENT ON TABLE sorting_task IS '分拣任务：某仓库内派给某位分拣员的一批订单行，实发事实的产生地';
COMMENT ON COLUMN sorting_task.id IS '主键';
COMMENT ON COLUMN sorting_task.task_no IS '分拣单号，SRT + 业务日(Asia/Shanghai) + 全局非重置序号';
COMMENT ON COLUMN sorting_task.warehouse_id IS '作业仓库，建单时由操作人显式选择并经服务端校验；不从订单/客户/线路推断';
COMMENT ON COLUMN sorting_task.warehouse_name_snapshot IS '建单时的仓库名称快照';
COMMENT ON COLUMN sorting_task.assignee_employee_id IS '受指派分拣员（t_employee.id）；NULL 表示未指派，仅对持分配权者可见';
COMMENT ON COLUMN sorting_task.status IS 'PENDING 待分拣 / SORTING 分拣中 / COMPLETED 已完成 / CANCELLED 已取消；取消即释放明细占用，不存在 RELEASED 任务状态';
COMMENT ON COLUMN sorting_task.remark IS '备注';
COMMENT ON COLUMN sorting_task.started_at IS '首次进入 SORTING 的时间';
COMMENT ON COLUMN sorting_task.completed_at IS '最近一次完成时间；重开后保留，作为该任务曾完成的痕迹';
COMMENT ON COLUMN sorting_task.cancelled_at IS '取消时间';
COMMENT ON COLUMN sorting_task.print_count IS '打印触发次数；打印只代表出单动作，不代表物理出纸成功，也不改任何状态';
COMMENT ON COLUMN sorting_task.last_printed_at IS '最近一次打印时间';
COMMENT ON COLUMN sorting_task.last_printed_by IS '最近一次打印人（loginId 形态，与审计列同口径）';
COMMENT ON COLUMN sorting_task.version IS '乐观锁版本';
COMMENT ON COLUMN sorting_task.deleted IS '逻辑删除标识；取消用状态表达，不用软删';
COMMENT ON COLUMN sorting_task.created_at IS '创建时间';
COMMENT ON COLUMN sorting_task.updated_at IS '最后修改时间';
COMMENT ON COLUMN sorting_task.created_by IS '创建人';
COMMENT ON COLUMN sorting_task.updated_by IS '最后修改人';

COMMENT ON TABLE sorting_task_item IS '分拣任务明细：一条订单行在本任务里的一次分拣，与订单行共用同一套实发事实';
COMMENT ON COLUMN sorting_task_item.id IS '主键';
COMMENT ON COLUMN sorting_task_item.task_id IS '所属分拣任务';
COMMENT ON COLUMN sorting_task_item.sales_order_id IS '销售订单ID';
COMMENT ON COLUMN sorting_task_item.sales_order_item_id IS '销售订单行ID；活动占用下全局唯一（见 uk_sorting_task_item_active_line）';
COMMENT ON COLUMN sorting_task_item.order_no_snapshot IS '销售订单编号快照';
COMMENT ON COLUMN sorting_task_item.customer_id IS '客户ID，供两视角分组与关联，不参与跨表约束';
COMMENT ON COLUMN sorting_task_item.customer_name_snapshot IS '客户名称快照，供标签与小票直接取用';
COMMENT ON COLUMN sorting_task_item.spu_id IS '商品SPU ID';
COMMENT ON COLUMN sorting_task_item.sku_id IS '商品SKU ID';
COMMENT ON COLUMN sorting_task_item.spu_code_snapshot IS '商品编码快照';
COMMENT ON COLUMN sorting_task_item.product_name_snapshot IS '商品名称快照';
COMMENT ON COLUMN sorting_task_item.sku_code_snapshot IS '规格编码快照';
COMMENT ON COLUMN sorting_task_item.spec_name_snapshot IS '规格名称快照';
COMMENT ON COLUMN sorting_task_item.sale_unit_snapshot IS '销售单位名称快照；P1 不做单位换算，汇总也不跨单位求和';
COMMENT ON COLUMN sorting_task_item.product_type_snapshot IS '商品类型快照：STANDARD 标品按数量确认，NON_STANDARD 非标品录入实重';
COMMENT ON COLUMN sorting_task_item.planned_quantity_snapshot IS '计划量 = 建单时冻结的订单行 actual_quantity，恒 > 0；不回写订单';
COMMENT ON COLUMN sorting_task_item.sorted_quantity IS '实际分拣量/实重，单位同 sale_unit_snapshot；允许 0（整行缺货），未处理时为 NULL';
COMMENT ON COLUMN sorting_task_item.result IS '分拣结果：NORMAL 正常 / SHORT 少拣 / OUT_OF_STOCK 缺货 / OVER 多拣；未处理时为 NULL';
COMMENT ON COLUMN sorting_task_item.reason IS '差异原因；结果非 NORMAL 时必填（库里由 ck_sorting_task_item_diff_reason 强制）';
COMMENT ON COLUMN sorting_task_item.sorted_by IS '录入该结果的操作人（loginId 形态）';
COMMENT ON COLUMN sorting_task_item.sorted_at IS '录入该结果的时间';
COMMENT ON COLUMN sorting_task_item.occupation_status IS 'ACTIVE 占用该订单行；任务取消时同一事务内置 RELEASED，行仍保留作历史';
COMMENT ON COLUMN sorting_task_item.version IS '乐观锁版本';
COMMENT ON COLUMN sorting_task_item.deleted IS '逻辑删除标识';
COMMENT ON COLUMN sorting_task_item.created_at IS '创建时间';
COMMENT ON COLUMN sorting_task_item.updated_at IS '最后修改时间';
COMMENT ON COLUMN sorting_task_item.created_by IS '创建人';
COMMENT ON COLUMN sorting_task_item.updated_by IS '最后修改人';

-- 单号不复用：唯一性覆盖软删行，与订单/收货单编号口径一致。
CREATE UNIQUE INDEX uk_sorting_task_no ON sorting_task(task_no);
-- 数据范围谓词：授权仓 ∩ 受指派人，状态用于「我的待办」过滤。
CREATE INDEX idx_sorting_task_scope ON sorting_task(warehouse_id,assignee_employee_id,status) WHERE deleted=FALSE;
-- 裁决第 2 条：一条订单行只能被一条活动明细占用；重复生成任务在此处兜底。
CREATE UNIQUE INDEX uk_sorting_task_item_active_line ON sorting_task_item(sales_order_item_id)
 WHERE deleted=FALSE AND occupation_status='ACTIVE';
CREATE INDEX idx_sorting_task_item_task ON sorting_task_item(task_id) WHERE deleted=FALSE;
-- 配送资格按订单聚合判定（补充第 18 条），需要按订单快速取到全部明细。
CREATE INDEX idx_sorting_task_item_order ON sorting_task_item(sales_order_id) WHERE deleted=FALSE;
-- 按商品汇总视角：按 SKU + 单位分组，不跨单位求和。
CREATE INDEX idx_sorting_task_item_sku ON sorting_task_item(sku_id,sale_unit_snapshot) WHERE deleted=FALSE;
