-- ============================================================================
-- P3 Finance R1 数据地基：八张财务事实表 + 五条单号序列。
--
-- 裁决依据 docs/decisions.md「P3 Finance R1 裁决（2026-09-25）」第一批 Q1–Q19、
-- 第二批 Q5–Q27、10 条全局不变量，与「第三批正式裁决（D-1 … D-5，2026-09-26）」；
-- 正式设计见 docs/plan/finance-r1-design.md（§3–§8、§11、§17）。
--
-- 边界（越界即违反裁决）：
--   * 本迁移**不 ALTER 任何既有表**：sales_order(_item) / order_return(_item) / order_refund /
--     purchase_order(_item) / purchase_receipt(_item) / inventory_* / delivery_* 一列未动，
--     所有关联都是新表上的新列指向既有主键。
--   * 财务域**没有状态机**（Q17 / Q20）：八张表都不含 status / settled_amount / open_amount /
--     approver / approval_state。已核销额、未核销额、超额核销、结清状态、有效额全部读时派生。
--   * 方向编码在 entry_type 里，金额与数量恒为正（照 inventory_movement 的既有纪律）：
--     应收 / 应付用 NORMAL / RED，收款 / 付款 / 核销用 NORMAL / REVERSE。
--   * **不存范围归属列**：seller_id / purchaser_id 是范围归属，读时 join 业务表取活值
--     （P0 裁决 2「授权范围即时生效」，落库即漂移）。customer_id / supplier_id 是结算对方，
--     属财务事实本身，落库；名称一律快照列，只服务展示与导出。
--   * **不存 due_date / 税率 / 税额 / 币种 / 账龄列**（Q14 / Q15，R2 才议）。
--   * append-only：七张事实表带 CHECK (deleted = FALSE)（照 V19:83 的
--     ck_inventory_movement_append_only）。它拒绝「用软删模拟删除历史财务事实」，
--     不拒绝正常列更新，因此与 @Version 乐观锁不冲突。finance_operation_log 照
--     order_operation_log 的形态**不设 deleted 列**，结构上不存在删除入口。
--     实体刻意不用 @TableLogic（它表达「可被软删的实体」，与财务事实语义相反），
--     读取一律在 SQL 里显式写 deleted = FALSE —— 与 inventory_movement 同一取舍。
--   * 无外键（项目级口径），关系完整性由服务层与下列 CHECK / 唯一索引共同保证。
--   * 不建 CHECK (amount = ROUND(quantity * unit_price, 4))：红字明细的 amount 直接取
--     order_return_item.approved_amount（订单域已算，财务不重算）。把跨域公式钉成本表的
--     CHECK，会让订单域任何一次金额口径调整**在数据库层阻塞 OrderReturn approve**，
--     正是 D-4 明令禁止的行为。金额一致性由 F1-2 的生成器 IT 断言，不由本表 CHECK 承担。
-- ============================================================================

-- 单号序列：全局非重置（照 sorting_task_no_seq），前缀 + 业务日(Asia/Shanghai) + %06d
-- 由 ScmDocumentNumbers.format 拼接，各表只保留自己的前缀常量与取号。
CREATE SEQUENCE finance_receivable_no_seq;
CREATE SEQUENCE finance_payable_no_seq;
CREATE SEQUENCE finance_receipt_no_seq;
CREATE SEQUENCE finance_payment_no_seq;
CREATE SEQUENCE finance_write_off_no_seq;

-- ============================================================================
-- 1. finance_receivable —— 应收单头（一张 sales_order 一单，Q4）
-- ============================================================================
CREATE TABLE finance_receivable (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receivable_no          VARCHAR(64) NOT NULL CHECK (btrim(receivable_no) <> ''),
    source_type            VARCHAR(32) NOT NULL
        CONSTRAINT ck_finance_receivable_source_type CHECK (source_type IN ('SALES_ORDER', 'ORDER_RETURN')),
    source_id              BIGINT      NOT NULL,
    order_id               BIGINT      NOT NULL,
    customer_id            BIGINT      NOT NULL,
    customer_name_snapshot VARCHAR(150) NOT NULL CHECK (btrim(customer_name_snapshot) <> ''),
    entry_type             VARCHAR(8)  NOT NULL
        CONSTRAINT ck_finance_receivable_entry_type CHECK (entry_type IN ('NORMAL', 'RED')),
    original_receivable_id BIGINT,
    amount                 NUMERIC(18, 4) NOT NULL CHECK (amount > 0),
    event_at               TIMESTAMPTZ NOT NULL,
    reason                 VARCHAR(500),
    version                INTEGER     NOT NULL DEFAULT 0 CHECK (version >= 0),
    deleted                BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by             VARCHAR(64),
    updated_by             VARCHAR(64),
    -- 方向与来源配对：正常应收只来自已签收订单，红字应收只来自已批准退货（Q1 / Q27）。
    CONSTRAINT ck_finance_receivable_source_pairing CHECK (
        (entry_type = 'NORMAL' AND source_type = 'SALES_ORDER')
            OR (entry_type = 'RED' AND source_type = 'ORDER_RETURN')
        ),
    -- 红字必须引用原应收并写原因；正常应收两者都必须为空（Q13 / Q27，全局不变量 1）。
    CONSTRAINT ck_finance_receivable_entry_pairing CHECK (
        (entry_type = 'NORMAL' AND original_receivable_id IS NULL)
            OR (entry_type = 'RED' AND original_receivable_id IS NOT NULL
                AND btrim(COALESCE(reason, '')) <> '')
        ),
    CONSTRAINT ck_finance_receivable_append_only CHECK (deleted = FALSE)
);

-- ============================================================================
-- 2. finance_receivable_item —— 应收明细
--    正常：一条 inventory_outbound_item 一行；红字：一条 order_return_item 一行。
-- ============================================================================
CREATE TABLE finance_receivable_item (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receivable_id     BIGINT      NOT NULL,
    source_type       VARCHAR(32) NOT NULL
        CONSTRAINT ck_finance_receivable_item_source_type
            CHECK (source_type IN ('INVENTORY_OUTBOUND_ITEM', 'ORDER_RETURN_ITEM')),
    source_id         BIGINT      NOT NULL,
    order_item_id     BIGINT      NOT NULL,
    sku_id            BIGINT      NOT NULL,
    sku_name_snapshot VARCHAR(150) NOT NULL CHECK (btrim(sku_name_snapshot) <> ''),
    unit_snapshot     VARCHAR(32) NOT NULL CHECK (btrim(unit_snapshot) <> ''),
    quantity          NUMERIC(18, 4) NOT NULL CHECK (quantity > 0),
    unit_price        NUMERIC(18, 4) NOT NULL CHECK (unit_price >= 0),
    amount            NUMERIC(18, 4) NOT NULL CHECK (amount >= 0),
    version           INTEGER     NOT NULL DEFAULT 0 CHECK (version >= 0),
    deleted           BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by        VARCHAR(64),
    updated_by        VARCHAR(64),
    CONSTRAINT ck_finance_receivable_item_append_only CHECK (deleted = FALSE)
);

-- ============================================================================
-- 3. finance_payable —— 应付单头（一张 purchase_receipt 一单，Q10）
--    红字应付是**另一张** entry_type='RED' 的单（Q13），来源为 MANUAL 且 source_id 为 NULL。
-- ============================================================================
CREATE TABLE finance_payable (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payable_no             VARCHAR(64) NOT NULL CHECK (btrim(payable_no) <> ''),
    source_type            VARCHAR(32) NOT NULL
        CONSTRAINT ck_finance_payable_source_type CHECK (source_type IN ('PURCHASE_RECEIPT', 'MANUAL')),
    source_id              BIGINT,
    purchase_order_id      BIGINT      NOT NULL,
    supplier_id            BIGINT      NOT NULL,
    supplier_name_snapshot VARCHAR(150) NOT NULL CHECK (btrim(supplier_name_snapshot) <> ''),
    entry_type             VARCHAR(8)  NOT NULL
        CONSTRAINT ck_finance_payable_entry_type CHECK (entry_type IN ('NORMAL', 'RED')),
    original_payable_id    BIGINT,
    amount                 NUMERIC(18, 4) NOT NULL CHECK (amount > 0),
    event_at               TIMESTAMPTZ NOT NULL,
    reason                 VARCHAR(500),
    version                INTEGER     NOT NULL DEFAULT 0 CHECK (version >= 0),
    deleted                BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by             VARCHAR(64),
    updated_by             VARCHAR(64),
    -- MANUAL 来源配对（设计稿 §3.1 修正）：红字应付是手工事实，没有外部业务行，
    -- 因此 source_id 必须为 NULL —— 这也让它落在 uk_finance_payable_source_active 的
    -- 「source_id IS NOT NULL」谓词之外，其防重由可冲上限 + 请求级幂等键承担（§8.3）。
    CONSTRAINT ck_finance_payable_source_pairing CHECK (
        (entry_type = 'NORMAL' AND source_type = 'PURCHASE_RECEIPT' AND source_id IS NOT NULL
            AND original_payable_id IS NULL)
            OR (entry_type = 'RED' AND source_type = 'MANUAL' AND source_id IS NULL
                AND original_payable_id IS NOT NULL AND btrim(COALESCE(reason, '')) <> '')
        ),
    CONSTRAINT ck_finance_payable_append_only CHECK (deleted = FALSE)
);

-- ============================================================================
-- 4. finance_payable_item —— 应付明细（一条 purchase_receipt_item 一行；红字为 MANUAL）
-- ============================================================================
CREATE TABLE finance_payable_item (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payable_id             BIGINT      NOT NULL,
    source_type            VARCHAR(32) NOT NULL
        CONSTRAINT ck_finance_payable_item_source_type
            CHECK (source_type IN ('PURCHASE_RECEIPT_ITEM', 'MANUAL')),
    source_id              BIGINT,
    purchase_order_item_id BIGINT      NOT NULL,
    sku_id                 BIGINT      NOT NULL,
    sku_name_snapshot      VARCHAR(150) NOT NULL CHECK (btrim(sku_name_snapshot) <> ''),
    unit_snapshot          VARCHAR(32) NOT NULL CHECK (btrim(unit_snapshot) <> ''),
    quantity               NUMERIC(18, 4) NOT NULL CHECK (quantity > 0),
    unit_price             NUMERIC(18, 4) NOT NULL CHECK (unit_price >= 0),
    amount                 NUMERIC(18, 4) NOT NULL CHECK (amount >= 0),
    version                INTEGER     NOT NULL DEFAULT 0 CHECK (version >= 0),
    deleted                BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by             VARCHAR(64),
    updated_by             VARCHAR(64),
    CONSTRAINT ck_finance_payable_item_source_pairing CHECK (
        (source_type = 'PURCHASE_RECEIPT_ITEM' AND source_id IS NOT NULL)
            OR (source_type = 'MANUAL' AND source_id IS NULL)
        ),
    CONSTRAINT ck_finance_payable_item_append_only CHECK (deleted = FALSE)
);

-- ============================================================================
-- 5. finance_receipt —— 收款（一笔钱一单，可无应收＝预收，Q16）
--    entry_type / reverse_of_id / reason 是 D-3 的 append-only 纠错三列。
-- ============================================================================
CREATE TABLE finance_receipt (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no             VARCHAR(64) NOT NULL CHECK (btrim(receipt_no) <> ''),
    customer_id            BIGINT      NOT NULL,
    customer_name_snapshot VARCHAR(150) NOT NULL CHECK (btrim(customer_name_snapshot) <> ''),
    amount                 NUMERIC(18, 4) NOT NULL CHECK (amount > 0),
    method                 VARCHAR(16) NOT NULL,
    received_at            TIMESTAMPTZ NOT NULL,
    entry_type             VARCHAR(8)  NOT NULL
        CONSTRAINT ck_finance_receipt_entry_type CHECK (entry_type IN ('NORMAL', 'REVERSE')),
    reverse_of_id          BIGINT,
    reason                 VARCHAR(500),
    external_reference     VARCHAR(128),
    remark                 VARCHAR(500),
    version                INTEGER     NOT NULL DEFAULT 0 CHECK (version >= 0),
    deleted                BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by             VARCHAR(64),
    updated_by             VARCHAR(64),
    -- 方式固定三值（Q21）：Java enum + DB CHECK，不用 t_dict。本期不得出现在线支付 / 余额 / COD / 充值。
    CONSTRAINT ck_finance_receipt_method CHECK (method IN ('CASH', 'BANK_TRANSFER', 'OTHER')),
    CONSTRAINT ck_finance_receipt_entry_pairing CHECK (
        (entry_type = 'NORMAL' AND reverse_of_id IS NULL)
            OR (entry_type = 'REVERSE' AND reverse_of_id IS NOT NULL
                AND btrim(COALESCE(reason, '')) <> '')
        ),
    CONSTRAINT ck_finance_receipt_append_only CHECK (deleted = FALSE)
);

-- ============================================================================
-- 6. finance_payment —— 付款（一笔钱一单，可无应付＝预付；退款付款带来源，Q19）
-- ============================================================================
CREATE TABLE finance_payment (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_no                  VARCHAR(64) NOT NULL CHECK (btrim(payment_no) <> ''),
    counterparty_type           VARCHAR(16) NOT NULL
        CONSTRAINT ck_finance_payment_counterparty_type CHECK (counterparty_type IN ('SUPPLIER', 'CUSTOMER')),
    counterparty_id             BIGINT      NOT NULL,
    counterparty_name_snapshot  VARCHAR(150) NOT NULL CHECK (btrim(counterparty_name_snapshot) <> ''),
    amount                      NUMERIC(18, 4) NOT NULL CHECK (amount > 0),
    method                      VARCHAR(16) NOT NULL,
    paid_at                     TIMESTAMPTZ NOT NULL,
    entry_type                  VARCHAR(8)  NOT NULL
        CONSTRAINT ck_finance_payment_entry_type CHECK (entry_type IN ('NORMAL', 'REVERSE')),
    reverse_of_id               BIGINT,
    reason                      VARCHAR(500),
    external_reference          VARCHAR(128),
    source_type                 VARCHAR(32)
        CONSTRAINT ck_finance_payment_source_type CHECK (source_type IS NULL OR source_type = 'ORDER_REFUND'),
    source_id                   BIGINT,
    remark                      VARCHAR(500),
    version                     INTEGER     NOT NULL DEFAULT 0 CHECK (version >= 0),
    deleted                     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by                  VARCHAR(64),
    updated_by                  VARCHAR(64),
    -- 与收款共用同一套三值枚举（Q21）。
    CONSTRAINT ck_finance_payment_method CHECK (method IN ('CASH', 'BANK_TRANSFER', 'OTHER')),
    CONSTRAINT ck_finance_payment_entry_pairing CHECK (
        (entry_type = 'NORMAL' AND reverse_of_id IS NULL)
            OR (entry_type = 'REVERSE' AND reverse_of_id IS NOT NULL
                AND btrim(COALESCE(reason, '')) <> '')
        ),
    -- ORDER_REFUND 来源配对：source_type 与 source_id 要么都为空，要么都齐（Q19 / Q26）。
    CONSTRAINT ck_finance_payment_source_pairing CHECK (
        (source_type IS NULL AND source_id IS NULL)
            OR (source_type = 'ORDER_REFUND' AND source_id IS NOT NULL)
        ),
    -- D-3：反向行的来源必须为 NULL。否则它会与原行抢同一个 ORDER_REFUND 唯一键，
    -- 结果是「登错一笔退款付款后再也反向不掉」—— 纠错路径被自己的防重索引锁死。
    CONSTRAINT ck_finance_payment_reverse_no_source CHECK (
        entry_type = 'NORMAL' OR (source_type IS NULL AND source_id IS NULL)
        ),
    CONSTRAINT ck_finance_payment_append_only CHECK (deleted = FALSE)
);

-- ============================================================================
-- 7. finance_write_off —— 核销关系行（M:N，Q17）；撤销＝反向核销事实（Q18）
--    刻意不存 settled_amount / open_amount / status：全部读时派生（Q17，全局不变量 6）。
-- ============================================================================
CREATE TABLE finance_write_off (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    write_off_no   VARCHAR(64) NOT NULL CHECK (btrim(write_off_no) <> ''),
    source_type    VARCHAR(16) NOT NULL
        CONSTRAINT ck_finance_write_off_source_type CHECK (source_type IN ('RECEIPT', 'PAYMENT')),
    source_id      BIGINT      NOT NULL,
    target_type    VARCHAR(16) NOT NULL
        CONSTRAINT ck_finance_write_off_target_type CHECK (target_type IN ('RECEIVABLE', 'PAYABLE')),
    target_id      BIGINT      NOT NULL,
    amount         NUMERIC(18, 4) NOT NULL CHECK (amount > 0),
    entry_type     VARCHAR(8)  NOT NULL
        CONSTRAINT ck_finance_write_off_entry_type CHECK (entry_type IN ('NORMAL', 'REVERSE')),
    reverse_of_id  BIGINT,
    reason         VARCHAR(500),
    written_off_at TIMESTAMPTZ NOT NULL,
    operator       VARCHAR(64) NOT NULL CHECK (btrim(operator) <> ''),
    version        INTEGER     NOT NULL DEFAULT 0 CHECK (version >= 0),
    deleted        BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by     VARCHAR(64),
    updated_by     VARCHAR(64),
    -- 收款只能核应收、付款只能核应付（Q17）。
    CONSTRAINT ck_finance_write_off_pairing CHECK (
        (source_type = 'RECEIPT' AND target_type = 'RECEIVABLE')
            OR (source_type = 'PAYMENT' AND target_type = 'PAYABLE')
        ),
    CONSTRAINT ck_finance_write_off_entry_pairing CHECK (
        (entry_type = 'NORMAL' AND reverse_of_id IS NULL)
            OR (entry_type = 'REVERSE' AND reverse_of_id IS NOT NULL
                AND btrim(COALESCE(reason, '')) <> '')
        ),
    CONSTRAINT ck_finance_write_off_append_only CHECK (deleted = FALSE)
);

-- ============================================================================
-- 8. finance_operation_log —— 财务操作日志（形态照 order_operation_log，V13:114-129）
--    刻意不设 deleted / version 列：本表没有任何删除或修改入口，append-only 是结构性的，
--    不需要一列恒为 FALSE 的 deleted 来表达。
-- ============================================================================
CREATE TABLE finance_operation_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_type  VARCHAR(16) NOT NULL,
    business_id    BIGINT      NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    operator       VARCHAR(64) NOT NULL CHECK (btrim(operator) <> ''),
    reason         VARCHAR(500),
    before_data    JSONB,
    after_data     JSONB,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by     VARCHAR(64),
    CONSTRAINT ck_finance_operation_log_business_type CHECK (
        business_type IN ('RECEIVABLE', 'PAYABLE', 'RECEIPT', 'PAYMENT', 'WRITE_OFF')
        ),
    -- 白名单即 F1-1 的最终范围（八个值，含 D-3 带来的 RECEIPT_REVERSE / PAYMENT_REVERSE）。
    CONSTRAINT ck_finance_operation_log_type CHECK (
        operation_type IN ('GENERATE', 'RED_GENERATE', 'RECEIVE', 'PAY',
                           'WRITE_OFF', 'WRITE_OFF_REVERSE',
                           'RECEIPT_REVERSE', 'PAYMENT_REVERSE')
        ),
    CONSTRAINT ck_finance_operation_log_before_data
        CHECK (before_data IS NULL OR jsonb_typeof(before_data) = 'object'),
    CONSTRAINT ck_finance_operation_log_after_data
        CHECK (after_data IS NULL OR jsonb_typeof(after_data) = 'object')
);

-- ============================================================================
-- COMMENT：写业务含义，不写「财务域 id」式占位说明（AGENTS.md §34.1）
-- ============================================================================
COMMENT ON TABLE finance_receivable IS '应收单头：一张已签收销售订单一条正常应收，一张已批准退货一条红字应收';
COMMENT ON COLUMN finance_receivable.id IS '主键';
COMMENT ON COLUMN finance_receivable.receivable_no IS '应收单号，AR + 业务日(Asia/Shanghai) + 全局非重置序号';
COMMENT ON COLUMN finance_receivable.source_type IS 'SALES_ORDER 正常应收来源 / ORDER_RETURN 红字应收来源；与 entry_type 配对';
COMMENT ON COLUMN finance_receivable.source_id IS '来源主键：正常＝sales_order.id，红字＝order_return.id';
COMMENT ON COLUMN finance_receivable.order_id IS '销售订单ID；红字也指向被冲订单，便于按单查询';
COMMENT ON COLUMN finance_receivable.customer_id IS '结算对方（财务事实本身，落库）；不存 seller_id，范围归属读时 join sales_order 取活值';
COMMENT ON COLUMN finance_receivable.customer_name_snapshot IS '客户名称快照，只服务展示与导出，不参与关联';
COMMENT ON COLUMN finance_receivable.entry_type IS 'NORMAL 正常 / RED 红字；方向编码在类型里，金额恒为正';
COMMENT ON COLUMN finance_receivable.original_receivable_id IS '红字必填，指向被冲的正常应收；正常应收必须为空';
COMMENT ON COLUMN finance_receivable.amount IS '单头金额＝明细之和，NUMERIC(18,4)、HALF_UP、恒 > 0；0 元事实不生成（Q8）';
COMMENT ON COLUMN finance_receivable.event_at IS '业务事件时点：正常＝签收 signed_at，红字＝退货 approved_at；不是写入时刻';
COMMENT ON COLUMN finance_receivable.reason IS '红字原因，红字必填非空';
COMMENT ON COLUMN finance_receivable.version IS '乐观锁版本';
COMMENT ON COLUMN finance_receivable.deleted IS '恒为 FALSE（ck_finance_receivable_append_only）；保留列只为匹配部分唯一索引谓词';
COMMENT ON COLUMN finance_receivable.created_at IS '创建时间';
COMMENT ON COLUMN finance_receivable.updated_at IS '最后修改时间';
COMMENT ON COLUMN finance_receivable.created_by IS '创建人';
COMMENT ON COLUMN finance_receivable.updated_by IS '最后修改人';

COMMENT ON TABLE finance_receivable_item IS '应收明细：正常一条出库行一行，红字一条退货行一行；行级追溯的落点';
COMMENT ON COLUMN finance_receivable_item.id IS '主键';
COMMENT ON COLUMN finance_receivable_item.receivable_id IS '所属应收单头';
COMMENT ON COLUMN finance_receivable_item.source_type IS 'INVENTORY_OUTBOUND_ITEM 正常明细来源 / ORDER_RETURN_ITEM 红字明细来源';
COMMENT ON COLUMN finance_receivable_item.source_id IS '来源主键：正常＝inventory_outbound_item.id，红字＝order_return_item.id';
COMMENT ON COLUMN finance_receivable_item.order_item_id IS '销售订单行ID；红字明细只保留本列，不存行级原明细指针（一条订单行将来可能对应多条出库行）';
COMMENT ON COLUMN finance_receivable_item.sku_id IS '商品SKU ID';
COMMENT ON COLUMN finance_receivable_item.sku_name_snapshot IS '商品名称快照';
COMMENT ON COLUMN finance_receivable_item.unit_snapshot IS '单位名称快照；不做单位换算，也不跨单位求和';
COMMENT ON COLUMN finance_receivable_item.quantity IS '正常＝实际出库量（Q2），红字＝退货批准量；恒 > 0';
COMMENT ON COLUMN finance_receivable_item.unit_price IS '正常＝sales_order_item.locked_unit_price（Q3，唯一价格源），红字＝退货行锁定单价；>= 0';
COMMENT ON COLUMN finance_receivable_item.amount IS '正常＝ROUND(quantity × unit_price, 4)，红字＝order_return_item.approved_amount（订单域已算，财务不重算）';
COMMENT ON COLUMN finance_receivable_item.version IS '乐观锁版本';
COMMENT ON COLUMN finance_receivable_item.deleted IS '恒为 FALSE（append-only）';
COMMENT ON COLUMN finance_receivable_item.created_at IS '创建时间';
COMMENT ON COLUMN finance_receivable_item.updated_at IS '最后修改时间';
COMMENT ON COLUMN finance_receivable_item.created_by IS '创建人';
COMMENT ON COLUMN finance_receivable_item.updated_by IS '最后修改人';

COMMENT ON TABLE finance_payable IS '应付单头：一张已确认收货单一条正常应付；红字应付是另一张 entry_type=RED 的手工单';
COMMENT ON COLUMN finance_payable.id IS '主键';
COMMENT ON COLUMN finance_payable.payable_no IS '应付单号，AP + 业务日(Asia/Shanghai) + 全局非重置序号';
COMMENT ON COLUMN finance_payable.source_type IS 'PURCHASE_RECEIPT 正常应付来源 / MANUAL 手工红字；与 entry_type 配对';
COMMENT ON COLUMN finance_payable.source_id IS '正常＝purchase_receipt.id；手工红字必须为 NULL（无外部业务行）';
COMMENT ON COLUMN finance_payable.purchase_order_id IS '采购订单ID；红字也指向原采购单';
COMMENT ON COLUMN finance_payable.supplier_id IS '结算对方（财务事实本身，落库）；不存 purchaser_id，范围归属读时 join purchase_receipt → purchase_order 取活值';
COMMENT ON COLUMN finance_payable.supplier_name_snapshot IS '供应商名称快照，只服务展示与导出';
COMMENT ON COLUMN finance_payable.entry_type IS 'NORMAL 正常 / RED 红字；方向编码在类型里，金额恒为正';
COMMENT ON COLUMN finance_payable.original_payable_id IS '红字必填，指向被冲的原应付；正常应付必须为空';
COMMENT ON COLUMN finance_payable.amount IS '单头金额＝明细之和，恒 > 0；含合法容差内超收（Q11）';
COMMENT ON COLUMN finance_payable.event_at IS '业务事件时点＝purchase_receipt.confirmed_at；DIRECT 与 WAREHOUSE_CONFIRM 同口径，putaway 不决定应付时点（Q9）';
COMMENT ON COLUMN finance_payable.reason IS '红字原因，红字必填非空（Q13）';
COMMENT ON COLUMN finance_payable.version IS '乐观锁版本';
COMMENT ON COLUMN finance_payable.deleted IS '恒为 FALSE（append-only）';
COMMENT ON COLUMN finance_payable.created_at IS '创建时间';
COMMENT ON COLUMN finance_payable.updated_at IS '最后修改时间';
COMMENT ON COLUMN finance_payable.created_by IS '创建人';
COMMENT ON COLUMN finance_payable.updated_by IS '最后修改人';

COMMENT ON TABLE finance_payable_item IS '应付明细：一条收货行一行；手工红字明细来源为 MANUAL 且无来源行';
COMMENT ON COLUMN finance_payable_item.id IS '主键';
COMMENT ON COLUMN finance_payable_item.payable_id IS '所属应付单头';
COMMENT ON COLUMN finance_payable_item.source_type IS 'PURCHASE_RECEIPT_ITEM 正常明细来源 / MANUAL 手工红字明细';
COMMENT ON COLUMN finance_payable_item.source_id IS '正常＝purchase_receipt_item.id；MANUAL 时必须为 NULL';
COMMENT ON COLUMN finance_payable_item.purchase_order_item_id IS '采购订单行ID，回溯结算单价来源（Q10）';
COMMENT ON COLUMN finance_payable_item.sku_id IS '商品SKU ID';
COMMENT ON COLUMN finance_payable_item.sku_name_snapshot IS '商品名称快照';
COMMENT ON COLUMN finance_payable_item.unit_snapshot IS '采购单位名称快照；不做单位换算，也不跨单位求和';
COMMENT ON COLUMN finance_payable_item.quantity IS '＝收货有效量（标品申报量 / 非标 actual_weight），含合法容差内超收；恒 > 0';
COMMENT ON COLUMN finance_payable_item.unit_price IS '＝purchase_order_item.purchase_price，语义为「采购结算单价」，不含税务含义（Q14）';
COMMENT ON COLUMN finance_payable_item.amount IS 'ROUND(quantity × unit_price, 4)';
COMMENT ON COLUMN finance_payable_item.version IS '乐观锁版本';
COMMENT ON COLUMN finance_payable_item.deleted IS '恒为 FALSE（append-only）';
COMMENT ON COLUMN finance_payable_item.created_at IS '创建时间';
COMMENT ON COLUMN finance_payable_item.updated_at IS '最后修改时间';
COMMENT ON COLUMN finance_payable_item.created_by IS '创建人';
COMMENT ON COLUMN finance_payable_item.updated_by IS '最后修改人';

COMMENT ON TABLE finance_receipt IS '收款：一笔钱一单，可无对应应收（预收）；纠错只能新增 REVERSE 行';
COMMENT ON COLUMN finance_receipt.id IS '主键';
COMMENT ON COLUMN finance_receipt.receipt_no IS '收款单号，RC + 业务日(Asia/Shanghai) + 全局非重置序号';
COMMENT ON COLUMN finance_receipt.customer_id IS '收款对象恒为客户（预收也来自客户，Q16）；范围按 customer.seller_id 收窄（D-5）';
COMMENT ON COLUMN finance_receipt.customer_name_snapshot IS '客户名称快照';
COMMENT ON COLUMN finance_receipt.amount IS '一笔钱一单，恒 > 0；反向行金额同样为正，方向由 entry_type 表达';
COMMENT ON COLUMN finance_receipt.method IS 'CASH 现金 / BANK_TRANSFER 银行转账 / OTHER 其它；固定三值，本期不含任何在线支付或余额方式（Q21）';
COMMENT ON COLUMN finance_receipt.received_at IS '收款时点，登记人填写';
COMMENT ON COLUMN finance_receipt.entry_type IS 'NORMAL 正常登记 / REVERSE 反向纠错（D-3）';
COMMENT ON COLUMN finance_receipt.reverse_of_id IS '反向行必填，指向被冲的 NORMAL 收款；正常行必须为空。一条 NORMAL 最多一条 REVERSE';
COMMENT ON COLUMN finance_receipt.reason IS '反向原因，反向行必填非空';
COMMENT ON COLUMN finance_receipt.external_reference IS '资金凭据号，只是文本（Q25 不启用附件）；**不唯一**，也不作幂等键';
COMMENT ON COLUMN finance_receipt.remark IS '备注';
COMMENT ON COLUMN finance_receipt.version IS '乐观锁版本';
COMMENT ON COLUMN finance_receipt.deleted IS '恒为 FALSE（append-only）；纠错走 REVERSE 行，不走软删';
COMMENT ON COLUMN finance_receipt.created_at IS '创建时间';
COMMENT ON COLUMN finance_receipt.updated_at IS '最后修改时间';
COMMENT ON COLUMN finance_receipt.created_by IS '创建人';
COMMENT ON COLUMN finance_receipt.updated_by IS '最后修改人';

COMMENT ON TABLE finance_payment IS '付款：一笔钱一单，可无对应应付（预付）；退款付款带 ORDER_REFUND 来源';
COMMENT ON COLUMN finance_payment.id IS '主键';
COMMENT ON COLUMN finance_payment.payment_no IS '付款单号，PM + 业务日(Asia/Shanghai) + 全局非重置序号';
COMMENT ON COLUMN finance_payment.counterparty_type IS 'SUPPLIER 付给供应商（应付/预付）/ CUSTOMER 付给客户（退款）';
COMMENT ON COLUMN finance_payment.counterparty_id IS '对方主键；SUPPLIER 侧本期不收窄范围，CUSTOMER 侧按 customer.seller_id 收窄（D-5）';
COMMENT ON COLUMN finance_payment.counterparty_name_snapshot IS '对方名称快照';
COMMENT ON COLUMN finance_payment.amount IS '恒 > 0；退款付款必须等于 order_refund.refund_amount（Q19）；反向行金额同样为正';
COMMENT ON COLUMN finance_payment.method IS 'CASH / BANK_TRANSFER / OTHER，与收款共用同一套三值枚举（Q21）';
COMMENT ON COLUMN finance_payment.paid_at IS '付款时点，登记人填写';
COMMENT ON COLUMN finance_payment.entry_type IS 'NORMAL 正常登记 / REVERSE 反向纠错（D-3）';
COMMENT ON COLUMN finance_payment.reverse_of_id IS '反向行必填，指向被冲的 NORMAL 付款；正常行必须为空。一条 NORMAL 最多一条 REVERSE';
COMMENT ON COLUMN finance_payment.reason IS '反向原因，反向行必填非空';
COMMENT ON COLUMN finance_payment.external_reference IS '资金凭据号，只是文本；**不唯一**，也不作幂等键';
COMMENT ON COLUMN finance_payment.source_type IS 'ORDER_REFUND 退款付款来源；反向行必须为 NULL';
COMMENT ON COLUMN finance_payment.source_id IS 'order_refund.id；反向行必须为 NULL，否则会与原始行抢同一来源唯一键';
COMMENT ON COLUMN finance_payment.remark IS '备注';
COMMENT ON COLUMN finance_payment.version IS '乐观锁版本';
COMMENT ON COLUMN finance_payment.deleted IS '恒为 FALSE（append-only）';
COMMENT ON COLUMN finance_payment.created_at IS '创建时间';
COMMENT ON COLUMN finance_payment.updated_at IS '最后修改时间';
COMMENT ON COLUMN finance_payment.created_by IS '创建人';
COMMENT ON COLUMN finance_payment.updated_by IS '最后修改人';

COMMENT ON TABLE finance_write_off IS '核销关系行：一笔收/付款对一笔应收/应付的一次分配（M:N）；撤销＝新增 REVERSE 行';
COMMENT ON COLUMN finance_write_off.id IS '主键';
COMMENT ON COLUMN finance_write_off.write_off_no IS '核销单号，WO + 业务日(Asia/Shanghai) + 全局非重置序号';
COMMENT ON COLUMN finance_write_off.source_type IS 'RECEIPT 收款 / PAYMENT 付款，钱从哪来';
COMMENT ON COLUMN finance_write_off.source_id IS 'finance_receipt.id 或 finance_payment.id';
COMMENT ON COLUMN finance_write_off.target_type IS 'RECEIVABLE 应收 / PAYABLE 应付，抵到哪去；数据范围随本列（D-5）';
COMMENT ON COLUMN finance_write_off.target_id IS 'finance_receivable.id 或 finance_payable.id';
COMMENT ON COLUMN finance_write_off.amount IS '本次核销金额，恒 > 0；已核销额由 NORMAL − REVERSE 读时派生，不落库（Q17）';
COMMENT ON COLUMN finance_write_off.entry_type IS 'NORMAL 正常核销 / REVERSE 反向核销（Q18）';
COMMENT ON COLUMN finance_write_off.reverse_of_id IS '反向行必填，指向被冲的 NORMAL 核销；正常行必须为空。一条 NORMAL 最多一条 REVERSE';
COMMENT ON COLUMN finance_write_off.reason IS '撤销原因，反向行必填非空（Q18）';
COMMENT ON COLUMN finance_write_off.written_off_at IS '核销时点；R0 接轨的「本期核销额」按本列取窗（设计稿 §27.2）';
COMMENT ON COLUMN finance_write_off.operator IS '操作人（loginId 形态，与审计列同口径）';
COMMENT ON COLUMN finance_write_off.version IS '乐观锁版本';
COMMENT ON COLUMN finance_write_off.deleted IS '恒为 FALSE（append-only）';
COMMENT ON COLUMN finance_write_off.created_at IS '创建时间';
COMMENT ON COLUMN finance_write_off.updated_at IS '最后修改时间';
COMMENT ON COLUMN finance_write_off.created_by IS '创建人';
COMMENT ON COLUMN finance_write_off.updated_by IS '最后修改人';

COMMENT ON TABLE finance_operation_log IS '财务操作日志：一次财务写动作一行，必须与业务写同一事务；无删除与修改入口';
COMMENT ON COLUMN finance_operation_log.id IS '主键';
COMMENT ON COLUMN finance_operation_log.business_type IS 'RECEIVABLE / PAYABLE / RECEIPT / PAYMENT / WRITE_OFF';
COMMENT ON COLUMN finance_operation_log.business_id IS '对应财务事实主键';
COMMENT ON COLUMN finance_operation_log.operation_type IS 'GENERATE 生成 / RED_GENERATE 红字生成 / RECEIVE 收款 / PAY 付款 / WRITE_OFF 核销 / WRITE_OFF_REVERSE 反向核销 / RECEIPT_REVERSE 反向收款 / PAYMENT_REVERSE 反向付款';
COMMENT ON COLUMN finance_operation_log.operator IS '操作人（loginId 形态）';
COMMENT ON COLUMN finance_operation_log.reason IS '原因；破坏性动作必填，由服务层与对应表的 CHECK 共同保证';
COMMENT ON COLUMN finance_operation_log.before_data IS '改前快照（JSONB object）；生成类动作为 NULL，核销与反向类为目标的派生余额快照';
COMMENT ON COLUMN finance_operation_log.after_data IS '改后快照（JSONB object）；生成类为单头快照，核销与反向类为写入后的派生余额快照';
COMMENT ON COLUMN finance_operation_log.created_at IS '创建时间';
COMMENT ON COLUMN finance_operation_log.created_by IS '创建人';

-- ============================================================================
-- 单号唯一索引：deleted 恒为 FALSE，故部分谓词与全表唯一等价；保留谓词只为与
-- 本仓库既有部分索引形态一致。单号不复用。
-- ============================================================================
CREATE UNIQUE INDEX uk_finance_receivable_no ON finance_receivable (receivable_no) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_finance_payable_no ON finance_payable (payable_no) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_finance_receipt_no ON finance_receipt (receipt_no) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_finance_payment_no ON finance_payment (payment_no) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_finance_write_off_no ON finance_write_off (write_off_no) WHERE deleted = FALSE;

-- ============================================================================
-- 来源唯一索引：一个业务事实最多产生一条财务事实（Q26「来源唯一索引是最终数据库防线」）。
-- 生成器一律走 insertOnConflictDoNothing，命中冲突即「已生成」，返回成功而不是报错。
--
-- 谓词差异是有意的：应收 / 应收明细的来源恒非空，只写 deleted = FALSE；
-- 应付 / 应付明细 / 付款存在 source_id 为 NULL 的行（手工红字、反向付款、无来源预付），
-- 必须加 AND source_id IS NOT NULL —— 否则 NULL 不等于任何值，PostgreSQL 会**放行任意多条**，
-- 索引形同不存在。ON CONFLICT 的目标必须逐字重复这里的谓词（Q11 同一条纪律）。
-- ============================================================================
CREATE UNIQUE INDEX uk_finance_receivable_source_active
    ON finance_receivable (source_type, source_id) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_finance_receivable_item_source_active
    ON finance_receivable_item (source_type, source_id) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_finance_payable_source_active
    ON finance_payable (source_type, source_id) WHERE deleted = FALSE AND source_id IS NOT NULL;
CREATE UNIQUE INDEX uk_finance_payable_item_source_active
    ON finance_payable_item (source_type, source_id) WHERE deleted = FALSE AND source_id IS NOT NULL;
CREATE UNIQUE INDEX uk_finance_payment_source_active
    ON finance_payment (source_type, source_id) WHERE deleted = FALSE AND source_id IS NOT NULL;

-- ============================================================================
-- 反向唯一索引：一条 NORMAL 事实最多被反向一次（Q18 核销 / D-3 收付款）。
-- 重复撤销在库级失败，而不是靠服务层先查后判。
-- ============================================================================
CREATE UNIQUE INDEX uk_finance_write_off_single_reverse
    ON finance_write_off (reverse_of_id) WHERE deleted = FALSE AND entry_type = 'REVERSE';
CREATE UNIQUE INDEX uk_finance_receipt_single_reverse
    ON finance_receipt (reverse_of_id) WHERE deleted = FALSE AND entry_type = 'REVERSE';
CREATE UNIQUE INDEX uk_finance_payment_single_reverse
    ON finance_payment (reverse_of_id) WHERE deleted = FALSE AND entry_type = 'REVERSE';

-- ============================================================================
-- 查询索引：范围谓词、事件时点排序与红字引用。
-- ============================================================================
CREATE INDEX idx_finance_receivable_order ON finance_receivable (order_id) WHERE deleted = FALSE;
CREATE INDEX idx_finance_receivable_customer_event
    ON finance_receivable (customer_id, event_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_finance_receivable_original
    ON finance_receivable (original_receivable_id) WHERE deleted = FALSE AND entry_type = 'RED';
-- 数据范围谓词落在 join 出的 sales_order.seller_id 上（Q23），本表按 order_id 关联。

CREATE INDEX idx_finance_receivable_item_receivable
    ON finance_receivable_item (receivable_id) WHERE deleted = FALSE;
CREATE INDEX idx_finance_receivable_item_order_item
    ON finance_receivable_item (order_item_id) WHERE deleted = FALSE;

CREATE INDEX idx_finance_payable_supplier_event
    ON finance_payable (supplier_id, event_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_finance_payable_order
    ON finance_payable (purchase_order_id) WHERE deleted = FALSE;
CREATE INDEX idx_finance_payable_original
    ON finance_payable (original_payable_id) WHERE deleted = FALSE AND entry_type = 'RED';

CREATE INDEX idx_finance_payable_item_payable
    ON finance_payable_item (payable_id) WHERE deleted = FALSE;
CREATE INDEX idx_finance_payable_item_purchase_order_item
    ON finance_payable_item (purchase_order_item_id) WHERE deleted = FALSE;

CREATE INDEX idx_finance_receipt_customer_received
    ON finance_receipt (customer_id, received_at DESC) WHERE deleted = FALSE;
-- external_reference 只是资金凭据文本，**刻意不建唯一索引**：全系统唯一从未被裁决，
-- 而银行流水号跨客户重复是真实存在的。防重复由 Idempotency-Key 与来源唯一索引承担。
CREATE INDEX idx_finance_receipt_external_ref
    ON finance_receipt (external_reference) WHERE deleted = FALSE AND external_reference IS NOT NULL;

CREATE INDEX idx_finance_payment_counterparty_paid
    ON finance_payment (counterparty_type, counterparty_id, paid_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_finance_payment_external_ref
    ON finance_payment (external_reference) WHERE deleted = FALSE AND external_reference IS NOT NULL;

CREATE INDEX idx_finance_write_off_target
    ON finance_write_off (target_type, target_id) WHERE deleted = FALSE;
CREATE INDEX idx_finance_write_off_source
    ON finance_write_off (source_type, source_id) WHERE deleted = FALSE;
CREATE INDEX idx_finance_write_off_written_off_at
    ON finance_write_off (written_off_at) WHERE deleted = FALSE;

CREATE INDEX idx_finance_operation_log_business
    ON finance_operation_log (business_type, business_id);
