-- W1 approved Product aggregate. Immutable after first successful Flyway application.

CREATE TABLE product_category (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id     BIGINT,
    category_code VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    level         SMALLINT     NOT NULL,
    sort_order    INTEGER      NOT NULL DEFAULT 0,
    status        VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    version       INTEGER      NOT NULL DEFAULT 0,
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(64),
    updated_by    VARCHAR(64),
    CONSTRAINT ck_product_category_level  CHECK (level BETWEEN 1 AND 3),
    CONSTRAINT ck_product_category_status CHECK (status IN ('ENABLED','DISABLED')),
    CONSTRAINT ck_product_category_parent CHECK (
        (level = 1 AND parent_id IS NULL) OR (level > 1 AND parent_id IS NOT NULL)),
    CONSTRAINT ck_product_category_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_product_category_code_active
    ON product_category (category_code) WHERE deleted = FALSE;
CREATE INDEX idx_product_category_parent_id ON product_category (parent_id);

CREATE TABLE product_spu (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spu_code    VARCHAR(64)  NOT NULL,
    name        VARCHAR(150) NOT NULL,
    alias       VARCHAR(150),
    category_id BIGINT       NOT NULL,
    description VARCHAR(1000),
    status      VARCHAR(20)  NOT NULL DEFAULT 'OFF_SHELF',
    version     INTEGER      NOT NULL DEFAULT 0,
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  VARCHAR(64),
    updated_by  VARCHAR(64),
    CONSTRAINT ck_product_spu_status  CHECK (status IN ('ON_SHELF','OFF_SHELF')),
    CONSTRAINT ck_product_spu_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_product_spu_code_active ON product_spu (spu_code) WHERE deleted = FALSE;
CREATE INDEX idx_product_spu_category_id ON product_spu (category_id);
CREATE INDEX idx_product_spu_name        ON product_spu (name);
CREATE INDEX idx_product_spu_status      ON product_spu (status);

CREATE TABLE product_sku (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spu_id       BIGINT        NOT NULL,
    sku_code     VARCHAR(64)   NOT NULL,
    barcode      VARCHAR(64),
    spec_name    VARCHAR(150)  NOT NULL,
    spec_values  JSONB         NOT NULL DEFAULT '{}'::JSONB,
    sale_unit    VARCHAR(32)   NOT NULL,
    product_type VARCHAR(20)   NOT NULL,
    market_price NUMERIC(18,4) NOT NULL,
    status       VARCHAR(20)   NOT NULL DEFAULT 'OFF_SHELF',
    is_default   BOOLEAN       NOT NULL DEFAULT FALSE,
    sort_order   INTEGER       NOT NULL DEFAULT 0,
    version      INTEGER       NOT NULL DEFAULT 0,
    deleted      BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by   VARCHAR(64),
    updated_by   VARCHAR(64),
    CONSTRAINT ck_product_sku_spec_values  CHECK (jsonb_typeof(spec_values) = 'object'),
    CONSTRAINT ck_product_sku_type         CHECK (product_type IN ('STANDARD','NON_STANDARD')),
    CONSTRAINT ck_product_sku_market_price CHECK (market_price >= 0),
    CONSTRAINT ck_product_sku_status       CHECK (status IN ('ON_SHELF','OFF_SHELF')),
    CONSTRAINT ck_product_sku_version      CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_product_sku_code_active    ON product_sku (sku_code) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_product_sku_barcode_active ON product_sku (barcode)
    WHERE deleted = FALSE AND barcode IS NOT NULL;
CREATE UNIQUE INDEX uk_product_sku_default_active ON product_sku (spu_id)
    WHERE deleted = FALSE AND is_default = TRUE;   -- P2/P3 的 DB 级兜底
CREATE INDEX idx_product_sku_spu_id ON product_sku (spu_id);
CREATE INDEX idx_product_sku_status ON product_sku (status);

CREATE TABLE product_image (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spu_id     BIGINT       NOT NULL,
    file_key   VARCHAR(255) NOT NULL,
    file_url   VARCHAR(500) NOT NULL,
    file_name  VARCHAR(255),
    file_size  BIGINT,
    is_primary BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order INTEGER      NOT NULL DEFAULT 0,
    version    INTEGER      NOT NULL DEFAULT 0,
    deleted    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_product_image_version CHECK (version >= 0)
);
CREATE INDEX idx_product_image_spu_id ON product_image (spu_id);
CREATE UNIQUE INDEX uk_product_image_primary_active ON product_image (spu_id)
    WHERE deleted = FALSE AND is_primary = TRUE;   -- 每个 SPU 至多一张主图

INSERT INTO product_category(category_code,name,level) VALUES ('FRESH','生鲜',1);
INSERT INTO product_category(parent_id,category_code,name,level)
SELECT id,'FRESH-PRODUCE','果蔬',2 FROM product_category WHERE category_code='FRESH';
INSERT INTO product_category(parent_id,category_code,name,level)
SELECT id,'FRESH-FRUIT','水果',3 FROM product_category WHERE category_code='FRESH-PRODUCE';
