-- 每日清单为生成时的采购事实快照，不回写采购单，不随后续业务操作刷新。
CREATE TABLE report_purchase_daily (
    report_date DATE PRIMARY KEY,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE report_purchase_daily IS '采购商品每日清单；同日只生成一次，无采购也保留生成记录';
COMMENT ON COLUMN report_purchase_daily.report_date IS 'Asia/Shanghai 提交日期';

CREATE TABLE report_purchase_daily_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_date DATE NOT NULL,
    warehouse_id BIGINT NOT NULL,
    purchaser_id BIGINT,
    sku_id BIGINT NOT NULL,
    spu_code VARCHAR(64) NOT NULL,
    product_name VARCHAR(200) NOT NULL,
    sku_code VARCHAR(64) NOT NULL,
    sku_name VARCHAR(200) NOT NULL,
    purchase_unit VARCHAR(32) NOT NULL,
    order_count BIGINT NOT NULL CHECK (order_count > 0),
    planned_quantity NUMERIC(24, 4) NOT NULL CHECK (planned_quantity >= 0),
    order_amount NUMERIC(24, 4) NOT NULL CHECK (order_amount >= 0)
);
CREATE INDEX idx_report_purchase_daily_item_scope
    ON report_purchase_daily_item (report_date, warehouse_id, purchaser_id, sku_id);
COMMENT ON TABLE report_purchase_daily_item IS '采购商品清单分组快照；查询先按仓库与采购员交集过滤，再合并 SKU 与单位';

CREATE INDEX idx_purchase_order_daily_submitted
    ON purchase_order (submitted_at) WHERE deleted = FALSE AND submitted_at IS NOT NULL;

INSERT INTO t_smart_job (job_name, job_class, trigger_type, trigger_value, enabled_flag, param, sort, remark,
                         deleted_flag, update_name, create_time, update_time)
SELECT '采购商品每日清单', 'com.xsy.scm.report.job.PurchaseDailyReportJob', 'cron', '0 0 3 * * ?',
       TRUE, '', 91,
       '默认每天03:00，可修改Cron时间。空参数生成昨日有效采购清单；手动执行可传yyyy-MM-dd补生成，已生成不覆盖。',
       FALSE, 'system', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM t_smart_job
                  WHERE job_class = 'com.xsy.scm.report.job.PurchaseDailyReportJob' AND deleted_flag = FALSE);
