CREATE TABLE purchase_demand_calculation_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    warehouse_id BIGINT NOT NULL,
    supplier_id BIGINT,
    purchaser_id BIGINT,
    category_id BIGINT,
    keyword VARCHAR(64),
    status VARCHAR(16) NOT NULL DEFAULT 'READY',
    source_line_count INTEGER NOT NULL DEFAULT 0,
    candidate_line_count INTEGER NOT NULL DEFAULT 0,
    generated_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    summary_snapshot JSONB NOT NULL,
    result_snapshot JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64) NOT NULL,
    generated_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(64),
    CONSTRAINT ck_purchase_demand_batch_window CHECK (start_at < end_at),
    CONSTRAINT ck_purchase_demand_batch_status CHECK (status IN ('READY','GENERATED')),
    CONSTRAINT ck_purchase_demand_batch_counts CHECK (source_line_count >= 0 AND candidate_line_count >= 0
        AND generated_count >= 0 AND skipped_count >= 0),
    CONSTRAINT ck_purchase_demand_batch_summary CHECK (jsonb_typeof(summary_snapshot)='object'),
    CONSTRAINT ck_purchase_demand_batch_result CHECK (result_snapshot IS NULL OR jsonb_typeof(result_snapshot)='object')
);
CREATE INDEX idx_purchase_demand_batch_window ON purchase_demand_calculation_batch (created_at DESC, id DESC);

CREATE TABLE purchase_demand_calculation_batch_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    line_no INTEGER NOT NULL,
    sales_order_id BIGINT NOT NULL,
    sales_order_item_id BIGINT NOT NULL,
    sales_order_no_snapshot VARCHAR(64) NOT NULL,
    source_confirmed_at TIMESTAMPTZ NOT NULL,
    spu_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    spu_code_snapshot VARCHAR(64) NOT NULL,
    product_name_snapshot VARCHAR(150) NOT NULL,
    sku_code_snapshot VARCHAR(64) NOT NULL,
    sku_name_snapshot VARCHAR(150) NOT NULL,
    spec_values_snapshot JSONB NOT NULL DEFAULT '{}'::JSONB,
    demand_unit_snapshot VARCHAR(32) NOT NULL,
    product_type_snapshot VARCHAR(20) NOT NULL,
    source_quantity NUMERIC(18,4) NOT NULL,
    required_quantity NUMERIC(18,4) NOT NULL,
    existing_demand_id BIGINT,
    CONSTRAINT ck_purchase_demand_batch_item_line CHECK (line_no > 0),
    CONSTRAINT ck_purchase_demand_batch_item_quantities CHECK (source_quantity > 0 AND required_quantity >= 0
        AND required_quantity <= source_quantity),
    CONSTRAINT ck_purchase_demand_batch_item_snapshot CHECK (jsonb_typeof(spec_values_snapshot)='object'),
    CONSTRAINT ck_purchase_demand_batch_item_product_type CHECK (product_type_snapshot IN ('STANDARD','NON_STANDARD')),
    CONSTRAINT uk_purchase_demand_batch_item_line UNIQUE (batch_id,line_no),
    CONSTRAINT uk_purchase_demand_batch_item_source UNIQUE (batch_id,sales_order_item_id)
);
CREATE INDEX idx_purchase_demand_batch_item_batch ON purchase_demand_calculation_batch_item (batch_id,line_no);

ALTER TABLE purchase_demand ADD COLUMN calculation_batch_id BIGINT;
ALTER TABLE purchase_demand ADD COLUMN calculation_batch_item_id BIGINT;
ALTER TABLE purchase_demand ADD CONSTRAINT ck_purchase_demand_batch_link CHECK
    ((calculation_batch_id IS NULL AND calculation_batch_item_id IS NULL)
     OR (calculation_batch_id IS NOT NULL AND calculation_batch_item_id IS NOT NULL));
CREATE UNIQUE INDEX uk_purchase_demand_calculation_item_active
    ON purchase_demand(calculation_batch_item_id) WHERE deleted=FALSE AND calculation_batch_item_id IS NOT NULL;

CREATE FUNCTION reject_purchase_demand_batch_item_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'purchase_demand_calculation_batch_item is an immutable snapshot';
END $$;
CREATE TRIGGER trg_purchase_demand_batch_item_immutable
    BEFORE UPDATE OR DELETE ON purchase_demand_calculation_batch_item
    FOR EACH ROW EXECUTE FUNCTION reject_purchase_demand_batch_item_mutation();
