-- Supplier statement versions are independent read-side snapshots of Finance facts.
CREATE TABLE scm_supplier_statement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    supplier_name VARCHAR(150) NOT NULL,
    warehouse_id BIGINT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    partial_scope BOOLEAN NOT NULL,
    generated_by_employee_id BIGINT NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL,
    opening_payable NUMERIC(22,4) NOT NULL,
    payable_increase NUMERIC(22,4) NOT NULL,
    payable_red NUMERIC(22,4) NOT NULL,
    write_off_net NUMERIC(22,4) NOT NULL,
    closing_payable NUMERIC(22,4) NOT NULL,
    opening_unallocated NUMERIC(22,4),
    payment_net NUMERIC(22,4) NOT NULL,
    closing_unallocated NUMERIC(22,4),
    CONSTRAINT ck_supplier_statement_period CHECK (start_date <= end_date)
);
CREATE INDEX idx_supplier_statement_history ON scm_supplier_statement
    (generated_by_employee_id, supplier_id, generated_at DESC);

CREATE TABLE scm_supplier_statement_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_id BIGINT NOT NULL REFERENCES scm_supplier_statement(id),
    line_no INTEGER NOT NULL,
    fact_type VARCHAR(24) NOT NULL,
    fact_id BIGINT NOT NULL,
    event_at TIMESTAMPTZ NOT NULL,
    document_no VARCHAR(64) NOT NULL,
    related_no VARCHAR(64),
    payable_delta NUMERIC(22,4) NOT NULL,
    payment_delta NUMERIC(22,4) NOT NULL,
    write_off_delta NUMERIC(22,4) NOT NULL,
    payable_balance NUMERIC(22,4) NOT NULL,
    CONSTRAINT uk_supplier_statement_line UNIQUE (statement_id, line_no),
    CONSTRAINT uk_supplier_statement_fact UNIQUE (statement_id, fact_type, fact_id)
);
CREATE TABLE scm_supplier_statement_source (
    statement_id BIGINT NOT NULL REFERENCES scm_supplier_statement(id),
    fact_type VARCHAR(24) NOT NULL,
    fact_id BIGINT NOT NULL,
    PRIMARY KEY (statement_id, fact_type, fact_id)
);

INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type,
                   api_perms, web_perms, icon, context_menu_id, visible_flag, create_user_id)
VALUES (1226, '供应商对账单', 2, 1200, 1226, '/report/report-supplier-statement',
        '/business/scm/report/report-supplier-statement.vue', NULL, NULL, NULL, 'FileTextOutlined', NULL, TRUE, 1),
       (1227, '供应商对账查询', 3, 1226, 1227, NULL, NULL, 1,
        'scm:report:supplier:statement:query', 'scm:report:supplier:statement:query', NULL, 1226, TRUE, 1),
       (1228, '供应商对账冻结', 3, 1226, 1228, NULL, NULL, 1,
        'scm:report:supplier:statement:freeze', 'scm:report:supplier:statement:freeze', NULL, 1226, TRUE, 1)
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO t_role_menu(role_id, menu_id)
SELECT r.role_id, m.menu_id FROM t_role r
CROSS JOIN LATERAL unnest(ARRAY[1226::bigint,1227::bigint,1228::bigint,1216::bigint]) AS m(menu_id)
WHERE r.role_code IN ('SCM_FINANCE','SUPER_ADMIN')
  AND NOT EXISTS (SELECT 1 FROM t_role_menu rm WHERE rm.role_id=r.role_id AND rm.menu_id=m.menu_id);
SELECT setval(pg_get_serial_sequence('t_menu','menu_id'), (SELECT MAX(menu_id)+1 FROM t_menu), FALSE);
