-- ADM-07 打印模板中心：受控模板配置 + 正式打印冻结。
--
-- 边界（ADR-007）：
--   * 模板是**受控 JSON 模型**（标题 / 纸张 / 方向 / 表头字段 / 列 / 合计 / 页脚备注），
--     不是任意 HTML 或脚本；可选字段由服务端按单据类型的白名单裁剪，模板存不进白名单外的键。
--   * 正式打印冻结模板版本、模型快照、业务数据快照、操作人和时间；历史重印只读快照，
--     不回表重算 —— 否则「当初打出来的那张」会随业务数据变化而变成另一张。
--   * 预览不写 scm_print_record（预览不计次、不留痕）。
--
-- 金额不是「模板里选了就有」：渲染时按调用者的金额权限二次剔除，模板本身不携带授权信息。

CREATE TABLE scm_print_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR(32) NOT NULL,
    template_code VARCHAR(64) NOT NULL,
    template_name VARCHAR(100) NOT NULL,
    default_flag BOOLEAN NOT NULL DEFAULT FALSE,
    enabled_flag BOOLEAN NOT NULL DEFAULT TRUE,
    model JSONB NOT NULL,
    remark VARCHAR(200),
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_scm_print_template_document_type CHECK (document_type IN ('PURCHASE_ORDER')),
    CONSTRAINT ck_scm_print_template_code CHECK (btrim(template_code) <> ''),
    CONSTRAINT ck_scm_print_template_name CHECK (btrim(template_name) <> ''),
    CONSTRAINT ck_scm_print_template_model CHECK (jsonb_typeof(model) = 'object')
);
-- 同类型下模板编码唯一（软删的不占位：删掉后可以用同一个编码重建）
CREATE UNIQUE INDEX uk_scm_print_template_code
    ON scm_print_template (document_type, template_code) WHERE deleted = FALSE;
-- 每种单据**至多一个**默认模板：多个默认等于没有默认（渲染时无法确定选谁）
CREATE UNIQUE INDEX uk_scm_print_template_default
    ON scm_print_template (document_type) WHERE deleted = FALSE AND default_flag = TRUE;
CREATE INDEX idx_scm_print_template_type ON scm_print_template (document_type, enabled_flag, deleted);

CREATE TABLE scm_print_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR(32) NOT NULL,
    business_id BIGINT NOT NULL,
    business_no VARCHAR(64),
    template_id BIGINT NOT NULL,
    template_code VARCHAR(64) NOT NULL,
    template_name VARCHAR(100) NOT NULL,
    template_version INTEGER NOT NULL,
    model_snapshot JSONB NOT NULL,
    data_snapshot JSONB NOT NULL,
    printed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    printed_by VARCHAR(64) NOT NULL,
    CONSTRAINT ck_scm_print_record_document_type CHECK (document_type IN ('PURCHASE_ORDER')),
    CONSTRAINT ck_scm_print_record_model CHECK (jsonb_typeof(model_snapshot) = 'object'),
    CONSTRAINT ck_scm_print_record_data CHECK (jsonb_typeof(data_snapshot) = 'object')
);
CREATE INDEX idx_scm_print_record_business
    ON scm_print_record (document_type, business_id, printed_at DESC, id DESC);

-- 冻结快照不可变：重印必须与当初那张逐字一致，能改就等于没冻结。
-- 与 purchase_demand_calculation_batch_item 用同一套做法（触发器拒绝 UPDATE / DELETE）。
CREATE FUNCTION reject_scm_print_record_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'scm_print_record is an immutable snapshot';
END $$;
CREATE TRIGGER trg_scm_print_record_immutable
    BEFORE UPDATE OR DELETE ON scm_print_record
    FOR EACH ROW EXECUTE FUNCTION reject_scm_print_record_mutation();

-- menu_id 已核对：1600-1699 空闲（1500 段属财务管理，16xx 未被占用）。
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type,
                   api_perms, web_perms, icon, context_menu_id, visible_flag, create_user_id)
VALUES (1600, '打印中心', 1, 0, 1600, '/print', NULL, NULL, NULL, NULL, 'PrinterOutlined', NULL, TRUE, 1),
       (1601, '打印模板', 2, 1600, 1601, '/print/print-template-list',
        '/business/scm/print/print-template-list.vue', NULL, NULL, NULL, NULL, NULL, TRUE, 1),
       (1602, '模板查询', 3, 1601, 1602, NULL, NULL, 1,
        'scm:print:template:query', 'scm:print:template:query', NULL, NULL, TRUE, 1),
       (1603, '模板新建', 3, 1601, 1603, NULL, NULL, 1,
        'scm:print:template:add', 'scm:print:template:add', NULL, NULL, TRUE, 1),
       (1604, '模板编辑', 3, 1601, 1604, NULL, NULL, 1,
        'scm:print:template:update', 'scm:print:template:update', NULL, NULL, TRUE, 1),
       (1605, '模板删除', 3, 1601, 1605, NULL, NULL, 1,
        'scm:print:template:delete', 'scm:print:template:delete', NULL, NULL, TRUE, 1),
       (1606, '打印记录', 2, 1600, 1606, '/print/print-record-list',
        '/business/scm/print/print-record-list.vue', NULL, NULL, NULL, NULL, NULL, TRUE, 1),
       (1607, '记录查询', 3, 1606, 1607, NULL, NULL, 1,
        'scm:print:record:query', 'scm:print:record:query', NULL, NULL, TRUE, 1)
ON CONFLICT (menu_id) DO NOTHING;

-- 模板维护与打印记录查看授予超管与仓库主管；采购单打印本身不在这里授权 ——
-- 打印一张采购单要求的是采购单的查看权（scm:purchase:query），
-- 否则「模板维护权」会变成一条读到业务单据的旁路。
INSERT INTO t_role_menu(role_id, menu_id)
SELECT r.role_id, m.menu_id FROM t_role r
CROSS JOIN LATERAL unnest(ARRAY[1600::bigint,1601::bigint,1602::bigint,1603::bigint,1604::bigint,1605::bigint,
                                1606::bigint,1607::bigint]) AS m(menu_id)
WHERE r.role_code IN ('SUPER_ADMIN','SCM_STOREKEEPER_LEAD')
  AND NOT EXISTS (SELECT 1 FROM t_role_menu rm WHERE rm.role_id=r.role_id AND rm.menu_id=m.menu_id);

-- 采购单内置默认模板。默认模型与接入前的固定版式一致，因此接入模板不会改变既有打印效果。
INSERT INTO scm_print_template (document_type, template_code, template_name, default_flag, enabled_flag, model,
                                remark, version, deleted, created_at, updated_at, created_by, updated_by)
VALUES ('PURCHASE_ORDER', 'PURCHASE_ORDER_DEFAULT', '采购单默认模板', TRUE, TRUE,
        '{"title":"采购单","paper":"A4","orientation":"PORTRAIT","headerFields":["supplierName","warehouseName","purchaserName","plannedArrivalDate"],"columns":["productName","skuCode","skuName","purchaseUnit","plannedQuantity","receivedQuantity","remainingQuantity","purchasePrice","lineAmount"],"showTotals":true,"footerNote":"白联：财务　红联：供应商　黄联：仓库"}'::JSONB,
        '内置默认模板；与接入前的固定版式一致', 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system')
ON CONFLICT DO NOTHING;

SELECT setval(pg_get_serial_sequence('t_menu','menu_id'), (SELECT MAX(menu_id)+1 FROM t_menu), FALSE);
