-- ADM-10 配送增强：辅助排线建议 + GPS 轨迹事件。
--
-- 边界（ADR-008）：
--   * 排线只生成**可解释建议**，冻结输入停靠点、约束、provider 版本与距离结果；
--     操作者比较后显式确认才写回停靠顺序。建议不自动发车，也不覆盖已发车的线路。
--   * 距离来自可替换 provider；估算实现必须**自报**为估算，不得宣称为真实路网或生产优化结果。
--   * GPS 事件带稳定幂等键，设备采集时间与服务端接收时间**分列**；轨迹只作配送证据，
--     不改变订单级签收，也不触发库存或财务事实。

CREATE TABLE delivery_plan_proposal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL REFERENCES delivery_route (id),
    status VARCHAR(16) NOT NULL,
    provider_code VARCHAR(64) NOT NULL,
    provider_version VARCHAR(32) NOT NULL,
    estimated_flag BOOLEAN NOT NULL,
    rule_code VARCHAR(64) NOT NULL,
    stop_count INTEGER NOT NULL,
    total_distance NUMERIC(18,4) NOT NULL,
    input_snapshot JSONB NOT NULL,
    result_snapshot JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64) NOT NULL,
    applied_at TIMESTAMPTZ,
    applied_by VARCHAR(64),
    discarded_at TIMESTAMPTZ,
    discarded_by VARCHAR(64),
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT ck_delivery_plan_proposal_status CHECK (status IN ('PROPOSED', 'APPLIED', 'DISCARDED')),
    CONSTRAINT ck_delivery_plan_proposal_counts CHECK (stop_count > 0 AND total_distance >= 0),
    CONSTRAINT ck_delivery_plan_proposal_input CHECK (jsonb_typeof(input_snapshot) = 'object'),
    CONSTRAINT ck_delivery_plan_proposal_result CHECK (jsonb_typeof(result_snapshot) = 'object'),
    -- 终态必须留下「谁在什么时候处理的」：一条被应用或被放弃的建议不能只有状态
    CONSTRAINT ck_delivery_plan_proposal_applied CHECK (
        (status <> 'APPLIED') OR (applied_at IS NOT NULL AND applied_by IS NOT NULL)),
    CONSTRAINT ck_delivery_plan_proposal_discarded CHECK (
        (status <> 'DISCARDED') OR (discarded_at IS NOT NULL AND discarded_by IS NOT NULL))
);
-- 一条线路至多一个待确认建议：两个待确认建议会让「应用哪一个」变成猜。
-- 生成新建议时旧的待确认建议转为 DISCARDED，而不是并存。
CREATE UNIQUE INDEX uk_delivery_plan_proposal_active
    ON delivery_plan_proposal (route_id) WHERE status = 'PROPOSED';
CREATE INDEX idx_delivery_plan_proposal_route ON delivery_plan_proposal (route_id, created_at DESC, id DESC);

-- 冻结快照不可变：建议一旦生成，输入与结果都不能再改（状态与处理痕迹除外）。
-- 能改快照就等于「建议里看到的距离」和「应用时依据的距离」可以不是同一份。
CREATE FUNCTION reject_delivery_plan_proposal_snapshot_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.input_snapshot IS DISTINCT FROM OLD.input_snapshot
        OR NEW.result_snapshot IS DISTINCT FROM OLD.result_snapshot
        OR NEW.provider_code IS DISTINCT FROM OLD.provider_code
        OR NEW.provider_version IS DISTINCT FROM OLD.provider_version
        OR NEW.total_distance IS DISTINCT FROM OLD.total_distance THEN
        RAISE EXCEPTION 'delivery_plan_proposal snapshots are immutable';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_delivery_plan_proposal_snapshot_immutable
    BEFORE UPDATE ON delivery_plan_proposal
    FOR EACH ROW EXECUTE FUNCTION reject_delivery_plan_proposal_snapshot_change();

CREATE TABLE delivery_gps_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key VARCHAR(160) NOT NULL,
    route_id BIGINT NOT NULL REFERENCES delivery_route (id),
    driver_id BIGINT,
    device_code VARCHAR(64),
    captured_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    longitude NUMERIC(11, 8) NOT NULL,
    latitude NUMERIC(10, 8) NOT NULL,
    geom_crs VARCHAR(8) NOT NULL,
    accuracy_meters NUMERIC(10, 2),
    speed_kph NUMERIC(10, 2),
    reported_by VARCHAR(64) NOT NULL,
    CONSTRAINT uk_delivery_gps_event_key UNIQUE (event_key),
    CONSTRAINT ck_delivery_gps_event_crs CHECK (geom_crs IN ('GCJ02', 'WGS84')),
    CONSTRAINT ck_delivery_gps_event_longitude CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_delivery_gps_event_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_delivery_gps_event_accuracy CHECK (accuracy_meters IS NULL OR accuracy_meters >= 0),
    -- 设备时钟不可信：允许采集时间早于接收时间（离线补传），但不允许它落在未来
    CONSTRAINT ck_delivery_gps_event_captured CHECK (captured_at <= received_at + INTERVAL '5 minutes')
);
CREATE INDEX idx_delivery_gps_event_route ON delivery_gps_event (route_id, captured_at, id);

-- menu_id 已核对：配送块用 1000-1032，1023-1030 空闲。
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, perms_type, api_perms, web_perms,
                   context_menu_id, visible_flag, create_user_id)
VALUES (1023, '排线建议查询', 3, 1001, 1023, 1, 'scm:delivery:plan:query', 'scm:delivery:plan:query', 1001, TRUE, 1),
       (1024, '生成排线建议', 3, 1001, 1024, 1, 'scm:delivery:plan:propose', 'scm:delivery:plan:propose', 1001, TRUE,
        1),
       (1025, '应用排线建议', 3, 1001, 1025, 1, 'scm:delivery:plan:apply', 'scm:delivery:plan:apply', 1001, TRUE, 1),
       (1026, '轨迹查询', 3, 1001, 1026, 1, 'scm:delivery:gps:query', 'scm:delivery:gps:query', 1001, TRUE, 1),
       (1027, '轨迹上报', 3, 1001, 1027, 1, 'scm:delivery:gps:report', 'scm:delivery:gps:report', 1001, TRUE, 1)
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO t_role_menu(role_id, menu_id)
SELECT 1, menu_id
FROM t_menu
WHERE menu_id IN (1023, 1024, 1025, 1026, 1027)
  AND NOT EXISTS (SELECT 1 FROM t_role_menu rm WHERE rm.role_id = 1 AND rm.menu_id = t_menu.menu_id);

-- 授权矩阵：排线建议 = 调度 + 仓库主管；轨迹查询 = 调度；轨迹上报 = 调度 + 司机。
-- 司机只上报与查询自己线路的轨迹，范围由服务端按司机档案判定，不由前端传参决定。
WITH grant_matrix(menu_id, role_code) AS (
    VALUES (1023::bigint, 'SCM_DISPATCHER'), (1024::bigint, 'SCM_DISPATCHER'), (1025::bigint, 'SCM_DISPATCHER'),
           (1026::bigint, 'SCM_DISPATCHER'), (1027::bigint, 'SCM_DISPATCHER'), (1027::bigint, 'SCM_DRIVER'),
           (1023::bigint, 'SCM_STOREKEEPER_LEAD'), (1024::bigint, 'SCM_STOREKEEPER_LEAD'),
           (1025::bigint, 'SCM_STOREKEEPER_LEAD')
)
INSERT INTO t_role_menu(role_id, menu_id)
SELECT r.role_id, g.menu_id
FROM grant_matrix g
         JOIN t_role r ON r.role_code = g.role_code
WHERE NOT EXISTS (SELECT 1 FROM t_role_menu rm WHERE rm.role_id = r.role_id AND rm.menu_id = g.menu_id);

SELECT setval(pg_get_serial_sequence('t_menu', 'menu_id'), (SELECT MAX(menu_id) + 1 FROM t_menu), false);
