-- ADM-11 分拣增强：任务冻结筛选维度 + 电子秤事件（设备事件 → 稳定读数 → 人工接受）。
--
-- 边界（ADR-008）：
--   * 送货时间取任务创建时**冻结的快照**；线路筛选由预配送波次表达；供应商筛选使用任务上
--     **显式冻结**的供应商来源，不从 SKU 与供应商的多对多关系猜测。
--   * 电子秤走「设备事件 → 稳定读数 → 人工接受」链路，设备、原始读数、稳定判定、任务明细、
--     接受人和时间可追溯；重复事件不得重复写入分拣结果。
--   * 一键分拣只处理已有**标准品**和可确定的任务明细，仍只写已分拣数量；替代商品、
--     非标准品自动结算、供应商代分拣不由一键操作推断。

-- 三个筛选维度在建单时冻结。做成快照而不是实时联表：任务一旦建出来，它的作业口径就不该
-- 随着客户/供应商主档或配送线路的变化而改变。
ALTER TABLE sorting_task
    ADD COLUMN delivery_time_snapshot TIMESTAMPTZ,
    ADD COLUMN delivery_wave          VARCHAR(64),
    ADD COLUMN supplier_id            BIGINT,
    ADD COLUMN supplier_name_snapshot VARCHAR(150);
COMMENT ON COLUMN sorting_task.delivery_time_snapshot IS '建单时冻结的送货时间；筛选按它，不按订单当前值';
COMMENT ON COLUMN sorting_task.delivery_wave IS '预配送波次标识；线路维度由它表达，不从订单反查线路';
COMMENT ON COLUMN sorting_task.supplier_id IS '建单时显式指定的供应商来源；不从 SKU 与供应商关系推断';
COMMENT ON COLUMN sorting_task.supplier_name_snapshot IS '建单时的供应商名称快照';

CREATE INDEX idx_sorting_task_frozen_filters
    ON sorting_task (warehouse_id, delivery_wave, supplier_id, delivery_time_snapshot) WHERE deleted = FALSE;

CREATE TABLE sorting_scale_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key VARCHAR(160) NOT NULL,
    task_id BIGINT NOT NULL REFERENCES sorting_task (id),
    task_item_id BIGINT REFERENCES sorting_task_item (id),
    sku_id BIGINT,
    device_code VARCHAR(64) NOT NULL,
    raw_reading NUMERIC(18, 4) NOT NULL,
    unit VARCHAR(32) NOT NULL,
    stable_flag BOOLEAN NOT NULL,
    captured_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    accepted_quantity NUMERIC(18, 4),
    accepted_at TIMESTAMPTZ,
    accepted_by VARCHAR(64),
    rejected_at TIMESTAMPTZ,
    rejected_by VARCHAR(64),
    reject_reason VARCHAR(200),
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_sorting_scale_event_key UNIQUE (event_key),
    CONSTRAINT ck_sorting_scale_event_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    CONSTRAINT ck_sorting_scale_event_reading CHECK (raw_reading >= 0),
    -- 终态必须留下「谁在什么时候处理的」：一条被接受或被驳回的读数不能只有状态
    CONSTRAINT ck_sorting_scale_event_accepted CHECK (
        (status <> 'ACCEPTED') OR (accepted_at IS NOT NULL AND accepted_by IS NOT NULL
            AND accepted_quantity IS NOT NULL AND task_item_id IS NOT NULL)),
    CONSTRAINT ck_sorting_scale_event_rejected CHECK (
        (status <> 'REJECTED') OR (rejected_at IS NOT NULL AND rejected_by IS NOT NULL)),
    -- 设备时钟不可信，允许离线补传，但不允许明显超前
    CONSTRAINT ck_sorting_scale_event_captured CHECK (captured_at <= received_at + INTERVAL '5 minutes')
);
-- 待处理读数按任务查（作业台上「这个任务有哪些秤读数等着接受」）
CREATE INDEX idx_sorting_scale_event_task ON sorting_scale_event (task_id, status, received_at DESC, id DESC);

-- menu_id 已核对：分拣块用 1400-1421，1422-1429 空闲。
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, perms_type, api_perms, web_perms,
                   context_menu_id, visible_flag, create_user_id)
VALUES (1422, '秤读数查询', 3, 1401, 1422, 1, 'scm:sorting:scale:query', 'scm:sorting:scale:query', 1401, TRUE, 1),
       (1423, '秤读数上报', 3, 1401, 1423, 1, 'scm:sorting:scale:report', 'scm:sorting:scale:report', 1401, TRUE,
        1),
       (1424, '接受秤读数', 3, 1401, 1424, 1, 'scm:sorting:scale:accept', 'scm:sorting:scale:accept', 1401, TRUE, 1)
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO t_role_menu(role_id, menu_id)
SELECT 1, menu_id
FROM t_menu
WHERE menu_id IN (1422, 1423, 1424)
  AND NOT EXISTS (SELECT 1 FROM t_role_menu rm WHERE rm.role_id = 1 AND rm.menu_id = t_menu.menu_id);

-- 分拣员是秤的直接使用者；仓库主管兜底。上报与接受分开授权：
-- 上报只是把设备读数记下来，接受才会写进分拣结果。
WITH grant_matrix(menu_id, role_code) AS (
    VALUES (1422::bigint, 'SCM_SORTER'), (1423::bigint, 'SCM_SORTER'), (1424::bigint, 'SCM_SORTER'),
           (1422::bigint, 'SCM_STOREKEEPER_LEAD'), (1423::bigint, 'SCM_STOREKEEPER_LEAD'),
           (1424::bigint, 'SCM_STOREKEEPER_LEAD')
)
INSERT INTO t_role_menu(role_id, menu_id)
SELECT r.role_id, g.menu_id
FROM grant_matrix g
         JOIN t_role r ON r.role_code = g.role_code
WHERE NOT EXISTS (SELECT 1 FROM t_role_menu rm WHERE rm.role_id = r.role_id AND rm.menu_id = g.menu_id);

SELECT setval(pg_get_serial_sequence('t_menu', 'menu_id'), (SELECT MAX(menu_id) + 1 FROM t_menu), false);
