-- W2 approved Customer + Supplier aggregate. Immutable after first successful Flyway application.
-- Scope: customer_type / customer / supplier / supplier_sku. No foreign keys (see AGENTS.md §8).
-- Deliberate omission: no unique index on (supplier_id) WHERE is_default = TRUE — legacy R12
-- explicitly allows a supplier to carry several default rows and forbids inventing a cardinality policy.

-- ---------------------------------------------------------------------------
-- customer_type : maintainable dictionary (legacy fact source; C's hard-coded
-- CustomerTypeEnum 1/2/3 becomes seed data here).
-- ---------------------------------------------------------------------------
CREATE TABLE customer_type
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_code  VARCHAR(64)  NOT NULL,
    name       VARCHAR(100) NOT NULL,
    status     VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    version    INTEGER      NOT NULL DEFAULT 0,
    deleted    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_customer_type_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_customer_type_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_customer_type_code_active ON customer_type (type_code) WHERE deleted = FALSE;
CREATE INDEX idx_customer_type_name ON customer_type (name);

-- ---------------------------------------------------------------------------
-- customer : legacy 7 business columns + W2 additions (contact / address /
-- settlement terms / ownership). Contact, address and credit terms are embedded
-- scalar columns (Q6); no child tables in W2.
-- ---------------------------------------------------------------------------
CREATE TABLE customer
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code           VARCHAR(64)    NOT NULL,
    name                    VARCHAR(150)   NOT NULL,
    customer_type_id        BIGINT         NOT NULL,
    status                  VARCHAR(20)    NOT NULL DEFAULT 'POTENTIAL',
    parent_customer_id      BIGINT,
    seller_id               BIGINT,
    supplier_id             BIGINT,
    contact_name            VARCHAR(100),
    contact_phone           VARCHAR(32),
    address                 VARCHAR(255),
    settle_mode             VARCHAR(20)    NOT NULL DEFAULT 'INDEPENDENT',
    credit_limit            NUMERIC(18, 4) NOT NULL DEFAULT 0,
    credit_period_type      VARCHAR(20),
    credit_amount_threshold NUMERIC(18, 4),
    credit_period_value     INTEGER,
    credit_period_unit      VARCHAR(10),
    settle_day              SMALLINT,
    remark                  VARCHAR(500),
    version                 INTEGER        NOT NULL DEFAULT 0,
    deleted                 BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              VARCHAR(64),
    updated_by              VARCHAR(64),
    CONSTRAINT ck_customer_status CHECK (status IN ('POTENTIAL', 'COOPERATING', 'SUSPENDED', 'BLACKLIST')),
    CONSTRAINT ck_customer_settle_mode CHECK (settle_mode IN ('INDEPENDENT', 'GROUP')),
    CONSTRAINT ck_customer_credit_limit CHECK (credit_limit >= 0),
    CONSTRAINT ck_customer_self_parent CHECK (parent_customer_id IS NULL OR parent_customer_id <> id),
    CONSTRAINT ck_customer_credit_period CHECK (
        (credit_period_type IS NULL
            AND credit_amount_threshold IS NULL
            AND credit_period_value IS NULL
            AND credit_period_unit IS NULL
            AND settle_day IS NULL)
            OR (credit_period_type = 'BY_AMOUNT'
            AND credit_amount_threshold IS NOT NULL
            AND credit_amount_threshold >= 0
            AND credit_period_value IS NULL
            AND credit_period_unit IS NULL
            AND settle_day IS NULL)
            OR (credit_period_type = 'BY_TIME'
            AND credit_amount_threshold IS NULL
            AND credit_period_value IS NOT NULL
            AND credit_period_value > 0
            AND credit_period_unit IN ('DAY', 'MONTH')
            AND ((credit_period_unit = 'DAY' AND settle_day IS NULL)
                OR (credit_period_unit = 'MONTH'
                    AND (settle_day IS NULL OR settle_day BETWEEN 1 AND 28))))
        ),
    CONSTRAINT ck_customer_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_customer_code_active ON customer (customer_code) WHERE deleted = FALSE;
CREATE INDEX idx_customer_type_id ON customer (customer_type_id);
CREATE INDEX idx_customer_name ON customer (name);
CREATE INDEX idx_customer_status ON customer (status);
CREATE INDEX idx_customer_parent_active ON customer (parent_customer_id)
    WHERE deleted = FALSE AND parent_customer_id IS NOT NULL;
CREATE INDEX idx_customer_seller_active ON customer (seller_id)
    WHERE deleted = FALSE AND seller_id IS NOT NULL;
CREATE INDEX idx_customer_supplier_active ON customer (supplier_id)
    WHERE deleted = FALSE AND supplier_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- supplier : legacy 4 business columns + remark + W2 additions.
-- ---------------------------------------------------------------------------
CREATE TABLE supplier
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_code VARCHAR(64)  NOT NULL,
    name          VARCHAR(150) NOT NULL,
    status        VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    contact_name  VARCHAR(100),
    contact_phone VARCHAR(32),
    address       VARCHAR(255),
    remark        VARCHAR(500),
    version       INTEGER      NOT NULL DEFAULT 0,
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(64),
    updated_by    VARCHAR(64),
    CONSTRAINT ck_supplier_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_supplier_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_supplier_code_active ON supplier (supplier_code) WHERE deleted = FALSE;
CREATE INDEX idx_supplier_name ON supplier (name);
CREATE INDEX idx_supplier_status ON supplier (status);

-- ---------------------------------------------------------------------------
-- supplier_sku : SKU-level product-supplier relation (legacy shape, not C's
-- SPU-level t_product_supplier). Snapshot columns freeze display data so the
-- relation stays readable even if the W1 product master is renamed later.
-- ---------------------------------------------------------------------------
CREATE TABLE supplier_sku
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id            BIGINT       NOT NULL,
    sku_id                 BIGINT       NOT NULL,
    supplier_code_snapshot VARCHAR(64)  NOT NULL,
    supplier_name_snapshot VARCHAR(150) NOT NULL,
    sku_code_snapshot      VARCHAR(64)  NOT NULL,
    sku_name_snapshot      VARCHAR(150) NOT NULL,
    spec_values_snapshot   JSONB        NOT NULL DEFAULT '{}'::JSONB,
    purchase_unit          VARCHAR(32)  NOT NULL,
    reference_price        NUMERIC(18, 4),
    purchaser_id           BIGINT,
    is_default             BOOLEAN      NOT NULL DEFAULT FALSE,
    status                 VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    version                INTEGER      NOT NULL DEFAULT 0,
    deleted                BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by             VARCHAR(64),
    updated_by             VARCHAR(64),
    CONSTRAINT ck_supplier_sku_spec_values CHECK (jsonb_typeof(spec_values_snapshot) = 'object'),
    CONSTRAINT ck_supplier_sku_reference_price CHECK (reference_price IS NULL OR reference_price >= 0),
    CONSTRAINT ck_supplier_sku_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_supplier_sku_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX uk_supplier_sku_active ON supplier_sku (supplier_id, sku_id) WHERE deleted = FALSE;
CREATE INDEX idx_supplier_sku_sku_id ON supplier_sku (sku_id) WHERE deleted = FALSE;
CREATE INDEX idx_supplier_sku_purchaser ON supplier_sku (purchaser_id)
    WHERE deleted = FALSE AND purchaser_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Seed: C's CustomerTypeEnum (ENTERPRISE / PERSONAL / GROUP) becomes dictionary
-- data. No demo customer / supplier rows (W1 carried no legacy demo products).
-- ---------------------------------------------------------------------------
INSERT INTO customer_type(type_code, name, status)
VALUES ('ENTERPRISE', '企业', 'ENABLED'),
       ('PERSONAL', '个人', 'ENABLED'),
       ('GROUP', '集团', 'ENABLED');
