-- ADM-12 第一阶段：营销规则与订单优惠分摊。
--
-- 边界（ADR-009）：
--   * 基础定价顺序保持「协议价 → 客户类型价 → 市场价」不变；活动价在选出的**基础价之后**计算。
--   * 活动规则按**版本冻结**；互斥组决定可否叠加，不允许客户端自行组合优惠。
--   * 订单优惠按订单行金额**比例分摊**并冻结；舍入差额以确定性规则归集。
--   * 优惠券的占用、核销、释放必须可追溯并具备幂等保护；结算预览不等于最终占用，
--     提交时由服务端重验适用范围、版本与并发状态。
--
-- 支付（intent / callback / refund / reconciliation）不在本阶段，按同一 ADR 另行交付。

CREATE TABLE promotion_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_code VARCHAR(64) NOT NULL,
    activity_name VARCHAR(150) NOT NULL,
    activity_type VARCHAR(24) NOT NULL,
    -- 互斥组：同一组内的活动不可叠加。NULL 表示不参与互斥判定（仍受「每单最多一个」的总闸约束）
    exclusive_group VARCHAR(64),
    -- 同组内取优先级最高的一条生效；相同优先级时按 id 升序，保证结果可复现
    priority INTEGER NOT NULL DEFAULT 0,
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    -- 规则内容（门槛、减免、赠品 SKU 等）。受控 JSON：只接受本域定义的键
    rule JSONB NOT NULL,
    remark VARCHAR(200),
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    -- 只收录本阶段真正能算的类型：满减、折扣、满赠。
    -- 限时特价是「改基础价」而不是「订单级优惠」，它与「基础定价顺序不变、活动价在基础价之后算」
    -- 这条边界冲突，需要单独裁决，因此不在这里先占一个算不出来的类型。
    CONSTRAINT ck_promotion_activity_type CHECK (activity_type IN ('FULL_REDUCE', 'DISCOUNT', 'FULL_GIFT')),
    CONSTRAINT ck_promotion_activity_status CHECK (status IN ('DRAFT', 'ACTIVE', 'STOPPED')),
    CONSTRAINT ck_promotion_activity_window CHECK (valid_from < valid_to),
    CONSTRAINT ck_promotion_activity_rule CHECK (jsonb_typeof(rule) = 'object')
);
CREATE UNIQUE INDEX uk_promotion_activity_code ON promotion_activity (activity_code) WHERE deleted = FALSE;
CREATE INDEX idx_promotion_activity_active
    ON promotion_activity (status, valid_from, valid_to, exclusive_group) WHERE deleted = FALSE;

CREATE TABLE promotion_coupon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_code VARCHAR(64) NOT NULL,
    coupon_name VARCHAR(150) NOT NULL,
    discount_type VARCHAR(16) NOT NULL,
    discount_value NUMERIC(18, 4) NOT NULL,
    min_order_amount NUMERIC(18, 4) NOT NULL DEFAULT 0,
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    remark VARCHAR(200),
    version INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    CONSTRAINT ck_promotion_coupon_type CHECK (discount_type IN ('AMOUNT', 'RATE')),
    CONSTRAINT ck_promotion_coupon_value CHECK (discount_value > 0),
    CONSTRAINT ck_promotion_coupon_min CHECK (min_order_amount >= 0),
    CONSTRAINT ck_promotion_coupon_status CHECK (status IN ('DRAFT', 'ACTIVE', 'STOPPED')),
    CONSTRAINT ck_promotion_coupon_window CHECK (valid_from < valid_to)
);
CREATE UNIQUE INDEX uk_promotion_coupon_code ON promotion_coupon (coupon_code) WHERE deleted = FALSE;

-- 客户持有的券。一张券模板对一个客户可以发多张，用 instance_no 区分。
CREATE TABLE promotion_coupon_instance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id BIGINT NOT NULL REFERENCES promotion_coupon (id),
    customer_id BIGINT NOT NULL,
    instance_no VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'AVAILABLE',
    -- 占用：结算预览**不**写这里，只有真正提交订单才占用（ADR-009：预览不等于最终占用）
    reserved_order_id BIGINT,
    reserved_at TIMESTAMPTZ,
    used_order_id BIGINT,
    used_at TIMESTAMPTZ,
    released_at TIMESTAMPTZ,
    release_reason VARCHAR(200),
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_promotion_coupon_instance UNIQUE (coupon_id, customer_id, instance_no),
    CONSTRAINT ck_promotion_coupon_instance_status CHECK (status IN ('AVAILABLE', 'RESERVED', 'USED', 'RELEASED')),
    -- 终态必须留下痕迹：只有状态没有时间的券实例无法回答「什么时候被用掉的」
    CONSTRAINT ck_promotion_coupon_instance_reserved CHECK (
        (status <> 'RESERVED') OR (reserved_order_id IS NOT NULL AND reserved_at IS NOT NULL)),
    CONSTRAINT ck_promotion_coupon_instance_used CHECK (
        (status <> 'USED') OR (used_order_id IS NOT NULL AND used_at IS NOT NULL)),
    CONSTRAINT ck_promotion_coupon_instance_released CHECK (
        (status <> 'RELEASED') OR (released_at IS NOT NULL))
);
CREATE INDEX idx_promotion_coupon_instance_customer ON promotion_coupon_instance (customer_id, status, id);

-- 订单优惠冻结：一个订单至多一份。金额与分摊明细一并冻结，退款按原分摊反向，不用当前活动重算。
CREATE TABLE order_discount (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id BIGINT NOT NULL,
    activity_id BIGINT,
    activity_version INTEGER,
    activity_snapshot JSONB,
    coupon_instance_id BIGINT,
    coupon_snapshot JSONB,
    base_amount NUMERIC(18, 4) NOT NULL,
    discount_amount NUMERIC(18, 4) NOT NULL,
    -- 逐行分摊：[{orderItemId, baseAmount, discountAmount}]
    allocations JSONB NOT NULL,
    -- 舍入差额归集到哪一行（确定性规则：分摊后余额归到基础金额最大的一行，同额时取 id 最小）
    rounding_target_item_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(64) NOT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_order_discount_order UNIQUE (sales_order_id),
    CONSTRAINT ck_order_discount_amounts CHECK (base_amount >= 0 AND discount_amount >= 0
        AND discount_amount <= base_amount),
    CONSTRAINT ck_order_discount_allocations CHECK (jsonb_typeof(allocations) = 'array'),
    CONSTRAINT ck_order_discount_activity_snapshot CHECK (
        activity_snapshot IS NULL OR jsonb_typeof(activity_snapshot) = 'object'),
    CONSTRAINT ck_order_discount_coupon_snapshot CHECK (
        coupon_snapshot IS NULL OR jsonb_typeof(coupon_snapshot) = 'object')
);

-- 冻结快照不可变：优惠一旦落到订单上，就不能再改 —— 能改等于退款时可以按新活动重算。
CREATE FUNCTION reject_order_discount_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.sales_order_id IS DISTINCT FROM OLD.sales_order_id
        OR NEW.discount_amount IS DISTINCT FROM OLD.discount_amount
        OR NEW.allocations IS DISTINCT FROM OLD.allocations
        OR NEW.activity_snapshot IS DISTINCT FROM OLD.activity_snapshot
        OR NEW.coupon_snapshot IS DISTINCT FROM OLD.coupon_snapshot THEN
        RAISE EXCEPTION 'order_discount is an immutable snapshot';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_order_discount_immutable
    BEFORE UPDATE ON order_discount
    FOR EACH ROW EXECUTE FUNCTION reject_order_discount_change();

-- menu_id 已核对：1600 段属打印中心，1700-1799 空闲。
INSERT INTO t_menu(menu_id, menu_name, menu_type, parent_id, sort, path, component, perms_type,
                   api_perms, web_perms, icon, context_menu_id, visible_flag, create_user_id)
VALUES (1700, '营销中心', 1, 0, 1700, '/promotion', NULL, NULL, NULL, NULL, 'GiftOutlined', NULL, TRUE, 1),
       (1701, '活动管理', 2, 1700, 1701, '/promotion/promotion-activity-list',
        '/business/scm/promotion/promotion-activity-list.vue', NULL, NULL, NULL, NULL, NULL, TRUE, 1),
       (1702, '活动查询', 3, 1701, 1702, NULL, NULL, 1,
        'scm:promotion:activity:query', 'scm:promotion:activity:query', NULL, NULL, TRUE, 1),
       (1703, '活动维护', 3, 1701, 1703, NULL, NULL, 1,
        'scm:promotion:activity:edit', 'scm:promotion:activity:edit', NULL, NULL, TRUE, 1),
       (1704, '活动启停', 3, 1701, 1704, NULL, NULL, 1,
        'scm:promotion:activity:status', 'scm:promotion:activity:status', NULL, NULL, TRUE, 1),
       (1705, '优惠券', 2, 1700, 1705, '/promotion/promotion-coupon-list',
        '/business/scm/promotion/promotion-coupon-list.vue', NULL, NULL, NULL, NULL, NULL, TRUE, 1),
       (1706, '券查询', 3, 1705, 1706, NULL, NULL, 1,
        'scm:promotion:coupon:query', 'scm:promotion:coupon:query', NULL, NULL, TRUE, 1),
       (1707, '券维护', 3, 1705, 1707, NULL, NULL, 1,
        'scm:promotion:coupon:edit', 'scm:promotion:coupon:edit', NULL, NULL, TRUE, 1),
       (1708, '发券', 3, 1705, 1708, NULL, NULL, 1,
        'scm:promotion:coupon:issue', 'scm:promotion:coupon:issue', NULL, NULL, TRUE, 1)
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO t_role_menu(role_id, menu_id)
SELECT 1, menu_id
FROM t_menu
WHERE menu_id BETWEEN 1700 AND 1708
  AND NOT EXISTS (SELECT 1 FROM t_role_menu rm WHERE rm.role_id = 1 AND rm.menu_id = t_menu.menu_id);

-- 授权：销售主管维护活动与券（营销是销售侧动作），销售只读活动。
WITH grant_matrix(menu_id, role_code) AS (
    VALUES (1700::bigint, 'SCM_SALES_LEAD'), (1701::bigint, 'SCM_SALES_LEAD'), (1702::bigint, 'SCM_SALES_LEAD'),
           (1703::bigint, 'SCM_SALES_LEAD'), (1704::bigint, 'SCM_SALES_LEAD'), (1705::bigint, 'SCM_SALES_LEAD'),
           (1706::bigint, 'SCM_SALES_LEAD'), (1707::bigint, 'SCM_SALES_LEAD'), (1708::bigint, 'SCM_SALES_LEAD'),
           (1700::bigint, 'SCM_SALES'), (1702::bigint, 'SCM_SALES'), (1706::bigint, 'SCM_SALES')
)
INSERT INTO t_role_menu(role_id, menu_id)
SELECT r.role_id, g.menu_id
FROM grant_matrix g
         JOIN t_role r ON r.role_code = g.role_code
WHERE NOT EXISTS (SELECT 1 FROM t_role_menu rm WHERE rm.role_id = r.role_id AND rm.menu_id = g.menu_id);

SELECT setval(pg_get_serial_sequence('t_menu', 'menu_id'), (SELECT MAX(menu_id) + 1 FROM t_menu), false);
