-- ADM-12 3-5a：满赠赠品权益冻结。
--
-- 口径（docs/decisions.md「营销优惠生命周期、赠品与限时特价口径」）：
--   * 满赠**不减订单收入**：赠品金额恒为 0，优惠额仍是 0。
--   * 赠品必须走**正式库存出库**，出库来源标为促销赠品，出库成本计入该订单履约成本。
--   * **不把赠品塞成普通 sales_order_item**：那会污染采购需求、销售数量、销售额与客户购买商品分析。
--
-- 本表是「这张订单因为哪个活动、拿到什么赠品」的**冻结事实**：下单确认时一次写定，
-- 出库、分拣、小票、成本归集都从它读，不在各自环节重算活动规则。
--
-- 出库本身不在本 migration：发车时的赠品出库需要新增库存流水类型与来源单据类型，
-- 见 3-5b。本表先让权益成为可追溯的事实。

CREATE TABLE order_promotion_gift (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id       BIGINT      NOT NULL,
    activity_id          BIGINT      NOT NULL,
    activity_version     INTEGER     NOT NULL,
    sku_id               BIGINT      NOT NULL,
    -- 赠品主档快照：活动规则将来改赠品或商品改名，都不该改变这一单已经承诺的赠品
    sku_code_snapshot    VARCHAR(64)  NOT NULL,
    product_name_snapshot VARCHAR(150) NOT NULL,
    spec_name_snapshot   VARCHAR(150) NOT NULL,
    sale_unit_snapshot   VARCHAR(32)  NOT NULL,
    quantity             NUMERIC(18, 4) NOT NULL,
    -- 活动规则原文（受控键值），供解释「满多少赠多少」
    rule_snapshot        JSONB       NOT NULL,
    version              INTEGER     NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by           VARCHAR(64) NOT NULL,
    -- 同一订单的同一活动只冻结一次：重复确认由外层 ORDER_CONFIRM 幂等拦住，这里是库级兜底
    CONSTRAINT uk_order_promotion_gift UNIQUE (sales_order_id, activity_id),
    CONSTRAINT ck_order_promotion_gift_quantity CHECK (quantity > 0),
    CONSTRAINT ck_order_promotion_gift_rule CHECK (jsonb_typeof(rule_snapshot) = 'object')
);

CREATE INDEX idx_order_promotion_gift_order ON order_promotion_gift (sales_order_id);

-- 冻结快照不可变：赠品权益一旦落到订单上就不能改 —— 能改等于发货时可以换赠品。
CREATE FUNCTION reject_order_promotion_gift_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.sales_order_id IS DISTINCT FROM OLD.sales_order_id
        OR NEW.activity_id IS DISTINCT FROM OLD.activity_id
        OR NEW.activity_version IS DISTINCT FROM OLD.activity_version
        OR NEW.sku_id IS DISTINCT FROM OLD.sku_id
        OR NEW.quantity IS DISTINCT FROM OLD.quantity
        OR NEW.rule_snapshot IS DISTINCT FROM OLD.rule_snapshot THEN
        RAISE EXCEPTION 'order_promotion_gift is a frozen entitlement';
    END IF;
    RETURN NEW;
END $$;

CREATE TRIGGER trg_order_promotion_gift_immutable
    BEFORE UPDATE ON order_promotion_gift
    FOR EACH ROW EXECUTE FUNCTION reject_order_promotion_gift_change();
