-- ADM-12 3-10：provider-neutral 支付核心（支付意图 / 交易 / 回调 / 退款 / 对账）。
--
-- 边界（ADR-009 第 16～17 条）：
--   * 模型是 provider-neutral 的：本地 mock 与将来的真实渠道走**同一套契约**，
--     换渠道只换 provider 实现，不重写业务域。
--   * 回调按「渠道事件 id / 渠道交易号」幂等；验签后的状态转换由服务端执行。
--   * 支付成功与 Finance 收款事实建立**唯一映射**，但不建第二套财务账（映射在 3-11）。
--   * 渠道密钥与通知地址不得进入业务规则或客户端。
--
-- 纪律：
--   * 交易与回调是**事实**，append-only（表上有 ck_*_append_only），纠错靠追加新行而不是改历史。
--   * 支付金额由调用方显式给出，**不从订单金额自动推断**；provider 回报的金额只作核对，
--     不覆盖本地应付金额。
--   * 本迁移**不碰** finance_receipt / order_refund：支付成功落 Finance 收款是 3-11 的事，
--     这里只把支付事实本身建起来。

-- ============================================================================
-- 0. 单号序列
-- ============================================================================
-- 与采购 / 出库同口径：单号唯一性由**全局单调递增的序列**保证，日期段只是可读性装饰。
-- 不用「按日 reset」：那需要一张计数表 + 锁，而跳号本身是可接受的（序列 nextval 不回滚）。
CREATE SEQUENCE payment_document_seq;

-- ============================================================================
-- 1. payment_intent —— 支付意图：这笔钱打算怎么收（一笔订单可以有多个意图）
-- ============================================================================
CREATE TABLE payment_intent (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intent_no               VARCHAR(64)  NOT NULL CHECK (btrim(intent_no) <> ''),
    customer_id             BIGINT       NOT NULL,
    customer_name_snapshot  VARCHAR(150) NOT NULL CHECK (btrim(customer_name_snapshot) <> ''),
    -- 收哪一笔业务的款：当前只有销售订单，将来可能有充值等，因此留 source_type
    source_type             VARCHAR(32)  NOT NULL
        CONSTRAINT ck_payment_intent_source_type CHECK (source_type IN ('SALES_ORDER')),
    source_id               BIGINT       NOT NULL,
    source_no_snapshot      VARCHAR(64)  NOT NULL CHECK (btrim(source_no_snapshot) <> ''),
    -- 应付金额：**显式给出**，不由订单金额推断（订单可能只收一部分，也可能叠加余额）
    amount                  NUMERIC(18, 4) NOT NULL CHECK (amount > 0),
    -- 渠道大类：ONLINE=在线支付、BALANCE=客户余额（3-12）。两者都落 Finance 收款事实，
    -- 但**分开记**：一张订单可以同时有余额与在线支付两条资金来源，不是一个被覆盖的字段。
    method                  VARCHAR(16)  NOT NULL
        CONSTRAINT ck_payment_intent_method CHECK (method IN ('ONLINE', 'BALANCE')),
    provider                VARCHAR(32)  NOT NULL
        CONSTRAINT ck_payment_intent_provider CHECK (provider IN ('MOCK', 'WECHAT')),
    status                  VARCHAR(16)  NOT NULL DEFAULT 'CREATED'
        CONSTRAINT ck_payment_intent_status CHECK (
            status IN ('CREATED', 'PENDING', 'SUCCEEDED', 'FAILED', 'EXPIRED', 'CLOSED')),
    -- provider 侧的意图号（预下单返回）。真实渠道的 prepay_id 落在这里。
    external_intent_id      VARCHAR(128),
    -- 仅 MOCK 有意义：让本地 mock 按指定剧本回放成功/失败/延迟。
    -- CHECK 保证非 mock 渠道不可能带剧本 —— 否则真实渠道会有一个客户端可控的行为开关。
    mock_scenario           VARCHAR(24)
        CONSTRAINT ck_payment_intent_mock_scenario CHECK (
            mock_scenario IS NULL OR (provider = 'MOCK' AND mock_scenario IN (
                'SUCCESS', 'FAILURE', 'DELAYED', 'EXPIRED'))),
    expire_at               TIMESTAMPTZ,
    succeeded_at            TIMESTAMPTZ,
    closed_at               TIMESTAMPTZ,
    remark                  VARCHAR(500),
    version                 INTEGER      NOT NULL DEFAULT 0 CHECK (version >= 0),
    deleted                 BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              VARCHAR(64),
    updated_by              VARCHAR(64),
    -- 成功时刻与状态必须配对：只写 status 不写时刻会让「什么时候收的」无从考证
    CONSTRAINT ck_payment_intent_succeeded_pairing CHECK (
        (status = 'SUCCEEDED' AND succeeded_at IS NOT NULL)
            OR (status <> 'SUCCEEDED' AND succeeded_at IS NULL)),
    CONSTRAINT ck_payment_intent_closed_pairing CHECK (
        (status = 'CLOSED' AND closed_at IS NOT NULL)
            OR (status <> 'CLOSED' AND closed_at IS NULL))
);
CREATE UNIQUE INDEX uk_payment_intent_no ON payment_intent (intent_no) WHERE deleted = FALSE;
CREATE INDEX idx_payment_intent_source ON payment_intent (source_type, source_id) WHERE deleted = FALSE;
CREATE INDEX idx_payment_intent_customer_created ON payment_intent (customer_id, created_at DESC)
    WHERE deleted = FALSE;
CREATE INDEX idx_payment_intent_status_created ON payment_intent (status, created_at DESC)
    WHERE deleted = FALSE;
-- provider 意图号在**同一渠道内**唯一（不同渠道可能撞号，因此带 provider）
CREATE UNIQUE INDEX uk_payment_intent_external ON payment_intent (provider, external_intent_id)
    WHERE deleted = FALSE AND external_intent_id IS NOT NULL;

-- ============================================================================
-- 2. payment_transaction —— 交易事实：一次发起一条流水（append-only）
-- ============================================================================
CREATE TABLE payment_transaction (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_no           VARCHAR(64)  NOT NULL CHECK (btrim(transaction_no) <> ''),
    intent_id                BIGINT       NOT NULL,
    provider                 VARCHAR(32)  NOT NULL,
    -- 渠道交易号：回调幂等的第二个锚点（第一个是 payment_callback_event 的事件 id）
    provider_transaction_no  VARCHAR(128) NOT NULL CHECK (btrim(provider_transaction_no) <> ''),
    -- 本地应付金额（发起时的意图金额）
    amount                   NUMERIC(18, 4) NOT NULL CHECK (amount > 0),
    -- 渠道确认的实付金额。与 amount 分开：**不覆盖**本地金额，差额靠对账发现而不是静默改账。
    provider_amount          NUMERIC(18, 4) CHECK (provider_amount IS NULL OR provider_amount > 0),
    status                   VARCHAR(16)  NOT NULL DEFAULT 'PENDING'
        CONSTRAINT ck_payment_transaction_status CHECK (
            status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'CLOSED')),
    paid_at                  TIMESTAMPTZ,
    failure_code             VARCHAR(64),
    failure_message          VARCHAR(500),
    version                  INTEGER      NOT NULL DEFAULT 0 CHECK (version >= 0),
    deleted                  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64),
    updated_by               VARCHAR(64),
    CONSTRAINT ck_payment_transaction_paid_pairing CHECK (
        (status = 'SUCCEEDED' AND paid_at IS NOT NULL)
            OR (status <> 'SUCCEEDED' AND paid_at IS NULL)),
    -- 事实表不可删：纠错靠追加反向事实（退款/对账差异），不靠抹掉历史
    CONSTRAINT ck_payment_transaction_append_only CHECK (deleted = FALSE)
);
CREATE UNIQUE INDEX uk_payment_transaction_no ON payment_transaction (transaction_no) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_payment_transaction_provider_no
    ON payment_transaction (provider, provider_transaction_no) WHERE deleted = FALSE;
CREATE INDEX idx_payment_transaction_intent ON payment_transaction (intent_id) WHERE deleted = FALSE;
CREATE INDEX idx_payment_transaction_status_paid ON payment_transaction (status, paid_at DESC)
    WHERE deleted = FALSE;

-- ============================================================================
-- 3. payment_callback_event —— 回调事件（幂等锚点，append-only）
-- ============================================================================
CREATE TABLE payment_callback_event (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider           VARCHAR(32)  NOT NULL,
    -- 渠道事件 id：**回调幂等的主锚点**。重复投递同一事件只落一行，状态转换只做一次。
    provider_event_id  VARCHAR(128) NOT NULL CHECK (btrim(provider_event_id) <> ''),
    -- 归一化事件名；渠道给的名字不认识时原样存渠道原文，两者都没有才留空（NULL=未识别）
    event_type         VARCHAR(32)  CHECK (event_type IS NULL OR btrim(event_type) <> ''),
    -- 验签结果。**未通过验签的事件照样落库**（留证据），但绝不进入状态转换。
    signature_verified BOOLEAN      NOT NULL,
    -- 原文摘要：留证 + 便于比对「同事件重投是否被篡改」
    payload_hash       VARCHAR(128) NOT NULL CHECK (btrim(payload_hash) <> ''),
    payload            JSONB        NOT NULL
        CONSTRAINT ck_payment_callback_payload CHECK (jsonb_typeof(payload) = 'object'),
    -- 关联到的交易（验签通过且能匹配上时才有值）
    transaction_id     BIGINT,
    -- RECEIVED=已收待处理 / APPLIED=已应用 / DUPLICATE=重复事件 / REJECTED=验签或格式失败
    process_status     VARCHAR(16)  NOT NULL
        CONSTRAINT ck_payment_callback_process_status CHECK (
            process_status IN ('RECEIVED', 'APPLIED', 'DUPLICATE', 'REJECTED')),
    reject_reason      VARCHAR(500),
    received_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at       TIMESTAMPTZ,
    deleted            BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(64),
    CONSTRAINT ck_payment_callback_append_only CHECK (deleted = FALSE)
);
-- 幂等主锚点：同一渠道的同一事件只能有一行。重复回调因此必然撞唯一索引，
-- 由服务层捕获后按「已处理」静默返回，而不是再走一遍状态转换。
CREATE UNIQUE INDEX uk_payment_callback_event ON payment_callback_event (provider, provider_event_id);
CREATE INDEX idx_payment_callback_transaction ON payment_callback_event (transaction_id)
    WHERE deleted = FALSE;
CREATE INDEX idx_payment_callback_received ON payment_callback_event (received_at DESC);

-- ============================================================================
-- 4. payment_refund —— 退款（对外付款事实，与 order_refund 是两件事）
-- ============================================================================
CREATE TABLE payment_refund (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_no          VARCHAR(64)  NOT NULL CHECK (btrim(refund_no) <> ''),
    intent_id          BIGINT       NOT NULL,
    transaction_id     BIGINT       NOT NULL,
    provider           VARCHAR(32)  NOT NULL,
    amount             NUMERIC(18, 4) NOT NULL CHECK (amount > 0),
    -- 业务来源：当前只有售后退款单
    source_type        VARCHAR(32)
        CONSTRAINT ck_payment_refund_source_type CHECK (
            source_type IS NULL OR source_type = 'ORDER_REFUND'),
    source_id          BIGINT,
    status             VARCHAR(16)  NOT NULL DEFAULT 'CREATED'
        CONSTRAINT ck_payment_refund_status CHECK (
            status IN ('CREATED', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CLOSED')),
    provider_refund_no VARCHAR(128),
    -- 仅 MOCK 有意义：让本地 mock 按剧本回放退款成功 / 失败。
    -- 与意图同一套纪律：非 mock 渠道不可能带剧本。
    mock_scenario      VARCHAR(24)
        CONSTRAINT ck_payment_refund_mock_scenario CHECK (
            mock_scenario IS NULL OR (provider = 'MOCK' AND mock_scenario IN ('SUCCESS', 'FAILURE'))),
    reason             VARCHAR(500),
    refunded_at        TIMESTAMPTZ,
    failure_code       VARCHAR(64),
    failure_message    VARCHAR(500),
    version            INTEGER      NOT NULL DEFAULT 0 CHECK (version >= 0),
    deleted            BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(64),
    updated_by         VARCHAR(64),
    CONSTRAINT ck_payment_refund_source_pairing CHECK (
        (source_type IS NULL AND source_id IS NULL)
            OR (source_type IS NOT NULL AND source_id IS NOT NULL)),
    CONSTRAINT ck_payment_refund_refunded_pairing CHECK (
        (status = 'SUCCEEDED' AND refunded_at IS NOT NULL)
            OR (status <> 'SUCCEEDED' AND refunded_at IS NULL))
);
CREATE UNIQUE INDEX uk_payment_refund_no ON payment_refund (refund_no) WHERE deleted = FALSE;
-- 渠道退款号在同一渠道内唯一：重复退款回调靠它判定「这笔退款已经成功了」
CREATE UNIQUE INDEX uk_payment_refund_provider_no ON payment_refund (provider, provider_refund_no)
    WHERE deleted = FALSE AND provider_refund_no IS NOT NULL;
-- 一张售后退款单只对应一笔渠道退款
CREATE UNIQUE INDEX uk_payment_refund_source ON payment_refund (source_type, source_id)
    WHERE deleted = FALSE AND source_type IS NOT NULL;
CREATE INDEX idx_payment_refund_transaction ON payment_refund (transaction_id) WHERE deleted = FALSE;
CREATE INDEX idx_payment_refund_status_created ON payment_refund (status, created_at DESC)
    WHERE deleted = FALSE;

-- ============================================================================
-- 5. payment_reconciliation —— 对账（渠道账 vs 本地账）
-- ============================================================================
CREATE TABLE payment_reconciliation (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reconciliation_no   VARCHAR(64)  NOT NULL CHECK (btrim(reconciliation_no) <> ''),
    provider            VARCHAR(32)  NOT NULL,
    biz_date            DATE         NOT NULL,
    -- 运行结论。**差异分类不在这里**：一次对账可能同时有「本地缺」和「金额不符」，
    -- 一个状态表达不了，逐条差异落在 payment_reconciliation_item。
    status              VARCHAR(16)  NOT NULL DEFAULT 'PENDING'
        CONSTRAINT ck_payment_reconciliation_status CHECK (
            status IN ('PENDING', 'MATCHED', 'MISMATCHED')),
    -- 渠道侧合计 / 本地侧合计 / 净差额。差额**落库**而不是每次现算：
    -- 对账结论是要被审计的历史事实，不能随之后的交易变动而变。
    provider_total      NUMERIC(18, 4) NOT NULL DEFAULT 0,
    local_total         NUMERIC(18, 4) NOT NULL DEFAULT 0,
    difference          NUMERIC(18, 4) NOT NULL DEFAULT 0,
    provider_count      INTEGER      NOT NULL DEFAULT 0 CHECK (provider_count >= 0),
    local_count         INTEGER      NOT NULL DEFAULT 0 CHECK (local_count >= 0),
    -- 参与比对的交易数（渠道侧与本地侧的并集）与其中的平账数
    total_count         INTEGER      NOT NULL DEFAULT 0 CHECK (total_count >= 0),
    matched_count       INTEGER      NOT NULL DEFAULT 0 CHECK (matched_count >= 0),
    -- 差异条数。**净差额可能为 0 而仍有差异（一正一负），所以平不平看条数而不是看差额。**
    difference_count    INTEGER      NOT NULL DEFAULT 0 CHECK (difference_count >= 0),
    -- 分类汇总（各类各几条），供页面直接展示
    detail              JSONB
        CONSTRAINT ck_payment_reconciliation_detail CHECK (
            detail IS NULL OR jsonb_typeof(detail) = 'object'),
    reconciled_at       TIMESTAMPTZ,
    remark              VARCHAR(500),
    version             INTEGER      NOT NULL DEFAULT 0 CHECK (version >= 0),
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          VARCHAR(64),
    updated_by          VARCHAR(64),
    -- MATCHED 当且仅当没有任何差异：不允许「状态说平了、还有差异条」
    CONSTRAINT ck_payment_reconciliation_balanced CHECK (
        status <> 'MATCHED' OR (difference_count = 0 AND matched_count = total_count)),
    -- 三个计数不许各说各话：平账数 = 总数 − 差异数
    CONSTRAINT ck_payment_reconciliation_counts CHECK (
        matched_count = total_count - difference_count)
);
CREATE UNIQUE INDEX uk_payment_reconciliation_no ON payment_reconciliation (reconciliation_no)
    WHERE deleted = FALSE;
-- 同一渠道同一业务日只有一份对账结论
CREATE UNIQUE INDEX uk_payment_reconciliation_day ON payment_reconciliation (provider, biz_date)
    WHERE deleted = FALSE;

-- ============================================================================
-- 6. payment_mock_ledger —— 本地模拟渠道**自己的账**
-- ============================================================================
-- 存在的理由：对账要能真的对出差异。如果 mock 的「渠道账」就是本地交易表的投影，
-- 它永远平账，差异路径根本不可测。
--
-- 关键设计：mock provider 写这张表时**必须用独立事务**（REQUIRES_NEW）——
-- 渠道是另一个系统，它的账不会因为本地事务回滚而消失。「渠道扣了钱、本地没记上」
-- 正是对账要发现的那一类差异，这里如实模拟。
CREATE TABLE payment_mock_ledger (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider                 VARCHAR(32)  NOT NULL DEFAULT 'MOCK'
        CONSTRAINT ck_payment_mock_ledger_provider CHECK (provider = 'MOCK'),
    provider_transaction_no  VARCHAR(128) NOT NULL CHECK (btrim(provider_transaction_no) <> ''),
    provider_refund_no       VARCHAR(128),
    -- 账目方向：收 / 退。合计时退款为负
    direction                VARCHAR(8)   NOT NULL
        CONSTRAINT ck_payment_mock_ledger_direction CHECK (direction IN ('IN', 'OUT')),
    amount                   NUMERIC(18, 4) NOT NULL CHECK (amount > 0),
    biz_date                 DATE         NOT NULL,
    occurred_at              TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 刻意**没有** deleted / version / updated_*：这是渠道的账本，只有追加。
    -- 结构上就没有「改一行」的入口，比加一个 CHECK 更硬。
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)
);
CREATE UNIQUE INDEX uk_payment_mock_ledger_in ON payment_mock_ledger (provider_transaction_no)
    WHERE direction = 'IN';
CREATE INDEX idx_payment_mock_ledger_date ON payment_mock_ledger (biz_date);

-- ============================================================================
-- 6. payment_reconciliation_item —— 逐条差异（冻结的差异事实）
-- ============================================================================
-- 对账**只发现差异、不自动修复**：自动改交易状态会让审计链变得说不清。
-- 差异落成独立事实，后台展示，人工处理。
CREATE TABLE payment_reconciliation_item (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reconciliation_id        BIGINT       NOT NULL,
    -- MATCHED 不落这里（它由「零差异」表达）；这四类才是要给人看的
    category                 VARCHAR(24)  NOT NULL
        CONSTRAINT ck_payment_reconciliation_item_category CHECK (
            category IN ('LOCAL_MISSING', 'PROVIDER_MISSING', 'AMOUNT_MISMATCH', 'STATUS_MISMATCH')),
    provider_transaction_no  VARCHAR(128),
    transaction_id           BIGINT,
    local_amount             NUMERIC(18, 4),
    provider_amount          NUMERIC(18, 4),
    local_status             VARCHAR(16),
    provider_status          VARCHAR(16),
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by               VARCHAR(64)
);
CREATE INDEX idx_payment_reconciliation_item_parent ON payment_reconciliation_item (reconciliation_id);

COMMENT ON TABLE payment_intent IS 'ADM-12 支付意图：provider-neutral，应付金额显式给出';
COMMENT ON TABLE payment_transaction IS 'ADM-12 交易事实（append-only）：一次发起一条流水';
COMMENT ON TABLE payment_callback_event IS 'ADM-12 回调事件（append-only）：渠道事件 id 为幂等主锚点';
COMMENT ON TABLE payment_refund IS 'ADM-12 渠道退款事实';
COMMENT ON TABLE payment_reconciliation IS 'ADM-12 对账结论（渠道账 vs 本地账）';
COMMENT ON TABLE payment_mock_ledger IS '本地模拟渠道自己的账（仅 MOCK 渠道使用，独立事务写入）';
COMMENT ON TABLE payment_reconciliation_item IS 'ADM-12 逐条对账差异（冻结事实，只发现不自动修复）';
